### PR TITLE
Ellipsoid geodsic surface distance nan

### PR DESCRIPTION
**Pull request by littlemurph**
This PR fixes: #9248
Given certain input, cosineTwiceSigmaMidpoint in the vincentyInverseFormula could be -INFINITY which was not being checked by the isNaN.  Changed to isFinite to cover both cases.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @littlemurph!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/EllipsoidGeodsic_SurfaceDistance_NaN/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks for the PR, @littlemurph!  I'll try to review this before the next release.
In the meantime, it looks like one of your files is failing for code formatting.  If you run `npm run prettier` it should fix it.  Also, please add a comment to `CHANGES.md`.

Thanks!

**Comment by littlemurph** [comment]
Great thanks!  I think I have everything in order now.  Let me know if I missed anything else.

**Comment by IanLilleyT** [comment]
Thanks @littlemurph! I confirmed the problem and the fix and made a small tweak to the test. Looks good

**Pull request merged**
