### PR TITLE
New Sandcastle Example: Parallels and Meridians

### PR DESCRIPTION
**Pull request by ptrgags**
This sandcastle is pretty simple, but it does a lot of neat things:

* Clicking a point on the globe gives coordinates in decimal degrees, which is something useful I've been wanting to have more readily available
* This gives an example of how to draw reference latitude/longitude arcs using rhumb polylines.
* It generates lat/lon grids which might come in handy someday when debugging tileset locations by eye.
* The "cross hairs" through the selected point allow you to see what points on the globe are at the same latitude/longitude. I added this mostly out of curiosity. However, it might be useful if you want a rough approximation of what countries might have similar climates or the same time zone.
* I also noticed it was simple to add a second pair of crosshairs at the antipodal point (opposite point through the center of the globe). This way you can also compare points across hemispheres in any direction. Or you can plan a trip through the center of the earth. Spoiler alert: most of the time you'll end up in the ocean somewhere.

@lilleyse could you review when you get the chance?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/parallels-and-meridians/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
@ptrgags thanks for opening this PR! It's already helped me debug misplaced datasets on the globe.

Few comments just from using the demo, I haven't looked deeply at the code yet:

There's an error if you click "Show antipodal point" before clicking on the globe.

> Uncaught TypeError: Cannot set property 'show' of undefined (on line 185)

Can the labels be smaller or maybe just less decimals? [Picking](https://sandcastle.cesium.com/?src=Picking.html) has a nice black background around the text which could help make it stand out.

decimals

We talked about it offline but it should be brought up here too. Can we improve the accuracy of the polyline when the viewer is closer to the surface?

Selection_479

**Comment by ptrgags** [comment]
@lilleyse sorry for the delay. I finished addressing your feedback!

**Comment by lilleyse** [comment]
Looks great @ptrgags. And now that polylines are fixed for log depth the demo looks all the better.

**Pull request merged**
