### PR TITLE
Add support for PolylineVolume in CZML

### LINKED ISSUE #3062: Add PolylineVolume to CZML
We're missing support for both polyline volumes via CZML

### PR DESCRIPTION
**Pull request by jrafidi**
Fixes #3062

Did my best to port forward https://github.com/CesiumGS/cesium/pull/7175. I'm somewhat fuzzy around the reference properties and time intervals and tried my best to follow other examples in the file. Please let me know if there are other test cases I should add or any other obvious issues.

CLA signing is in progress.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jrafidi!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/jr/czml-polyline-volume/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks @jrafidi!  We'll review this once we get your CLA

**Comment by jrafidi** [comment]
@hpinkos I believe the CLA has been submitted. Have you received it on your end?

**Comment by hpinkos** [comment]
Got it, thanks @jrafidi!  I'll have time to review this later this week.

**Comment by jrafidi** [comment]
@hpinkos Do you have time to take a look this week? Would be nice to have this in the next release.

**Comment by hpinkos** [comment]
@jrafidi sorry, I had a deadline for something else creep up on me.  I won't have time today, but hopefully before the end of the week?

@mramato @shunter would you have a minute to review this?

**Comment by hpinkos** [comment]
@jrafidi sorry, it looks like we won't be able to get this in for the June release, but I'll make sure to review it in time for the July release.  Thanks for your understanding

**Comment by hpinkos** [comment]
great work on this, thanks @jrafidi!

fyi @shunter

**Comment by shunter** [comment]
Finally taking a look at trying to add this to the CZML spec.  Note that in CZML "cartesian" exclusively refers to a three-dimensional value X, Y, Z, where "cartesian2" exclusively refers to a two-dimensional value X, Y.  So the "shape" of the volume should have been defined as a "cartesian2" list value.

I think for backwards compatibility we can keep the erroneous "cartesian" property support. There are other cases like this where we still support old incorrect syntax.

**Pull request merged**
