### PR TITLE
ContextOptions TypeScript fix

### PR DESCRIPTION
**Pull request by romejoe**
Recent versions of the '@cesium/widgets' package have failed to build in TypeScript projects, as reported in #10963, because of a missing `ContextOptions` reference. This pull request fixes that by including `ContextOptions` and `WebGLOptions` in the type definitions.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @romejoe!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/contextoptions-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Great, thanks @romejoe! 

The CI failure is unrelated to this PR. 

Would you mind adding a note to `CHANGES.md` that this fixes https://github.com/CesiumGS/cesium/issues/10963?

**Comment by romejoe** [comment]
@ggetz  I just updated `Changes.md ` with a note that this fixes #10963

**Comment by ggetz** [comment]
Thanks @romejoe! It looks like formatting is failing CI. Would you mind running `npm run prettier` on your branch and committing the result?

**Comment by romejoe** [comment]
Of course, I'll take care of that now.

**Comment by romejoe** [comment]
@ggetz all set

**Comment by ggetz** [comment]
Thanks so much @romejoe! And congrats on your first CesiumJS contribution.

**Pull request merged**
