### PR TITLE
Add clipping surface updates to 3D Tiles primitive when picking #11410

### PR DESCRIPTION
**Pull request by dslming**
# Description
Fix there is a possibility of throw an error in a frame when continuously modifying the clipping planes and picking #11410

If the operation of 3D tiles (updating clipping plane) is not allowed during picking, then the presence judgment must be added.

The clipping surface of 3D Tiles Primitive may not have been created.

## Issue number and link
[11410](https://github.com/CesiumGS/cesium/issues/11410)

https://github.com/CesiumGS/cesium/issues/11410

## Testing plan

[demo](http://127.0.0.1:5500/Apps/Sandcastle/index.html#c=pVVhb9s2EP0rhLEP8qBQcroNheME69IATbEgwex0wKZhZaizzYUiBZKS6xb+7zuSki17KTBsgCGTx7vj4+O7Y5aRN2VJGOFS1LVQK1JLpiBFSxiQFegKnNkSp4ld6w1xayAGagMWlGNOaEX00lsLlWX7aFUSrpUzWoaAiq2UcE0JnW+XvBTWMcWBbIRbR0fdWKCFKhSGW0daARsw5JIo2JBrsKKp6IdgS4oRD/Nr3IcJBaYYpeRLoQgRaql/0p+mZMmkhdSbLEjgHuytKgVnTpvD6m580W9nOSCsy25bGqYXHk1n4FLzZ8obY/DwC1F53w7V+0YKpt4yB3RpdHVr9esf8kniNy9G5/n5+Vn++iyfLPJ8Gn6/FaNCjUNyCW7P/4MnxgZzIPSxLjFlxxdyHQjCbws9Zj9+h4TLU57m3ACoec043LSIt3MKkIYHpJypltmIZpCNWnC3qm7cm8BcsmxUGJDEO1WYcRz5jllqwZ/3KxRU+aCt8P4+7S79GqrFtgZ6d/84v/nz7v7Dzbg7uufECYkqc2hhdqs42QOQmpWLuJigEHVjOIqu0iXIO+aM+BSAeWjHtB7zcz1cu9ayU0gSzkQi5XZKfo9T8tXQpHc4dmHG4YipV0lO85SEz9mE5uP04I/GftKb/+j+oVzBr6J06ynBoGDcRXII8fXYoYwaaIzEs7ENE448oPoEFpEnRrawJ8gH+4iO1b1/jzf8vXrb8RpE/GhkgqnTfrNTPqcn8w76HueJzmojKlREC5ayskw6IAfneJYn3WCNqtW8XoPxBdb50eOFi2GMYaVo/PUe+9BoP0XzWetqoffX1uVPX7jnd8B8tgfh+PoXplaAd/k9XmNOz9N+02/Jd3ipMbjnOH6xfFECDuWqa+yZS7yJ9UmjtdEzVJoD0zK5L7NkfKC9p+B/yPlFSf9LWf8XaZ/Ieyjxocw7tYRBSiYHMRhwjVGDHoAOBDs3X5MEjNFmPCwBLYFKvUo+3vil0CA8x334lHzzJQTtPsbddtiSDq+MUPEdKh99HcWWTWmGvzmragnY1Vl2VCDZbR9yGN0b0T+JWX9hf1mtilHs8oOmNdwwHnmUjmbWbSVc9bz8KKpam1DbCSJxgEjwKbDZU8OfvRas7ZmbZcPQWSlaIsrLFx5IVB+zFleWjZRz8RmK0dUsQ/9/hHYM3rdgJNt6t/Xk6udopJTOMpy+HOm0lk/MnGT+Gw)

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [x] I have added or updated unit tests to ensure consistent code coverage
- [x] I have update the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Review by dslming — COMMENTED** [review]
I have completed it

**Comment by ggetz** [comment]
Thank you for the pull request, @dslming ! I don't see a CLA on file for you.

In order for us to review your PR, please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA).

**Comment by dslming** [comment]
I've signed the CLA.

**Comment by ggetz** [comment]
Thanks @dslming!

@lilleyse Would you mind confirming the approach here?

**Comment by lilleyse** [comment]
The fix makes sense, but I'm not sure about the wider implications of the change. I posted a workaround in the issue: https://github.com/CesiumGS/cesium/issues/11410#issuecomment-1914874522.

**Comment by lilleyse** [comment]
I looked through some of the other sandcastle examples in #11410 and I'm not sure the workaround will apply there.

This PR is probably ok to merge. Looking at `prePassesUpdate` I think it can safely be called multiple times per frame, though more testing may be needed.

**Comment by ggetz** [comment]
@lilleyse @dslming I'm concerned that, based on the test failure in CI, the tiles would be processed twice: Once in the render pass and once in the pick pass.

**Review by dslming — COMMENTED** [review]
gl setting texture increase existence judgment

**Review by dslming — COMMENTED** [review]
I've reviewed.

**Comment by ggetz** [comment]
@lilleyse Do you mind taking another pass?

**Comment by dslming** [comment]
> @lilleyse你介意再拿一张通行证吗？



> @lilleyse你介意再拿一张通行证吗？

Did you forget me?

**Comment by ggetz** [comment]
Bump @lilleyse ?

**Comment by lilleyse** [comment]
The new fix is just hiding the issue. A better fix that also avoids processing tiles twice would be to move the clipping plane update code from `prePassesUpdate` to `update`.

Basically move the code [here](https://github.com/CesiumGS/cesium/blob/f30c70b5dacb52ec66081ce643f5f24b2036df2f/packages/engine/Source/Scene/Cesium3DTileset.js#L2516-L2521) to [here](https://github.com/CesiumGS/cesium/blob/f30c70b5dacb52ec66081ce643f5f24b2036df2f/packages/engine/Source/Scene/Cesium3DTileset.js#L3234).

I haven't tried it, but hopefully that solves the issue.

**Comment by dslming** [comment]
> The new fix is just hiding the issue. A better fix that also avoids processing tiles twice would be to move the clipping plane update code from `prePassesUpdate` to `update`.
> 
> Basically move the code [here](https://github.com/CesiumGS/cesium/blob/f30c70b5dacb52ec66081ce643f5f24b2036df2f/packages/engine/Source/Scene/Cesium3DTileset.js#L2516-L2521) to [here](https://github.com/CesiumGS/cesium/blob/f30c70b5dacb52ec66081ce643f5f24b2036df2f/packages/engine/Source/Scene/Cesium3DTileset.js#L3234).
> 
> I haven't tried it, but hopefully that solves the issue.

Thank you very much for your guidance.
This modification will be better than before, but there will still be issues.
Because even if the beginning stage of this frame (executeCommandsInViewport ->Cesium3DFileset. update) already has clipping planes, it is possible that clipping planes will be removed at the end of this frame (executeCommand), and its texture will also be destroyed.
The removal of clipping planes can occur at any time in this frame, so when executing the command, the texture may not exist. Therefore, my idea is to increase the presence detection of this texture.

**Comment by ggetz** [comment]
@lilleyse @dslming Could we instead ensure that the removals are are actually executed at the expected time during the frame? For example with the `scene.preUpdate` event?

**Comment by lilleyse** [comment]
@dslming all of that should happen serially:

`pick -> executeCommandsInViewport -> Cesium3DTileset update -> executeCommand`

so I don't think clipping plane state could change during a pick. Are you still seeing issues after the suggested change?

**Comment by ggetz** [comment]
@dslming Are you still actively working on this PR, or should we close it for the time being until its ready for re-review?

**Comment by ggetz** [comment]
@dslming I'm closing this PR due to lack of activity. If you get the chance to work on this, please feel free to re-open. Thanks!

**Pull request closed without merging**
