### PR TITLE
January npm Updates

### PR DESCRIPTION
**Pull request by ggetz**
# Description

This updates outdated npm dependencies, excluded those which are pinned and that we have an issue tracking.

## Issue number and link

N/A

## Testing plan

Run `npm install`. 
Ensure `npm run eslint` still passes.
Ensure the `coverage` task still opens results after tests have been run.

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] ~I have updated `CHANGES.md` with a short summary of my change~
- [ ] ~I have added or updated unit tests to ensure consistent code coverage~
- [ ] ~I have update the inline documentation, and included code examples where relevant~
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
@jjspace Can you please review? This should be merged for the release today.

**Comment by jjspace** [comment]
Confirmed eslint works and coverage opens. I did run into some test errors that will be covered in https://github.com/CesiumGS/cesium/pull/11729. I will retest when that's merged but I think this should be good to go

**Comment by ggetz** [comment]
Thanks @jjspace! https://github.com/CesiumGS/cesium/pull/11729 is merged now.

**Comment by jjspace** [comment]
@ggetz I'm now getting some other test errors. I see them in `main` too and I think they're another occurrence of this: https://github.com/CesiumGS/cesium/issues/11666#issuecomment-1874248629
I think they may be unrelated to this branch, do you want to merge this or hold it up?

**Comment by jjspace** [comment]
Those errors have been present since the last release, not going to hold this up for them. Otherwise, looks good!

**Pull request merged**
