### PR TITLE
Dequantize normalized accessor min/max for `KHR_mesh_quantization` 

### PR DESCRIPTION
**Pull request by ptrgags**
Fixes https://github.com/CesiumGS/cesium/issues/10737

In [the `KHR_mesh_quantization` spec](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md) there's an implementation note that wasn't being accounted for:

>**Implementation Note:** For quantized data, accessor.min and accessor.max properties also contain quantized values. Applications that use these properties, e.g. for bounding box computations, will need to dequantize them first.

This PR does this dequantization in `GltfLoader`, only if the extension is present and the attribute is normalized.

The end result is that bounding volumes are computed correctly, so [this Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=zVZbT9swFP4rVp9SKTgphcGygsZg0iYNjQHay7oH45w2Fr5ktlMKqP99x7nQtGMPk5BGXhqfy/ed7xzbKTfaebIQcAeWHBENd+QUnKgU/V7boumA1+tToz0TGux0EJPHqSZE6Jn5YJYZmTHpIA4mBxK4F0Z/1rngzBu74S1Ybu5cRrytOoupZH6ihWIenuyr4bupnupZpWsswi2g+9zkIKPKypgUIOaFHzZlNLVT0F54AY5aUGYBJ1JGDQwhvNZYGidquKNO4SmzHt+YHtOZNeoM5hbARSGFkJ3R7pimB3t7b0Zv48a0t0fT/XR8kL5pDU0d4T1QdUQFsFzo+ZrnnPmCenOJZqZdNBrv98NL4XmBwWnPZo2UW6ai3JrPp4bmIqRfYnzU8sYNYlyD9ImMFdgkttmDa4slzYxVjhZbgN8q7LrVGN62pOtgp760nfQ1ST2Ge8TfHgvL8+ixSdRM4bDDJDdxs22GXsVZf9G6VdgRGWlRCSKKPiwGCNxZlboQS5BX4gFJR7uHay9bBu8VZxI9uyk+rW9V/66a5rVCvGX8FvKPnb5GKEasgvy2w2WozqH3R8hsC/Ow9BmZDs4qfouHp5Wmm7OC56Pb5tFwLaW/5TsbQYzC+zJLEmmw6MI4nx2mh6OkboRLFLhi51fFsLKHuk87YK2xSY7EdC797Ik9PKM0pWm3bKQ+KY//Uj6JlCJ9huF/E7RpV0JKoQD360sJ5a9TKA/77kWF5q9TaA78ZXXiAj8N8DqnWt3AP+v8WV+8V0znnDkvIVyx18bIG2bPQVdRexuFxEE8mDh/L+G4g3svVGmsD9dlRGniQZUSFbrkBosDT7lzHeMk6adOcrEgIj965n8B4ZI5h55ZJev7djo4niQY/0eqNPWn5usCrGT3IawYHX9pjJTSSYLL5zN9I3AL+Tc) should now work properly (all the models should be visible) 
image

For convenience, here is the [test data from the original issue](https://github.com/CesiumGS/cesium/files/9447657/mesh-quantization-issues.zip)

@j9liu could you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/quantization-normalization/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Review by j9liu — COMMENTED** [review]
@ptrgags looks good, just a couple comments for clarity

**Comment by ptrgags** [comment]
@j9liu updated!

**Comment by j9liu** [comment]
@ptrgags looks good, thanks!

**Pull request merged**
