### PR TITLE
Specs data fixes

### PR DESCRIPTION
**Pull request by javagl**
Some fixes for the `Specs/Data` that have been the result of running the validator against that data.

These changes often affect _many_ files, but _the same modification_ is applied to all files. So it may be best to review that on a "per-commit" basis instead of looking at the files.

**Notes**: 

Some the `Specs` data has apparently been auto-generated. Probably. Somehow. For example, there is the `Specs/Data/Geometry` subfolder without any information about where exactly these files come from. **Iff** there is a known tool that was used for creating them, then these fixes should preferably be done in the _tool_ , and not manually in its output. Some of these fixes are already the result of fixes from https://github.com/CesiumGS/3d-tiles-samples-generator/pull/2 , and are therefore automated. But the overall approach for maintaining the `Specs` data is not perfectly transparent.

This does not yet fix _all_ errors in the data (and some of them are not even supposed to be fixed). Also, I did **not** run the CesiumJS unit tests against the results (yet). But as a ballpark estimate: Running the validator against the `Cesium3DTiles` directory of the `main` state validated 204 files, where 146 files had errors. Now, only 34 files have errors. (For now...)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @javagl! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/javagl/cesium/blob/specs-data-fixes/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/specs-data-fixes/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by javagl** [comment]
So the build is failing. Running the tests locally on the current `main` causes 4 failures for me. Running them on the PR branch causes 4 failures for me. I have a hard time understanding the travis output ...
```
  ✗ clipping planes cull tiles completely inside clipping region for i3dm
	Unhandled promise rejection: RuntimeError: Failed to load model: http://localhost:9876/Data/Cesium3DTiles/Tilesets/TilesetWithExternalResources/external.i3dm?v=1.2.3
	Failed to load glTF
	Failed to load texture
	Failed to load image: bricks.jpg
	undefined
	Original stack:
	Original stack:
	Original stack:
	Original stack:
	undefined
```
These seem to be different failures than in the local tests (and I'm reasonably sure that I did not touch any file called `bricks.jpg` in this PR...). Maybe I'll have a closer look at this at a later point in time.

**Comment by javagl** [comment]
There have been some further fixes, based on the last validator state ( https://github.com/CesiumGS/3d-tiles-validator/tree/a33be6b016b10b195f187f9298f168902e6f9594 , supposed to become release `0.2.0` soon)

With the support for configuration files, one can run the validator with
`npx ts-node ./src/main.ts --configFile validationConfigSpecs.json`

where the `validationConfigSpecs.json` is
```JSON
{
  "tilesetsDirectory": "../cesium/Specs/Data/Cesium3DTiles/",
  "tilesetGlobPattern": "../**/*tileset*.json",
  "writeReports": false,
  "options": {
    "excludeContentTypes": [
        "CONTENT_TYPE_GEOJSON",
        "CONTENT_TYPE_VCTR",
        "CONTENT_TYPE_GEOM"
    ]
  }
}
```
(This assumes that `cesium` is a sibling directory of the validator - otherwise, the path has to be adjusted accordingly)

There are still _some_ errors. Some of them are anticipated (e.g. the spec files with legacy B3DM headers, or files that do not exist because they are not needed for the specs). Others are a bit non-trivial to fix (inconsistent availability- or buffer lengths). Bur reducing the number of errors from 146 to 4 is not a bad start.

**Comment by javagl** [comment]
1. Many of the current build errors have been caused by an image that was not found. 
2. Other failures have been due to the test expecting `Cartesian3` objects, where the result was actually a `Cartesian4`. 

Both should be fixed now.

---

Details: 

For 1.: The missing image was hidden behind several layers of "this-is-not-what-this-test-is-about", causing some misleading error messages. The `3d-tiles-samples-generator` generates many of the specs tilesets. One of them is a tileset that uses an I3DM that does not _contain_ a GLB, but only _refer_ to a GLB with a URI. The GLB that this I3DM refers to is https://github.com/CesiumGS/3d-tiles-samples-generator/tree/dbad666839838626674399637fd61995278a2be5/data/textured_box_separate . Apparently, at some point, this GLB had been modified (manually?) in the specs data, to replace an image URI that referred to a `bricks.jpg` with one that referred to a file called `Cesium_Logo_Flat.png`. So the output of the samples generator still referred to `bricks.jpg`, but this file was not found here in the specs data. (I considered modifying the file in the samples generator, to point to the `Cesium_Logo_Flat.png` - but unless there are specifi reasons to do that (copyright or Corporate Identity), replacing the `Cesium_Logo_Flat.png` with the `bricks.jpg` should be fine.

For 2.: The colors should be `Cartesian4`, because the metadata schema defines the colors to be 4D vectors. The metadata JSON only defined them as 3D vectors. This had already been updated in https://github.com/CesiumGS/cesium/pull/10852/commits/29c53e64f0bfb4d06678c342475bad8e1e2231e5 and https://github.com/CesiumGS/cesium/pull/10852/commits/50b52ab9bcdabc20543d436640d0e24d4c72a7e4 , but the spec had not been updated yet.

**Comment by javagl** [comment]
**All checks have passed** 🎉

**Comment by lilleyse** [comment]
Thanks @javagl for tracking down all the issues!

**Pull request merged**
