### PR TITLE
Fix incorrect `distanceSquaredTo` calculation in `BoundingSphere`

### PR DESCRIPTION
**Pull request by j9liu**
As noted in [the forum](https://community.cesium.com/t/distance-to-bounding-sphere-function-looks-wrong/13567), the `distanceSquaredTo` calculation of `BoundingSphere` was incorrect. It was calculated as `(position - center)**2 - radius**2`, instead of `((position - center) - radius)**2`. This PR fixes the algorithm and the unit test that corresponds to it.

cc @lilleyse @ebogo1

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @j9liu!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
Thanks @j9liu for the fix, and thanks @donhatch for letting us know about the problem in the forum post and in https://github.com/CesiumGS/cesium/issues/9534

Looks like this problem goes way back: https://github.com/CesiumGS/cesium/commit/febb47baeb45a9ad93f05cc0784d6cba149cc2bb

Turns out this function is only used for sorting translucent commands and sorting tiles for globe picking which have managed to get away with less than perfect results. Thankfully SSE calculations are correct since they use [TileBoundingSphere.prototype.distanceToCamera](https://github.com/CesiumGS/cesium/blob/dddcd9a8e4b4c475611f1082dc28b82f09be13a3/Source/Scene/TileBoundingSphere.js#L93-L103) which is actually implemented correctly.

Just a couple suggestions

* It should return 0.0 if the point is inside the sphere. `OrientedBoundingBox` does the same thing. This should be mentioned in both classes' documentation like it is in `TileBoundingSphere.prototype.distanceToCamera`. Add a test for this.
* In the `BoundingSphere` doc remove the word "estimated". It can just be "The distance squared from the bounding sphere to the point"
* Looks like the `OrientedBoundingBox` doc copied the same line "The estimated distance squared from the bounding sphere to the point." It should be "The distance squared from the oriented bounding box to the point."

**Comment by j9liu** [comment]
@lilleyse - Thanks for the review. I just made some changes that addressed your points, let me know if I missed anything!

**Comment by lilleyse** [comment]
Thanks! Looks good.

**Pull request merged**
