### PR TITLE
Add support for Bing Maps mapLayer template parameters

### PR DESCRIPTION
**Pull request by mramato**
Bing Maps [mapLayer template parameters](https://learn.microsoft.com/en-us/bingmaps/rest-services/imagery/get-imagery-metadata#template-parameters) allow users to customize imagery to enable certain features, such as traffic flow. This change updates `BingMapsImageryProvider.fromUrl` to take an optional `mapLayer` string parameter which is then maps directly to the equivalent Bing query parameter.

Also had to change Bing to identify itself as having transparency when this option is used.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks for the PR @mramato!

I gave this a test in this branch as follows:

```js
const viewer = new Cesium.Viewer("cesiumContainer", {
  baseLayerPicker: false,
  baseLayer: false
});

const labels = Cesium.ImageryLayer.fromProviderAsync(Cesium.BingMapsImageryProvider.fromUrl("https://dev.virtualearth.net", {
        mapLayer: "Foreground",
        key: "<KEY>"
    }));

viewer.imageryLayers.add(labels);
```

While I can confirm that the query parameter was sent in the request, I'm not seeing the labels or any other of the options in the rendered imagery layer, just the background basemap:

image
image


Am I doing anything wrong?

**Comment by mramato** [comment]
@ggetz It looks like you are using the default `BingMapsStyle.AERIAL` style, you need to specify `AERIAL_WITH_LABELS_ON_DEMAND` or `ROAD_ON_DEMAND`for the mapLayer features to work. Sorry for not including an example in my original PR description.

**Comment by ggetz** [comment]
Got it, thanks @mramato!

image

I added a quick test in the specs to confirm the query parameter is being sent. Once CI passes I will merge.

**Comment by mramato** [comment]
Thanks, @ggetz!

**Pull request merged**
