### PR TITLE
Fixed imageBasedLightingFactor setting for i3dm

### PR DESCRIPTION
**Pull request by bbbbx**
Setting `tileset.imageBasedLightingFactor` has no effect on i3dm content

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @bbbbx!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Hi @bbbbx, thanks for the PR! You have a few failing tests that will need fixing.

@sanjeetsuhag Would you be able to review this when you get the chance?

**Comment by sanjeetsuhag** [comment]
I can confirm that this is an issue.

| [B3DM Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=pVRdc9o4FP0rWp5ghgjLEv5IaGYDJKmZANtAmpTxi7BlULBl1pLJQif/vfIHpdkm+7IvsnV17rm65x670wG3GRUKDJjkeTKaARoETEqgUrBP8wzwVAAqJVPSFxUGeqmAIYtoHqurEjxPN0yAT8BvsP1ovbwN+JSPvIeDhybck5647wYDz/I226evg5ELNejv8HajQd5hktysx4dFMp4hPn7e7O/mX8h4OFbTx+vDdIA2i+Tmefz47Z9F8rCfPHr8bjDaLjTZZPhFekm8DvX7eP7tZTK/QuP5VXeCDRjaT8lkeeMlf13jfpevRk+jB3vhDGnfsLd9+Xy/3KDPSs2H+cZvXPjCFzuagR1nLyzTXQj2UqsBv5axpt8Iyv0gFYpywTK/0fqZx5fxtaDLmIU6V2U5u/gZn4q3dAOaKf1GhdlE0GgDvbR+QUfRh3CjgBsVvEq4nY3TkMWyn/M45GIldW7VApQBEwxuM55wxXdMQhqGTV+AN9zlAw/nPGZ6uM3vxTkAeRafg9OY75nUHggYjLI0uSpc4IVN5NjYIa12lcETumJ9Kll4x1drpW9yQwOVZueVAAXoteWL+uLVBQOasIzCKN7P06pyyKROpapw2/m7GuDmmUm6pmshaFkmRoQQw2qDM2LbLkIIYosQF9td0gaYmPqJoG0S00IudqzqsmnGmR5gXaTuWNfmGQv+s7IBieGiLiIGwi5BrmnoKmc6ikjXsSyECbaRXrtl1EGmQ8ziwCK2S5yjUlrd7cfNGdB0DGyZtoWtrlbYQlUN1yAO0UTYtk3TsZzCBtg0sOPa2HAcjLFZV3gt1zDPjh1iX7xWuvtiRkUYUKliVrhhnq5WMevnSqWidIbfqELAK8YJynmC40BBNVG/URY4+b3cRrmoxGsGaxZsWNg6Kvvmw/jjtLuojyPQPAVbp3n85mz4kcc0b2mymvEV6Cz2P4iiqGaq+UpVK+822o2eVPuYXR7Z/+TJNs1U8ck0IewolmxjqsfZWeZaBgUDKVs1Xa/za2ov5DvAw0/v/FVAEOt/rT6J8jie8QPzG5e9jsb/lhqntGhpumNZTPcFbI0u76oghLDX0dv3M1Waxkua/Yv5Bw) | [I3DM Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=nVRbc+I2FP4rKk8wQ4RlybeEzTRAkpoJ0E2cTZbxi7AFKNgytWRS6OS/V76wbNqkD32RraPvfOfyHanXA7c5FQoMmeRFOn4ANIqYlEBlYJ8VOeCZAFRKpmQoagz0MwFjtqRFoq4qcJBtmABfQNhi+/F6cRvxGR/7jwcfTbkvfXFvRUPf9jfb52/DsQc16I/4dqNB/mGa3qwnh3k6eUB88rLZ3wVfyWQ0UbOn68NsiDbz9OZl8vT9z3n6uJ8++fxuON7ONdl09FX6abKO9f8k+P46Da7QJLiyptiAsfOcThc3fvr7NR5YfDV+Hj86c3dEB4azHciX+8UG/aZUMCo2YesiFKHY0RzsOHtlua5CsNemG/BbZWuHrajaDzOhKBcsD1udH358kVwLukhYrH1VXrCLH/aZeE83pLnSf1SYbQMaXaCXzk/o5fJTOCrhqIbXDrfBJItZIoOcMan96vShjJhgcJvzlCu+YxLSOG6HArzjrT54FPCEaWHbf5XnABR5cg5OEt8zqfWPGFzmWXpVToAft5GLTdvqdGsPntIVG1DJ4ju+WisuVjc0Ull+Xhdfgt46oWiSrhOMaMpyCpfJPsjqyDGT2pWqctLOP6wft89MYpmejaBtmxgRQgy7C86I43gIIYhtQjzsWKQLMDH1F0HHJKaNPOzadbJZzpkWrwnSVKxj85xF/xnZgMTwkIWIgbBHkGcaOsqZtiJiubaNMMEO0qtVWV1kusQsD2zieMQ9dkp3d/t5cQY0XQPbpmNj23IdbKM6hmcQl2gi7Dim6dpuOTHYNLDrOdhwXYyx2UR4q9a4yI8V4lC81X0PxQMVcUSlSlg5DUG2WiVsUCiViWoywlZtAn4pJ6j0BEdBQa1o2KoCnGa92i4LUTevHa1ZtGFx59jZd5fil9PuojlegvbJ2Dnp8W6q4WfzpTnr+9LQvQHtwv4ni2hIGqqqm/XMtrqtvlT7hF0eiX/l6TbLVXlV2hD2FEu3CdUy9haFLl/BSMpOQ9fv/ezaj/kO8PjLBy8JiBL9vuqTZZEkD/zAwtZlv6fx/3JNMhrr7Gc7lid0X8LW6PKuNkII+z29/dhTZVmyoPk/mP8G) |
| - | - |
| b3dm | i3dm |

The root cause here is that the `Instanced3DModelContent.update` function does not propagate the `tileset.imageBasedLightingFactor` property.

https://github.com/CesiumGS/cesium/blob/9a7088e9891b989b99afc9da49cdbceaff3b5bc5/Source/Scene/Instanced3DModel3DTileContent.js#L515-L534

This is not an issue in `Batched3DModelTileContent`:

https://github.com/CesiumGS/cesium/blob/9a7088e9891b989b99afc9da49cdbceaff3b5bc5/Source/Scene/Batched3DModel3DTileContent.js#L429

Once that is fixed, it should work as intended:

i3dm-fixed

**Comment by bbbbx** [comment]
After digging into the CI details, I found that the tests failed because the `tileset` has no `imageBasedLightingFactor` property, so I added it in `Specs/Cesium3DTilesTester.js`.
@ggetz Could you review again? Thanks!

**Comment by sanjeetsuhag** [comment]
The changes here look good. I've tested the Sandcastles above, and it works as expected! @bbbbx Could you also add this fix to `CHANGES.md`?

**Comment by bbbbx** [comment]
`CHANGES.md` was updated. /ping @sanjeetsuhag

**Review by sanjeetsuhag — APPROVED** [review]
Looks good. Thanks again @bbbbx!

**Pull request merged**
