### PR TITLE
Allow normals to be used when model material is unlit

### PR DESCRIPTION
**Pull request by lilleyse**
When a model uses the `KHR_materials_unlit` extension its normal shader attribute is disabled which could be a problem if normals are used for purposes other than lighting. This PR has two fixes:

* Allow normals to still be used but disable lighting code when the material is unlit 
* Prevent attributes from being optimized out of the vertex array in case subsequent shader compiles use the normal attribute

Thanks @ErixenCruz and @jtorresfabra for looking into this

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/unlit-model-normals/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Review by jtorresfabra — APPROVED** [review]
:+1: Approved, changes look sensible.
As a proposal maybe in the future we can revisit this part to try to avoid extra shader compilation.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
I'm going to merge since this was approved by Jordi and I can confirm it fixes the issue with a non-public test case.

**Pull request merged**
