### PR TITLE
Support for Multiple Globes (on hold)

### PR DESCRIPTION
**Pull request by jasonbeverage**
Hi everyone!

This PR adds support for multiple globes on a Scene.  It is a subset of what was included in my [Underwater Rendering](https://github.com/AnalyticalGraphicsInc/cesium/pull/6047) PR, but without any of the underwater stuff. 

The main purpose of this PR is to allow users to use a slider to compare multiple terrain datasets in addition to multiple imagery datasets.  Globes can now have a splitDirection setting just like ImageryLayers.  In addition to the main globe object on a Scene, there is also an array of secondary globes that are rendered in the "globes" property on Scene.  You can see a demo of this PR in the Multiple Globes sandcaste example which compares the Cesium terrain dataset with the VR-TheWorld elevation dataset.  You'll notice in the example that I need to update VR-TheWorld to apply an egm96 vdatum transformation on the server to feed Cesium, this is done client-side with osgEarth so it was never really an issue, but it does show off the slider pretty nicely :)  This could also be a really cool demo to show off the improved resolution of the new Cesium Ion terrain dataset vs the old terrain.

terrain_slider

### CODE REVIEW

**Comment by pjcozzi** [comment]
Awesome, thanks @jasonbeverage!  I have two cross-country flights this week, will see if I can look at this during one of them.

**Comment by jasonbeverage** [comment]
Awesome, hope you're going somewhere cool!

**Comment by cesium-concierge** [comment]
Thanks again for the pull request!

Looks like this pull request hasn't been updated in 30 days since I last commented.

To keep things tidy should this be closed? Perhaps keep the branch and submit an issue?
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by jasonbeverage** [comment]
Hey Patrick, were you still interested in merging this?   Is there anything
else you need from me?

**Comment by gberaudo** [comment]
Having support for underwater / underterrain would be very nice. I am also looking to see what are the plans / roadmap for adding such support to Cesium.

**Comment by hpinkos** [comment]
@jasonbeverage this is probably something we're interested in, we just haven't had a chance to take a closer look at it yet.  @pjcozzi do you have any input?

**Comment by jasonbeverage** [comment]
No worries @hpinkos, just trying to keep the cesium-concierge happy :)

@gberaudo There were some ideas from @pjcozzi about how to proceed.  I'm hoping to get funding to finish up the integration per Patrick's request, but nothing has been finalized yet.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @jasonbeverage! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by hpinkos** [comment]
@cesium-concierge stop

**Comment by ebogo1** [comment]
This feature would be nice to support but the implementation needs more work to merge at this point.

**Pull request closed without merging**
