### PR TITLE
update the UniformType : mat3

### PR DESCRIPTION
**Pull request by wqy224488**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @wqy224488! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/wqy224488/cesium/blob/main/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks for the PR @wqy224488. I can confirm we have your CLA.

Could you please update `CHANGES.md` with a summary of the change? For example:

`Fixed `UniformType.MAT3` value for custom shaders. [#11235](https://github.com/CesiumGS/cesium/pull/11235)`.

**Comment by wqy224488** [comment]
> Thanks for the PR @wqy224488. I can confirm we have your CLA.
> 
> Could you please update `CHANGES.md` with a summary of the change? For example:
> 
> `Fixed `UniformType.MAT3` value for custom shaders. [#11235](https://github.com/CesiumGS/cesium/pull/11235)`.

Hello, ggetz, I have updated the CHANGES.md.

**Comment by ggetz** [comment]
Thanks @wqy224488 for your first Cesium contribution!

**Comment by wqy224488** [comment]
It's a pleasure.

**Pull request merged**
