### PR TITLE
Optimizes S2 position calculations and distanceToCamera check

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
This PR adds some optimizations for the S2 implementation in CesiumJS.

1. Avoid redundant re-computation of the `level` in `S2Cell.getCenter()` and `S2Cell.getVertex()`.
2. Pre-computes the vertices per-plane in the `TileBoundingS2Cell` so we don't have to re-allocate arrays in the `distanceToCamera` function.

Here are the results from a benchmark that calculates how much faster is the `distanceToCamera` check in  `OrientedBoundingBox` versus the kDOP in `TileBoundingS2Cell`:

| Run # 	| [`master`](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/feature-id-texture-mvp/Build/Apps/Sandcastle/index.html#c=3VZtbxo5EP4rFl+y22xMQlupIjS6Qrjrh6SpoJeoykYns2sWq14b2V4CqfLfO7bXQDgSaKVKp0OI9csz45nnGc+SSaENmjF6TxV6jwS9Rz2qWVXia7cWpY3MzXtSGMIEVWkjPk1F5uwyUlJFPkvNDIMFcHB799xmjygjC0WmE5YFYCrGlcjsNioo+CaGDojIZbm0ikSCSjKHHwYjRXXFTQKuV750jL6nAqEZUYid2tFYKhQxOOP4FDHUQQIeh4c1zAPnQ1YIQFwSM8HKHRnF6AxM8NvTFWyxH+xhN8xHfsvunpJsSYEREa8jj0N1aK82nL1CEdCAjiwPMTp0dASLxU9bPPykRVxn8YR3n8xaImEHj5Usl5lFy9S9l8dUPFrlnxP85Nh9EtSCgGrvfc7ZVEuW45u/hu/eYAiTlVU5IDmrdLInaqMek5cKNHbFmQqrrm51r5+q9oVx2pWVyJkohq0e5TxytWXkNyraKG2cpA3HHDBoI/hIWTExbXTsF31YYdHnC6T4M/1VxDoDevBUsRKCm1GNSZ5HNhKcKQqsndNRVVxLXpU0ChJILhUe9M/j2hPELkejlUZXilFhaB5C78q5k+qzZMJo7/2fGVWGwZW3PmoP29Lf4stVMMBxZndUEqYTwscf5lSnYneG7rRdKXYv/u6v5ahoZlZJDmBGRMHp0yr8oBRZbKSINYdH9CZB7+KQrqIF1MJLgg8cwguuwmFtN9xb89bb/UUPEe1i5Wv/4uLqZo0Xls/dmFMDNawNUAFZTamC/lgSkVEs5H1k8b5h5vO6ZcKgs3k5MKeiMBO3u+yljs6cgWvw9kX2nEn0PfQKO2uHrovQtPZ102ujTfe34PYu2USu38j2S9fVmXvrx9pLKXNQpWZoaIm9hBU87PU/9V+fu0ZkU38M/FCRP8NOQFxSYpt85LFHgdMYNZ8jy78JJdQil0V0MGyh6LxmK4Y2kRr4HkCj9b6xkX+yOc2hA8ah/9iT4U4Mf4N4/qr9knr/MfEgk/4O9QAS5KvRR0te9xfwqtvdVNDKVztf1w9WDxLYRnY/8vo2a1y8BLYcbn6witNf9t8h97KN/B8U98nsEt2jgu4rm6N1mvdX3zf+bQWwOmhnDayg28qgkTQ62iw4PQvc/sHKqYRiqBSPMG4aWk45vAV0c1Rl36jBmdbhz1mnuW7aydkMCuD9lv/vKONEa9gZV5wP2QNNG2edJuD/Zcolsa+8K3hjcrKwsMnJ2YVfxBh3mjDdbmmk5COiNjz/AA)	| [`s2-optimize` ](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/s2-optimize/Build/Apps/Sandcastle/index.html#c=3VZhbxo5EP0rFl/YbTYmoa1UERpdIejuQ3KpoE10ykYns2sWq14b2V4CqfLfb2yvgVAS6EmVTheh4LXfPM+8Z8+SSaENmjP6QBX6iAR9QH2qWVXiGzcXpY3MPfelMIQJqtJGfJaKzMVlpKSKfJaaGQYTQHB3/9JinygjC0VmU5YFYComlcjsMioocBNDh0TkslxFRSJBJVnAPwYjRXXFTQLUay4do++pQGhOFGJndjSRCkUM9jg5Qwx1kYCvo6Ma5oGLESsEIK6ImWLltoxidA4h+P3ZGrY8DPa4H+Yzv2P3z0W2osCIiLeRx6E6tTdbZG9QBDKgY6tDjI6cHCFi+dMRjz8ZEddVPNPdF7NRSFjBEyXLVWXRqnTP8pSKJ+v8S4afnri/BLUhoZp9wDmbaclyfPv76MM7DGmysiqHJGeVTg5EbZ3H5LUDGrvDmQrrrm73bp679oVx2pOVyJkoRu0+5TxyZ8vIb1R0UNo4TRtOOVDQZvAHZcXUdNCJn/RphUlfL4ji9/RXEesM5MEzxUpIbk41Jnke2UxwpiiodkHHVXEjeVXSKFgguVR4OLiIaybIXY7Ha4+uFaPC0Dyk3pMLZ9VnyYTRnv3vOVWGwZW3HDXDrvJ3cLkTDHCc2RWVhMcp4ZNPC6pTsb9Ct9u+EnuXXwcbNSqamXWRQ3giouD0+Sn8pBRZbpWINYev6F2CPsShXEULOAuvGT50CG+4Cpt13PBgz9vvDzc9ZLRPlb8Gl5fXtxu6sHzhxpwaOMPagBRQ1Ywq6I8lERnFQj5EFu8bZr6oWyYMutuXA3MqCjN1q6te6uTMGVAD2xfZdyHR99Ar7FMndF2EZjXXbb+DtunvgPY+2UZu3sjOa9fVhfvop5qllDm4Uis0ssJewQwe9Qd/Dt5euEZkS38K+lCRv6BOQFxRYpt85LHHQdMYtV4Sy78JJZxFLouoOWqj6KJWK4Y2kRr4NKHReu7Qc+xucA9Gv8Awf73+lWP/McOgksEexwASLKvRxytdDzftutfbds1aFsiPUDOBKWTnIu9jq16zr9DmorlOyN/kX+Hrqkf8H6z1xexz16OCweuY402ZD7fZd/VdTm9stMvs9fLK70bS6Gqz5PQ8iPgbK2cSXK8UjzBuGVrOOPRy3RpX2TdqcKZ1+InVbW2GdnM2B6c/7vgVjjJOtIaVScX5iD3StHHebQH+h1AuiX1xXcN7j5OlhU1Pzy/9JMa424LH3ZFGSj4maov5Hw)	|
|-------	|----------	|---------------	|
| 1     	| 3.52x    	| 2.24x         	|
| 2     	| 3.24x    	| 2.49x         	|
| 3     	| 3.62x    	| 2.09x         	|
| 4     	| 3.39x    	| 2.37x         	|
| 5     	| 3.56x    	| 2.46x         	|

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/s2-optimize/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
I'm not deep in the S2 code but these definitely sound like good fixes.

For future PRs, while it sounds extreme, scrutinize every allocation because any allocations that happen in the main loop can really hurt performance (as you've seen). @ptrgags make sure to pay attention to this as well.

And if you haven't used the profiler already you should. Maybe there are some other hotspots that can be optimized.

**Comment by sanjeetsuhag** [comment]
@ptrgags actually [did point this out in the review](https://github.com/CesiumGS/cesium/pull/9506#discussion_r640862379), but the impact wasn't as drastic when I initially profiled this. Maybe because I was profiling with smaller S2 cells.

**Comment by lilleyse** [comment]
Ok good to know that @ptrgags brought it up. That's the type of thing that's worth acting on right away rather than deferring.

**Comment by ptrgags** [comment]
@sanjeetsuhag I tried out your benchmark in a few browsers in Linux, Windows and Android: [s2-optimize.xlsx](https://github.com/CesiumGS/cesium/files/6617951/s2-optimize.xlsx). Results were similar to yours

The code looks good, I just want to try some past sandcastles again before I merge this.

**Comment by ptrgags** [comment]
I tried out the global scale tileset example again as a smoke test, that's working fine. Thanks @sanjeetsuhag!

**Pull request merged**
