### PR TITLE
3D Tiles: Don't double-apply transform from placeholder implicit tile

### PR DESCRIPTION
**Pull request by IanLilleyT**
The placeholder implicit tile transform was being double-applied to its child tile, causing it to go to the wrong spot and not render. This was happening because the `combine` function was copying the parent transform to the child transform and then multiplying with the parent transform again in `Cesium3DTile`. The fix is similar to https://github.com/CesiumGS/cesium/pull/9940.

[Sample Data](https://github.com/CesiumGS/cesium/files/7681284/tileset.zip) - [Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bZHJbtswEIZfhdBJBgLSTS6FqxgFkkuABCnQoCdeGGocT0PNCORIXoq8e6mlTtqal8Es3z8LexdVj7CDqK4VwU7dQMKu0T/GWGkLP/o3TOKQINpi8cWSpT5zbcQGBXvI6KShkwcCfUok7eq6/CA7mavbJwyQQMpflpTqYlgpW2xF2pUxgb0LW06y+rxcXpokTtAbmYA/Vv9MTLaw9LaY5jm11BFcffgWucEEWrZA5aYjL8hULtTYb571yNw8cXkiB6G3hebMxF2G3zmIcUY9U+IAOvDLGB2R6SCTKOwFqC7ndafgX0vfUWrBC8cH3CMN7Ez6s1WjxAPXEPS8ej72aeRMFxdFleQQYD3MN7yv2LQcZThrqbURaNrgBJJ57vxrPp1PaWg7lFbmI1rV2Cusr898uvLBpZQzmy6E73gEW6wrk+v/QwO7GunlsYcY3GEo235a309BrXVlsnueFObw7OI/yr8B)

Before                     |  After
:-------------------------:|:-------------------------:
  |

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/implicitTransformFix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Review by ptrgags — COMMENTED** [review]
@IanLilleyT looks good, could we add an entry to `CHANGES.md`? though the implementation is experimental, now that we've started mentioning 3D Tiles Next stuff in the changelog we're trying to keep it updated.

**Comment by IanLilleyT** [comment]
@ptrgags all set

**Comment by ptrgags** [comment]
Thanks @IanLilleyT!

**Pull request merged**
