### PR TITLE
Simplify Custom Shader Sandcastle examples

### PR DESCRIPTION
**Pull request by ptrgags**
This PR is a draft, this only makes sense if #10067 is merged.

This is a small tweak to some sandcastles. I was using `[].join("\n")` to do multiline shaders, but an ES6 template literal is cleaner. I kept this as a separate PR since these changes can't be detected by `eslint --fix`

@ggetz no rush on this PR

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Review by ggetz — COMMENTED** [review]
Looks good @ptrgags. How about "customer per-feature post process" and "custom post process" sandcastles too?

**Comment by ptrgags** [comment]
@ggetz good point, I'll update the post-processing Sandcastles too! 

I'll also sweep through the sandcastles directory, this reminds me that I had more shaders in the Sandcastle [`development/Custom Primitive`](http://localhost:8080/Apps/Sandcastle/index.html?src=development%2FCustom%20Primitive.html&label=Development), but there could be more out there I'm not aware of.

**Comment by ptrgags** [comment]
@ggetz updated the sandcastles!

**Comment by ggetz** [comment]
Thanks @ptrgags !

**Pull request merged**
