### PR TITLE
Account for degenerate axes of OrientedBoundingBox in distanceSquaredTo

### LINKED ISSUE #9658: `OrientedBoundingBox.distanceSquaredTo` fails when halfAxes have magnitude near 0
This was exposed in the [Particle System Sandcastle](https://sandcastle.cesium.com/?src=Particle%20System%20Fireworks.html) on Windows in Edge and Chrome after implementing the changes reverted in #9657. We considered adding epsilon checks to the OBB during creation, but this is inconsistent with the current behavior of defaulting the halfAxes matrix to the zero matrix.

The bug itself happens in `distanceSquaredTo` when we try to normalize a near-zero magnitude `w` axis. Maybe the math can be reworked in this function to handle this edge case.

### PR DESCRIPTION
**Pull request by j9liu**
Fixes #9658. Before normalizing the `halfAxes`, the function will check if their magnitude is nonzero. If not, it will generate new substitute axes based on which ones are degenerate, then proceed with the same algorithm. I added a bunch of specs to account for these changes.

I'm sure the code organization / style can be cleaned up a bit. @lilleyse - do you mind taking a look?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @j9liu!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Review by lilleyse — COMMENTED** [review]
Overall the approach makes sense and it fits into the current algorithm cleanly, though it feels a little verbose and I wonder if specialized distance functions for each degenerate axes case would be less code and/or faster. The non-degenerate case ought to run fast still which is most important.

Since `distanceSquaredTo` is a hotspot in the code it would be worth benchmarking. The benchmark should create some randomly sized, non-degenerate OBBs, and call `distanceSquaredTo` multiple times for each. You can look at @sanjeetsuhag's sandcastles in https://github.com/CesiumGS/cesium/pull/9599 for reference. Make sure to test with the built version of CesiumJS (~`npm run minifyRelease`~ `npm run combineRelease`, `npm run buildApps`, then go to http://localhost:8080/Build/Apps/Sandcastle/index.html). Run the benchmark on this branch and `master`.

Other than that, very robust tests like usual!

**Comment by j9liu** [comment]
Here's the [benchmark sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=tVdtbyI3EP4rFp9MQwy53EmnwkUNSa496a6ckoi0zUYns2vAqtfe2l4CVPffO/a+L3BJI4Uv9o7nGT8zHs+YUElj0YqzR6bRByTZI7pghqcxmXoZDjqh/75Q0lIumQ463WEgQ49Ts9m51nQDyPuHuvSSzdLFniVNZaTir8pwy0FQLAZynsrQidCCwR7UsuuGJo657KGYrrvo30AipJlNtazTvaDawozKU+wUEPpC7ZJk++Eu+glhQKNjBIa66MgNvdfQc7H5/gyHDHb+5E71wB+TCps7t6Ia8aGbzZVGmEOUBkPE0QhJGI6OcjWUo+75A2g8FTdv7/shcpPZzDNKlPnC89HxMiEVzEuyWcW1GP1J7xB3M4+45PM5sCvQELDCZE0PGITLa2Wp59TIQoi65utT3D2kfuPM/QgDMfxBCEuiTRM72bR7/pV7R1WYXk058wWhivX6XC487Ta8isKSfP30bTK9uv52ezcZVtDNy6Hbl0FrtGvn3DwvMtcqLlb/wJl/3Trt50H/xJsd6PZ50L/wtgGtDOiD+BguAU/EBpf0epWTvXa6FpafYW9bGdFPmatTLG7EAbvjjVfAdZvwXW2y63zIpPXt4UCRaVaNOidoBc2LNdHcGYvGKpURl4uxWuPMfK/pQG/vRW/ZHk+b1m+5YPt2KG4aQEi+W120pGJ+vmYmk5V7+AZIDAAYSTSPwdkVM4RGEfZ7k1AzCIavgFMl0pjhonwooTS5++3T7VW3PPFasQZ4Q+pNlEvjaaNYN2r0u0HJPP8d53teCcETo3hE7n69ef+WQNHncRpf04inpg16LQzqo9M3LwS+b+OK18UeefW+6A7rMWo32ZOB//VQO2hvqpL1v4LwUlzr4VMkRfkLpG+e0XqYzcDHz0wu7DJLCe8qEV6SayTFqLi0plRubVRhAimYRcZCZwO1hGlojDGVISNSPfpe6TtltM57JUxGFQ0vKPtmdbULbvew/FD22ySzkYCFOj2Q1Fqvu3kRB0LA4eaflGoW3Src4n+fPNSfLs4FJqMDDmTrMaOurGKnd5w53IX0ahDJ3qNKMCLUAt645ytInwVDO3yQ5TH7GQUd98YDw9k2jdKwEGrGiAXiRqQgCTeESToTzNG0OmXDpwHQhKT9SEN2LpIlHW8ucx7N8vY7o/oj1a4SUu2L2rvBgGQV4SQfQVKIBuRtAIQ7vc7I2I1gZ0XO/cLjREEapFpgQvqWxYmAy2P6szT8m1kSmjJBR/06dBTxFSTChz1/ClAoqDGwMk+FuOFbFnTORn3Q34EKRV1dnkDIBd04teXJ2edMSAgZ9eFzP9IqJWZUtyz/Bw) (localhost) I used to get the following numbers:

| Run # | `master` | `obb-distancesquared` | times faster than `master` |
| ------ | --------- | ------------------------- | ---------------------------- |
| 1 | 0.004259199999809265 | 0.0033573000001907347 | 1.26863849 |
| 2 | 0.004131300000190735 | 0.0034534000000953674 | 1.1962993 |
| 3 | 0.004191300000190735 | 0.0034055 | 1.23074438 |
| 4 | 0.004239 | 0.0034258000001907347 | 1.23737521 |
| 5 | 0.00422310000038147 | 0.003418300000190735 | 1.23543867 |

It seems that right now, `obb-distancesquared` is slightly faster than `master` -- maybe this is because of the use of `Cartesian3.normalize` (and thus the duplicate call to `Cartesian3.magnitude`) in the original code.

**Comment by lilleyse** [comment]
I'm seeing similar results on Firefox Linux: 0.012589 (`master`) 0.013468 (`obb-distancesquared`) :+1:

**Comment by lilleyse** [comment]
I confirmed this fixes the particle system crash in https://github.com/CesiumGS/cesium/issues/9658 when `TileBoundingRegion` uses an obb distance check.

@kring @baothientran would you like to review as well? Assuming this makes its way back to cesium-native.

**Comment by lilleyse** [comment]
I'm going to merge - but any more feedback is welcome after.

Thanks @j9liu!

**Pull request merged**
