### PR TITLE
Fix typo in Cesium3DTilePass

### LINKED ISSUE #11516: maybe a bug in Cesium3DTilePass.js
hi,  @na9da , there maybe a bug in Cesium3DTilePass.js 

the pass option key is Cesium3DTilePass.PRELOAD,  but the assignment of pass is Cesium3DTilePass.SHADOW

as follows:

passOptions[Cesium3DTilePass.**PRELOAD**] = Object.freeze({
  pass: Cesium3DTilePass.**SHADOW**,
  isRender: false,
  requestTiles: true,
  ignoreCommands: true,
});

### PR DESCRIPTION
**Pull request by jjhembd**
Fixes #11516. There was a copy-paste error in `Cesium3DTilePass` from #11167 which affected the `PRELOAD` pass.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jjhembd!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/pass-options-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Awesome, thanks @jjhembd! Please update `CHANGES.md` with a summary of the fix.

**Comment by jjhembd** [comment]
@ggetz updated!

**Comment by ggetz** [comment]
Thanks @jjhembd! CI is failing due to an unrelated travis error, so I'm going to go ahead and merge.

**Pull request merged**
