### PR TITLE
Apply appropriate styling to error panel

### LINKED ISSUE #8739: Improve styling of error panel
Hey all! One of the areas that I think takes some improvement is the error panel. Whenever I see it in a forum question or Github issue, it feels a bit scary with its dark background 😄. In conjunction with the light color fonts, they create a high contrast situation that is not preserved very well.

I think that the error panel should take an overall re-styling that will be closer to Cesium colors (green, blue) and improve the user experience for users. If you think that this is a good idea, I would love to help with this and submit a suggestion PR.

### PR DESCRIPTION
**Pull request by bampakoa**
fixes #8739 

Here is a preview of the new style:
image

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @bampakoa!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks @bampakoa!  This change looks good to me.  Does anyone else have any feedback?  If not, I'll merge it at the end of the week.

**Comment by bampakoa** [comment]
@hpinkos my PR has the usual merge conflict in the CHANGES.md file 😄 Should I take care of it or wait till it is close to merge?

**Comment by hpinkos** [comment]
I just pushed some styling changes.  I also added functionality to hide the call stack behind a `See more...` clickable link

image

**Comment by hpinkos** [comment]
Since I made some bigger changes, can someone else give this a quick once-over?  @mramato? @emackey?

**Comment by bampakoa** [comment]
@hpinkos the `See more` link looks awesome! From a UX point of view, should we place the OK button on the far right of the panel?

**Comment by hpinkos** [comment]
@bampakoa whether the button should be on the left or the right is a little contested, but you're right, the trend seems to be converging on putting the button to the right.  I had moved it back to the read-line on the left because it looked really strange on a large screen because the button would be sooooo far away from the text.  So to fix that I added a `max-width: 500px` to keep the panel from growing too wide, and I put the button back on the right edge.

**Comment by hpinkos** [comment]
Can someone give this a quick review?  I'd like to get it in for the release tomorrow.  @OmarShehata?  @mramato?

**Comment by OmarShehata** [comment]
Reviewing this now.

**Comment by OmarShehata** [comment]
I think this all looks good to me. The only thing I have is to consider allowing it to grow a little wider. I tested it with a real stack trace on here (http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Styling.html) by changing the "Height" styling to some variable that doesn't exist, and it looks like this:

image

Compared to before:

image

Is there a reason the max-width is set to this current size? I generally find it easier to read stack traces when there's no line wrapping.

Works as expected in IE11 and Edge.

**Comment by hpinkos** [comment]
Good point @OmarShehata, the reason I added the max-width is explained here: https://github.com/CesiumGS/cesium/pull/8960#issuecomment-648961480

I'll resolve this by removing the max-width when you click to see the stack trace

**Comment by hpinkos** [comment]
@OmarShehata ready!

**Comment by OmarShehata** [comment]
Much better, thanks @hpinkos !

**Comment by hpinkos** [comment]
And thanks @bampakoa for getting this started!  This panel was definitely in need of a refresh =)

**Pull request merged**
