### PR TITLE
Google Sandcastle Examples Tweak: Set `globe: false`

### PR DESCRIPTION
**Pull request by ggetz**
Fixes https://github.com/CesiumGS/cesium/issues/11534 by using `globe: false` rather than setting `globe.show = false`. This simplifies the example and also keeps the viewer from making an unneeded background request to Bing Maps.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/google-example-globe/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
- [ ] Once https://github.com/CesiumGS/cesium/pull/11547 is merged, these example should also turn on the sky atmosphere

**Comment by ggetz** [comment]
@jjhembd I've update this based on https://github.com/CesiumGS/cesium/pull/11547 to show the sky atmosphere. Could you please review and merge when ready?

**Review by jjhembd — APPROVED** [review]
Looks good, thanks @ggetz!

**Pull request merged**
