### PR TITLE
Potential fix for Event.raiseEvent() typescript

### PR DESCRIPTION
**Pull request by chris-cooper**
I think this may be a fix for the `Event.raiseEvent()` type, as `Parameters<Listener>` is already a spread `...args: any[]`.  It looks like the additional spread operator is turning it into something like an `...any[][]`.

i.e. `Listener extends (...args: any[]) => void` so `Parameters<Listener>` would be an `(...any[])`

Issue: https://github.com/CesiumGS/cesium/issues/10498

```
    // before
    raiseEvent(...arguments: Parameters<Listener>[]): void;

    // after
    raiseEvent(arguments: Parameters<Listener>): void;
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @chris-cooper!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/raiseEvent-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by thw0rted** [comment]
I've just come up with a slightly terrible workaround, that I think actually kinda-sorta fixes it: https://github.com/thw0rted/cesium/tree/raiseEvent-fix

This manually replaces the invalid TS output during the Gulp post-processing phase.  I've used this crutch in the past to work around things that tsd-jsdoc can't quite do.  It's brittle, but hopefully if it breaks in the future, the simple tests I added will break and someone will notice.

**Comment by chris-cooper** [comment]
Ok thanks @thw0rted .  I've tested your branch on our code and it allows removal of the `@ts-expect-error` s that were introduced with 1.95.  I think it would be preferable to incorporate either your workaround, or even a rollback to a more loosely typed `raiseEvent()` rather than imposing an incorrect type.

**Comment by chris-cooper** [comment]
I've cherry-picked aee2bbfe135f77514c96170c877bce9907d81f0e and merged master in case you want to proceed with this PR, or feel free to close and open a  fresh one @thw0rted .

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Pull request closed without merging**
