### PR TITLE
Locked protobufjs version

### PR DESCRIPTION
**Pull request by ggetz**
# Description

The `build` command errors on a fresh `npm install` due to https://github.com/protobufjs/protobuf.js/issues/2022. This locks the version to the latest working version.

## Issue number and link

https://github.com/CesiumGS/cesium/issues/12143, though I'd like to leave that issue open to track why we have the locked version. We can close it when protobuf addressed the issue.

## Testing plan

1. `git clean -dxf`
2. `npm install`
3. `npm run build`

The last command should succeed without error.

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] ~I have updated `CHANGES.md` with a short summary of my change~
- [ ] ~I have added or updated unit tests to ensure consistent code coverage~
- [ ] ~I have updated the inline documentation, and included code examples where relevant~
- [x] I have performed a self-review of my code

### CODE REVIEW

**Review by jjspace — COMMENTED** [review]
I no longer see the build error in question but I am seeing multiple of these warning blocks that I don't remember seeing before, is this known?



Also it seems protobuf itself already has a fix open, do we want to just wait on this a little in case they release a patch really fast before the next release?
Edit: I now see this is causing CI errors across other branches so it might be good to just get it in asap then revert closer to the release

Also have some CI test errors but I don't get those locally, were those known tests that fail sometimes?

**Comment by ggetz** [comment]
> I no longer see the build error in question but I am seeing multiple of these warning blocks that I don't remember seeing before, is this known?

No, please go ahead and open a separate issue. Offhand it could be due to a new version of esbuild.

**Comment by ggetz** [comment]
> Also have some CI test errors but I don't get those locally, were those known tests that fail sometimes?

Yes, documented in https://github.com/CesiumGS/cesium/issues/11958.

**Comment by jjspace** [comment]
It seems protobuf _was_ really fast on the new release so I'm going to close this. https://github.com/protobufjs/protobuf.js/pull/2023

I opened #12148 for the esbuild warning.

**Pull request closed without merging**
