### PR TITLE
Add Cartesian2.cross

### PR DESCRIPTION
**Pull request by hpinkos**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/cartesian2-cross/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by IanLilleyT** [comment]
Code looks fine but if we use the name "cross product" there might need to be some explanation in the description like `Computes the magnitude of the cross product that would result from implicitly setting the Z coordinate of the input vectors to 0`. More elegant description welcome.

**Comment by hpinkos** [comment]
Works for me, thanks @IanLilleyT!  Updated

**Comment by IanLilleyT** [comment]
Looks good, thanks @hpinkos !

**Pull request merged**
