### PR TITLE
KmlDataSource: fix #9327 handle relative URLs for additional elements - video, audio, iframe etc.

### LINKED ISSUE #9327: KmlDataSource: placemark descriptions handle relative URLs only for img and a tags
**KmlDataSource** handles relative URLs in placemark popup balloon descriptions only for `` and `<a href=>` elements/attributes. Relative URLs for `<video src=>` for example will fail (if the loaded KML is in a different folder to the HTML).

Test case: http://www.tryse.net/cesium-kml/bug2/index.html
Test case with fix: http://www.tryse.net/cesium-kml/bug2/index-fix2.html

The left icon in the test case loads the KML from the source document folder and the `<iframe>`, `<video>` and `<link>` tests work. The popup balloon for the right icon loads the KML from a different folder and the tests fail.
(The `` and `<a>` tests are already covered and work everywhere. The `<script>` checks always fail as they are sanitized out anyway.)

Submitting a pull request that adds support for:
* `<link href=>`
* `<area href=>`
* `<iframe src=>`
* `<video src=>`
* `<audio src=>`
* `<source src=>`
* `<track src=>`
* `<input src=>`
* `<embed src=>`
* `<script src=>`
* `<video poster=>`

Would it make more sense to leave `<script>` off the list...since it's sanitized out anyway for security?

### PR DESCRIPTION
**Pull request by dtryse**
Fix for KmlDataSource issue #9327 to handle relative URLs for additional elements - video, audio, iframe etc.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @dtryse! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/dtryse/cesium/blob/KmlDataSource-relative-URL-fix/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/KmlDataSource-relative-URL-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @dtryse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @dtryse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @dtryse! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @dtryse! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @dtryse! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
I'm not super familiar with KML but the change looks good. The test case in https://github.com/CesiumGS/cesium/issues/9327 was helpful. Thanks @dtryse.

**Comment by dtryse** [comment]
Thanks @lilleyse!

**Pull request merged**
