### PR TITLE
Update knockout to 3.5.1

### PR DESCRIPTION
**Pull request by mramato**
This is just a maintenance update with no changes required on our end.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Node seems to be having an issue, I'll bump when ready.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks @mramato, this change looks good to me.  There was a weird CI failure so I just restarted it to see if it was an actual problem

**Comment by hpinkos** [comment]
@mramato yeah, can you look at the CI failure here?

**Comment by mramato** [comment]
@hpinkos only took 4 weeks, but this is ready :smile:

**Comment by hpinkos** [comment]
:+1:

**Pull request merged**
