### PR TITLE
Allow to set a `pickGroup` to `Entity` and `Primitive`

### PR DESCRIPTION
**Pull request by addam**
This patch allows objects (Primitives and Entities) to be grouped into custom numbered groups. These numbers can later be queried within PostProcess shaders so that each group can be assigned a specific style. The code was created as part of [luucy.ch](https://luucy.ch) project.

For quick overview of the feature, see `Sandcastle/Custom Group Post Process.html`. It is useful for managing large datasets where listing all the pickIds would not work well.

Pick groups require the selection feature to be enabled (by setting `stage.selected = []`) but can be used independently of selection.

Current implementation requires the total number of groups to be defined when creating Cesium Viewer. This requirement is somewhat annoying and could be removed.

I'll add documentation when the code passes some initial review -- I don't know if a feature like this can make it into master.

- [ ] add Documentation
- [ ] add unit tests
- [ ] edit CHANGES.md
- [ ] sign the License Agreement
- [ ] add myself to CONTRIBUTORS.md

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @addam! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/addam/cesium/blob/pick-groups/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/pick-groups/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by addam** [comment]
I'm waiting for any kind of comment whether this feature is welcome or not. Please see `Sandcastle/Custom Group Post Process.html` for a live example.

Then I'll fix the remaining non-functional issues as listed above.

**Comment by lilleyse** [comment]
@addam `PostProcessStageComposite` offers a similar workflow of assigning selected objects to individual post process effects and running together as a logical unit (see [3D Tiles Feature Picking](https://sandcastle.cesium.com/?src=3D%20Tiles%20Feature%20Picking.html)). The sandcastle example you posted takes more of the ubershader approach of packing multiple post process effects into a single shader and switching based on the pick group. I'm curious if you tried `PostProcessStageComposite` and ran into any issues, performance or otherwise.

If we decided to go with pick groups (which I'm not sure yet) the current implementation would need work before we could merge it. `pickGroup` would need to be an actual property on the entities/primitives that use it and the context-level `pickGroups` would need to be removed for something easier to use.

Longer term I would prefer to see a system where feature properties become accessible to post processing shaders. I'm mainly thinking of this in terms of 3D Tiles, like assigning each building a post process id that can be used as a switch in the post process shader, or an index to a color table, or something like that functionally similar to `pickGroup` but more flexible. This might work for entities as well.

**Comment by addam** [comment]
@lilleyse, we want to apply a shader to a specific tileset (planned buildings) with many other tilesets in view. In order to allow selecting any individual building, the `PostProcessStage.selected` list would be huge. We did not actually try that solution -- it just seemed both difficult to manage and badly scalable.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @addam! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by ggetz** [comment]
Thanks @addam, but upon further review, we think this implementation is not general purpose enough for all use cases and are opting to close this PR. If you are still interested in finding a more generic solution want to discuss further, please open an issue.

**Pull request closed without merging**
