### PR TITLE
Fix 3d tiles vctr polylines feature table reading

### PR DESCRIPTION
**Pull request by jtfell**
Fixes as few issues with the .vctr 3d tiles format reader.

 - Use `POLYLINE_COUNTS` instead of `POLYLINE_COUNT` (see [spec](https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/TileFormats/VectorData))
- Read the positions array based on the number of polylines rather than buffer size to avoid reading zero padding at end of array used for byte offset alignment
- Allow widths and counts to be specified directly in JSON or in binary format as per feature table spec

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jtfell!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/3d-tiles-polylines/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
@jtfell thanks for the PR, it's already in really good shape.

I pushed a fix for reading feature table binary properties. This fixes the sample data in [Picking](http://localhost:8080/Apps/Sandcastle/index.html?src=development%2FPicking.html&label=Development) (select `Vector tile polylines`).

I also added a backwards compatibility for `POLYLINE_COUNT` since I know there are a few vector tilesets out there in production without a good way to regenerate them. Once vector tiles becomes part of the core spec sometime in summer/fall we'll remove this workaround and maybe provide some sort of upgrade path.

Do you plan on making the same changes to polygons?

**Comment by jtfell** [comment]
Thanks for looking at this @lilleyse! Your fixes look good to me.

Unfortunately, I don't have a polygon example file on hand so can't easily test any changes to that code path.

**Comment by lilleyse** [comment]
@jtfell I made the changes for polygons. Could you double check them?

I tested [Picking](http://localhost:8080/Apps/Sandcastle/index.html?src=development%2FPicking.html&label=Development) and [3D Tiles Terrain Classification](http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Terrain%20Classification.html) for polygons but I don't have an example that uses feature table array properties, just binary ones.

**Comment by jtfell** [comment]
Everything still works for my polyline and points files (using feature table array properties) and your code changes look good to me @lilleyse.

**Comment by lilleyse** [comment]
@jtfell cool, thanks checking again. I'll merge now.

**Pull request merged**
