### PR TITLE
Added imageUrl and imageScale to GeoJsonDataSource for points

### PR DESCRIPTION
**Pull request by rob-64**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @rob-64!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @rob-64! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @rob-64! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @rob-64! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Review by ebogo1 — COMMENTED** [review]
@rob-64 Thanks for the pull request. A few questions, since I haven't seen the `image-url` and `image-scale` properties in GeoJSON spec before -

1. How are you generating GeoJSONs with those properties? Are these properties that you added for a specific use case?
2. Have you tried using the `fromUrl` function in PinBuilder? It looks like it might be doing the same thing as your change.

https://github.com/CesiumGS/cesium/blob/6f4c4cc7019aad071086effd575a146b76523e3c/Source/Core/PinBuilder.js#L44-L52

**Comment by ggetz** [comment]
Due to lack of activity, I'm going to close this to keep things tidy. @rob-64 If you get a chance to update, please feel free to reopen this! Thank you!

**Pull request closed without merging**
