### PR TITLE
Adds Experimental Sandcastles

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
This PR adds Sandcastles under the Experimental tab to highlight 3D Tiles Next and `ModelExperimental` capabilities.

| | |
| - | - |
| [Model Experimental 3D Models](http://localhost:8080/Apps/Sandcastle/index.html?src=Model%20Experimental%203D%20Models.html&label=Experimental) |  [3D Tiles Next S2 Globe](http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Next%20S2%20Globe.html&label=Experimental) |
| Model Experimental 3D Models | 3D Tiles Next S2 Globe |
| [3D Tiles Next Photogrammetry Classification](http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Next%20Feature%20ID%20Textures.html&label=3D%20Tiles%20Next) | [3D Tiles Next CDB Yemen](http://localhost:8080/Apps/Sandcastle/index.html?src=3D%20Tiles%20Next%20CDB%20Yemen.html&label=Experimental) |
| 3DPhotogrammetry Classification | 3D Tiles Next CDB Yemen |

To-Do:
- [x] Update old Yemen CDB with asset hosted on CesiumJS ion account

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/model-experimental-sandcastle/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by lilleyse** [comment]
Meta feedback:

* Rename `Experimental` to `3D Tiles Next` for better discoverability - it's ok if some of the examples are individual models
* Move `Custom Shaders ModelExperimental` into the `3D Tiles Next` tab. Rename it to `Custom Shaders Models`
* Move `Custom Shaders 3D Tiles` into the `3D Tiles Next` tab as well
    * Let's get some more interesting style here - e.g. elevation gradient, color by proximity to a center point, etc.
    * CC @ptrgags for ideas.

3D Tiles Next CDB Yemen

* The view starts too far out. Maybe go with a zoom-in effect like the Montreal Point Cloud demo. Also add some preset views like the Montreal demo.
* Set a specific time so that the buildings are well lit. Also consider increasing the light intensity. 
* Is it possible to "upsample" the raster materials onto the high res terrain and re-export the 3D Tiles. It's distracting to see it blip out when zoomed in.
* Increase the maximumScreenSpaceError for the buildings tileset to avoid some sluggishness
* Take more from the previous two demos - the UI elements and mouse-over picking really made those demos stand out - https://github.com/CesiumGS/cdb-to-3dtiles/blob/c943875e251564af32e3cc7a1d152d2cb96db72e/README.md#demo

S2 Base Globe

* Start the default view a bit further out
* Add a "Pick classification" toggle button for hover-over picking
* @ptrgags do you have any low-effort ideas for making the water effect not fixed to the view?

Model Experimental 3D Models

* Maybe rename to just `Model Experimental`
* Wherever appropriate place models on the ground. It's a bit odd to see vehicles and such floating.
* Change the camera angle so it isn't looking straight on. Maybe use an oblique angle like the `3D Models` sandcastle

I'll check out the code more closely after these changes.

**Comment by ptrgags** [comment]
@sanjeetsuhag just a heads up, I have another sandcastle to add to your branch

**Comment by ptrgags** [comment]
Just pushed my sandcastle

**Comment by ptrgags** [comment]
Just added a different shader for the S2 base globe, as the previous one was based on code that had an unclear license.

**Comment by sanjeetsuhag** [comment]
@lilleyse Addressed all your feedback.

**Review by ptrgags — COMMENTED** [review]
@sanjeetsuhag `Model Experimental 3D Models.png` seems to be an extraneous file

**Comment by ptrgags** [comment]
@sanjeetsuhag looks good, I'll merge once CI passes

**Comment by ptrgags** [comment]
Merged! thanks @sanjeetsuhag!

**Pull request merged**
