### PR TITLE
Use more concise syntax for PipelineStage constants

### PR DESCRIPTION
**Pull request by jjhembd**
As suggested by @ptrgags in https://github.com/CesiumGS/cesium/pull/10683#discussion_r968563051, this PR updates the declaration of PipelineStage constants to use a more concise syntax. 

The new syntax is consistent with what we already have in MetadataPipelineStage.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jjhembd!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/pipeline-constants/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by sanjeetsuhag** [comment]
@jjhembd or @ptrgags: What about functions that are exposed for testing by being attached to the main export? For example,

https://github.com/CesiumGS/cesium/blob/6711352fac656b7a30c2403b9980383ed6498d17/Source/Scene/Model/InstancingPipelineStage.js#L1038-L1040

Do we want to attach these at the top too, for discoverability? I think it's also ok to leave them as is, just wanted to make sure we're covering everything.

**Comment by jjhembd** [comment]
> What about functions that are exposed for testing by being attached to the main export?

Thanks @sanjeetsuhag, I think it makes sense to use similar syntax for these. I just updated `InstancingPipelineStage`, along with `CustomShaderPipelineStage`, `MaterialPipelineStage`, and `PrimitiveStatisticsPipelineStage`

**Comment by sanjeetsuhag** [comment]
@jjhembd The changes here look good, but there's several other `Source/Scene/Model/*PipelineStage.js` files that need to be updated to match this syntax.

**Review by sanjeetsuhag — APPROVED** [review]
Changes look good! I ran the `Scene` spec suite, just to make sure, and ran into no issues there. Thanks @jjhembd!

**Pull request merged**
