### PR TITLE
Extension of the use cases to classify a tileset with a B3DM tileset [with Draco]

### PR DESCRIPTION
**Pull request by ppoulainpro**
Extension of the use cases to classify a tileset with a B3DM tileset.

**Removed restrictions:**
- Only one node is supported for classification and it must have a mesh.
- Only one mesh is supported when using b3dm for classification.
- Only one primitive per mesh is supported when using b3dm for classification.

**Updated restrictions:**
- The mesh primitive must have a position attribute.
- The mesh primitive must have a batch id attribute.
- Capacity to use Draco compressed GLTF.

**This PR replaces PR #8274**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ppoulainpro!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
@ppoulainpro sorry for the long delay, I think this is a good fix and I'll try to find some time soon to review it.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@lilleyse bump

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
Hi @ppoulainpro , I was trying to test this but the version in this PR doesn't seem to be working? I get the following error trying to build:

```
npm run build

> cesium@1.62.0 build /home/omar/Workspace/cesium
> gulp build

(node:7207) ExperimentalWarning: The ESM module loader is experimental.
ReferenceError: require is not defined
    at file:///home/omar/Workspace/cesium/gulpfile.js:4:10
    at ModuleJob.run (internal/modules/esm/module_job.js:139:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

Copying your changes in `ClassificationModel.js` to `master` produces a `Error: Could not resolve '../Core/defineProperties.js' from Source/Scene/ClassificationModel.js` because it looks like that was changed to just be `Object.defineProperties` (but then I got further errors after fixing that).

**Comment by ppoulainpro** [comment]
Hi Omar,
The PR has been done one year ago on 1.62 when the major reorganisation to support ES6 (1.63) was in preparation.
After some other updates has been done in Cesium:

- remove of  define properties (1.67)
- 1.69 rework of the code formatting rules
- and some other few fixes ->1.71

I will share to yo in pm the current ClassificationModel.js I have in my private repo in 1.73, you can test with it.
Pascal

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ppoulainpro! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
I'm planning on fixing this in the [`model-loading`](https://github.com/CesiumGS/cesium/tree/model-loading) refactor branch, though it's not ready for testing yet. Just to keep the PR list tidy I'm going to close this. Thanks @ppoulainpro.

**Pull request closed without merging**
