### PR TITLE
Remove deprecated API for 1.107

### PR DESCRIPTION
**Pull request by ggetz**
Fixes https://github.com/CesiumGS/cesium/issues/11195
Fixes https://github.com/CesiumGS/cesium/issues/11259
Fixes https://github.com/CesiumGS/cesium/issues/11375

Removes deprecated APIs and cleanup corresponding specs in preparation for the 1.107 release.

TODO:
- [x] Fix `I3SDataProvider` and related specs
- [x] Fix TS errors
- [x] Merge `main`

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
For the most part, this was a pretty wrote find & remove/replace. There were some updates needed to unit tests in order to ensure everything was up to date with the newer APIs. In particular, I3S specs needed some significant cleanup due to tightly coupled specs. I removed a few specs which were really testing mocks more than the actual classes.

@jjhembd I think this is ready for review.

**Review by jjhembd — APPROVED** [review]
Thanks @ggetz, this looks good to me! There were a couple things in the voxels sandcastle that still looked like the old API. I pushed a quick fix for those.
Once CI passes, I think this is ready to merge.

**Comment by ggetz** [comment]
Thanks @jjhembd!

**Pull request merged**
