### PR TITLE
Improve ImageryLayer.cancelReprojections() handling

### LINKED ISSUE #6021: Some tiles not get loaded when switching terrainProvider
If you change terrainProvider during reprojection of the tile, right after
```
            this.state = ImageryState.TRANSITIONING;
            this.imageryLayer._reprojectTexture(frameState, this, needGeographicProjection);
```
gets called, Imagery stucks in TRANSITIONING state and prevents tile from loading. It is happens because `cancelReprojections` gets called.

is method `tileProvider.cancelReprojections` affects something at all? Maybe we could remove it? If you comment it out, everything seems working fine.

In our application terrainProvider is changed early and it randomly causes one or two halves of the globe not loaded:
half

### PR DESCRIPTION
**Pull request by kring**
Same as #9161 but in the main cesium repo, since I don't have commit access to @chris-cooper's branch. Also updates CHANGES.md.

This looks good to me, but someone else should review because I wrote it a year-ish ago.

We reproject web mercator imagery to geographic using a ComputeCommand. When the reproject command is created, we flip the imagery tile to the `TRANSITIONING` state. When the command completes, the state becomes `READY`. The problem is, when a new terrainProvider is set, `cancelReprojections` gets called, which simply throws away all pending imagery layer compute commands. If that happens after the reproject command is created but before it executes, then the imagery tile will _never_ exit the `TRANSITIONING` state and any terrain tiles that its attached to will never be able to render.

So this PR extends a `ComputeCommand` with a `canceled` callback, and calls the callback before the command is thrown away. That way the imagery tile knows that it still needs to be reprojected later with a new command.

Fixes #6021

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @kring!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@IanLilleyT @lilleyse @likangning93 any chance one of you can review/merge this for the release tomorrow? (Only if it's the clear cut good change we think it is of course)

**Comment by lilleyse** [comment]
I can't seem to trigger the problem where half the globe is missing but I do occasionally see lower-res imagery get stuck, which is fixed on this branch.

globe-side

**Comment by lilleyse** [comment]
I pushed a small style fix: https://github.com/CesiumGS/cesium/pull/9163/commits/3f81df1bf0ca32fe9d6a2c7d3921e4f830049608

**Pull request merged**
