### PR TITLE
Adds boundingSphere and debugShowBoundingVolume to ModelExperimental

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
This is a pretty simple PR in terms of features being added, but it'll pave the path for how we want to handle dynamic updates (cases where we need to modify or reset draw commands).

Additionally, implementing this revealed a flaw in the way we were handling the `readyPromise`. The model is not considered ready in `Model.js` until the first `update()`, so I fixed that here.

Here is a [local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=xVdbj+I2FP4rFk8ZKZMwHXa3peyoZW4daVHRQmcemj6Y5ABWHRvZDoRW89977FwIbGjLbtlKgGP7XL5zMf6ypoqsGWxAkfdEwIbcgmZZGjy7NS/qxG5+K4WhTICKOhffRyISYUhGMgFOxlIbJgUTi0is0dhKamYX0Fxp6pYqg09UXAdzJdM7WCgA7UWCkMurb66D7rte7+3Vd75d6PWC7pvu9bvuWzd9042E9WcNL1cHEH8CmqDbMTPx8qPk3Ov6xH4qhTnLIXlQNIWpokLPpUp3oOolHXAZU17IyYda5xEwWmqkckCjjpDKLKOOX8w2oE3UKcA106EL16l7Rm+/WvE/7Q8hBnLTR92hlOlQ5qUtQqTQwCHGvXkmYpc776JSIqTYdNa9as1CCCcriHV4Rw0NC9/hePgxLK1XY7DgZm6RFmoWrx1f7fDqt6LL71OmNVvD2RDWHprPn4P0F8GZOR9MZ75++ByAT0IbKmJIzgDyEeF8kDQBFTY9hQs+fQhnMr9k1dIXIXcnhVOL9OsF0XDaEs+l2W3/V7G9MLMcMTGi+f8S5c79P8R7mTL80vyL4n4SBhQHuv6ajdlw2hYj222fHNuIxUrGUqfnjaZ2U+BPq+nJeKcKr8MFB1t1mZknkTC8Z88Lvt1nEUn73ulhbeSEJZCMORXnuj32fOzPTsb7DMhM8lvJpZq6C/0siA+8HM5PRv0C1CwtEztnt5ROivbYFJO/RRqJ3xwXsvQngVm2mCzlZigzYTnas+RZCsiH5pRrKPlZAQwS59zp1vibmDPFy2gKnhroGKlZsFIsRaK5xjZVkMo1/IgMsIC0ZxidHtOjSVJmpCSFTuE+XwHKABJe7girzYpXpxPh9O2PXy0wESMAJ863NntTrFOmQPeLaGtBRwpH1CiW91to6PKAzjbJaKNwFb/2d0vIjBuz0vI952ylJUuCl8fJt72GQAsvrktaix0pYf/YRtkKF3YsqvBJJbBONNmOMaNMQ4ANJbyWhi2LFSM8RYM5305l5WmywiYEb9/obG/T3/V9kil3YfZJtwLncLnhtaDtEyqSmGrDwTbDVEo+o2oEIvMKBm9FD2UW+D85zIyRAt+ObCLInU0JqVCSMiEd/1iu/MZBtYjiJcS/400syiSwOfHKKiYwx7euZD/mizpZxw9aabM8ovsp+3damCJMVcfvDLTZcrip8voDS1f4LmTPgBcEoYF0hcwEb5JZhromiLWu/hkGYVN1kLA1Ycn7lndKEnOqNe7MM84n7A/M3s0gRPlPVLl0p+TnNXIFurViy6ubD8ViEASDEKftmqao7oHlvwA) for testing.

@ptrgags Let me know your thoughts on how the update pattern is implemented here and what your suggestions are for improving it. I think we may want to move some update functions to `ModelExperimentalSceneGraph` but we may risk making that file a monolith.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
> Additionally, implementing this revealed a flaw in the way we were handling the `readyPromise`. The model is not considered ready in `Model.js` until the first `update()`, so I fixed that here.

`Model.js` also waits until after the first update so that the user sees the correct bounding volume. Maybe that is relevant here as well? `Primitive.js` does the same sort of thing.

https://github.com/CesiumGS/cesium/blob/ffcc025a9ed8c9f54e7d7ce6cb09bf89bcdac273/Source/Scene/Model.js#L5657-L5665

**Comment by ptrgags** [comment]
@sanjeetsuhag looks good, I'll merge once CI finishes.

**Comment by ptrgags** [comment]
Merged! Thanks @sanjeetsuhag!

**Pull request merged**
