### PR TITLE
Sandcastle: Update Codemirror + JSHint to support ES6+ syntax

### PR DESCRIPTION
**Pull request by ptrgags**
when using Sandcastle locally for debugging, I've found it quite annoying that the linter complains about my use of ES6 syntax which I find helpful for prototyping quickly.

I know that there are lots of things that could be better in Sandcastle, but this one was easy to fix in the short term. I updated CodeMirror to 5.52.0 and JSHint to 2.11.0 to support ES6 syntax and beyond in Sandcastle. 

As far as I could tell from searching the code, this shouldn't impact anything beyond Sandcastle, but please correct me if there are any other side effects I'm not aware of.

I set `esversion: 10` in the Sandcastle `.jshintrc`. Maybe that's a bit presumptuous of a setting, but it allows the most flexibility for the user, and it will probably make this tweak effective for a longer period of time without further maintenance.

[No errors! (Sandcastle example)](http://localhost:8080/Apps/Sandcastle/index.html#c=bVNNb9swDP0rXDAgzurISdrtEidY0WG7DNuhwC5xgCo23WhVpEySE7tF/vsofyXtphsfHx/JR+jADRwEHtHAAhQe4Q6tKHbsV40Fw7QO77RyXCg0w9E8UYmKIiDIOuAqA4kONkJlQj3ad4lK60SuNQleE7tOcy8/62q/oHWmSF1hqAZsReJlLZVrM9Y5SK33Z6k9F8ZS+Wo1DWG2DmF1HcLNek1qxIegYa3KEKo1UHXNH8FLooCez2qJTOrHwFP8Aqd2jltqnQI/ctFsgvYT5OjSbTCCvFCpE1rRGLymdUDDuP0qJAZ9F4O0jGqlGomh0m7Mxwa5HOdEZr+tVsO2/aUGc1tUwcWcI5Zyr9BBaIw2vfH3e5LMWtd6k7gxU+/RTQgfvTM9OvOoNy4Eso0x5pkdozPG8/oG35AOzR1Z263sb9Gv/wEUp2W5/FHsNmjs2QR/6ZLaTeZNfNzSfhDQqbHn+FcJlBmU8zNSXl210amx53zX0p/0bcf/Xvfh/Ut5Avun4AYzEBYopmnL08OoFRc5BCUsFzCdTF5NtCFLny4mGISD2LpK4rLBPovdXhsHhZEBY5HD3V5yhzbaFOkTOpZa63vEUVcUZ+IAIlskgzcfKBlAKrm1lMkLKe/FMyaDZRwR/1WZ1Nx/qJ8HNJJXnrKdLr83IB0xjij8t8ppLemvXSj+BQ)

@lilleyse
@emackey (Sean suggested I tag you as well)

### CODE REVIEW

**Comment by lilleyse** [comment]
This is really welcome change!

I'm not the best person to review but I can confirm it works locally and when built:

[Non built version](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/sandcastle-es6-syntax/Apps/Sandcastle/index.html#c=bVNNb9swDP0rXDAgzurISdrtEidY0WG7DNuhwC5xgCo23WhVpEySE7tF/vsofyXtphsfHx/JR+jADRwEHtHAAhQe4Q6tKHbsV40Fw7QO77RyXCg0w9E8UYmKIiDIOuAqA4kONkJlQj3ad4lK60SuNQleE7tOcy8/62q/oHWmSF1hqAZsReJlLZVrM9Y5SK33Z6k9F8ZS+Wo1DWG2DmF1HcLNek1qxIegYa3KEKo1UHXNH8FLooCez2qJTOrHwFP8Aqd2jltqnQI/ctFsgvYT5OjSbTCCvFCpE1rRGLymdUDDuP0qJAZ9F4O0jGqlGomh0m7Mxwa5HOdEZr+tVsO2/aUGc1tUwcWcI5Zyr9BBaIw2vfH3e5LMWtd6k7gxU+/RTQgfvTM9OvOoNy4Eso0x5pkdozPG8/oG35AOzR1Z263sb9Gv/wEUp2W5/FHsNmjs2QR/6ZLaTeZNfNzSfhDQqbHn+FcJlBmU8zNSXl210amx53zX0p/0bcf/Xvfh/Ut5Avun4AYzEBYopmnL08OoFRc5BCUsFzCdTF5NtCFLny4mGISD2LpK4rLBPovdXhsHhZEBY5HD3V5yhzbaFOkTOpZa63vEUVcUZ+IAIlskgzcfKBlAKrm1lMkLKe/FMyaDZRwR/1WZ1Nx/qJ8HNJJXnrKdLr83IB0xjij8t8ppLemvXSj+BQ)
[Built version](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/sandcastle-es6-syntax/Build/Apps/Sandcastle/index.html#c=bVNNb9swDP0rXDAgzurISdrtEidY0WG7DNuhwC5xgCo23WhVpEySE7tF/vsofyXtphsfHx/JR+jADRwEHtHAAhQe4Q6tKHbsV40Fw7QO77RyXCg0w9E8UYmKIiDIOuAqA4kONkJlQj3ad4lK60SuNQleE7tOcy8/62q/oHWmSF1hqAZsReJlLZVrM9Y5SK33Z6k9F8ZS+Wo1DWG2DmF1HcLNek1qxIegYa3KEKo1UHXNH8FLooCez2qJTOrHwFP8Aqd2jltqnQI/ctFsgvYT5OjSbTCCvFCpE1rRGLymdUDDuP0qJAZ9F4O0jGqlGomh0m7Mxwa5HOdEZr+tVsO2/aUGc1tUwcWcI5Zyr9BBaIw2vfH3e5LMWtd6k7gxU+/RTQgfvTM9OvOoNy4Eso0x5pkdozPG8/oG35AOzR1Z263sb9Gv/wEUp2W5/FHsNmjs2QR/6ZLaTeZNfNzSfhDQqbHn+FcJlBmU8zNSXl210amx53zX0p/0bcf/Xvfh/Ut5Avun4AYzEBYopmnL08OoFRc5BCUsFzCdTF5NtCFLny4mGISD2LpK4rLBPovdXhsHhZEBY5HD3V5yhzbaFOkTOpZa63vEUVcUZ+IAIlskgzcfKBlAKrm1lMkLKe/FMyaDZRwR/1WZ1Nx/qJ8HNJJXnrKdLr83IB0xjij8t8ppLemvXSj+BQ)

**Comment by mramato** [comment]
While I welcome this change, the main reason we limited Sandcastle to older JS versions was so that we can maintain IE11 compatibility in our examples.   However, I think ultimately not using newer JS syntax makes our examples harder for new users to read and understand (because stuff like async/await is the norm in modern JS).

IE11 has been slowly fading away into obscurity, so I'm perfectly fine with taking this step, but wanted to bring it up for discussion.

**Comment by ptrgags** [comment]
@mramato yeah that's the kind of consideration I wasn't sure about.

The compromise I had in mind might be to keep writing official examples in the older style (so long as long as IE11 needs to be supported), but still allow the editor to support newer syntax to allow flexibility for the end user.

**Comment by ptrgags** [comment]
Wonderful, thanks @emackey!

**Pull request merged**
