### PR TITLE
Move Gltf-Pipeline to Source/Scene

### PR DESCRIPTION
**Pull request by ebogo1**
Part of https://github.com/CesiumGS/cesium/issues/9473. 

Since there were eslint errors throughout I had to add a line to .eslintignore. Should these be fixed in Gltf-Pipeline? As far as I could tell they were all in one file so it shouldn't be to big of a fix.

Should there be a CHANGES.md line for this?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ebogo1!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by ebogo1** [comment]
Build issues look to be due to prettier no longer ignoring GltfPipeline and something else with the tsconfig stage that I'm looking into.

**Comment by lilleyse** [comment]
Thanks, once you have the tooling issues sorted out this should be good to merge. Eventually we'd like to use npm instead. Can you open an issue for that?

I checked over all the files to make sure gltf-pipeline wasn't getting into the CesiumJS documentation. I noticed that some functions weren't marked as `@private`. I pushed a fix in gltf-pipeline here: https://github.com/CesiumGS/gltf-pipeline/commit/93f69ec1e6e13b451f7508f4bd16829df1b5ba5e and made the same fix here: https://github.com/CesiumGS/cesium/pull/9699/commits/c0be36390327217e9798ed193693cd24e736e747
> Should there be a CHANGES.md line for this?

Nope, this is all internal so no `CHANGES.md` entry required.

**Comment by ebogo1** [comment]
It looks like I was using an outdated version of `gltf-pipeline`. To revert the `prettier` changes I added a line in 3764981 to .prettierignore and copied the files over from the latest commit in `gltf-pipeline`, which looks like it added a few lines for meshopt in `removeUnusedElements.js`.

**Comment by ebogo1** [comment]
@lilleyse I had to restart CI for a bunch of spec errors that I couldn't reproduce locally with our Travis build steps and it worked the second time. I think this is good to merge.

**Pull request merged**
