### PR TITLE
Add Dependabot for Github actions

### PR DESCRIPTION
**Pull request by pjonsson**
# Description

Dependabot will submit pull requests
when packages get new versions released.
After merging this, Dependabot should
open pull requests that resolve the warnings
for the workflows in the actions tab,
as seen here for example:

https://github.com/CesiumGS/cesium/actions/runs/8487635213
image

Link to Dependabot documentation:

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

## Testing plan

Does not do anything to the repository/production code, only difference is that Dependabot will open pull requests for updating Github action versions after this is merged.

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have update the inline documentation, and included code examples where relevant
- [X] I have performed a self-review of my code

### CODE REVIEW

**Comment by pjonsson** [comment]
I have signed the CLA and added myself to contributors (but I feel adding myself to contributors for a trivial thing  diminishes the value of those who do the real work), not sure why github-actions bot is not updating the status.

**Comment by ggetz** [comment]
Thanks @pjonsson! 

This update is scope just for dependabot to update action versions, not other dependencies, correct?

**Comment by ggetz** [comment]
Got it, thanks @pjonsson! We'll give this workflow a try.

**Comment by pjonsson** [comment]
@ggetz it looks like the PRs opened by dependabot were merged. Do you want me to look into getting dependabot configured for submitting PRs for updating nodejs dependencies for this repository?

**Comment by ggetz** [comment]
Not yet; though we may do so soon.

**Pull request merged**
