### PR TITLE
Create 1bikeride.kml

### PR DESCRIPTION
**Pull request by giovannigabriella**
I'm tryimg to undestand the roles of this services

Yhank You

"...Our Horizons are Your Horizons..."

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @giovannigabriella! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/giovannigabriella/cesium/blob/patch-2/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/patch-2/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by giovannigabriella** [comment]
Thank U, for the suggests but it's the first time for me.
Is it possible to have an help to verify this script.
Thank U Community

**Comment by giovannigabriella** [comment]
Ok everything is right?
is possible to verify if these rows are right?
______________________________________________________________________________________________________________________________var viewer = new Cesium.Viewer("cesiumContainer");
var options = {
  camera: viewer.scene.camera,
  canvas: viewer.scene.canvas,
};

Sandcastle.addToolbarMenu(
  [
    {
      text: "gx KML extensions - Bike Ride",
      onselect: function () {
        viewer.dataSources
          .add(
            Cesium.KmlDataSource.load(
              "../SampleData/kml/1bikeRide.kml",
              options
            )
          )
          .then(function (dataSource) {
            viewer.clock.shouldAnimate = false;
            var rider = dataSource.entities.getById("tour");
            viewer.flyTo(rider).then(function () {
              viewer.trackedEntity = rider;
              viewer.selectedEntity = viewer.trackedEntity;
              viewer.clock.multiplier = 30;
              viewer.clock.shouldAnimate = true;
            });
          });
      },
    },
  ],
  "toolbar"
);

Sandcastle.reset = function () {
  viewer.dataSources.removeAll();
  viewer.clock.clockRange = Cesium.ClockRange.UNBOUNDED;
  viewer.clock.clockStep = Cesium.ClockStep.SYSTEM_CLOCK;
};
_______________________________________________________________________
Like U can read i'm trying to call "1bikekml" in "sandcastle.cesium.com".
But the service by cesium gives an error 404.

Thank U community

**Comment by OmarShehata** [comment]
@giovannigabriella it sounds like you're looking to learn how to visualize your KML file with CesiumJS? If so, please use the Cesium community forum (https://community.cesium.com/) to search for answers and ask your questions.

You can drag and drop a KML file into your Cesium ion account (https://cesium.com/ion/) to host and visualize it. You may find this tutorial on creating your first app useful: https://cesium.com/docs/tutorials/interactive-building-proposal/

**Pull request closed without merging**
