### PR TITLE
dayAlpha and nightAlpha in the ImageryLayer

### PR DESCRIPTION
**Pull request by epranka**
Yesterday I created this pull request: #8862. But I closed it because, after some tests, I found that it has a big issue than using the multi-layers setup. Sorry for that, I had to test more before opening the pull request.

But today I create it again with improvement. I added the two options to `ImageryLayer`:

 - `dayAlpha`: The alpha blending value of this layer on the day side of the globe.
 - `nightAlpha`: The alpha blending value of this layer on the night side of the globe.

This only takes effect when `enableLighting` is `true`

The main reason to do this was to have day and night Earth textures depending on the lighting as an example below.

Also, I created the showcase of it called **Night textures on the shade side** in the *Sandcastle*.

Earth night textures example

Sample usage code (from showcase):

```js
var globe = new Cesium.Globe();
globe.enableLighting = true;
globe.dynamicAtmosphereLightingFromSun = true;
globe.showGroundAtmosphere = true;

var clock = new Cesium.Clock({
  multiplier: 4000,
  shouldAnimate: true,
});

var viewer = new Cesium.Viewer("cesiumContainer", {
  imageryProvider: new Cesium.IonImageryProvider({ assetId: 3845 }),
  clockViewModel: new Cesium.ClockViewModel(clock),
  globe: globe,
});

var nightLayer = viewer.imageryLayers.addImageryProvider(
  new Cesium.IonImageryProvider({ assetId: 3812 })
);

// Line below sets that nightLayer invisible on the day side of the globe.
// So it only visible on the night side.
nightLayer.dayAlpha = 0.0;
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @epranka!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks for the pull request @epranka!  This is a really cool feature.  @lilleyse  or @IanLilleyT would you be able to take a look at this?

**Comment by IanLilleyT** [comment]
Thanks for the feature @epranka ! I just reviewed it and the only major change I made was moving this behavior to the [Earth at Night sandcastle](http://localhost:8080/Apps/Sandcastle/index.html?src=Earth%20at%20Night.html) instead of its own. Toggle `Dynamic lighting` to see it in action.

If anyone else wants to take a quick look at this before the month is over, please do! This should be able to fit in the June release if all goes well.

**Comment by hpinkos** [comment]
Looks good to me!  @IanLilleyT do you want to merge this?

**Pull request merged**
