### PR TITLE
Updates protobufjs version to 7.0.0

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
~~This takes care of [this really annoying issue](https://github.com/CesiumGS/cesium/issues/10173) that would cause the debugger to always catch two exceptions in this dependency if you had enabled pausing on exceptions. The [latest version of `protobufjs`](https://github.com/protobufjs/protobuf.js/blob/master/CHANGELOG.md) solves this issue.~~ 

Seems like it's still an issue - I can't trigger it from the browser anymore, but it still happens in VSCode Debugger.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/protobuf-7-0-0/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag! Can you also run `build-third-party` to update the licensing info?

**Comment by ggetz** [comment]
@sanjeetsuhag See a [script update here](https://github.com/CesiumGS/cesium/pull/10573) for `build-third-party`.

**Comment by sanjeetsuhag** [comment]
@ggetz Updated.

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag!

**Pull request merged**
