### PR TITLE
Refactor "Source/ThirdParty" imports

### LINKED ISSUE #10568: Refactor "Source/ThirdParty" imports
Modules which are simply imported and exported in [`Source/ThirdParty`](https://github.com/CesiumGS/cesium/tree/main/Source/ThirdParty) are not strictly needed now that we no longer need to package them ahead of time for development, and most likely should not be exported from `Cesium.js`.

They should be removed, and anywhere in the code which relies on these files should instead require the node module directly.

### PR DESCRIPTION
**Pull request by nshen**
Fixes #10568 

As @ggetz mentioned, anywhere in the code which relies on these files should instead require the node module directly.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @nshen! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/nshen/cesium/blob/main/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/CesiumGS/cesium/blob/main/LICENSE.md) and that its license information is up to date with this new version.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by nshen** [comment]
image

**Comment by nshen** [comment]
Hi, I don't know why the coverage command failed, even I checkout the main head.

**Comment by ggetz** [comment]
Thanks for the PR @nshen! It looks like the coverage command is failing due to the `Uri` import.

Perhaps this PR would be easier to review if it's broken up into individual PRs for each dependency. That way we can verify functionality and if anything breaks it's easy to identify the issue.

**Comment by nshen** [comment]
Thanks for the replay @ggetz , I'll request them one by one,here is the first one https://github.com/CesiumGS/cesium/pull/10660

**Pull request closed without merging**
