### PR TITLE
Entity.merge does not overwrite _children.

### PR DESCRIPTION
**Pull request by i-tengfei**
Fix https://github.com/CesiumGS/cesium/issues/11101

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @i-tengfei! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/i-tengfei/cesium/blob/main/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks @i-tengfei! We'll review this shortly. In the meantime, could you please add your name to `CONTRIBUTORS.md` and a new item to `CHANGES.md` summarizing the change? This will likely go out with the 1.104 release.

**Comment by ggetz** [comment]
Thanks @i-tengfei, changes look good. 

I tried to merge in `main` and resolve the conflicts, but I get `permission denied` when pushing to your branch.

Would you mind resolving the merge?

To do so in `CHANGES.md`, I moved your item to the next release:

```
### 1.104 - 2023-04-03

#### @cesium/engine

##### Fixes :wrench:

- Fixed issue where passing `children` in the Entity constructor options will override children. [#11101](https://github.com/CesiumGS/cesium/issues/11101)
```

**Comment by ggetz** [comment]
Great, thank you @i-tengfei!

**Pull request merged**
