### PR TITLE
Add Transforms.eastNorthUp

### PR DESCRIPTION
**Pull request by vrana**
I need to keep the camera where it is and just point it to an entity I'm about to track. `Entity.viewFrom` accepts east-north-up and I don't see an obvious way how to compute it from the entity and camera positions.

This function does that in a dumb way - just create two points (one south from the entity and one down below camera) and compute the distance to them. Maybe it could be done easier with some matrix operations but I don't understand them.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @vrana!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks @vrana ! I know you mentioned your use case in your forum thread here (https://community.cesium.com/t/do-not-move-camera-when-setting-trackedentity/9554/3?u=omar) - could you create a minimal [Sandcastle example](https://sandcastle.cesium.com/index.html?) to help us test this and determine if there's a better approach to computing this? Or may be helpful to re-use the setup in one the existing sandcastles like this: https://sandcastle.cesium.com/index.html?src=Interpolation.html

**Comment by vrana** [comment]
I've added a Sandcastle example. Notice how the camera stays in the place when the Go/Stop button is repeatedly pressed. Also notice how the camera can freely move while the plane is not flying.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @vrana! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks for the PR @vrana.  However, I don't think this is one we're going to take.  It's a little too specific of a use case to be included in the `Transforms` core class.  I think this kind of calculation is better handled by your application than as part of the library.

**Pull request closed without merging**
