### PR TITLE
Add option to give billboard canvas image cache identifier

### PR DESCRIPTION
**Pull request by Nadav42**
realted to issue #6477, currently canvases get random ids which makes billboards not use the same texture in the TextureAtlas.

I made it that if the canvas has an id attribute then it will use that as the imageId, this should also give us more control if we want multiple billboards to use the same canvas image in the TextureAtlas

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @Nadav42! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Nadav42/cesium/blob/master/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by Nadav42** [comment]
@cesium-concierge

**Comment by thw0rted** [comment]
I'm not sure this is a desirable feature. Look at the other ways that images are indexed in the cache:

* If the reference is a string, it's a URL (possibly data-URL), which the user agent reasonably expects to fetch or decode once and display
* If it's an `img` or `video` tag, the `src` attribute is used; that's a URL, see above
* If it's anything else, a GUID is generated

In the first two cases, the URL can be treated as pointing to an *immutable* image (or video).  In the last case, the texture atlas captures a *snapshot* of the content at this moment and assigns a GUID to it.  The problem with passing a canvas element then caching it by ID is that the content could change.

I know it's a bit contrived but consider

````js
const scratch = document.createElement("canvas");
scratch.id = "scratch";
function drawUpdates(data, ent) {
  const context = scratch.getContext('2d');
  context.clearRect(0, 0, scratch.width, scratch.height);

  data.drawOnAContext(context);

  ent.billboard.image = scratch;  // Why won't this draw the update?!?
}
````

If you know that the canvas's ID is used, you could update it, but if you didn't know that (or just forgot) you won't know why it's failing. The point is, this can cause surprising, difficult-to-diagnose behavior. I think the current default behavior (caching by URL) makes sense, because the URL should uniquely identify the image content, but there is no property of a canvas that uniquely identifies its contents, because it's designed to be changed.

It's very easy to build your own (in-memory) cache instead:

````js
const cache = new Map();
function drawUpdates(data, ent) {
  const key = data.uniqueKey(); // All unique values concatenated into a string, or something like that
  const cached = cache.get(key);
  if (cached) { return cached; }

  // do actual drawing

  const pngImage = scratch.toDataURL();
  cache.set(key, pngImage);
  ent.billboard.image = pngImage;
}
````

Now, if you want to dig a bit, you can figure out that the `billboard.image` setter does its own caching based on the data URL you're passing as a source, but due to anti-fingerprinting measures, the same drawing commands will never produce exactly the same data URL, meaning the built-in cache could never hit.  That's why it makes sense to have your own.

One solution that might make sense is to expose a two-argument `setImage` method on `BillboardGraphics`, like the one that already exists [on `Billboard`](https://cesium.com/docs/cesiumjs-ref-doc/Billboard.html#setImage).  That way, advanced users can explicitly tell Cesium what cache ID to use, regardless of where the image comes from.

**Comment by Nadav42** [comment]
Agreed, good point. Exposing setImage would be nice.

**Comment by Nadav42** [comment]
hmmm I looked in cesium source code and seems like it auto resolves functions, this seem to work:

```
  setInterval(() => {
            index = index + 1;
            ctx.clearRect(0, 0, 200, 200);
            ctx.fillText(`test${index}`, 100, 100);
            billboardEntity.billboard.image = new Cesium.ConstantProperty(() => canvas);
        }, 1000);
```

can this cause any problem or performance issues?

**Pull request closed without merging**
