### PR TITLE
Fix transform for IBL environment maps

### PR DESCRIPTION
**Pull request by jjhembd**
# Description

This PR flips the X-axis of the transform applied to IBL environment maps.

Prior to this PR, a mirror ball shows the environment map image in its original orientation, rather than in the expected mirrored view.

The environment used in our test Sandcastles is the [Kiara 6 Afternoon image from polyhaven.com](https://polyhaven.com/a/kiara_6_afternoon). Notice how the sun is to the left of the shadowed peak in the distance. A rocky outcrop in the foreground angles from the sun towards the right of the image.

image

Before this PR, a mirror ball shows the same orientation in the reflection. Again, the sun is to the left of the shadowy peak, with the outcrop angling toward the right.

image

After this PR, the orientation of the environment is flipped from left to right, as expected for a mirror ball reflection.
image

This new orientation matches the [glTF Sample Viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/).
image

## Issue number and link

Addresses part of https://github.com/CesiumGS/cesium/issues/12028.

## Testing plan

Load [this local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=tVkLb9s4Ev4rvGCBdQ62rPcjTYpL0rTbu/RaJNlboJdDwki0zQtFCiSV1Fv0v++QekR2XMdbYItAlkjON08Oh9NccKXRAyWPRKIjxMkjOiWK1qXzHzs2ut7L7fep4BpTTuT13hh9veYIYU5LrKngB2iGmSJjM6hpSRgsG47VipxI8aiIvCC5KEvCC1JcECVYvUr+bf/VNb/muZXpK1I54WSMclwSieGXifwefQMpG3HtWjpDo7/ZhY6qSF4zLM/4A5WCAxv9AVfqsq4qITUp9huxHykvxKODGZF6ZAYQut67WlCF7hohUSGIQlxopBpS1CEj8gSNSsB2rvcMghH7m5GmEaRUGF/ismIAc4TCgU4LQucLDYO+67iv+tFqzfS/EFxQPv9Edb64EIyNYPUYdY/9nlBIOqccaFu6Uwx6Kop54MykKN+QuSREWSUnnh84bhKGsZdZp4Sh40ZukLix/Wwku+ZP4KUoCPuAtaRfnjhcSczVTMhSOYs1Ia/EW/qFFG8luMuybKRr0CvZQHcmYq0dBkq/oZLkJh4wOzezI+utohs9GK59UrT1oOv4YRT6SRq4bhS6XuaNu4k0Df04gMnIy4Ks1d5MBFniZ2HqeVkURmnqRtaVdppyTbiienlgrd5H5nSKbKSsxQF6xApVUsBOUaSAeAe7oH8tYIVQPys0Z1dv0fuTc9QEhXTQleiWo6WoJRKP/MCie2iC3sAXE7iADVagu5qyAukF6fCeoaHRQutKHUync6oX9Z0DW2zaLn4nRV1NDcUEKCYtxb5jefnA66Lm6DZnFE0or2r9CesFmlbwnGoxhe09J86ikGgian1a3xHYT0/TMAYkzr3+4t86A6TFLYIIQZgxJCrjOtgmbUyRla3568U5OjLmvt7rVGhyjVWhqu8YzaeXYIUcK81II/0brPH0nmKJb+IbPNNEciH4jX9/Q++YFeZ6r/eVQHOINok1sSZU1YJImmOGFliWgtMc5YLMZjSnIBEkAMLE49jkK/ROiDkj4Ly3lGHrZ3DY/yEUN/jJQPfLJGEEA8Amr8wt6HTWrp22a9Uzh5QgNppMuJiUVEow5mSilxU5AvXgtSAVE8ujNUds8Nttg2v+fQQhpfELpGyFsCTgHyW6DEcKZ5XzgrBqkxsBLQApr/B9Y9HOvMWqIU3kdqYpYTe1+/aflwg2ilqA4Rpb94Fx7rqr2WBth3uOH4RplgRJ5Llx6vnjdtT3YG97buD7UeKm3WgSBEnopm4cJVmUDbPauXfjvcDJC2IPUoibwl/key2ml3ihl2VJCj9JGnWc0iTNwgAkSrw481c5vagSpCzPhZTkAUYUjPvRJPPcJIm9IA28nlHgxgkM+64b+8Eqoxc1chPPDwM/BUg/7TXy/DhLIF/6CYjQWdSLAtDTg4MBTBCkK4z8G/8FTm4ah14EkKEXZGEL6SZZ5obwDIPEj+KOket7fuSGaRwkQbbG50WNMtcFhcB6aeAnPWQau1nmZ24aJknSR4MXxn6SQaJPI1BsldN2H0Hy9wAoiEMIp8BrgwFGfRdCJMjiMIAgSfvRKPASP3EDN4UIXGXkvWi5BDCBPgKr9N6wmmR+7JvDzY96z5kgjCMPHhA4q4y2u2gCYoJ3/DhJ0yyKMj8Zd8MhRBu4LorjFI7Lp2EPtl0aQVjEYegNea1s+SP0X9jEY7vBzNO+mjcIGvu072bUt2/+/wZ1kc1YJ5AKC3v0m+NzRYn3z+ab6oDVJeWY5+RYfyYcEq05rxuN+lz/S5vqTwfSHqzI3q7fWD0ePD+z1gtV1or0scmSxhIG8GtTZ2jyRR/ACXe2VjJ0VFBONwuBFI4DOGDQaB8dve7o0QbjOFuVAwGG2r3airNRaUB4pvU2mOdDb3Gu4fA46ojQs3D0nY//PutBB1Wh0xdfIEZTJpsV36yZmueaaT+ZUqqoJZzr6n7511q2hrvLDO43xY+ZdSfyv86c3i7mbArx3oxgPrb8IVv+mB6fzy4+/pAiJqE8VYsOLoorIdgdlh8Ir0dru3QMinZD7bLrvWZXM9JeflavQtu39ylUchKdCqzRbzS/t9fkzRYzddEHAzjyoxTOsGz/+6647C6eV0TpnRDh+Em2IR5zqoSWolqiSy0Jn0PBvzM4nAt+vBv4G6ryPwOcRuluwBdC26bDnwPfZpKB63bHBMfFu2FCaKNPGIJ3Z+BtlrgSS4O4K1bgbcH6JDQSMyMlUzsDulsAT7Dk6ByuaTv6Jdlqww9EYza5EPV8wc1N+dKkZrKTpHAngJptC/ZvcGeR6ERoyBQ7AUZhlCXbhG3uaSdwXdoJLwmhCtvfMXcN849JXPZbraSt51nF5jKsljxHs5rbHspAAvg6Voro911bTMtlp1OT9MDUopY5gYSHHzHVfS0m+EU7ZbtMLcwQsU3NVsx1csveEr5jenZs5Bv1h0gt2UHPeNyNDjpRB8OP8ffPnnaqrdOeTpJK0pJq+kCUI0kpHsgxY6NO3mdLwA2N7Z9g7CfQ4mJ59gDnulljX86p0uYyPFo7F38XorwSjdF7rF42+EE51vkCjYgJoP2OcKVLeXtmg8t4zxzIFuYA/fTVkny7bYHaHmTv7OecG/CueOeQUBmzbd+2gZpLQvhlhXNyanuup/2aVy1h++lA2U3LuvwMLCDTa1OCm7LTUoFza6XB1Rxy4DrhTUtp0zi5MJ2Z7jS3BT0xjV8JetbKtnobe98JKJxA9SYFWEzT+G3XHSLPtEU7002n6PL7mtjuLv9ZowVsN0aQKk2Ho9lR6JHA9h3sAQWFoBUQ8NG0lav1XxfPNhRDp6yZphVbnix/5dT0WS4N7Wglhp1NwWt5jL+7rpnogqbV+O9HDVnn+Ce3tl3Zp44toCwcLS5gGHM1avvH3fLKdG8HdXbrQSbE/XHXHd/kAgcCBjJoK/b3WteYz8molWjc8Br3KiAfRBl0z/fGe4dKLxl53dniH7S07XfICiPHmWpSVgwCRk3vaqiwtJMr1dnlcDokPSzoA6LF0Yb/u0A5w0rBzKxm7JL+Dtn/9eEU1j8jbXfbxwciGV6aZQvv9Xkz6DjO4RQ+N1PqLjH3mgxQ12vOFYzhyrUkv8pr8P4H) and view the "Mirror Ball" model with "Environment Map Lighting".

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have updated the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by jjhembd** [comment]
@ggetz OK, I added a spec checking the value of the IBL transform.

**Comment by ggetz** [comment]
Thanks @jjhembd. The spec seems to be timing out in CI?

**Comment by jjhembd** [comment]
> The spec seems to be timing out in CI?

@ggetz Yes, and I can't explain why. The spec passes locally, and similar specs (loading the same environment map) run through on CI.

**Comment by ggetz** [comment]
@jjhembd My guess would be the KTX2 loading. I would make sure the URL is correct in both environments and that the environment supports the needed features with `OctahedralProjectedCubeMap.isSupported`.

**Comment by jjhembd** [comment]
@ggetz it's the same URL as the other specs. But the other IBL specs had this check:
```javascript
        if (!scene.highDynamicRangeSupported) {
          return;
        }
```

This condition fails on the WebGL stub, so the spec is skipped.

I added the same check to the new spec.

**Comment by ggetz** [comment]
Great, thanks @jjhembd!

**Pull request merged**
