### PR TITLE
Fix allowPartial parameter handling in getBoundingSphere to prevent blocking by other visualizers in update function

### PR DESCRIPTION
**Pull request by Levi-Montgomery**
# Description

This pull request addresses a bug in the getBoundingSphere method where the allowPartial parameter was not functioning correctly. The issue caused the bounding sphere creation for one entity to be blocked by another entity belonging to a different visualizer that is not ready, even when allowPartial was set to true. This, combined with the fact that the allowPartial parameter being set to false when creating a boundingSphere for the tracked entity, resulted in the flicker bug seen in issue [Issue 4647](https://github.com/CesiumGS/cesium/issues/4647) and [Community Forum Post 35516](https://community.cesium.com/t/how-to-fix-flicker-upon-updating-position-of-an-entity/35516). The tracked entity was unable to get its bounding sphere if the Polyline was being drawn at the same time.

Changes Made:
Added a check for !allowPartial before setting the BoundingSphereState to PENDING in the getBoundingSphere method.

Tested:
Ensured that the method does not halt and return pending if allowPartial is true even when the desired visualizer is ready.
Tested with Cesium Sandcastle Provided in Community Forum Post 35516
(For some reason i cant get the 2016 issue sandcastle working locally on my mac even when im on the main branch so ive been unable to test it with that)

## Issue number and link

4647 https://github.com/CesiumGS/cesium/issues/4647
35516 https://community.cesium.com/t/how-to-fix-flicker-upon-updating-position-of-an-entity/35516

## Testing plan

I used the example cesium sandcastle code provided in the community forum post and visually verified the flicker is no longer there.

# Author checklist

- [X] I have submitted a Contributor License Agreement
- [X] I have added my name to `CONTRIBUTORS.md`
- [X] I have updated `CHANGES.md` with a short summary of my change
- [X] I have added or updated unit tests to ensure consistent code coverage
- [X] I have updated the inline documentation, and included code examples where relevant
- [X] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
Thanks for the fix @Levi-Montgomery! @lukemckinstry could you please do a review pass on this?

**Comment by lukemckinstry** [comment]
Thanks for this PR @Levi-Montgomery 
I see the fix is looking good for the sandcastle example described in https://github.com/CesiumGS/cesium/issues/4647
But in the [sandcastle example](https://community.cesium.com/t/how-to-fix-flicker-upon-updating-position-of-an-entity/35516) at the top of the forum thread https://community.cesium.com/t/how-to-fix-flicker-upon-updating-position-of-an-entity/35516 it seems the model is no longer visible. Are you seeing something different?

**Comment by Levi-Montgomery** [comment]
@lukemckinstry Thanks for testing.

> the model is no longer visible.

Could it be because the model path on line 31 does not exist in that location on your computer when you're running locally?

I did have to change that string to a different 3D model that i already had on my computer for testing purposes.

**Comment by Levi-Montgomery** [comment]
@lukemckinstry Ah, I see. If you replace the path on line 31 with `../../SampleData/models/CesiumDrone/CesiumDrone.glb` it will work. Not sure why a single ../ works in the deployed environment but in local you need ../../

**Comment by lukemckinstry** [comment]
Thanks for this PR @Levi-Montgomery and for helping me troubleshoot. 
The flickering caused by the misalignment of the model and camera positions appears fixed in the sandcastle example described in #4647 and the [sandcastle example](https://sandcastle.cesium.com/#c=pVb/b+I2FP9XrE5TwxoCHN10o7TaDth0ErpWYt1pK2gyiQFrjh3ZDl926v++ZydxHJq1Jy0/QPLs9/x5n/fNseBKoz0lByLRLeLkgCZE0TyNfreyYHkR2++J4BpTTuTyonOz5Eve66Ep2YAE6R1BmWAnBh+XCl4V1RTsooBy9PnXxftrFAshE8qxJqoTLXlsT6033qKn1U0l5nn6ICjXRjzs9/tugQm+0FhqkHffN8QznoDQl2FdbR3+6EuLndcDJ8NMU50nBKSDfr84bsk3QqKAEY0oyPs38DeuccHn1VUHfVlyBI8DATsdwivQLmB1nbCDvgNGUA8FtYddNOgYOj1D2IB2+I2hAnXXCd8y5HiNslztgjKeE9CEN8yH0UaKdEq2khBlYIbGcuiYsHaeyxD/nCQutkgLG2sVE068KJart2UaRYSDIUpUhJMk+FJhKnaNKtoaQEf1a1gvH2iidyP0vSdKIYMkxWxUZelEMCGjP2bz+f3nYhsgf3YZOpEENBBGwylKRUIYsuBO4AfwfKCMgXgPG4CGbSORnX9WbVZoveFi4YLnzFN/VYK3VhrO55KO0GUU9RY4zRiZYo17dpfqFb5NpeDEf4+2bH3pk0E5TSED6JGwBf0HuP3husHV0SwvYsxg6V2/H6LXGFIE/PWD3cbQgeqdpakgE4MCOWoCfwOUEogNyojM4JvGOcPSI3FP+XYOdr+OydeT5alBcINu+ASnitpxYBVOTWChUF4k1/Dt5Powf5ydE1eC1xLHf5PE+eTlit1mOkicSwlOfuQJOdpmUhL/S85jg9pUFYTI8GXj0CCwQO3IxQd8QqZ6rVul5cqzTWXQWXvwTdlGEVRcnbUvDlF8KJcAZM1o0IB/BV0Gfes1GEb4Vu9WZePxLSZUkrg097IDqXxtuNOBf3AdydAfRLVa4FrcS4tcyBQzqILAnRzWIDoNhCbtRZrlLXzvYT/0fhhchmGCle6CZb3r5hkKZp8eO0A/ZJPvKay0ufj46eNvf/3Z6O3No9qUYimU8j3Is//FRePEsAmg0P9PfPebjSK6FWWaw6jI2OnDyTQXLM+PGb6JufiVROeStxxgekGdCy2wXj3guaXC8iwx5eVal3dPsV3Mtv5GeMoh4KqqsFBUUV09zeL+qmpppESp0Fp7vrGVbRtukhQ9JspqtTNDbntLZK0PRuWVPnFmruPsAa/fuMeUUWpakMg1UEgVqu4JG3pEG0ahO0q0zreejnkqT5pDIXKzt3EzPIMStjiz8qL+qKDhE2ANGuYeMwPGDrB6apXXGNN66iQgeyJP5RCEsHsWAi/yob0kdm4uwoux0idG7qrx8RNNM2gUMNZZAENdExjq5rrbW+dAgo5iparkH/d81XFC94gmty0XbRQzrBSsbHJmJ/zy4m7cg/0vVJnAcL3e3oMTDJ/Mtt3gbl4Ioyga9+CzXVMLwdZYnln+Fw) at the top of the forum thread https://community.cesium.com/t/how-to-fix-flicker-upon-updating-position-of-an-entity/35516
This is looking good @ggetz

**Review by ggetz — CHANGES_REQUESTED** [review]
Thanks @Levi-Montgomery!

Please update `CHANGES.md` with a summary of your fix. Then this should be good to merge,

**Comment by Levi-Montgomery** [comment]
@ggetz Awesome!! I've pushed up a summary.

**Review by ggetz — APPROVED** [review]

**Comment by javagl** [comment]
I'd have to cross-check the details, but maybe someone can quickly say whether this fixes https://github.com/CesiumGS/cesium/issues/4647 (meaning that this issue could be closed) ... ?

**Comment by ggetz** [comment]
Thanks @javagl! Closed.

**Pull request merged**
