### PR TITLE
Replace defineProperties with native Object.defineProperties

### PR DESCRIPTION
**Pull request by fredj**
Related to #8515

`Object.defineProperties` is supported since IE 9 (ES5)

I've neither updated `CHANGES.md` nor deprecated the `defineProperties` polyfill because it was private.

eslint is now correctly checking if the getters are returning a value so I had to add few `eslint-disable-line` (211148e)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @fredj!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/rm_defineProperties/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@shunter any arguments against here?  I know the original reason for this polyfill was so CesiumJS could fail gracefully on IE < 11, but at this point those browsers should no longer be a concern.

**Comment by hpinkos** [comment]
@mramato @shunter threw his two cents in in this PR https://github.com/CesiumGS/cesium/pull/8526#issuecomment-579823679

I think we can probably merge both if you agree

**Comment by mramato** [comment]
Thanks @hpinkos 

And thanks @fredj!

**Comment by nmschulte** [comment]
> I've neither updated `CHANGES.md` nor deprecated the `defineProperties` polyfill because it was private.

Ouch.

**Pull request merged**
