### PR TITLE
Pare down build scripts; naming consistancy

### PR DESCRIPTION
**Pull request by ggetz**
Fixes https://github.com/CesiumGS/cesium/issues/10313

This PR pares down the number of build command in favor of using flags with the `build` script as needed. It also makes sure naming conventions are consistant.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/scripts/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by sanjeetsuhag** [comment]
@ggetz This is a good change. There's a few areas that still need to be updated:
- The `generateDocumentation` command is referenced in `CesiumSandcastle.js` and the Documentation Guide. We should document the `build-docs-watch` command somewhere.
- The `buildApps` command is referenced in the Performance Testing Guide.
- The `makeZipFile` command is referenced in the Release Guide in the Wiki.

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag! I'll update the Release Guide after this PR. I think it may make sense to check this into the repo proper rather than the wiki so we don't have to make separate updates.

**Review by sanjeetsuhag — APPROVED** [review]
Thanks @ggetz!

(CI failures are unrelated and random so I'm merging)

**Pull request merged**
