### PR TITLE
Improve underground rendering

### PR DESCRIPTION
**Pull request by lilleyse**
Detects if the camera is underground, and if it is:
* Disable skirts
* Disable back-face culling
* Disable fog
* Disable ellipsoid occlusion culling for both terrain tiles and primitives. Primitives inside the globe will not be culled.

artifacts

Known issues that don't need to hold up this PR:

* Because skirts are disabled it's easy to see through terrain seams. Instead it would better to invert the skirts.
* The depth plane is non-existent when you're underground so stuff above the surface on the opposite side of the globe will be visible. Like in [this sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=vVh5b9s2FP8qRIBBcu3Suo8cxXINC5Z2QZJuKOahkCXa5iqLBkU5Sdd89z2S1uW4XZYBTf9I+C6+93sHn7pOOEpJSavl74zn2S3hPKEFOkKniohTThJBujxzcDAp1qBG8pyuSkazK87WNCMctApyV2ue1+yNXi2l9LWFNSV322q/KZppaKdOWSFAl3BjhP6eFAh+RN8c2t/h/6R43NyirGFyL0iRmZsrNFEfLopyRVLB+Ft6T4vWtTIlBQHPNgbUcRN3miwJT4CniFgfN7x5zqakYanTNlrAVXTcUA4aP7VazuYJp2KxpOkZWYnFSTWbKZhmSV6SbelMitySUhzPIfJStCmsxbUDU3Z/mnDB5jxZ0bQPesNY0NR0sBs7sRVagR25oee7/gi9trAV2l4c+bbnuW7ou14AVMe3LODUFTHNK3LC7lvYSCGooKTESZaZm/wVgBckzTgBYemUMdL0FStBlhX7u5zCgskjMJLC7Ecy2OgDFcxuLpE/GV2SogSLJdC3glWGXNNW7o9Q5zdEM2ptLKH4OU1y1HrFcsbxyeX7cy312NTa+FUvL7oucEmELOk6+gwSRYtEBvpVrxw79GInwJ5teU5gu76E2g58x3KsADtOEAVRFIbgrh1asR84GARj17UCr/adcQrY77jmZ5JktJhfUZEurlmem2AwciGpvm3bju3ZPmTbkpc4fuwDxbWsOHRGCORcSHwYRoEfWpEb1VdBY93ypChnjC9bmN4mgtN7D1+cnb+7vbj9oFB6Ne705P9F6bUXeC4AhN0wth0risBxDyKx/AD7YexD+cYxAAeRRU6EoziIbDuKQ/+lGEW+Cz0AlqNANUQY+b4X2wA8lE0YBwqjvtwLMJII3SRFlialyIlsnFvG8mnCTyohWGEaEifdN2hWFal03xzUdf8MbL8bvt8Z4/+Cs2pcibUGY1rN54QftK+GnPKsKgRMMquhcLJka3K+JoreQxpml7iGy4EACVMil7SENwdesiZJSrTNlLIoVUh2S3NSgs0//jxomTlLsl2s7r36IflYVnyWpARD2OcJ4Nkx214v4DTozsfe7XhVlQslgz/mZE1yNEQG/BsiTbvfOj9snXMo1xuSE3XXNSmrXNT4NkA/w/XLJuhvON5B5nu4vZ2lPm4l48Ic4L8YbEbGZFIYtVo/f12fd6popRReK5arFcA0fuLQwPvKW1WNteWe0HvpzJwDP9OiO0ZAR2anjbpg9pH0Bmz0QtypohPVKHTCq8XpDJnK7eEQHR0dybd1q/yadjIbzJ83Ao+zDNYFWohy9xCE7tHsJ33K6RKWjPVmI+nMoyspf1Wz4ZHf1IQ5aJMDNYpM3ZrFnIoqk5veazuyDjqUQ9QnDIe9qPVogRWiXbH1RnF18e6Xg1ZOome2Vn9AzkCh2MdQp2WHtdMPx+861h7rEPphwFyuo4ilz/X5EHWPWxHoXU2i293q+ly9yaH9p88KnnG2PCNzTkjZxjdqLutO836E+/p3n9006SbKfhHppJfwDUOKmxWMmVPVDvKjgssMywU1meYq3VRuimdE6LQ/2Z7TBH516kmfga3/kI/ssYBnZloJYhoimVLoIPlGGxa0NxqP4fEj0CJIMLSqBCQhrUoEF4kF2RhvbLEizWn6SfqwXdsbCaWtuuZReZjBGZZd8fT1MT6Rh4zdFZ1GQWYzTmWVEQwiqraM1EBfviBFOGWyLoAYhN3s975/Gig2H0AdmVLIkjS+vY7A6Gi1pMYQVJ67nqipqC3W9YbVtB+hXayHr7M+SxbU3Vfdef4S0zG/0Lyn10rhJ1RZjv/mxjOXm5360BAdaneSg8SgnzsOLZAU83z787dOYMqWUMFEJvG6FjUHu623Ti7gE67u++YGfAeZHrxQt2SVWLxUmSQvv7iA97u5WE+bvdHeYSkecvJGW/yRLlcghSqemxiPBVmuYMKRcjyt0k9E4LRU7+ThuFY6zOga0exosrf1Hx+TPZTCllICZ1bl+Q39TCZ7bw7HIN9Tky8w1Nuva8Lz5EGKLOw3l5qIMT4cw/GpltAPa8fiPw) (click "Add points")

Don't merge until after the February release, this needs more time to sit in master. Camera navigation PR to follow this one.

@fredj @gberaudo

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@IanLilleyT @lilleyse is this still waiting for a review?

**Comment by lilleyse** [comment]
@IanLilleyT's going to review after Friday, it's ok if this doesn't make the March release.

**Comment by IanLilleyT** [comment]
Looks good to me, thanks @lilleyse !

**Pull request merged**
