### PR TITLE
Change default Sandcastle tab from "Showcases" to "3D Tiles"

### PR DESCRIPTION
**Pull request by j9liu**
Fixes [#7462
](https://github.com/CesiumGS/cesium/issues/7462)

Changed the default demo to "3D Tiles Interactivity" based on @shehzan10's suggestion. Happy to change this based on others' consensus (and I will update changes.md when finalized).

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @j9liu! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/CesiumGS/cesium/blob/sandcastle-default/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/sandcastle-default/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
Is there a way to keep Hello World as the default example but 3D Tiles as the default tab? One thing nice about Hello World is that if I'm prototyping something I have a clean slate to work from.

**Comment by j9liu** [comment]
There is! I changed the default example and the default tab so they meet your specifications in the latest commit. I also logged it in CHANGES.md.

**Comment by lilleyse** [comment]
Cool, we can see what others think but I'm good with this change 👍

**Comment by hpinkos** [comment]
@lilleyse I'm not sure I agree with your decision here.  I like the idea of changing the default example to be something more interesting to give a better first impression to someone who is just starting to explore CesiumJS.  It's not like the Hello World example is going away... I think it's better that you have to make one extra click to get there than our end users having to browse further to see more capabilities of the library

**Comment by j9liu** [comment]
@lilleyse - do you have any new thoughts or response?

**Comment by lilleyse** [comment]
I'm _ok_ with switch back to 3D Tiles Interactivity though I wish we had better 3D Tiles sandcastles overall.

I'll have to get used to clicking the "New" button.

Any more thoughts from anyone else?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @j9liu! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Pull request closed without merging**
