### PR TITLE
Replace when with native Promises

### PR DESCRIPTION
**Pull request by mramato**
Me and @kring were discussing this last week and I had a branch that had it mostly done, so I figured I'd start fresh and get a PR open.

1. Replace all use of `when` with native promises.
2. Add `Core/defer.js` to replace `when.defer`.
3. Remove `when.js`

- [ ] Fix failing unit tests
- [ ] Polyfill web workers to support IE11
- [ ] Update CHANGES.md to state IE11 support requires a Promise polyfill (and recommend one).
- [ ] Decide if we should deprecate and put back `when.js`, but it's basically impossible for this not to be a breaking change, so why bother.
- [ ] Any performance implications we need to worry about?
- [x] Do full release testing to be sure of no surprises.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/native-promises/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
Do native promises have a one frame delay? Or is it like `when` where if a promise resolves the handler gets called immediately?

**Comment by mramato** [comment]
> Do native promises have a one frame delay? Or is it like `when` where if a promise resolves the handler gets called immediately?

Promises, by spec, do not execute immediately.  Even new versions of `when` have this behavior.  We are using an ancient pre-spec version. 

Given the below code:

```js
function a() {
    console.log('1'); 
    Promise.resolve('2').then(console.log);
    console.log('3');}
}
```

The output is 1, 3, 2.

While it's a change for us, I don't think it has any negative consequences on actual performance (but that's something we should objectively measure which is why I had the task for it).

**Comment by lilleyse** [comment]
Ok.. there's one area in `Cesium3DTileset` that I may need to look at. Will get to that tonight and report back.

**Comment by shunter** [comment]
> I don't think it has any negative consequences on actual performance

I have been assuming that this would have a performance consequence.  We should measure for sure.  My expectation has been that a naive port would introduce multiple additional frames of latency for terrain and imagery loading.

**Comment by lilleyse** [comment]
> Ok.. there's one area in `Cesium3DTileset` that I may need to look at. Will get to that tonight and report back.

Opened a fix here: https://github.com/AnalyticalGraphicsInc/cesium/pull/8535

**Comment by mramato** [comment]
> I have been assuming that this would have a performance consequence. We should measure for sure. My expectation has been that a naive port would introduce multiple additional frames of latency for terrain and imagery loading.

@YonatanKra mentioned [on Twitter](https://twitter.com/YonatanKra/status/1216989040685322240) that already resolved promises run at the end of the current frame.  So while they don't run immediately, using resolved promises should not introduce an extra frame of lag, which is the best case scenario if true in all browsers.

**Comment by mramato** [comment]
So the good news is that Cesium appears to be running at the same level of performance with native promises and all of the Sandcastle demos I tried looks great.

The bad news is there are 400 test failures because they were written with the assumption that resolved promises are synchronous.  Should be straightforward to fix, just tedious.

**Comment by mramato** [comment]
Just to update everyone on this, I've had no time to work on it but literally it's just test failures (because tons of our tests assumed sync promises)  Cesium itself is done (except for polyfilling Promise in IE11, but that's trivial).

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by mramato** [comment]
Ugh, I really want to get this finished up but it's going to be such a slog fixing all of the specs.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @mramato! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by mramato** [comment]
@cesium-concierge stop

**Comment by ggetz** [comment]
Closing in favor of https://github.com/CesiumGS/cesium/pull/10149

**Pull request closed without merging**
