### PR TITLE
Updates to typedefs and documentation defaults 

### PR DESCRIPTION
**Pull request by lukemckinstry**
# Description

Type definition and documentation fix for the problem identified & described here https://github.com/CesiumGS/cesium/issues/11749#issuecomment-1950184016
which identifies an inconsistency in the documentation where we list default: undefined but our typedef requires a specific type. 

Made fixes using the following logic
 - if the argument is required in pragmas on the constructor
   - make sure it is not marked `optional` in the constructor args
   - make sure the `@default` is not listed as undefined (either change to default used in constructor or remove the line entirely)
 - if the argument is optional
   - change the typedef to allow undefined eg `... | undefined`

This PR covers fixes for `Source/Core`, other areas of the codebase will be covered in future PRs 

## Issue number and link

https://github.com/CesiumGS/cesium/issues/11749#issuecomment-1950184016

## Testing plan

 - build the documentation `npm run build-docs` and note changes to `default` values for targeted properties 
 - when using cesium with typescript, note you can set targeted properties to undefined

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [x] I have updated the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
Thanks @lukemckinstry! I can confirm we now have you on file in the Cesium CLA.

**Comment by ggetz** [comment]
> So for attributes with default values they cannot later be reassigned to undefined, only attributes without defaults can.
Does this make sense? Would it be useful to design the types so the developer could later reassign those attributes to undefined as well?

Let me confirm my understanding– You're suggesting that we should allow the properties with default value to be set to `undefined`, correct?

**Comment by lukemckinstry** [comment]
> Let me confirm my understanding– You're suggesting that we should allow the properties with default value to be set to `undefined`, correct?

as discussed, this additional change is not necessary as the primary purpose of this PR is to update type definitions for optional parameters to include undefined.

**Comment by lukemckinstry** [comment]
@ggetz updated CHANGES.md so this is ready for review (pending whether the CI occurs again)

**Comment by ggetz** [comment]
Awesome, thanks @lukemckinstry!

**Comment by javagl** [comment]
Just stumbled over this: I assume that the first checkbox from https://github.com/CesiumGS/cesium/issues/11749#issuecomment-1950184016 can now be ticked. (At least, I did that, updating that comment to point to this PR)

**Comment by lukemckinstry** [comment]
> Just stumbled over this: I assume that the first checkbox from [#11749 (comment)](https://github.com/CesiumGS/cesium/issues/11749#issuecomment-1950184016) can now be ticked. (At least, I did that, updating that comment to point to this PR)

Hey @javagl, this didn't address all instances of the problem, only most of the ones that occurred in `Source/Core`, so I think the comment should be left unchecked until we address all cases.

**Pull request merged**
