### PR TITLE
Update packages (hopefully fixes CI)

### PR DESCRIPTION
**Pull request by lilleyse**
Several packages had major version bumps and a few required changes to the code:

https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21 (no changes required)
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-700-2020-12-05 (no changes required)
~https://github.com/typicode/husky/releases/tag/v5.0.0 (no changes required)~
~https://github.com/typicode/husky/releases/tag/v6.0.0 (see 22b347b0a3, started by running https://github.com/typicode/husky-4-to-6)~
~https://github.com/karma-runner/karma/releases/tag/v6.0.0 (no changes required)~
https://github.com/karma-runner/karma-firefox-launcher/releases/tag/v2.0.0 (Node 10 requirement)
https://github.com/sindresorhus/open/releases/tag/v8.0.0 (Node 12 requirement)
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#breaking-changes (no changes required)

This fixes the build-ts problems we've been having since the switchover to travis-ci.com. Though some new build errors were introduced that I still have to look into.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/update-packages/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
These are the errors I'm seeing now. The second error can be triggered locally by updating karma to 6.3.4 and running

```
npm install && npm --silent run makeZipFile && npm --silent run build-specs && npm --silent run test -- --browsers ChromeCI --failTaskOnError --webgl-stub --release --suppressPassed
```

```
[0K$ npm --silent run coverage -- --browsers FirefoxHeadless --webgl-stub --failTaskOnError --suppressPassed
[04:30:47] Using gulpfile ~/build/CesiumGS/cesium/gulpfile.cjs
[04:30:47] Starting 'coverage'...
[33m22 06 2021 04:30:47.727:WARN [karma-server]: [39mPassing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.
[31mFirefox 89.0 (Linux x86_64) ERROR[39m
  An error was thrown in afterAll
  uncaught exception: Error loading Specs/Scene/CameraFlightPathSpec.js
  http://localhost:9876/context.html:1

```

```
[0K$ npm --silent run test -- --browsers ChromeCI --failTaskOnError --webgl-stub --release --suppressPassed
[04:40:33] Using gulpfile ~/build/CesiumGS/cesium/gulpfile.cjs
[04:40:33] Starting 'test'...
[31mChrome Headless 91.0.4472.114 (Linux x86_64) ERROR[39m
  An error was thrown in afterAll
  Uncaught Error loading Specs/ThirdParty/knockoutSpec.js
  http://localhost:9876/context.html:1275
  Uncaught Error loading Specs/ThirdParty/whenSpec.js
  http://localhost:9876/context.html:1276
Chrome Headless 91.0.4472.114 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Uncaught Error loading Specs/ThirdParty/knockoutSpec.js
  http://localhost:9876/context.html:1275
  Uncaught Error loading Specs/ThirdParty/whenSpec.js
  http://localhost:9876/context.html:1276
```

The problem goes away when using karma 5.2.3 instead. I'm tempted to do that so we can get CI working again and then open and issue to look into it later.

**Comment by lilleyse** [comment]
Any concern about the Node 12 requirement for development? I believe `open` is only used to open coverage.

**Comment by ebogo1** [comment]
I was able to `npm install; npm run build; npm start` with no issues and tested a few Sandcastles just in case.

**Comment by mramato** [comment]
@lilleyse Node 12 is currently the minimum version to build Cesium anyway. And you are correct, `open` is only used by coverage.

**Comment by mramato** [comment]
husky 6 doesn't work for me as well as 4 did (I did a completely fresh clone just to confirm everything was new).  I often use git gui to commit and husky just doesn't run.  I think it may be related to https://github.com/typicode/husky/issues/125 or https://github.com/typicode/husky/issues/715 or https://github.com/typicode/husky/issues/980

Can we roll back just this one library.

Otherwise this looks fine to me.

**Comment by mramato** [comment]
I was mildly concerned that updating TypeScript to 4.x would affect our TS definition generation, but this branch is identical to master so no concerns there.

**Comment by mramato** [comment]
Looks like CI is fixed and this gets us over the immediate hurdle and is fine by me.  We should definitely look into upgrade all of the other module major version numbers soon to stay, but they can each be in their own PRs (Assuming they require code changes).  @ebogo1 feel free to merge if you are happy with this.

**Comment by lilleyse** [comment]
I opened https://github.com/CesiumGS/cesium/issues/9635 from karma and https://github.com/CesiumGS/cesium/issues/9636 for husky

**Pull request merged**
