### PR TITLE
Webgl2 reimplement HBAO postprocess

### PR DESCRIPTION
**Pull request by baothientran**
Re-implement HBAO post-process based on [NVIDIA paper](https://dl.acm.org/doi/pdf/10.1145/1401032.1401061) and [presentation](https://developer.download.nvidia.com/presentations/2008/SIGGRAPH/HBAO_SIG08b.pdf). Below are the results of the new implementation:

Screen Shot 2020-06-26 at 10 55 21 AM

Screen Shot 2020-06-26 at 10 56 53 AM

@lilleyse can you please take a look at it?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @baothientran!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/webgl2-AO/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
@baothientran but could you provide some before/after screenshots comparing master to this branch. Also could you cover some of the technical differences between this approach and the previous one? Is the main advantage that this one works without linear filtering of the depth texture? Also post any performance numbers if you have them.

@byumjin do you remember the original paper you worked off of?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
@cesium-concierge stop

**Comment by ggetz** [comment]
@baothientran To keep things tidy, I'm going to go ahead and close this PR. If you get some time to work on this and have updates, feel free to reopen. Thanks!

**Pull request closed without merging**
