### PR TITLE
change cesiumScriptRegex value

### PR DESCRIPTION
**Pull request by xiaobaogeit**
fixes Issue #8902

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @xiaobaogeit!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/cesiumScriptRegex/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks @xiaobaogeit ! Can you test and/or add a unit test to confirm that `CesiumSomething.js` does NOT match with this regex as Matt suggested in that issue?

**Comment by xiaobaogeit** [comment]
@OmarShehata  I've added tests and the results are the same as expected

**Comment by OmarShehata** [comment]
Thanks @xiaobaogeit .

Bumping to @mramato for final review.

**Comment by mramato** [comment]
Thanks @xiaobaogeit.  The regex was a little loose than it should have been, since only ? or # should be the first valid character after `Cesium.js`.  I pushed a small fix and test for this and will merge as soon as CI passes.

**Pull request merged**
