### PR TITLE
Maki update 8.0

### PR DESCRIPTION
**Pull request by JohnRDOrazio**
Following the instructions on the page [Maki Icon Generation](https://github.com/CesiumGS/cesium/wiki/Maki-Icon-Generation), I pulled in the latest release of maki icons from https://github.com/mapbox/maki/archive/refs/tags/v8.0.0.tar.gz . I generated the related `png` files as per the instructions on above cited page, and uploaded the results.

Fixes issue #11261.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @JohnRDOrazio! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/JohnRDOrazio/cesium/blob/maki-update-8.0/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/maki-update-8.0/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by JohnRDOrazio** [comment]
It seems that some icons have been renamed, I've kept both the old and the new naming to make sure nothing breaks. Perhaps it should be considered whether the new naming should be announced at some point? Or should both naming schemes be kept viable?

Here are the icons with new names, and sometimes with an updated look ( `N/A` means it has been removed as far as I can tell, you can visually compare against https://labs.mapbox.com/maki-icons/ ):
|- old name -|- new name -|
|------------|-------------|
|`america-football.png`|`american-football.png`|
|`camera.png`|`attraction.png`|
|`chemist.png`| N/A |
|`disability.png`|`wheelchair.png`|
|`emergency-telephone.png`|`emergency-phone.png`|
|`industrial.png`|`industry.png`|
|`land-use.png`|`landuse.png`|
|`london-underground.png`| N/A |
|`minefield.png`| N/A |
|`mobilephone.png`|`mobile-phone.png`|
|`oil-well.png`| N/A |
|`park.png`|`park-alt1.png`|
|`park2.png`|`park.png`|
|`polling-place.png`| N/A |
|`rail-underground.png`| N/A |
|`rail-above.png`| N/A |
|`toilets.png`|`toilet.png`|

**Comment by ggetz** [comment]
Thanks for the PR @JohnRDOrazio!

Since its been almost 10 years since the maki update process was established, there may now be a better solution today. Many of the problem described in https://github.com/CesiumGS/cesium/pull/2161 will likely no longer be issues: We no longer support IE11, and the layout of the icons themsleves appears to have been updated. Perhaps we can consider making https://github.com/mapbox/maki an npm dependency.

Regarding the renaming, I think maintaining backwards compatibility is a good idea. Ideally, we could remap the old names to a new name rather than including two images.

We'll also need to update our Maki attribution accordingly.

**Comment by JohnRDOrazio** [comment]
In fact the npm package https://www.npmjs.com/package/@mapbox/maki still uses only the source svg files. There is certainly better support for svg in canvas now, so perhaps it could be an idea to try to implement the SVGs directly. But perhaps in the meantime a quick update of the PNGs would be an intermediate and more immediate solution?

**Comment by ggetz** [comment]
@JohnRDOrazio I'm closing this issue due to inactivity. If you'd like to discuss further, please feel free to re-open. Thanks!

**Pull request closed without merging**
