### PR TITLE
Fix for Node 14 Gulp Build issue

### LINKED ISSUE #8864: NPM task 'build' is passed a non-Buffer / String variable.
[The method 'glslToJavaScript'](https://github.com/CesiumGS/cesium/blob/master/gulpfile.cjs#L1117) is [sometimes passed a Boolean](https://github.com/CesiumGS/cesium/blob/master/gulpfile.cjs#L332).  

Type conversions are not forced in Node 14.x and an exception is thrown.  Recommend testing for Boolean and handling accordingly.

### PR DESCRIPTION
**Pull request by LuminousPath**
Fixes #8864 by passing the `minify` argument as a string to `fs.writeFileSync`

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @LuminousPath!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/gulp_node14_fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Thanks @LuminousPath, even with a small change like this we need a CLA to accept the code. It's up to you if you want to contribute as an individual or on behalf of a company. See [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) for links to the web forms.

If you can't sign a CLA for whatever reason, I'm happy to make this change on your behalf (since it's tiny), but we can't add you to Contributors.md without the CLA.  So just let us know either way.

Thanks again.

**Comment by LuminousPath** [comment]
No problem, I had to have a little back-and-forth with my business team but it looks like everything's in order. I've signed the CLA for my company, Navagis, so I think I should be good to go now.

**Comment by OmarShehata** [comment]
Thanks @LuminousPath ! Can confirm we've received your corporate CLA.

**Comment by mramato** [comment]
Thanks @LuminousPath!

**Pull request merged**
