### PR TITLE
Adds Release Guide to Documentation

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
Checking the Release Guide into the repo will allow us to better maintain and update it as time goes on.

- 53b0980dd3fb2d69076b801615fd08653c654fe9 : Copies the Release Guide from the Wiki verbatim.
- 426800a2c090e342f701cef859b6e3d03004d605 : Updates the Release Guide.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/release-guide/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks for moving this out of the wiki @sanjeetsuhag! I agree that this will make it easier to update the documented process, as this guide can now be updated as part of a PR with the other code and documentation changes.

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag! The link to `CHANGES.md` looks broken, but otherwise this should be good to go!

**Comment by sanjeetsuhag** [comment]
@ggetz I've updated the links here.

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag!

**Pull request merged**
