### PR TITLE
Inline workers into Cesium.js

### PR DESCRIPTION
**Pull request by ggetz**
Fixes https://github.com/CesiumGS/cesium/issues/11505

Part of https://github.com/CesiumGS/cesium/issues/10619

This inlines all the worker files into `Cesium.js` rather than having `Cesium.js` request each additional worker file. This is appealing because:

* When using `Cesium.js` as a CDN as it reduces the number of additional files requested in turn
* It simplifies deployment for those not using tooling, as the built `Workers` directory does not need to be served, and because cached versions of Cesium.js and the workers will always be the same.
* Theoretically, since network bandwidth will not be used requesting these additional files, time to see content on screen can be reduced.

The CesiumJS build will still ship individual worker modules for those using the ESM version of the library.

| | **Before** | **After** |
| --- | --- | --- | 
| `CesiumUnminified/Cesium.js` | 9.6MB | 12.8MB |
| `CesiumUnminified/Workers` | 2.2MB |  |
| `Cesium/Cesium.js` | 3.8MB | 4.9 MB |
| `Cesium/Workers` | 0.9MB |  |
| `Cesium-1.*.zip` | 68.1MB | 70.2MB |

To test:
* run `npm run make-zip`
* ensure `Build/Cesium/Cesium.js` and `Build/CesiumUnminified/Cesium.js` work
* run `npm start`
* ensure each link on `localhost:8080` still works as expected

TODO:
- [x] Fix specs
- [x] Verify and document built file sizes

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/worker-inline/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by jjhembd** [comment]
Thanks @ggetz. 
I'm getting HTTP 404 errors for http://localhost:8080/Build/Apps/Sandcastle/index.html and http://localhost:8080/Build/Apps/CesiumViewer/index.html.

**Comment by ggetz** [comment]
Thanks @jjhembd! The issue also appears to be happening in `main` and is unrelated to the above changes.

Running `build-apps` requires the `Build/Cesium` directory to exist. You can build it by running `make-zip` before `build-apps`. I think this is confusing and I'll document the issue, but I don't think it should hold up this PR.

**Review by jjhembd — APPROVED** [review]
Thanks @ggetz! It's working for me now, on both Firefox and Chrome.

**Comment by selimsezr** [comment]
Hi everyone,  I am currently encountering this problem while running. How can I solve?
image

**Comment by ggetz** [comment]
Hi @selimsezr, do you have any info about your build process? Perhaps a webpack config file?

**Comment by rodrigonzalz** [comment]
Hi, I am getting same error as @selimsezr 
@ggetz In my case I use Cesium with NextJS, have the webpack setup as described on [cesium-webpacl-example](https://github.com/CesiumGS/cesium-webpack-example ) and it has been working fine until now.
After finding this change, I have removed Workers from the CopyWebpackPlugin and everything is working now.

**Comment by selimsezr** [comment]
Hello, 

I also asked the link [here](https://community.cesium.com/t/cesium-ion-1-110-webpack-problem/27351) and found my solution myself and shared it. I hope it helps everyone

**Comment by ashley-mort** [comment]
In Cesium 1.115, is there a way to import (as ESM) such that it doesn't load the ~50 worker/chunk resources individually upon first polygon draw? I am doing:

import * as Cesium from './Cesium/1.115/Cesium/index.js'; //this is from the downloaded Build directory

But it's still loading a ton of resources when the first geometry is drawn. Is there a way to avoid this yet?

**Pull request merged**
