### PR TITLE
Whole new way of computing a polyline arrow interior.

### LINKED ISSUE #3491: Polyline with arrow material is blurry
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/sFOMs4XMJQk

It's particularly noticeable when the polyline has a large width:
image

### PR DESCRIPTION
**Pull request by emackey**
How did I get roped into this?  It has nothing to do with anything I'm working on.

Fixes #3491

Possible continued crazy ideas:

- [x] Outlines (color + width) would be a good idea to add to this, and would make the arrow head and line pop a little better.  Also given this new method, the outline should be able to hold a constant width even around the arrow head and interface with the rest of the line, the same way that `fuzz` does now.  Previously there was a sharply aliased boundary between the head and the line, which is fixed here.
- Would be nice someday to add a uniform to control `headLength`
- Would be nice someday to add a uniform to control `centerAmount` which I guess should be renamed to `centerWidth` or some such.

Don't try to read this as a line-by-line diff.  The whole body has been replaced by new math.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/polyline-arrow-rewrite/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
> How did I get roped into this? It has nothing to do with anything I'm working on.

:laughing: I guess I'm just that charismatic.

**Comment by emackey** [comment]
`outlineColor` and `outlineWidth` have been added to the uniforms at the primitive level.

There's a default 1-pixel width black outline.  The previous arrow had an unintentional dark blur around it, on account of blending against transparent black.  So, the new default looks somewhat similar to the previous effect, except it's crisp and controllable by uniforms.

**Comment by emackey** [comment]
Since outlines work, you can now do [hollow arrows](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/polyline-arrow-rewrite/Apps/Sandcastle/index.html?#c=hZJRT8IwFIX/SrOnkYwORBKDg0gg0QcMJhp9cD6U7QKNXbu03cgk/nfbbkMEEvfSnnvPd9q7rSQSlRR2INEYcdihGShaZPjV1fzYS5yeCa4J5SBjr3Mb89JQKgEOBqpp7GTTygWrmHEr03Z1nEuaUU1LUJikqX900FPjnQnGINFUcL9jj4j5IcUh+5gjE6yotahRi8+I1GZH+ACvpcjmsJEAaiolqR6AbrZa+e+WRKjbv+rhXlCLwfCwHfbs04juzX+ej45bdjTV2xE62DOiQVLCDhd7bAruWi9VDn4dddpu5zdXFjvrC/a1EaFEMCF/J7XKpU1ZviX+n/L9cjEPUA8POkFLi0I37/UsxLlPfG/1QNdN/dsuNuy7/hhe4EVKVwwmLXdHs1xIjQrJfIxDDVnOzFAqXBXJJ2icKGVRa43CYzRKaYloOr7wb6GEEaVMZ10w9ky/IPYmUWj8ZygTJKV8syxBMlJZ27Y/WdRFjHEUGnmZ1EKwFZEnyT8).

```
var viewer = new Cesium.Viewer("cesiumContainer");
var scene = viewer.scene;
var polylines = scene.primitives.add(new Cesium.PolylineCollection());

polylines.add({
  positions: Cesium.Cartesian3.fromDegreesArrayHeights([
    -120.0,
    35.0,
    500000,
    -80.0,
    35.0,
    500000,
  ]),
  width: 80.0,
  material: Cesium.Material.fromType(
    Cesium.Material.PolylineArrowType,{
      color: Cesium.Color.fromAlpha(Cesium.Color.GOLD, 0.3),
      outlineColor: Cesium.Color.GOLD,
      outlineWidth: 4,
    }
  ),
});
```

**Comment by mramato** [comment]
Looks awesome @emackey the lines are definitely much nicer and crisper.

There are some issues with horizon views and ending up with an arrow head on each side, from your Sandcastle:

Peek 2020-04-23 20-55

**Comment by emackey** [comment]
Yep, I believe those are known issues with the way polylines generate their texture coordinates.

**Comment by emackey** [comment]
Or maybe it's an artifact of the line being too short for its own head...

**Comment by emackey** [comment]
Well it's... less terrible?  CI still running.

**Comment by mramato** [comment]
I’m not seeing the arrow at all on my iPad. I can try desktop Safari tomorrow.

**Comment by emackey** [comment]
The arrow worked on my kids' iPad (Pro or something?  2016-era iPad, I can't keep track of their generations).  More testing always welcome.

**Comment by mramato** [comment]
Weird.  I tried both my iPhone Xs running 13.4.1 (model MTAL2LL/A) and iPad Pro (10.5 inch) running 13.4.1 (model MQDT2LL/A)

Can anyone else with an iPad/iPhone give a try and confirm if they see the arrow?

**Comment by emackey** [comment]
@shunter Any chance you can test [this demo](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/polyline-arrow-rewrite/Apps/Sandcastle/standalone.html#c=hZLfa9swEMf/FeEnB2wpWVYYqRsWUtgeOjpo2R7mPVzsaywmS0KSbdzS/32Sf2RtWphfpLv7fr66s9SCIS3HDg25IhI7skfLm5r+GHJxHhVDvFfSAZdo8mhxmcvWU7ZAiR4aaTqEU0kr0Quvtr485Kk2vOaOt2gplGX84qDvk3avhMDCcSXjRTgilyeXAXnKJfHGlgeJ3cz4HozzO5Br+mBUfY1Hg2h3xkD/Ffmxcjb+FUhC0tWHJV0mY7C+OG0vluGbgvTT/zS/F8PS8dJVG3KS1+DQcBCnxr5NiaGt+15jPFqdl+f5fcuqC7rkaRQSUiihzL9JQzS47YSuIH6V/nJ7c52QJV0vkplWjZv+6xuTQX2m+zkO9HHKP4clmD2PlxElUWZdL3A7c595rZVxpDEippQ5rLXwQ1l2aIo/6GhhbUCDNGMv0azkLeHl1TtvixQCrPWVh0aIO/6IebTNmNe/QYWCksvjbYtGQB9k1Wp7MyYppRnz4fukU0ocwJw5+/kq5/SGsbGptMSW2nXa4cE/OUwbmyJYl64o1PCoJHSWFqqe1Gx+qymEa0wNdsZTbKe1ZXcgy8KzAtkR/CM3PfsL) on your iPhone or other iOS gear?

It should look like this:

ThickArrow

**Comment by emackey** [comment]
For comparison, here's a [similar demo in master](https://sandcastle.cesium.com/#c=hZFRa8IwEMe/SuhTBU11IgxXZaPC9uBwsLGXdQ+xPfVYmpQkrXTid1/S1k6csLwk/7v/7+6SlEyREmEPisyIgD2JQGOR0fc65sdeUutICsNQgIq93l0sSkvpBARYqKFpLdtULnnFrVvbdB2nucIMDZagKUtT/6zRS+uNJOeQGJTC77kWseiq1MghFsQW1ugsenrCI6aMPTExphslswVsFYB+UIpVT4DbndH+hyMJGYxuhnTYb8R40h0nQ7daMbj9z/PZq7c9pmY3JZ09YwYUMt4N9twG6rHeqhz8ptRl+nR/O7LcO1//0BgJSSSX6vemTtHH1XLR5I9uc8Mcm+fy+l6oTcVhfuLvMculMqRQ3Kc0MJDl3LbVwbpIvsDQRGuHOmsYnKNhiiXBdHbl90nCmdY2syk4f8VviL15GFj/H5RLlqLYrkpQnFXOthvNl02QUhoGVl4njZR8zdRF5R8) with the blurry solid-color arrow.

**Comment by shunter** [comment]
No polyline at all.  iPad Air 2 and iPhone 7.  I checked the console and there were no related errors (some 404s about missing JS source map files)

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by emackey** [comment]
I'm at a stalemate on this.  I presume it's some issue between GLSL and older iOS, but it could be the branch, and I have no hardware that can reproduce it (we have 3 iPads here circa 2017, all show the arrow).

If it's not salvageable, feel free to close this.

**Comment by mramato** [comment]
I believe the next version of Safari is getting a new angle-based WebGL backend.  So I'm okay with just leaving this open and revisiting as soon as that update is out.  I appreciate the effort either way @emackey!

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by emackey** [comment]
Merged master in, just in case #9064 fixed anything here.

**Comment by mramato** [comment]
Thanks @emackey!  Unfortunately not.  But I still hold out hope the next version of Safari will (since there's a big WebGL overhaul).

I also wonder if there is some undiscovered bug in Cesium that is causing this, (vs the WebGL implementation)

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by mramato** [comment]
I was curious about this PR since Safari is now using ANGLE and has much better WebGL support. I merged in main and the arrow now shows up on iOS. So aspects of this PR is a huge improvement over what's in main. There are still some weird behavior at certain angles that someone might look into, but I feel like this PR is something we can revisit sometimes soon.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @emackey! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by ggetz** [comment]
I'm closing this for now as it's quite out of date with main. If we wish to revisit this in the future, let's open a fresh PR. Thanks all.

**Pull request closed without merging**
