### PR TITLE
Set `ExperimentalFeatures.enableModelExperimental` to true

### PR DESCRIPTION
**Pull request by ptrgags**
in preparation for #10346, we wanted to enable ModelExperimental by default early in the month so there's time to catch any bugs we may have missed.

That said, there are a few known issues (see #10346) so in a few sandcastles we explicitly set the flag to false:

* BIM model that needs to be updated to not use techniques:
  * Apps/Sandcastle/gallery/3D Tiles BIM.html
  * Apps/Sandcastle/gallery/3D Tiles Clipping Planes.html
  * Apps/Sandcastle/gallery/Ambient Occlusion.html
  * Apps/Sandcastle/gallery/MSAA.html
  * Apps/Sandcastle/gallery/Polylines on 3D Tiles.html
* getNode needs to be implemented:
  * Apps/Sandcastle/gallery/CZML Model - Node Transformations.html
  * Apps/Sandcastle/gallery/Time Dynamic Wheels.html
* Point cloud styling is not yet supported
  * Apps/Sandcastle/gallery/3D Tiles Point Cloud Styling.html
  * Apps/Sandcastle/gallery/Montreal Point Cloud.html
* Classification model needs to be updated to use GltfLoader
  * Apps/Sandcastle/gallery/3D Tiles Photogrammetry * Classification.html

All other 3D Tiles sandcastles should work fine.

@j9liu could you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/model-experimental-by-default/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ptrgags** [comment]
Today we're looking into the test failures. Some of them are due to test code that is only used for the old Model and will be removed soon, so in some cases setting the flag to `false` is the simplest way to address them.

* [x] ModelVisualizer
	* **Action**: Disable ModelExperimental since getNode() is not implemented (@j9liu will be implementing this soon)
	* getNode() not defined
	* Computes bounding sphere (cannot set properties of `loadfail`)
* [ ] B3dmParser
	* **Action**: Investigate
	* expected undefined to be defined
* [ ] Batched3DModel3DTileContent
	* **Action**: Disable ModelExperimental since this is the old Model?
* [ ] Cesium3DTileBatchTable
	* **Action**: Investigate
	* batch table hierarchy not working correctly
	* byte lengths not the same
* [ ] Cesium3DTileset
	* **Action**: Evaluate on case-by-case basis
	* animates instance gives same matrix
	* animates batched tileset gives same matrix
	* statistics not the same
	* debugColorizeTiles renders wrong color
	* apply style renders wrong color
	* backface commands not the same
* [ ] Implicit3DTileContent
	* **Action**: investigate
	* multiple contents instead of b3dm content?
* [x] Instanced3DModel3DTileContent
	* **Action**: Disable ModelExperimental
* [x] PointCloud3DTileContent
	* **Action**: Disable ModelExperimental

**Comment by ptrgags** [comment]
To fix some of the tests in `Cesium3DTileset` without skipping them entirely, I opened #10532

**Comment by j9liu** [comment]
One of the unit tests requires a longer fix, so I opened #10535 to handle it later

**Comment by j9liu** [comment]
I opened #10536  for the two statistics-related tests in `Cesium3DTilesetSpec`, we'll visit it later

**Comment by j9liu** [comment]
@ptrgags and I cross-checked each other's changes, and Travis is finally passing, so I'll go ahead and merge. Thanks @ptrgags !

**Pull request merged**
