### PR TITLE
Improve control over CustomShader translucency settings

### PR DESCRIPTION
**Pull request by ptrgags**
Originally, CustomShader had a `isTranslucent` flag that worked like this:

* `isTranslucent: true` - override the material settings and always render in the translucent pass
* `isTranslucent: false (default)` - override the material settings and always render in an opaque pass

However, this is sometimes confusing and may be limiting in cases where primitives have some opaque and some translucent materials.

Instead, I added `translucencyMode` with 3 states:

* ~NO_CHANGE~ `INHERIT` - Inherit settings from the primitive's material (i.e. if the shader is applied to an opaque primitive, the alpha channel will be ignored, but if applied to a translucent primitive, the alpha channel will be used)
* `TRANSLUCENT` - override the material and render as translucent
* `OPAQUE` - override the material and render as opaque.

@lilleyse could you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/custom-shader-translucency-mode/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by lilleyse** [comment]
This is pretty minor, but I noticed a comment that still uses the name `isTranslucent`

    // always check the current value, because custom shaders may
    // change the value with the isTranslucent flag
    return renderResources.alphaOptions.pass === Pass.TRANSLUCENT;

**Comment by lilleyse** [comment]
The actual code looks good and I'm pretty much fine with the naming.

**Comment by ptrgags** [comment]
@lilleyse updated!

**Pull request merged**
