### PR TITLE
Adds ability to get vctr polyline positions

### PR DESCRIPTION
**Pull request by lilleyse**
Adds a `polylinePositions` getter to `Cesium3DTileFeature` that returns a Float64Array of cartesian coordinates for a polyline in a vctr tile. It works for both clamped and unclamped polylines.

Also adds an option to `Cesium3DTileset` called `vectorKeepDecodedPositions`. This option allows positions and offsets to stay in memory even after the positions have been uploaded  to the GPU. This must be set to true in order to use this feature. It is false by default so that applications that don't use this feature don't pay the extra memory cost.

Both are marked as `@experimental`.

There are some limitations:

* If multiple polylines have the same batch id there isn't a way to distinguish positions in one polyline vs. another. I haven't run across this case in practice. I was considering returning an array of `Float64Array` but thought it might make the API too complicated.
* The positions don't update correctly if the tileset model matrix changes. I'm pretty sure this is broken for vector tiles in general because the model matrix is only used once to transform the center point in the beginning (the rotational component is not applied to the positions). I'm not too surprised because the vctr format, like quantized mesh, defines positions in cartographic coordinates so there isn't usually a need to transform the data.
* Doesn't returned the clamped positions, just the positions as they are in the data

@angrycat9000 @mramato this is good for testing though I still need to finish up the to-do items below:

* [x] Tests
* [x] `CHANGES.md`

Untitled

[Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=zVdtTxs5EP4rbr6wOZZdWvopAXQoBIGaACopVdWtkLM7IT4ce2V7E9Jr/vuNvS/J5oVSqapOgiRrz2PPPPN4PDulikwZzECREyJgRjqgWTYJ7t2Ytxe7x44UhjIBaq/ZjsQUMToGAQjJsYF7xKlIhCG5lFNczn2MgJpMgSZGEg1AzBiYIqnUzDAptDPvcBY/1SwTRWeEEp2OQQGRggCNxxXKgT5L9aTJSCoy6H78eHZ17ZNO9+7qU//h6PxhcNXr+oSKhFzfXHdJzKnWbMRimsPzCAzjoMHUw86/js4H+aT3byQIyRRvkagRBGH+d5dCrMNzamhYsw/vITZSFV926FbyOUfedFjsFvyj0YOGb5etuzWYp9Cq3NiYCsowLTIMfw1rWXDAqfPsA0B6DrFMILktM9EiRmUQiUXTZbFI63cpJwPpFc673K/kO0gVmyB8CjqgSbJqFolRJmK7ss3RhJqSiWpDL10faRLHtssNPNvERI2o0S7HKtH0QDyaMU5vrBDwfCokRw5m5eFZLEPrwzZ+Ha8v0yb7+6zYmeT77m9Z+Ssjf5Gjb2QfffLxH3/ssMGZt6+0e5fbRUhXHubCfijAcyCcKzi4qHGJLPepegL1/6TP2sZUGRQiFYgpFVkOHQWZSGn8tOm8TxwpzfZyoSHPoMs5S7VkybLSgDAIKRRX7Esqt1rL/f1yDspFWqSyR5ppwlirdvYrN713h8GhT5afTX8JRDGDYpQvD5zkUgWdL2fXldWi+LVolnldlLVx0O+50sjp3BGsx3LGxGNZ/4igE1fyJjLTYA3zamWHbwrYCUlknE2QiSBWCEOawD55USNh06ixck7jsnAHNE1BJJ0x44m3spi1XXkMXGG5tj5Y/QwxWYmSqdPRqpk2cw5BwnSaOxQ1hBSww6xMjrOjQy15ZnbZDqUxcuIsD3eYcBiZlwy+Ro1UMoFZOoAp0qKjxrefuIiQ2ZgZONAoTyjtU7UzIhSfTZq1ep8+74oF2XtUMkParURyRjkOOvs8r2P2OOb4b8Bq3OmzUEKLIBBGmLzEqUkq9sgE5W6tunDtiGc1ulgt3hrFAeLORtS1PFzihcjtOJgrkWbmzNUUryouUvSt5vooOm+CH1ZSxdFG4V6N8EYuRTqjmiA7U4YAPl8NwrdeS3vPL0ftCmxEvMLdIihvBRUUCzerUrJlEsWcs7g6V2OlvROLqIrNZanFsG5t70Edm4VpVTBxBpKLCl+/+XCyIglrUnWR5gfeRvtmLdzaek3y4wd5Ux8jTGhDRQxytK0duVin6JXn0RU7d6csAy+CvyyJcvkqqULnmdnTREhDKMcCk8yxd+PYOiCfFrmd31osbqtafYw5OuTl7tRM87T6m6mrpdZO59xuAa9cNW6vL91e7+Zzu4w0v/7Wbpx1j4MNi92Z3Lh6f2NOzuqHzLnoEy3dRZEnprw+bHFH+Vngy/sOuSyKzjbLquSWdwbFyqQxYcwWDXD6OCDbxB7MXQNTFMBtaxe1eiv4eTfYNjCdPDoXwLJNdc0SAl/fVdomyi/1cbdWE1173L/5dNd96N/cd5u/oX6615n1AvqLBSX989Vkmxz/4MHZtv2L3e7P09rrXgweOr2rzoc8rQ2/cexUeVq2aX+zSSqVsS94Hr7XGZjgkcEeMBxmGCB2V1qXHelxuAo9xj6LsOQkaqy9H6M2XQeFM6OM8zv2HQ/86XGI9htQLqltIgrNW7Px29NePhgEwXGIj9uRRko+pGpt5f8A)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
Updated with tests. One thing to note is that `Vector3DTileContentSpec` tests are currently disabled with `xdescribe` since https://github.com/CesiumGS/cesium/pull/8317 so if you're testing locally you'll need to change that to `describe`. The new tests should pass but some of the existing tests do not, mainly those related to rendering points.

@ebogo1 can you review?

**Review by ebogo1 — COMMENTED** [review]
Tests well in Sandcastle and locally in Jasmine. Are any of the known limitations you listed enough to hold up the PR? Code looks good to me otherwise, I think it's ready after CI passes (just pushed a commit to fix prettier).

**Comment by lilleyse** [comment]
> Are any of the known limitations you listed enough to hold up the PR?

No, I think it's fine to proceed without those fixes. There's a little bit of leeway because vector tiles are still marked as experimental in the API.

**Comment by junglelan** [comment]
is polygon vctr can use in lastest version? Have any demo data to provide?

**Pull request merged**
