### PR TITLE
Fog post process sandcastle

### PR DESCRIPTION
**Pull request by lilleyse**
While working on globe translucency I created a fog post process effect that might be nice to include in sandcastle. It's implemented with a custom post process where the fog distance and color are uniforms and can be changed dynamically.

fog

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fog-post-process/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @lilleyse! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks @lilleyse!  This is a great demo =)

**Comment by hpinkos** [comment]
Added a comment to CHANGES.md here https://github.com/CesiumGS/cesium/commit/7efc9157ed220c62d8d2f4d7925bd85041fe31c3

**Pull request merged**
