### PR TITLE
Fix broken image in KML Sandcastle

### PR DESCRIPTION
**Pull request by j9liu**
Fixes issue in #9527.

Downloaded the AGI logo so it is stored in SampleData; the page uses a local path to reference the image.

@ebogo1 for review.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @j9liu! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/CesiumGS/cesium/blob/fix-broken-image/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-broken-image/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by ebogo1** [comment]
@j9liu This looks good, I confirmed this fixes the broken image in Sandcastle. Like in the previous PR, could you please move the CHANGES.md line to the new 1.83 section?

**Comment by j9liu** [comment]
@ebogo1 Done!

**Comment by ebogo1** [comment]
@j9liu Thanks - I closed #9527 but like Sean mentioned, if you use the "Fixes #XXXX" syntax it should do so automatically.

**Comment by lilleyse** [comment]
@ebogo1 @j9liu Something might have went wrong when merging `master` into this branch since there are a bunch of extraneous commits in this PR.

I think it's ok, but in the future if you see anything suspicious like that definitely reach out.

Otherwise, thanks for the fix @j9liu!

**Comment by ebogo1** [comment]
@lilleyse I noticed that but the diff looked correct to me; I did a squash+merge on this one to keep the commit history cleaner. Do we usually do something different for things like this?

**Comment by lilleyse** [comment]
Squash+merge can be fine depending on the situation and the commands that are used. Let's talk offline about the process you went through.

**Comment by j9liu** [comment]
@lilleyse when I did "git pull origin master" on my branch, it started a rebase as opposed to a merge, so that's my bad! I'll be more careful about it next time

**Pull request merged**
