### PR TITLE
Convert implicit subtrees from binary to JSON

### PR DESCRIPTION
**Pull request by ptrgags**
Followup PR to #10151 that makes the same binary -> JSON subtree change but for the non-metadata tilesets.

@j9liu We can wait on merging this until after #10151

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by j9liu** [comment]
@ptrgags Regarding the change to `ImplicitTileset`: there's already an `ImplicitTilesetWithJsonSubtree`. Do we want to keep around the `.subtree` version for testing purposes, and just rename it as `ImplicitTilesetWithBinarySubtree`?

**Comment by ptrgags** [comment]
@j9liu ah good point, I converted one tileset too many. I'm just going to keep it called `ImplicitTileset`

**Comment by j9liu** [comment]
Thanks @ptrgags ! Merging now.

**Pull request merged**
