### PR TITLE
Fix label background in request render mode

### PR DESCRIPTION
**Pull request by ggetz**
Fixes https://github.com/CesiumGS/cesium/issues/11529 by making sure another frame renders after the label background is ready.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by jjhembd** [comment]
Thanks @ggetz. If I use the Sandcastle from #11529, this PR fixes the first added label, but not subsequent labels.

image

I think we need to add an `afterRender` every time `_labelsToUpdate.length > 0`.

**Comment by ggetz** [comment]
Thanks @jjhembd! I tweaked where to request the additional frame render to cover all the cases.

**Review by jjhembd — APPROVED** [review]
Thanks @ggetz! This is working well now.

**Comment by rropp5** [comment]
@ggetz Unfortunately, I believe the change you made to Billboard.js in your second commit introduced some unexpected behavior that causes a render every time a Billboard is added to the system. 

This eliminates any performance gains from request render mode when the system needs to add Billboards very frequently so I think we need to revisit the original solution to come up with something better. See my Sandcastle below for details.

[Sandcastle: Add a billboard every 100ms in request render mode. Observe renders happen each time a billboard is added.](https://sandcastle.cesium.com/#c=fVNNj9MwEP0rQ04pTZ2k3Zb0U6CeVgItYhGnXFxnmlo4drGdfizqf8dxGlS6K3yJ5/nN85sZhylpLBw4HlHDEiQeYY2G1xX54bEwD5iP10payiXqPOjNc5nLOIZntKDxV42m+crCSVSqwFy2esQwlEiujG+e8MWdu3usrnHuNZ6kOHfJxx1KwNNecMath30mFneKFT3xqq5axe+8wvWOyrLRfZRbLrk9e4fM12Ys1farMv9Wt3ag21E5CgfZMBklGfmQJlk6eciyNILBeDgZTocZGQ2nWTIep9MIRg/TyWQ6JeMkdfRxkjV9EK4FTNXSOvnExQbto7SoD1SEYQ+WK/idS4DWCqu1/p+TRhBe44QJJTHsCok6nZZ+DcjJyXYUF/QhTdyC9629ft+TOy9KIBGqdNP9VBRclkC9pQ0XYqOoLmAwcDPiZYnauLPb+XDX0p2qRQFS2Xfta4DrCyIoLbccDaFFEfrKAfbKOEzJWWc1avG/l83gyrxdvKIlziAPCIn93sRbyrhwwyUl3+bBfcqlAS6Nm0vU1A69eRAFC2PPAlcd+SOv9kpbqLUInbDFai+oa3O8qdlPtISZa1cBFvFt6qLgB+DF8o3fAZigxriTbS3EM3/BPFgtYsd/lSoUbZr9dEAt6Lmh7dLV5xYkhCxiF76daZUSG6rvlP8A)

As the original bug was related to the label's background failing to draw, do you think there's a better way to encapsulate the solution within LabelCollection.js? 

I'm not familiar with the preferred workflow for Cesium yet but should I report this as a new bug or do you want to reopen this?

**Pull request merged**
