### PR TITLE
Deprecate some Model options that will not be supported in `ModelExperimental`

### PR DESCRIPTION
**Pull request by ptrgags**
This PR deprecates the following properties for consistency with the API we want for `ModelExperimental` (which will eventually replace `Model`)

* `Model.gltf` (getter)
* `Model.basePath` (getter)
* `Model.pendingTextureLoads` (getter)
* `dequantizeInShader` (constructor option)

It also notifies users that `Model.boundingSphere` will use a different coordinate system in a future release (ECEF rather than model space). (How to report this is under discussion)

@lilleyse could you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ptrgags** [comment]
@lilleyse updated!

**Comment by ggetz** [comment]
@ptrgags I think we're missing a deprecation warning for the `dequantizeInShader` option.

**Comment by ggetz** [comment]
Thanks @ptrgags! This looks good to me. I'll merge when CI passes.

**Pull request merged**
