### PR TITLE
Allow mipmaps with KHR_texture_transform

### LINKED ISSUE #10787: mipmap will be lost when use KHR_texture_transform in Cesium
[correct.zip](https://github.com/CesiumGS/cesium/files/9562204/correct.zip) without 'KHR_texture_transform'

three.js
1_threejs
babylon.js
1_babylon
cesium
1_cesium

[wrong.zip](https://github.com/CesiumGS/cesium/files/9562205/wrong.zip) with 'KHR_texture_transform'
three.js
2_threejs
babylon.js
2_babylon
cesium
2_cesium

### PR DESCRIPTION
**Pull request by jjhembd**
Resolves #10787 by allowing mipmaps in the sampler for textures using `KHR_texture_transform`.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jjhembd!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/khr-transform-mipmap/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by jjhembd** [comment]
@sweco-sekrsv, could you test this branch and let us know if it works for your datasets?

**Comment by ggetz** [comment]
@lilleyse Could you please give this change a look?

**Comment by lilleyse** [comment]
Looks good to me. Feel free to merge after resolving the conflicts.

**Comment by ggetz** [comment]
Thanks all!

**Pull request merged**
