### PR TITLE
Show/hide collections

### PR DESCRIPTION
**Pull request by hpinkos**
Adds `show` property to `BillboardCollection`, `EntityCluster`, `LabelCollection`, `PointPrimitiveCollection`, and `PolylineCollection` for a convenient way to control show of the entire collection

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@IanLilleyT can you review?

**Review by IanLilleyT — CHANGES_REQUESTED** [review]
I'm not exactly sure when `EntityCluster.show` would be used. `DataSource` already has a `show` property.

**Comment by hpinkos** [comment]
Thanks @IanLilleyT !  This is ready now

**Comment by hpinkos** [comment]
bump @IanLilleyT

**Comment by IanLilleyT** [comment]
Thank @hpinkos , merged!

**Pull request merged**
