### PR TITLE
Documentation fixes 2024-01-20

### PR DESCRIPTION
**Pull request by javagl**
Addresses https://github.com/CesiumGS/cesium/issues/11749#issue-2072624863 (not the issue as a whole, but only the points mentioned in this comment)

The commits basically correspond to the points that are listed in the comment, each implementing the 'Suggested fix'.

For the last point (entity constructor options) I also documented `viewFrom` as `{Property | Cartesian3}`. (It could probably be a `PositionProperty`, but ... maybe that would be confusing..?)

Note: The `EntityCollection#add` function originally threw a `RuntimeError` for duplicate IDs, and now throws a `DeveloperError` (as of  https://github.com/CesiumGS/cesium/commit/80d09540657df549ec70bdd0803167f827ce8aeb ). This could be considered as a "breaking change", or.... as a bugfix: The documentation already said that it throws a `DeveloperError`, so this just aligns the implementation with the existing documentation...

Beyond that, I'm not sure whether anything here should be mentioned in the `CHANGES.md`...

### CODE REVIEW

**Comment by ggetz** [comment]
@javagl Are all your changes in?

**Comment by javagl** [comment]
@ggetz I added the change notes in https://github.com/CesiumGS/cesium/pull/11776/commits/328b12df88a5f3c3f56f4bbdaeba27ccc3e3fe75 , explicitly pointing out the `RuntimeError`-to-`DeveloperError` fix, but summarizing the others, mentioning that they may resolve potential issues with the TypeScript typings. 

An aside: Is there a "good" reason to _not_ track `Cesium.d.ts` in Git? (Besides its size ... 2MB...). It could be good to have another way of ensuring that there are not accidental changes, except for locally diff'ing an old and a new version...

Cesium TS diff

**Comment by ggetz** [comment]
Thanks @javagl!

> Is there a "good" reason to not track Cesium.d.ts in Git? (Besides its size ... 2MB...). It could be good to have another way of ensuring that there are not accidental changes, except for locally diff'ing an old and a new version...

As a generality, we usually don't commit generated files. I may need help imagining the use cases for tracking the changes directly. We do review the source documentation changes.

**Comment by ggetz** [comment]
Changes look good @javagl. I'll merge as soon as CI passes.

**Comment by javagl** [comment]
> I may need help imagining the use cases for tracking the changes directly.

I thought that it might be tricky to foresee the implication that a change in the _JSDoc documentation_ has on the actual _bindings_ that are generated. 

Or to put it that way: The goal would be to avoid the case where a 'trivial, innocent-looking, typo-like JSDoc fix' causes a _breaking change_ for TypeScript users. 

(Right now, generating the TS bindings causes the message _"...this is likely due to invalid JSDoc"_ being printed 2716 times, and I think that nobody would notice if this suddenly turned to 2717....)

But maybe that's unlikely enough to not be an issue.

**Pull request merged**
