### PR TITLE
Fixed typo in BillboardCollection

### PR DESCRIPTION
**Pull request by IanLilleyT**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/billboardCollectionTypo/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
:woman_facepalming:

**Comment by mramato** [comment]
This is the typo of issue that makes me scratch my head and wonder how we never noticed it or how many bugs it fixes that we didn't realize were caused by this typo.

Did you have a bug that was triggering this, or did you just noticed it in the code?

**Comment by lilleyse** [comment]
It looks like `ComponentType.FLOAT` is the default in `VertexArrayFacade`, which explains why this typo didn't completely break things.

https://github.com/CesiumGS/cesium/blob/4603fd33e40db78c0baf9531ad301f64d9d63049/Source/Renderer/VertexArrayFacade.js#L110-L112

**Comment by lilleyse** [comment]
Also thankfully `componentDatatyps` doesn't show up anywhere else in the code 😄

**Pull request merged**
