### PR TITLE
Fixed depth plane for orthographic

### PR DESCRIPTION
**Pull request by IanLilleyT**
This PR fixes the polyline subissue in https://github.com/CesiumGS/cesium/issues/5110 (which is not actually related to ground primitives).

Two fixes went into this
1) Keep the orthographic depth plane centered at the ellipsoid center instead of moving closer to the camera.
2) In the depth plane shader when intersecting the ellipsoid, need to shoot rays from the near plane all in the same direction.

[Before Sandcastle (look at the left edge of the globe)](https://sandcastle.cesium.com/#c=lVRhb9owEP0rFp/CSh1oN00CWo3SakNqB2pZ92GZKpMciTfHjmwHxib++85OYNDSqeUDts/vnt9zzrdgmiw4LEGTMyJhSYZgeJnTex8Lokbs10MlLeMSdNRokT+RJKTQ6gfElis54fFP0F1idQktt8VzloJeTbRa8MTt7PBOuYAbVtyBXvAYRvvIwDMTUmrR3STMSi6SG5WUAr5ogYIGxoA14RR+2VKDCT8zHJm4Ytpmo1HUaHoNazesm71IRrLyR00MEmgq1AyoydTyo1alTAY2V6bIQANewJwJA71txmOP1MVRCwhqltzG2VSN8VSValZkPA6ePS6BwmZTMHaQ4i0aOwWtcbJz4h2TScyMFUBZkkxVmgq4KK1VMnB2osaloyAWOfATuNDLj/HweSm9ExLEGaCZpEnq236V3jq55+84kgccC5UyzW2W89hrvijnc19drj5e4vRapcQLOGT0MPtrHD6r77A1fB+FEiuBxW8QtEdVaJ5zyxdgnBUvf6fUJ3XaUAlRVVHQrGgdqSzz65rzBENzpUng4hwD7R4O/S0EV0dHtRkHEaALRHESkmBLc0w6TS99q9Zrqm+gUIY7Bab7WN2EF+BGmqIjzSwM8SEhhMmBjjfphwi2uFM61yq/hFQDmAEWyir4tkkj5Ljzvk3b5Ih02m3yxmtv7ey+fUfbO+v/QPeQ35v1dL2ZLHlisy45qUH+6a+fFGfMcjRJsYO4BlfZS7DOuWTO3V6r+mcwOG1XPyQnm7/qYKU5YGt8kvwJWMJlOnFd4hYLIKhUbhwc17AbZjM6GT2M769uH6Zfx/V22w07HazRavSNXQk431zAB54XSlvXKgNKQwt5IfDjmXBWYhFbGhtTlQMh/XA3tZ/wBeHJ2YHOTmLBjMGdeSnEHf8NUeO8HyL+SapQ3t14AVqwlYNlnfPrKkgp7Ye4PJxplRIzph8x/wU)

Screen Shot 2020-05-15 at 11 58 09 PM

[After Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=lVRhb9owEP0rFp/CSh1oN00CWo3SakNqB2pZ92GZKpMciTfHjmwHxib++85OYNDSqeUDts/vnt9zzrdgmiw4LEGTMyJhSYZgeJnTex8Lokbs10MlLeMSdNRokT+RJKTQ6gfElis54fFP0F1idQktt8VzloJeTbRa8MTt7PBOuYAbVtyBXvAYRvvIwDMTUmrR3STMSi6SG5WUAr5ogYIGxoA14RR+2VKDCT8zHJm4Ytpmo1HUaHoNazesm71IRrLyR00MEmgq1AyoydTyo1alTAY2V6bIQANewJwJA71txmOP1MVRCwhqltzG2VSN8VSValZkPA6ePS6BwmZTMHaQ4i0aOwWtcbJz4h2TScyMFUBZkkxVmgq4KK1VMnB2osaloyAWOfATuNDLj/HweSm9ExLEGaCZpEnq236V3jq55+84kgccC5UyzW2W89hrvijnc19drj5e4vRapcQLOGT0MPtrHD6r77A1fB+FEiuBxW8QtEdVaJ5zyxdgnBUvf6fUJ3XaUAlRVVHQrGgdqSzz65rzBENzpUng4hwD7R4O/S0EV0dHtRkHEaALRHESkmBLc0w6TS99q9Zrqm+gUIY7Bab7WN2EF+BGmqIjzSwM8SEhhMmBjjfphwi2uFM61yq/hFQDmAEWyir4tkkj5Ljzvk3b5Ih02m3yxmtv7ey+fUfbO+v/QPeQ35v1dL2ZLHlisy45qUH+6a+fFGfMcjRJsYO4BlfZS7DOuWTO3V6r+mcwOG1XPyQnm7/qYKU5YGt8kvwJWMJlOnFd4hYLIKhUbhwc17AbZjM6GT2M769uH6Zfx/V22w07HazRavSNXQk431zAB54XSlvXKgNKQwt5IfDjmXBWYhFbGhtTlQMh/XA3tZ/wBeHJ2YHOTmLBjMGdeSnEHf8NUeO8HyL+SapQ3t14AVqwlYNlnfPrKkgp7Ye4PJxplRIzph8x/wU)

Screen Shot 2020-05-15 at 11 58 16 PM

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/orthoDepthPlaneFix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by he-hesce** [comment]
Would like to see this merged and included in 1.70. Thanks to @IanLilleyT for addressing this critical issue #5110 for us. 👍 🥇

**Comment by mramato** [comment]
Does this fix #8653?

**Comment by IanLilleyT** [comment]
@mramato: Nope, that bug is unrelated to depth plane, I added more info there: #8653.

**Comment by lilleyse** [comment]
Looks good for this sandcastle too: [sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bVNtb9MwEP4rViSkVBR3G1+gTStKQaiCdZVWkJDyxU2uyYHji2wnXUH779hJ2malVqT43p577sW10KxG2INmU6ZgzxZgsCr4j0YXxkHSyAtSVqACHQdD9jdWjBmQkFgktVQpJsKSHrOdkAaG3opqRx/pqa8qNf1qI9aY/AbnbnXVeRciA31Ya6ox9ZYekQ1KuBflI+gaE1i+9AwbKoxVWo6PAdsKZXpPaSXhu5augrkxYM1oA0+20mBGK+H+Qn4W2ubLZRwMGg7Pg1g9DyaxilXbD24SUMAzSVvgJqf9F02VSue2IFPmoME1rKlucoq4LJF7vaMCkps92iTf0INLSpkWZY5J2KVzI2hyOcB+amfsU0ihtPkGjJ1nbhLGbkBrd+mxaKFKQmXNBZajhgVarMFwkaZhr8Fr778+mhcku7mGg5bejjQLPbAklaGtUs/zze27m0lPE7GXitfT25sB66bjgxOS5FesS7rwIl8vV18nrQ/uWBie8V6xuwGbTqfsjOLPVZTFz/mqQ3n2hP3lTFrYE+f3nuFRjlhffMHXn7aLTa962tZi0PeHnTZu4TbJ3YR6y3eaik+QaQBzrmZ4StOu2vm09Yzb/4WtxCeQj/gHxuzu5mxqdrSr1X3BMIiMPUiYHV0+YFGStv5NhJyPLBSlS+/2flu5nbQ8MeYIEY36oVGKNcN0euXNs0QKY5xlV8mGUxzMopHz/y9UkkhRZQ81aCkO3i2/nX1rlZzzaOTE65GWSG6FvkD+Bw)

**master**
before
**orthoDepthPlaneFix**
after

**Comment by lilleyse** [comment]
Code looks good 👍

**Comment by he-hesce** [comment]
Thanks @lilleyse! 💯

**Pull request merged**
