### PR TITLE
Update documentation examples to use const/let

### PR DESCRIPTION
**Pull request by ggetz**
Fixes https://github.com/CesiumGS/cesium/issues/10047

As a follow up to https://github.com/CesiumGS/cesium/pull/10026, this updates the inline code examples to use cons and let syntax.

@sanjeetsuhag Could you please review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/let-const-code-examples/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by sanjeetsuhag** [comment]
@ggetz Mostly looks good. Two spots missed are:
1. [Documentation Guide](https://github.com/CesiumGS/cesium/tree/let-const-code-examples/Documentation/Contributors/DocumentationGuide)
2. [`ImplicitTilingTester.js`](https://github.com/CesiumGS/cesium/blob/let-const-code-examples/Specs/ImplicitTilingTester.js)

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag! Updated.

**Comment by sanjeetsuhag** [comment]
This is a slight nit, but it caught my eye:

| `main` | `let-const-code-examples` |
| - | - |
| image | image |

I noticed that `const` is not highlighted. Is there something in the documentation generation that we need to change to enable ES6 highlighting?

**Comment by ggetz** [comment]
@sanjeetsuhag Yes, let's address that separately. I'll open an issue.

**Review by sanjeetsuhag — APPROVED** [review]
That's fine by me. The changes here look good! Thanks @ggetz!

**Comment by ggetz** [comment]
Opened https://github.com/CesiumGS/cesium/issues/10051 to track the jsdoc highlighting issue.

**Pull request merged**
