### PR TITLE
Use npm for third party libraries

### PR DESCRIPTION
**Pull request by ebogo1**
Part of https://github.com/CesiumGS/cesium/issues/9473. This moves most of the third party libraries to npm.

A few things are missing from this PR still, but maybe the missing packages can be a follow-up PR:
- [x] Test `NoSleep` on mobile
- [x] Test npm with release steps (i.e. `makeZipFile`)
~- [ ] `protobuf` is missing due to a circular dependency that looks incompatible with rollup - https://github.com/protobufjs/protobuf.js/issues/1402~
~- [ ] `knockout` wrapper is missing because we added our own export to the `knockout-es5` module and I haven't figured out how to access the `attachToKo` function with the npm package version.~
~- [ ] `zip.js` is missing because we used an old version that used the `createWriter` function which doesn't exist in any of the npm releases. This probably isn't hard to work around, just needs some changes in `exportKml` and `KmlDataSource`.~

This might be a question for @mramato, but I noticed there is a `pako.min.js` file in Apps/Sandcastle/ThirdParty. Are we fine with keeping this here now that we use the `pako` npm package?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ebogo1!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/CesiumGS/cesium/blob/main/LICENSE.md) and that its license information is up to date with this new version.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
Can `ktx-parse` be added too? CC https://github.com/CesiumGS/cesium/issues/9473#issuecomment-866257585

**Comment by lilleyse** [comment]
I didn't test all that carefully besides running the unit tests but the changes look fine. @mramato do you want to review?

**Comment by mramato** [comment]
Thanks, I will take a look.  @ebogo1 what is your plan for the checklist?

**Comment by ebogo1** [comment]
> Can ktx-parse be added too? CC #9473 (comment)

Yeah, good call #:+1: 

> what is your plan for the checklist?

For this PR's checklist, I will test NoSleep and try to get zip.js working with the newer version. Not sure what the best workarounds are for knockout or protobuf yet, but I'd be okay with doing them in a separate pass. 

For the issue checklist, I imagine there will be a PR for whatever's left in the "npm category" after this one, another for moving files into Source/ (i.e. FXAA), and maybe a couple small ones for individual packages like Uri.js if they can be removed entirely now that IE11 is dropped. Also I'd like to try and make gltf-pipeline and npm package.

**Comment by lilleyse** [comment]
Thanks @ebogo1. I built the code and did some spot checks of sandcastle examples and ran the units tests. Will do a full review once the staging branch is ready to merge into main.

**Comment by lilleyse** [comment]
Also, what's the order of events for follow up PRs?

**Comment by ebogo1** [comment]
> what's the order of events for follow up PRs?

I'm thinking: 

1. zip.js, which should be able to remove the inflate/deflate files in the Workers folder
2. knockout and protobuf in some order (these are the npm modules that didn't work straight away)
3. measureText + Uri (probably to be removed)
4.  google-earth-dbroot-parser.js, GltfPipeline, FXAA (to be moved into Source)
5. Draco decoder with npm

These can be done in any order though.

**Pull request merged**
