### PR TITLE
GroundPolyline BoundingSphere fix?

### PR DESCRIPTION
**Pull request by malaretv**
We work a lot with cesium on terrain datasets with fairly extreme values compared to Earth. For example, lunar terrain is roughly between -11000 and 10000 meters.

We've been trying to get GroundPolyline to work reliably on these terrain providers but even after generating a custom `approximateTerrainHeights.json` we were still seeing issues with the polylines disappearing. Upon investigation it was because the bounding spheres weren't stretching to encompass the actual geometry on the terrain.

Within the GroundPolylineGeometry source `sumHeights` is used only in one place below
https://github.com/CesiumGS/cesium/blob/4244bc02def1c931808dbeb7bd5c748218c31046/packages/engine/Source/Core/GroundPolylineGeometry.js#L1590-L1591
 It seems to me maybe the purpose of `sumHeights` is really more to get the average height distance from the ellipsoid across segments, and then using that value to adjust the bounding sphere radius accordingly.
 
Ensuring we're getting the absolute value of minimum and maximum heights when calculating sumHeights seems to get us better behavior on terrain datasets with large negative min elevation values such as the moon.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @malaretv!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/groundpolyline-boundingspheres/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks again @malaretv. Would you mind:

1. Adding a short inline comment to explain why `Math.abs` value is being used? It's a bit unintuitive without the explanation
2. Add a unit tests to ensure this is working with terrain values causing the issue
3. Update `CHANGES.md` with a summary of the fix?

**Comment by malaretv** [comment]
will do. thanks @ggetz for taking a look!

**Comment by ggetz** [comment]
Hi @malaretv, what's the status on this PR?

**Comment by malaretv** [comment]
Thanks for pinging me on this @ggetz

Today had free time to wrap up the remaining items. Let me know if anything else remains.

**Comment by ggetz** [comment]
All looks good, thanks @malaretv!

**Pull request merged**
