### PR TITLE
Minor argument type fixes in JSDoc

### PR DESCRIPTION
**Pull request by javagl**
Fixes https://github.com/CesiumGS/cesium/issues/10801 (which I had kept open in a tab for ~2 months now...)

I assume that there are (potentially many) similar issues like that, with different levels of severity

- types that are plainly wrong
- types that are not found
- types that are capitalized wrong (e.g. `{Number}` instead of `{number}` - whatever is "right" there, it's certainly not _consistent_ right now - see https://jsdoc.app/tags-type.html )

In order to find them, one should use a dedicated tool (maybe one of the tools that have once been used in the first experiments for generating TypeScript bindings?). 

But these are the ones that I noticed in the issue.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @javagl! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/javagl/cesium/blob/argument-type-fixes-2022-11-12/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/argument-type-fixes-2022-11-12/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by javagl** [comment]
The `CONTRIBUTORS.md` update can be skipped for such a fix. 

Regarding the `CHANGES.md`... I'm not sure: Strictly speaking, this **is** a breaking change, namely for the generated TypeScript bindings (and that's where I noticed that issue in the first place...)

**Comment by ggetz** [comment]
Thanks for the fix, @javagl!

> In order to find them, one should use a dedicated tool (maybe one of the tools that have once been used in the first experiments for generating TypeScript bindings?).

The tool we current use does issue some warnings, but unfortunately [due to an issue with the tool, the output is very noisy](https://github.com/CesiumGS/cesium/issues/10455). Happy to hear if you have alternative suggestions!

> Regarding the CHANGES.md... I'm not sure: Strictly speaking, this is a breaking change, namely for the generated TypeScript bindings (and that's where I noticed that issue in the first place...)

Yes, there should be an item for this in `CHANGES.md` for this exact reason. However, we have put previous items like this under "Fixes" rather than "Breaking Changes".

**Comment by javagl** [comment]
Similar to https://github.com/CesiumGS/cesium/pull/10912#issuecomment-1321704234 , I wasn't sure about the form for the `CHANGES.md` update. I guess the approach is to just add a section with the new version (and a somewhat "arbitrary" date - this has to be checked during the release anyhow). I have updated `CHANGES.md` accordingly. The responsibility for resolving merge conflicts here will likely be determined by the merge order, but consider this PR as "low priority" compared to others.

**Comment by ggetz** [comment]
Thanks @javagl!

**Pull request merged**
