### PR TITLE
Removes Specs, gulpfile.cjs and web.config file from makeZipFile

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
Fixes https://github.com/CesiumGS/cesium/issues/10270

| | `main` | `remove-specs-from-zip` |
| - | :-: | :-: |
| Compressed Size (MB) | 66.2 | 52.3 |
| Uncompressed Size (MB) | 192.3 | 159 |

I noticed that we don't really do much with the `gulpfile.cjs` and the `web.config` files, so this PR removes them too. Not sure if that's the right thing to do, but none of the commands through gulp from inside the zip file anyway.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/remove-specs-from-zip/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by sanjeetsuhag** [comment]
> However, they technically could before this PR.

There seems to be something wrong with the default configuration inside the ZIP file. From `main`, I ran `npm run makeZipFile`. From inside the contents of the zip file, I tried running `npm install`, then `npm run build` and I got the following error:

Screen Shot 2022-04-11 at 10 15 06 AM

**Comment by sanjeetsuhag** [comment]
@ggetz I've restored the `web.config` file. Is there anything else that needs addressing?

**Comment by ggetz** [comment]
Nope, thanks @sanjeetsuhag!

**Pull request merged**
