### PR TITLE
Generate tighter near far bounds in View.js

### PR DESCRIPTION
**Pull request by IanLilleyT**
Fixes https://github.com/CesiumGS/cesium/issues/8346
Fixes https://github.com/CesiumGS/cesium/issues/8439

`View.js` is responsible for deciding which commands get rendered into which frustums, and every frame it calculates the global near / far values of all commands in order to figure out how many frustums are needed. Problem is, the heuristics it was using to decide if the frustums needed to be adjusted was not triggered when switching to orthographic camera, resulting in the orthographic transform using near / far bounds meant for logarithmic depth (since perspective camera uses logdepth and we just switched away from it). This resulted in an extremely tiny value in the orthographic matrix which ended up becoming 0 by the time it was converted to float32 for the shader. So all triangles were considered to have the same Z value post-transformation, overwriting each other.

This PR recalculates the frustums whenever the near / far changes, resulting in a much more sane transformation matrix. It also has the added benefit of making our depth values more accurate for all kinds of projections, though I haven't noticed any visual quality difference. 

This can be seen from displaying the camera's frustum before and after using tighter near / far (using perspective + log depth):

Before:

Screen Shot 2020-05-13 at 6 22 57 PM

After:

Screen Shot 2020-05-13 at 6 18 26 PM

One thing to watch out for is now the near / far change constantly when you move the camera. I don't think this is a problem though.

In working on this a bug, another bug popped up with point cloud eye dome lighting. Somehow, the farther near value created some floating point imprecision issues when reading and writing the log depth value. Then @lilleyse realized we could just passthrough the depth value without unpacking and repacking it, solving the problem. This hit a snag with derived commands because it expects to see czm_writeLogDepth, otherwise it appends log depth code to the shader. Had to add a `LOG_DEPTH_WRITE` define to inform the system that log depth was truly being written already.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/orthoCameraFixBounds/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by IanLilleyT** [comment]
Turns out this PR fixed the polyline issues in https://github.com/CesiumGS/cesium/issues/5110 (which are technically not ground polylines, which is why they weren't affected by the fix here: https://github.com/CesiumGS/cesium/pull/8854)

**Comment by hpinkos** [comment]
bump @lilleyse

**Comment by IanLilleyT** [comment]
I think it makes sense to move this to the July release, but we should merge it as soon as possible after the June release is out.

**Comment by hpinkos** [comment]
@IanLilleyT @lilleyse bump

**Comment by lilleyse** [comment]
I like the approach and I like how much the simpler the code got. Performance is comparable with master - this [sandcastle](https://sandcastle.cesium.com/#c=nVXvb9s2EP1XCH+xjKa0qB+U1NrBBifDCnRb0BgbBvgLLZ1jIjRpkJSTtM3/vpNsOU7sYk38xeTde3dPj0dpIywpwcl69Y+xqpqCtUJqMiaTNkhLC8LDYS4YfJzpDdJAKbl2RlZX1mxkBRZZGu465mWX3vE6VMvfVthIuHtJ+7uNBf2tqInRHrlg+2fk20wT/Pnn5ciHE/pn+nHXpa1GXQkaaAXz+uZ6ae5+s2IF7grsNZRGVyjA2xqOCQ6fHvT1WpQwQYYVjRxrlEIEaDFXMMGNdNLoC/BQelxgsYVQDvYPWbZMDD8rvY0egPDPPYG2e0xvF9SB/9V7K+e1h6DvxVzqCu7RlH7YH3wkwyFaCBVUxBuyrj1ZmLJ2BNX4JeyK72sZXSpZ3jZCa91qDgY7c3eIlt2e02OrsML9CrSnoqouN7j4LJ3Hp8BjuoWHytxpVNIVIwF05eQCNxQhZDwek37ZJ9+/kzYwMRW0QZ514OZ3yq+9UwcY55up6Z9wtHGqGaHg22ym+0+shvEOKc26AuelFq3YD4ezNxHW40roOOiTdzsldG2cbLD0HmON5SdSDz9OfW1Sg7MfyzFWoqUn5PwOopL65kr6cvkFB+1Q1HKbO27bgI+izcz+nwzQ1dQK7RbGrlDHTsMfAqfuPqGfLi7/nH6a/nuaj7ftIIp3yhkFVJmbABGD52dn8Z4IfaPg9JWgpVnhBENziF86aDA4Xf1J5JJ6cwE3eF9dsO9A7/CkB2/kOlP75VvJIN7eWBv71Pjx9KvsaNj1zw72+4hHaZpzmseMZ1HG8viMvE+SOCvShIZJwhmPsuSMxFkSRSGnWRLHEcuLFIdHv25eU5pxniY5T9IiycMiw04hDQuWFSxK8zRjqCTGXpxGOUuLIi4yzooo3vf6yaHsPGreca0xC/UwNa+0JeYszGkaspA3z5w2tsRFyvOQ5ig24RFnjS15UrCYRkXBM56zKHuLL3kRMp6EOU+jPI6L1pcozPKCpSxjMbZLs50vUZgWiEtSnuTR63zZgavadqpYSNnOrd5Zb+T8g4Lzbkp/kas1zh6prQooHXpYrRV+/N1wXpe34GnpXDfSo+EhdVTJDZHVeNZ78dWe9UiphHOYWdRKXcuvMOudj4aIP6Iq07r01wasEg8NbMnOP2+DlNLRELenmd4YNRf2ReX/AA) shows `createPotentiallyVisibleSet` using about `0.2%` less in the chrome profiler on this branch vs. master with built versions of sandcastle.

The only thing that should be addressed is that `commandExtents` may hold onto old draw command references like `ManagedArray` did before https://github.com/CesiumGS/cesium/pull/8889. It'll still be important to have a `CommandExtent` pool but extents past the end of the current length should set have their command set to undefined.

**Comment by lilleyse** [comment]
This also appears to fix https://github.com/CesiumGS/cesium/issues/8439. I added "Fixes #8439" to the PR description.

**Comment by IanLilleyT** [comment]
@lilleyse updated

**Comment by lilleyse** [comment]
The latest changes look good. Thanks @IanLilleyT

**Pull request merged**
