### PR TITLE
More specific types for metadata picking

### PR DESCRIPTION
**Pull request by javagl**
This is a draft PR to show how more specific type information could be provided for metadata picking.

The only relevant commit is https://github.com/CesiumGS/cesium/commit/4599ab0b2269d6a10d06af4cd1ebed899fb83262 , which adds more specific type information to the `Scene.pickMetadata` and related functions. Previously, these had been declared to return `{any}`, which is undesirable. Following the [discussion in a PR comment](https://github.com/CesiumGS/cesium/pull/12237#discussion_r1819529987), I tried to be more specific here.

I did some experiments for "nicely" encoding this metadata type information, in https://github.com/CesiumGS/cesium/issues/12269, but the limitations of the JSDoc-based type extraction make this approach infeasible. 

So the main change is that there now is a 
`@typedef {(number|bigint|string|boolean|Cartesian2|Cartesian3|Cartesian4|Matrix2|Matrix3|Matrix4|number[]|bigint[]|string[]|boolean[]|Cartesian2[]|Cartesian3[]|Cartesian4[]|Matrix2[]|Matrix3[]|Matrix4[])} MetadataValue`
in `MetadataType.js`. This is used as the return type for the metadata picking functions.

Right now, the metadata picking does not actually allow picking things like a `Matrix4[]`. But this limitation is an implementation detail. Ideally, it _should_ be possible to pick such values.

---

In the `Cesium.d.ts`, this arrives as the following:
```
/**
 * An instance of a metadata value.<br>
 * <br>
 * This can be one of the following types:
 * <ul>
 *   <li><code>number</code> for type <code>SCALAR</code> and numeric component types except for <code>INT64</code> or <code>UINT64</code></li>
 *   <li><code>bigint</code> for type <code>SCALAR</code> and component type <code>INT64</code> or <code>UINT64</code></li>
 *   <li><code>string</code> for type <code>STRING</code> or <code>ENUM</code></li>
 *   <li><code>boolean</code> for type <code>BOOLEAN</code></li>
 *   <li><code>Cartesian2</code> for type <code>VEC2</code></li>
 *   <li><code>Cartesian3</code> for type <code>VEC3</code></li>
 *   <li><code>Cartesian4</code> for type <code>VEC4</code></li>
 *   <li><code>Matrix2</code> for type <code>MAT2</code></li>
 *   <li><code>Matrix3</code> for type <code>MAT3</code></li>
 *   <li><code>Matrix4</code> for type <code>MAT4</code></li>
 *   <li>Arrays of these types when the metadata value is an array</li>
 * </ul>
 */
export type MetadataValue = number | bigint | string | boolean | Cartesian2 | Cartesian3 | Cartesian4 | Matrix2 | Matrix3 | Matrix4 | number[] | bigint[] | string[] | boolean[] | Cartesian2[] | Cartesian3[] | Cartesian4[] | Matrix2[] | Matrix3[] | Matrix4[];
```

Consequently, the `Scene.pickMetada` function there is now
```
pickMetadata(windowPosition: Cartesian2, schemaId: string | undefined, className: string, propertyName: string): MetadataValue | undefined;
```

---

In the documentation, this is hotlinked accordingly:

Cesium Metadata Picking Type 01

And leads to the documentation of the global type:

Cesium Metadata Picking Type 02

### CODE REVIEW

**Comment by jjspace** [comment]
> This was supposed to be opened against https://github.com/CesiumGS/cesium/pull/12237 and show only the last commit, but for some reason, GitHub messes up the comparison and seems to pick a completely random base when selecting the "right" base from the dropdown. Hope that this works when actually merging it into my local branch 🤞

Not reviewing this yet as i'm out of the loop but you have a merge from `origin/main` into this branch that's not present on `metadata-picking-offset-scale` which I think is what's making the comparison show a lot more changes than you intended

**Comment by javagl** [comment]
@jjspace That would explain it, but a
`git checkout metadata-picking-offset-scale`
`git merge origin/main`
tells me 
"Already up to date"
I would expect that to fetch the same merge from `origin/main` that is present _here_ if it wasn't already there - and it it doesn't, I don't know from the tip of my head whether I should try "force" this.

Given that all the changes that are relevant for _this_ (draft) are in https://github.com/CesiumGS/cesium/pull/12315/commits/4599ab0b2269d6a10d06af4cd1ebed899fb83262 , I hope that it doesn't cause a burden for reviewers.

**Comment by jjspace** [comment]
@javagl are you missing a `git push` on the other branch? :thinking: Otherwise I don't know and sorry for distracting

**Comment by javagl** [comment]
This PR is now obsolete, and https://github.com/CesiumGS/cesium/pull/12237#issuecomment-2486117705 has been updated. A bit embarrassing, but not a big deal, I guess.

**Pull request closed without merging**
