### PR TITLE
Fix type of SingleTileImageryProvider.fromUrl return type

### PR DESCRIPTION
**Pull request by matthias-ccri**
Fixed the type of `SingleTileImageryProvider.fromUrl`.

The current type has a return type of `void` but the return type should be `Promise<SingleTileImageryProvider>`

Selection_034
(from `Cesium.d.ts`)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @matthias-ccri! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/matthias-ccri/cesium/blob/types-singleimageryprovider-fromurl/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/types-singleimageryprovider-fromurl/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Hi @matthias-ccri, we'll need a signed CLA in order to review this PR. I don't see one from you in our records.

Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!

**Comment by matthias-ccri** [comment]
Thanks, yeah I'm going through the process of getting the CLA signed by the proper people.

**Comment by matthias-ccri** [comment]
I was just told that the CLA was submitted!

**Comment by ggetz** [comment]
Awesome, I can confirm the submitted CLA @matthias-ccri!

Everything looks great! I would ask that you add a note to `CHANGES.md` with a summary of the fix. Typically we don't include documentation updates, but we do generate a TypeScript definitions file from the documented types, which will be updated with this change.

**Comment by matthias-ccri** [comment]
Thanks @ggetz I've updated the CHANGES.md

**Comment by ggetz** [comment]
Thanks @matthias-ccri!

**Pull request merged**
