### PR TITLE
Point cloud styling fixes

### PR DESCRIPTION
**Pull request by lilleyse**
`${feature.propertyName}` and `${feature['propertyName']}` syntax now works for point clouds using the GLSL styling backend. It was an oversight in `getShaderExpression` and required just a few small changes.

The bigger change here is supporting feature properties with non-alphanumeric characters, like `${feature['temperature value 😀']}`. The shader was using the property name as-is which doesn't compile if the name has spaces or unicode characters. Now the shader attribute is named with a unique id.

[Local sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=dVXhcto4EH4VDdcr5kqEMaG5EMhcBxJiLsAFCGkS8kPIAgS25FoyBFpm7jHuX1+xj3BrGyjkDs9gS7vffivtfhJzEqA5ZwsWoAoSbIGqTPHQw/3YZqRpPK1KoQkXLEhnLgYiwWPqSjrDNAwCJnSPe+yQoRG6nIga0cywTotnRcvC+eLp2bkVUQAJJNbcZYrpw7jkU6j1EqfxdSAQPGHglrYQW4oOUzIMKMOjQHqfFABtxzgvnOZ/z6JNBEKEwvJVT86YKKE0WzYmwzrlbd6w71d2vsVtZYtOkVbtj/bM/9yvNs4xgL449RmAbKvp3VutWst7quan7Yc+v+11vOZ0rNv1vttamoV2re8+1a6KT/Xr6eNDk99WG/4TkLW7C06t1pzW+yt76g9t73pFo2SeM7VdU8Vzq2/Spf3xYTVbtWpXp58hhjxcm/ZUvrZ64wL8Vs2pnR/dYfpl+Hg//6TuiGmObk4adwty01f+Y8NqWD2/Ojy5/rOxeL06C17NdLLzdWYg1nudUpQJhv2Ae1zzOVOYOI6xKf4ebCWl15NbR3a/KTeMOFyM/+KaTjpEjJlhYjOLTvLRuwjjzM+uKr0EAmjq8wvYRqGgmkuBIGc38hiCeCyboDJJr+Ix9iUXustXkY42aR02IqGr+8QNmfEGBXkh7cUuXmE/VJOtXKIkpfidTQwxppR8YlNcoHW06N3KBqmWRPFwkAIZrZM97bk7zIk9UTyVrgxKaJCKB0b6l9HIhCedAcSm/Aex1QiG6gEUEs7LMZoM+g29+zpiRIcBe05r5vksiCdoHlUB/fj+z9/pl/WRJN2JXKBuOFQsLrrapVHgiLLsuDF31qhSqaA8+vYNUkbTS2QVTfT+/WZaRgXTPJKoKZ3j3M9p7sAa0a/IilMckOwEARpL2PalEDAgEGgHMjLb47yRJY7Rx6+MfcpYHOttm3fabPtxbXYKhbYYkZODxbyAT3mrKJeJsZ5coA8f+GYdOxLAJqBn/vJThBvqAylq9qo3wsN7ggQYc6FNpTeFSDaYeaPRLhEOJUqDH7rQk9IdkqDJRGjs543gqWyqHNsut9fgH9zzZaCjK9TAOBdpyoVrWeWGIZ1BRalSSakQKuf2Q8sOnyPuVECch38DgxSiLlEKPKPQdaPjOEhdlnOA/0+oK+Oroz1ngUuWEWySv7xNjBjjcg6m/x+pk12+Yf4X)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Awesome!  Thanks for the quick fix @lilleyse!

**Comment by sanjeetsuhag** [comment]
@lilleyse It would be good to have tests for handling properties with spaces and Unicode characters

**Comment by lilleyse** [comment]
Added a test and confirmed the test fails in master. @sanjeetsuhag do you have other feedback?

**Comment by mramato** [comment]
Would love to see this go into the next release. @sanjeetsuhag is there anything else you're looking for here?

**Comment by sanjeetsuhag** [comment]
Code, sandcastle and test look good. Thanks @lilleyse!

**Pull request merged**
