### PR TITLE
Fix DebugCameraPrimitive render error

### PR DESCRIPTION
**Pull request by jiangheng90**
fix render error in #11159

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jiangheng90!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by jiangheng90** [comment]
> Hi @jiangheng90. I'm a bit confused why this change is needed. Isn't `update` called as part of the getter for `projectMatrix`?

@ggetz yes it does called in getter for `projectMatrix` but it will not automaticly called in `DebugCameraPrimitive`

https://sandcastle.cesium.com/#c=fVRbb5swGP0rKE9Eoo7x3WtabUu3p0qd1mlPeXHBSawRQAZSdVX/ez9DSFhXlQf47uf42CaryqaNDs4+Wh9dRaV9jFa2cd0e/e5j8XqW9f6qKlvjSuvXs/nlulyXWd/5HDWZLW30As3DlEmyrhrXuqr8d/DK+BYsU9KYKMlFiriimKRUMZVwwYTAGlHwMMdcJ0QLyrSAiGCpUJoF+GF+7rzNPgS4wAgzphXBXHDCsVCEJhBUihLJIUEJD8AhBsBCp5wLQggV4gzT1R/OJ1RSEZhJLYWmmh6HYVgcU1pzTkUSIBkjOGVUY4CVk/nebXftRxBaK4m5DPQkZZLBNNBGCXgJzniqhCbJBYimpNREEMAmiqb2IiVnlEeXtztAoZIrhSjQ4xQrDMJcRmONaWoQ9KcBTaOrFCQP2mMFamCqyGlUaU04LBilp9Cmj6QYnskByMzeevN2aSEW98emZ9f7aHJWRvOcnG70yT6n+w3q6nNgVLT/nsMb3zVttz/yGQnd+XZXbb2pdy77PlTEz+sygqfXLBnsiTbHSJDhaG5662W4Gf3SUO3dHpZxsA0yeR6PLScdbuxDtx3E+DGWjrjRUbnk5FZF5T+dJAweuru9uf2y+naseZkHYyAwXEQ0rrp4+lV9rboyd+X2vt5Zb+MJjzeZUfwkImEz5/PLWTJbNu1TYa9HNp/dvq48XAxfxAgtWruvCwPndfHQZX9si7KmCURC6XIxbV3m7hC5/Oqdn0qUFaZpILPpiuLe/bXr2fVyAfX/tRaVCXzvDtYX5imU7dLr2yGIEFouwH2/s62q4sH4N5NfAQ

this case will shows cesium crash of the ```update``` not called by `DebugCameraPrimitive`

**Comment by jiangheng90** [comment]
@ggetz I think change like this will be proper than call ```update``` in ```OrthographicFrustum ```

**Comment by ggetz** [comment]
Thanks @jiangheng90, this revised change makes sense.

**Pull request merged**
