### PR TITLE
[FIX] Added undefined as union type fo contrainedAxis

### PR DESCRIPTION
**Pull request by harshlakhara**
# Description

Added undefined as union type for contrainedAxis so in typescript it won't show errow while assinging undefined to it.

## Issue number and link

#11475

## Testing plan

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have update the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
Thanks for the PR @harshlakhara! 

I can confirm we have a signed CLA on file for you.

This change is looking good to me! 

Since this fixes a bug in the TS definitions, can you please add an item to `CHANGES.md` with a short summary?

OK to skip a unit test as this doesn't change the source code.

**Comment by harshlakhara** [comment]
Yes, I will do that.

**Comment by harshlakhara** [comment]
@ggetz I have update the commit. Please check.

**Comment by ggetz** [comment]
Thank you @harshlakhara! I'll merge as soon as CI passes.

**Pull request merged**
