### PR TITLE
Use var version instead of const

### PR DESCRIPTION
**Pull request by hpinkos**
This error slipped through from https://github.com/CesiumGS/cesium/pull/9294

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/accidental-const/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by kring** [comment]
Did this break IE11 support completely? If so, we should probably do a patch release.

**Comment by kring** [comment]
To answer my own question: No, IE11 supports const. Makes me wonder why we're avoiding it. :)

**Comment by hpinkos** [comment]
I honestly don't think we have a very good reason anymore, we just need a moment to go through and update it all at once

**Comment by mramato** [comment]
I actually didn't realize IE11 supported it.  At one point the language level in Cesium was ES5.  When we switched to modules, it got bumped to ES6 but we are using a `restrict-to-es5` eslint plugin (but maybe const/var are ES5 and it was just not widely supported when we started Cesium).

ESLint can get us like 90% of the way their with auto-fixing, it's actually not that hard of a change to make.

**Pull request merged**
