### PR TITLE
Fix `Quaternion.computeAxis`

### PR DESCRIPTION
**Pull request by javagl**
Addresses https://github.com/CesiumGS/cesium/issues/11665 : 

Use the x-axis as the result for the unit quaternion and for the quaternion that describes as rotation about 360 degrees.

### CODE REVIEW

**Comment by javagl** [comment]
(Not sure which parts of the build failures are related to this PR itself, but ... I assume ... none of them...)

**Comment by ggetz** [comment]
> (Not sure which parts of the build failures are related to this PR itself, but ... I assume ... none of them...)

Huh. @javagl Would you mind merging in `main` just to confirm there's no discrepancies?

**Comment by javagl** [comment]
Not sure what happened here - I'm pretty sure that I branched off from `main`, but now merging in main caused something to wreak havoc up to a point where the pre-commit hooks couldn't be run.  Some juggling in the style of xkcd 1597 may have fixed this, otherwise, this will have to be closed and fixed at a later point in time.

**Comment by ggetz** [comment]
@javagl The CI failure is fixed in https://github.com/CesiumGS/cesium/pull/11689#event-11227052354. I'm going to update the branch for you.

**Comment by ggetz** [comment]
Thanks @javagl!

**Pull request merged**
