### PR TITLE
Replace glTF model implementation

### LINKED ISSUE #2387: Change the material of a primitive in a ModelMesh
Is there a way of changing the material linked to a primitive in a ModelMesh created from a glTF model?

The goal is to highlight the picked node by changing the material's parameters but  `ModelMaterial.selValue` is applied over every primitive linked to that material. I think that the best solution is to temporary link the primitive to a special 'highlight' material but it does not have any effect over the rendered model. Maybe there is a better solution to solve the problem so I am open to suggestions!

Thanks!

### LINKED ISSUE #6299: Support gltf 2.0 POINTS
A gltf 2.0 model that contains points doesn't get rendered. The fix is to add `gl_PointSize` to the vertex shader in `processPbrMetallicRoughness`.
```
vertexShader += 'void main(void) \n{\n';
vertexShader += vertexShaderMain;
vertexShader += '    gl_PointSize = 10.0;\n'; // ADDED
vertexShader += '}\n';
```
Since there is a bit more work to kick this fix into shape (like test models, controllable point size, etc), I'm just going to leave this as an issue for now. 3D Tiles point clouds is where the main focus is.

Brought up on the forum: https://groups.google.com/forum/#!topic/cesium-dev/P2DVkLAbb3U

### LINKED ISSUE #7062: Expose an interface to ModelInstanceCollection
The best way to have hundreds of instances that all share the same model is to use the `ModelInstanceCollection` class. It's currently used internally when loading 3D Tiles but there's no public interface to it. 

I think it would be a good idea to allow users to create this directly. 

[Forum discussion](https://groups.google.com/d/msg/cesium-dev/IfXK7gh6pwI/05O5mWCZCQAJ).

### LINKED ISSUE #9303: Model mutates the gltf object parameter
Reported here: https://community.cesium.com/t/giving-model-a-frozen-gltf-object-crashes-cesium/11884

[Sandcastle example](https://sandcastle.cesium.com/#c=rVlpc9o6F/4rTD7lzhCwzZKQ23auMISQEJJCwlY6GdkWthNvtWQI6fS/v1q8UqdN73uZ4qCz6TmLpGNV9z1MKlsb7VBY+Vjx0K6iImxHbm3GacfrI52PVd8j0PZQuD766++1t/bq9YruBzYyKpvQdysWIQE+r9dDuKuZNrEiLcIo1KkW8khN9936tRX6no8HoR8FddO5vziZQjdw0MmNbyAH112ICQrrck2qd/0XIdF3NWQYyGCUmumQzdrTOWL2m+L9TpEcQZ1CxH6I10fnRcqjIqc0LdpsUMi8YqT8+FHprI+qXGZP0O1mgxFhMlJKm5LQNlBGo+4Evkcdu98HnNySlUbMiTyu3GjzMYkF1kdTFYzAZH209n5Uixgb78HYkN6NUVbeBNkuglSafOzCFzb6svakWquae669r0LA9mKBE8HL/UlkMk9nfbVR5mfr//BTOTv7bz2Vq/G3xEdGjx+/8C510LNdSGxalty/mIhj4NxfE9GFA4kfChO67zjQgAor4n8k5XRz2my0242mbLTaHQPBpoI6sH2mncpSU9cbZx1FajXjsAQhciOH2IFDlx5wAgsymySMUMz2N7aDspUQ2GLOOdIGo9jGFoWY4hUMut5qSpauQ17GyZKESxLJF1GBKkzQhZtL6Ah5JrEY51R5s5oJDE0xbjQ77cbP8/Mi+YO5WqftksliBMXZlFxihenMWW4+mbYwQbt5dlAlMAzhPsHGeVEYZ8KABJ7DgCZQ52VT93WCyAkmIYLu3xrEqN2sAgC6AAwB2AEVgD4bXACwBN0dGADwwIhXAPhA3YFrAJ5BD4AxAE3Q24FbACSqASagOwT9HZiCbp8pz0B3CS52YA66D4B9tjv6GJ2xn3X2uDsYc37vgN/7jXypPfWAr77LXsZX37b3C3zbMv1eGZ5yf7dvzqe+i3/3pr9inH6G4F+PTYEf/PlYFXjSz5+OY3u9s385VkW8cvb/bJyPx2E8fz8u7OB0+0ahDZ1sqffpwtXJyQQZKcmDbry2OVWsd6Rbnv0tihnpMDnDttCJUGbVsDcb2hWlZy3bNKT4m5402LI92mdhrqa0xM6FA6RHDgxTVaVafDJ14VHqFMJWbu4B8l1Ewv0Jo0uSUuLXDeWkp4zt2sTeCgN0RnGYEHryahHJmR3fTm7AKN7z8ic9N3N3Ox3eD2/Hh/xce2B7hq0Lgwd9WyE1gp9Pi2D7ohFocse/5tz3KOdt78exHmfqlu0YIRLH/9dk2tDOtwrSwffdtLS9SNPxpTwdieBhPvIOPcrloN92MZ3+dw5JSc/zK28KHmVAl48Pd4/3IfTwxg/dwtKi/YgZQjfLREx4zE7wYlVxX+CjRw2xrItm6jHwsU14W5LMvgmh6dKWb2pBI3f+SxfTrMkh6OWQPZsW4GGddmbxsYw2kDZWU0HJuLnlW5BIlk9SZ1/ySSrWIuYgCo0ExxkPk66h0Wo3lJJegbpB6oFD376S7kC/vHKWivMK551oOLCClWLthoMV1pQL6XYXKMvFVQvOW97wcuUsX29Mw+lEWuOKLOe7U9WbRXC+2uquZBru7GmsduWFMglW7krWlYdyfmO8W83Hsja42FP7suY6LrOXzDm8nG10xQooPVotxq8Mg6Y4z8OBbMF50zfcTrBSn01E6av5zetw0KL2ZUtTQSf9PXDaq6mlLJSE90yxMPyfzaXSwVpjaN5Nu0xfuu6BaKSC3cjemTdqEw/p+PoeX8d4nyl+11iMnWEv8cEsyFLdl5Gd2dcbXWfZmOHlYniqumks2HwHscniwG3POq/6YPZkzF8s/QlfrwaOu/Jmr6tpq4kWvnn9JJna/KJ5PZhsDdVKcoAZpps9x8S+DEsg/KGY3PFWG3T2I89qIRuEFEPqD6fReX6KxyDRufKWNvg2HKSYo+V0Z+ZwWSxOK+VlM/GurJUk9JgvsU3qo3Sd7TrJmikp1cZ/UaqWcTnZw/mVbAweTBGWrrVodLe64khM502ZpEx6LO0XezSnpbfvivK6XG00t7OnocfFcpUto3fD0han4mW8XFDbC7NQ9lRPEstC3q4GMzxzHceQqO7lVYDYfPMWDS+1P+2S5eKzKP/Lqy2k2IyBs9Wec7K89KkcxXd9udrC+edgeJmW6k5r3MRlVjKXSlPJl/BnfznrUNlxwO2zknkCAVtm2XKhS4niSPy+pz7ortMcqr65nOWWv2vghZzFNy7jne52vtHS5rS8rj7osOXcUc2PH4tb57NdeONNm59sn8v3Q6Wb/ffiZs/K6M2NnzHzx0B8vkB6mCCS311zXdZhzbbbaXfE7pzYu+RNejByYYxc6BFbj0/g215/NBv250m/l5k6bWcHc4K+xELSHx2qt1tF9ffBGI5n/cm0fz8B4yntrfolsFK7+ciV2Mxas7eh0bP6ifZb1Mgv4d1Nbq/6armxLEyFvraQGHZbk0rlGt3S7B00FnFdZE2FsEJgvsKQBzUnabuVjtKhQsrZWVOc0mIb82zWu2Q60WOujnJFJaQfS+qnpKhi4cMUHyY9FisLd1kSYvFCQAvxTQRyscxHNn1PoP/4Va64UvVD27S9ysfkAliFtIHCNvQaNXbD20NmiBA+PpEVpVppnFUrsiSxq2ChzX0XCDMTaU+IawhiMvZDYj0E9/6F/YKMC7Zyj8WsmR0rOLiHvkTQsD3zzia6NfEd51iqVmijWpHSa+gHquqyXrBCLBtXHBqFCvSMSojCiErcaix+1AeEXtExu3P7K+c1x12ckd9HH9MqqPBr5nP+rLKhS0PsRu4dhe9M7VfEbn4EI/P+PD/gTKxDh4rKrHv+IeYWF+413mDWspetGjSMY67OxGIhnYYphDWMCCut4++03yS2x6+OzuOkVdlfGoCYSGP442cDrr9FXag/72BoHNPc0QAeVY8+YLJ30CeGk33+sd2AZqkShc5xrVYnyKWnOS2Duhbpz4jUdIyZZSb6oZ5X/WDY24ptfCz5/4KK7kCMKWcTOTxs66NPH+pU/idVx+e5vqW9uwP3TMySP40EsVarfajTYbkm8X1HY8Vd4P8P)

If cesium needs to alter the gltf param, it should make a copy first.

### LINKED ISSUE #10346: `ModelExperimental` -> `Model` Roadmap
One of the major items on the 3D Tiles Next Roadmap (#9520) is bringing `ModelExperimental` up to feature parity with `Model`, so that it can entirely replace it. In other words, we aim to remove the current `Model` class and any related files, and rename `ModelExperimental` to `Model` without any hiccups.

This issue goes into more detail than the overall roadmap and will be updated as necessary.

**Remaining `ModelExperimental` Features**
- [x] Basic 2D / CV rendering: #9934
- [x] Clamp to ground #10448 
- [x] Support `AGI_articulations` #10479 
- [x] Support silhouettes #10457 
- [x] Support `distanceDisplayCondition` #10481 
- [x] Add `options.id` for picking #10491 
- [x] Add `options.credit` #10489 
- [x] Add `options.asynchronous` #10490 
- [x] Rendering statistics #9886
- [x] Support outline extension for OSM buildings: #10338
- [x] Integration with entities and CZML systems: #10285
- [ ] Use `GltfLoader` in `ClassificationModel`

**Important bugfixes**
- [ ] Normal mapping rendering bug: #10296
- [x] Custom shaders and instancing bug: #10113
- [ ] 3D Tiles BIM model crashes: [comment](https://github.com/CesiumGS/cesium/issues/10379#issuecomment-1127913756) in #10379 
- [x] OSM buildings render differently #10338 

**Lower-priority bugfixes**
- [ ] Quantized animation bug: #10321 
- [ ] Morph targets unit test failure:  #10354 
- [ ] Artifacts in 2D / CV when rendering over IDL: #10401 (fix in the distant future)
- [ ] Some tilesets not showing up with `projectTo2D` in 2D / CV #10402 (more related to bounding volumes in 2D than `ModelExperimental` itself)

**Testing**
- [x] Ensure all models from [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0) load correctly with `ModelExperimental`
- [ ] Ensure that tilesets load correctly with `ExperimentalFeatures.enableModelExperimental` set to true
- [x] Ensure that entities and CZML work with `ModelExperimental`
- [ ] Go through the "category - gltf" label for any important lingering issues
- [ ] Go through Sandcastles and make sure they work with ModelExperimental. See https://github.com/CesiumGS/cesium/issues/10379

**Files to remove**
- [ ] `Model`
- [ ] `ModelInstanceCollection`
- [ ] `ModelAnimationCache`
- [ ] `ModelAnimation`
- [ ] `ModelAnimationCollection`
- [ ] `ModelNode`
- [ ] `ModelMesh`
- [ ] `ModelUtility` -- make sure it no longer needs to be used by `ClassificationModel`
- [ ] `ModelOutlineLoader`
- [ ] all related specs

**Files to rename**
- [ ] `ModelExperimental` and related architecture
  - [x] `ModelExperimentalSceneGraph`
  - [ ] `ModelExperimentalNode`
  - [x] `ModelExperimentalPrimitive`
  - [x] `ModelExperimentalSkin`
  - [x] `ModelExperimentalAnimationChannel`
  - [ ] `ModelExperimentalAnimation`
  - [ ] `ModelExperimentalAnimationCollection`
  - [x] `ModelExperimental3DTileContent`
  - [x] `ModelExperimentalType`
  - [ ] `ModelExperimentalUtility`
- [ ] Shaders
  - [ ] `ModelExperimentalVS`
  - [ ] `ModelExperimentalFS`
- [ ] `loadAndZoomToModelExperimental`
- [ ] all related specs

### LINKED ISSUE #10379: `ModelExperimental` Sandcastle Testing
## ModelExperimental Sandcastles

As part of https://github.com/CesiumGS/cesium/issues/10346, I did a sweep through the old 3D Tiles and Model Sandcastles to see what happens when I set `enableModelExperimental = true` or use `ModelExperimental.fromGltf` instead of `Model.fromGltf`.

EDITED: 07/08/2022

### 3D Tiles Sandcastles

Working Sandcastles:

* 3D Tiles Adjust Height
* 3D Tiles Batch Table Hierarchy
* 3D Tiles Compare
* 3D Tiles Feature Picking
* 3D Tiles Feature Styling
* 3D Tiles Formats
* 3D Tiles Inspector
* 3D Tiles Interior
* 3D Tiles Photogrammetry
* 3D Tiles Point Cloud Classification
* 3D Tiles Point Cloud Shading
* 3D Tiles Point Cloud
* 3D Tiles Terrain Classification
* Clamp to 3D Tiles
* Sample Height from 3D Tiles
* Development/3D Tiles Split

Broken Sandcastles:

* 3D Tiles BIM
  * Shader compilation error. Expected, this is glTF 1.0
* ~3D Tiles Batch Table Hierarchy~ -- fixed in #10525 
  * "Color all doors" doesn't work, as `batchTable.isExactClass` is not a function
  * "Color all features derived from door" doesn't work, as `batchTable.isClass` is not a function
* 3D Tiles Clipping Planes
  * Fails due to the glTF 1.0 BIM model
* ~3D Tiles Compare~ fixed in #10506 
  * OSM Buildings have incorrect shading (see #10338)
* ~3D Tiles Feature Styling~ fixed in #10514 
  * OSM Buildings have incorrect shading
  * Color by Distance to Selected Location crashes shader -- fixed by #10514 
* ~3D Tiles Formats~ fixed in #10524 
  * Wireframe mode will need `enableDebugWireframe: true`
  * Composite tileset is repeated for some reason
* ~3D Tiles Inspector~ fixed in #10526 
  * Wireframe mode will need `enableDebugWireframe: true`
  * Statistics are not available (not yet implemented)
* ~3D Tiles Interior~ fixed in #10524 
  * Some parts of the model (most notably the floor!) are not loading
* 3D Tiles Photogrammetry Classification
  * The classification isn't showing up
* 3D Tiles Point Cloud Styling
  * Many of the styles are failing due to an `undefined` property value
* Polylines on 3D Tiles
  * Fails due to glTF 1.0 BIM model
* ~Development/3D Tiles Split~ fixed in #10524 
  * still using `.otherwise()`
  * Again, composite model renders multiple times

### Other 3D Tiles Sandcastles

These Sandcastles were found by searching "Cesium3DTileset" and "osmBuildings"
in the Sandcastle searchbar

Working Sandcastles:

* Classification Types
* Classification
* Cesium OSM Buildings
* Clouds
* FXAA
* Fog Post Process
* Scene Rendering Performance
* Terrain Clipping Planes
* development/3D Tiles Performance Testing
* development/Many Clipping Planes
* development/Pick From Ray
* development/Picking
* development/Shadows
* CZML 3D Tiles

Broken Sandcastles:

* Ambient Occlusion
  * Fails due to glTF 1.0 BIM model
* MSAA
  * Fails due to glTF 1.0 BIM model
* Montreal Point Cloud
  * Point cloud styling not showing up (GPU styling not implemented). See also #9944 
* ~Cesium OSM Buildings~ - fixed in #10506 
  * Incorrect lighting of OSM Buildings
  * No outlines
* ~Clouds~ fixed in #10506 
  * Incorrect Lighting of OSM Buildings

### Model Sandcastles

For these ones, I replaced `Model.fromGltf` with `ModelExperimental.fromGltf`

Working Sandcastles:

* Manually Controlled Animation
* development/Display Conditions
* development/Multiple Shadows

Broken Sandcastles:

* HeadingPitchRoll
  * Plane is frozen in place.
  * The camera doesn't zoom to the model correctly
* Image-Based Lighting
  * Doesn't seem to load the environment map. The sandcastle might need more
    adjustment to the new IBL API
  * The camera doesn't zoom in correctly
* LocalToFixedFrame
  * The camera zooming is incorrect
* development/3D Models Articulations
  * 404 on asset from `assets.agi.com`
* development/3D Models Instancing
  * ModelInstanceCollection... how will that work with ModelExperimental?
* development/3D Models Node Explorer
  * `nodesByName` is undefined
* development/3D Models
  * Again, the camera zooming doesn't work properly

### LINKED ISSUE #10416: Remove deprecated Model features in CesiumJS 1.97
In preparation for replacing `Model` with `ModelExperimental`, some features were deprecated. See the following PRs:

* glTF 1.0 support - #10414
* some getters - #10415 

These details should be removed in CesiumJS 1.97

### PR DESCRIPTION
**Pull request by ptrgags**
Fixes #10346
Fixes #10416
Fixes #10379
Fixes #9303
Fixes #7062
Fixes #6299
Fixes #2387

This PR replaces CesiumJS's glTF model implementation. the old `Model` was removed, and `ModelExperimental` was renamed to `Model` as a drop-in replacement. The new architecture is a lot more decoupled, and it made it easier to implement features such as 3D Tiles Next metadata and `CustomShader`

This PR merges the staging branch `replace-model` into `main`. It includes changes from the following PRs:

* https://github.com/CesiumGS/cesium/pull/10595
* https://github.com/CesiumGS/cesium/pull/10600
* https://github.com/CesiumGS/cesium/pull/10623
* https://github.com/CesiumGS/cesium/pull/10639
* https://github.com/CesiumGS/cesium/pull/10643
* https://github.com/CesiumGS/cesium/pull/10633
* https://github.com/CesiumGS/cesium/pull/10635
* https://github.com/CesiumGS/cesium/pull/10637
* https://github.com/CesiumGS/cesium/pull/10642
* https://github.com/CesiumGS/cesium/pull/10646
* https://github.com/CesiumGS/cesium/pull/10647

To Do:

- [x] Update CHANGES.md with an announcement
- [x] Test Sandcastles again
- [x] Sweep through and see if we need to remove `@experimental` anywhere
- [x] ~Add changes from https://github.com/CesiumGS/gltf-pipeline/pull/619 so we can have (limited) support for `glTF 1.0` and `KHR_techniques_webgl`~ Will be done separately

### CODE REVIEW

**Comment by lilleyse** [comment]
Does this implicitly close https://github.com/CesiumGS/cesium/issues/10416 as well?

**Comment by ptrgags** [comment]
@lilleyse yes, it closes that issue as well as #10379. Possibly others too

**Comment by j9liu** [comment]
This could also close:
- #9303
- #7062 (`ModelInstanceCollection` no longer exists)
- #6299
- #2387 (`ModelMesh` no longer exists)

**Comment by ptrgags** [comment]
@j9liu I updated the description so this PR closes those issues.

**Comment by j9liu** [comment]
@ptrgags @lilleyse merging now!

**Pull request merged**
