### PR TITLE
A Globe lambertDiffuseMultiplier property to enhance terrain lighting

### PR DESCRIPTION
**Pull request by xtassin**
Proposing a lambertDiffuseMultiplier property for the Globe object in order to enhance lambert lighting. The property defaults to the original 0.9 value. The multiplier is applied to the result of czm_getLambertDiffuse in GlobeFS.glsl - only when ENABLE_VERTEX_LIGHTING is defined.

### CODE REVIEW

**Comment by xtassin** [comment]
This screenshot shows the increased sharpness in shading particularly noticeable on mountains and hills. Left side is rendered with default 0.9 multiplier. Right side uses a 10.0 multiplier.
image

**Comment by onsummer** [comment]
good!

**Comment by xtassin** [comment]
Not sure why @cesium-concierge says CHANGES.md was not updated as I believe I made the proper amendments.

**Comment by lilleyse** [comment]
Thanks @xtassin! Initially I wasn't seeing any difference when changing the value and then realized the uniform wasn't hooked up 100%. I pushed a fix in https://github.com/CesiumGS/cesium/pull/9878/commits/fe3c59f1886a133cbf048fb2d4a0be082e71b8bd. I also added a test in https://github.com/CesiumGS/cesium/pull/9878/commits/b754a44d71162a500cda8a9072b81bdab5629ef3.

Here's the sandcastle I was testing with: [Local sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=lVFNb9swDP0rhE8JEMjpcY0bDOuO/RiQor34Iku0I5SWMkpy1hb972NkDMi6XnYiyPce9R41aYbJ4REZrsDjEa4xujyqxzJbtJUp/XXwSTuP3FYreGs9QEJmmfzgMDmLfPlHaBh1wqfAZB9myqLwARh/ZozpSWC+1fH5EhJnXP0FPiIn/HUXeNQUzwjvSynvy03rWz+J5WjQozieravSCliqGih0qNDrjvDGDfvk/CDc07KyYKe9NTomQqWtfQjDQPgtpxS85N0dXTL7U8xeLKCU7E1ygpk9mme0yzm/6+HDBOD8edJjJ2G+u77PEW8zJXcgV858sVbrTUkFKE/8p3qtvszicpBqVTUxvRBu5yUAX914CJwgMy2UqhOOB5KTx7rLYjYpE+NyM5Ob+lzaWDeBs1ef/DkY0jEK0meinXvFtto2tfD/kVLQVs59PyGTfjnR9hfbm3molGpqaT9XphCo0/xh828)

**Comment by xtassin** [comment]
Thank you for your help @lilleyse

**Pull request merged**
