### PR TITLE
Update `approximateHeights.json` for CWB

### PR DESCRIPTION
**Pull request by jjspace**
# Description

Update our approximate heights to account for the min/max heights from CWB to provide better support in the ocean. This is a somewhat temporary solution until we can finish the work for https://github.com/CesiumGS/cesium/issues/8480

I spent some time testing the performance implications of this and didn't see any significant negative impact running through all the demo Sandcastles we have or trying a few with many ground primitives.
See this one for an example:
- [Local Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=rVZtc9o4EP4rGr7UvhABuaTTCTR3hCadzqTXDKG93AwzN8JeY6W2xMgylLvhv99KRrKBJse9fACs1fPs+y6OpCg0WXJYgSJviYAVGUHBy5x+sbLgVWSPIyk04wLUqzb5cyoI0aAUCi4dfFKdaaJk/qtUWXzNdLrOQas1+ekIUBCS53VtBUHYnopN2J+KqVgyRVK2YpyPIdJMzDNA/7cKvMiqeAdzBVAEp73XvTbpvWmT097FeZuc/WhUGUU5U5wJNlEgovRofb3zM1TXxc/5a9R2XjnW6ZB7Hn0lynGmIrJJVg29e573HWYF+OXNfsTsUC2dPa+AGljoSUIqnR7BsriaBuwoWwZWkwpZHmXL4nxCRgqYBsLIXMlSxPeK51zzJTSTZOrgjx/QFhMR7Lbk+112YBtxDtI2kKMUlzuUvduKU7N2wL4ejuXQpPbssn5su8sU+DzVl6TrJUtQGr7dSpUz7dv6HpRzYyQzqYaLBTBljvTLzXhy8/j77afxx+Fkq2UTbh+Y1orPSm1C8w5FRoNXbfXtxzp0PNu1FhI08fT67vMNXXGdDrNFyoIuvQidzY393fiBqzYELSIQQBeuAgVlcRwcVM3X/R0kuDOw6jwmCwwV3QNVbGstVwWW9+xiO4MYUJkLL3INV+UWpbbV2KwIqnY/rVoxJB3HrIeIx7ZHPcNO1alteIM3lp2H7zEeZXrT+iiTurroZiIVCYxvHLV1+/gzqMiEn5yEVS085qnCPCHGOUSePAxbAjEySQrQj4h8Ij9sQ+vvX/+G1xyvbRjWz6reJrRIKvT3DhKTERvWiWP1D3HXUmuZI7KaWgd99EqNUez/5sb7u3FrDs8/G7l/M3Z7o/fiOm5ySCNT7e9dVKlpP8fBXNn0v8BFSFXAJiTcIRzuhf9rN+zsh2d3xH/YE7tx72wNAxozEcs8CPe2x3Op2PjnhtNRxoqCJzximksxWS/qAo8OrujkZjwefvjF78a6h1/YTM3eDu2AbHCf2deHihXhSlKMJtl6Iquui3GouLB291d9XKqtvNt4D2maj2FWzh9Subo1u67Aoj4ADmSMc6VVaf7mW+3WoNDrDK5cGn7m+QI3GilVFlDa0ZAvMlxIRWdWRl9B06gowu1sDzpN6iDmS8Ljt9PW3ivatFXlFm+SMsse+B8wbV0NOog/oGaSxVzMP2FTZmxtYGnv6q4SUkoHHTx+n6mlzGZM7Wn+Cw)
- [Deployed Sandcastle](https://sandcastle.cesium.com/#c=rVZtc9o4EP4rGr7UvhABuaTTCTR3hCadzqTXDKG93AwzN8JeY6W2xMgylLvhv99KRrKBJse9fACs1fPs+y6OpCg0WXJYgSJviYAVGUHBy5x+sbLgVWSPIyk04wLUqzb5cyoI0aAUCi4dfFKdaaJk/qtUWXzNdLrOQas1+ekIUBCS53VtBUHYnopN2J+KqVgyRVK2YpyPIdJMzDNA/7cKvMiqeAdzBVAEp73XvTbpvWmT097FeZuc/WhUGUU5U5wJNlEgovRofb3zM1TXxc/5a9R2XjnW6ZB7Hn0lynGmIrJJVg29e573HWYF+OXNfsTsUC2dPa+AGljoSUIqnR7BsriaBuwoWwZWkwpZHmXL4nxCRgqYBsLIXMlSxPeK51zzJTSTZOrgjx/QFhMR7Lbk+112YBtxDtI2kKMUlzuUvduKU7N2wL4ejuXQpPbssn5su8sU+DzVl6TrJUtQGr7dSpUz7dv6HpRzYyQzqYaLBTBljvTLzXhy8/j77afxx+Fkq2UTbh+Y1orPSm1C8w5FRoNXbfXtxzp0PNu1FhI08fT67vMNXXGdDrNFyoIuvQidzY393fiBqzYELSIQQBeuAgVlcRwcVM3X/R0kuDOw6jwmCwwV3QNVbGstVwWW9+xiO4MYUJkLL3INV+UWpbbV2KwIqnY/rVoxJB3HrIeIx7ZHPcNO1alteIM3lp2H7zEeZXrT+iiTurroZiIVCYxvHLV1+/gzqMiEn5yEVS085qnCPCHGOUSePAxbAjEySQrQj4h8Ij9sQ+vvX/+G1xyvbRjWz6reJrRIKvT3DhKTERvWiWP1D3HXUmuZI7KaWgd99EqNUez/5sb7u3FrDs8/G7l/M3Z7o/fiOm5ySCNT7e9dVKlpP8fBXNn0v8BFSFXAJiTcIRzuhf9rN+zsh2d3xH/YE7tx72wNAxozEcs8CPe2x3Op2PjnhtNRxoqCJzximksxWS/qAo8OrujkZjwefvjF78a6h1/YTM3eDu2AbHCf2deHihXhSlKMJtl6Iquui3GouLB291d9XKqtvNt4D2maj2FWzh9Subo1u67Aoj4ADmSMc6VVaf7mW+3WoNDrDK5cGn7m+QI3GilVFlDa0ZAvMlxIRWdWRl9B06gowu1sDzpN6iDmS8Ljt9PW3ivatFXlFm+SMsse+B8wbV0NOog/oGaSxVzMP2FTZmxtYGnv6q4SUkoHHTx+n6mlzGZM7Wn+Cw) which still uses the old heights

## Testing plan

Explore the sandcastles above and observe the performance is the same between the deployed and local versions of sandcastle

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [x] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have update the inline documentation, and included code examples where relevant
- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
@jjspace It looks like there are some failing unit tests which just need to have some values updated.

**Comment by ggetz** [comment]
Thanks for test cases @jjspace! I agree that performance appears comparable.

Can you please update `CHANGES.md` with a summary of the change? I would list this under fixes as it should help cases where ground primitives were used with any bathymetric terrain.

**Comment by jjspace** [comment]
@ggetz Updated, test should be fixed and changes comment added

**Comment by ggetz** [comment]
Looks good! Thanks @jjspace!

**Pull request merged**
