### PR TITLE
Fix OpenStreetMapImageryProvider usage in comments, change default url

### PR DESCRIPTION
**Pull request by fredj**
See https://github.com/openstreetmap/operations/issues/737 for the url change

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @fredj!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/osm_usage_url/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Awesome, thanks @fredj! Please update `CHANGES.md` with a summary of the change.

> tile.openstreetmap.org supports [HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) and [HTTP/3](https://en.wikipedia.org/wiki/HTTP/3) which no longer require the old (a|b|c) aliases to increase browser connection concurrency. Using a single URL improves performance and ability to cache.

Given this, I would also suggest adding `tile.openstreetmap.org` to `RequestScheduler.requestsByServer`. This will allow Cesium apps to take advantage of increased concurrency with HTTP2+ requests by default, resulting in better performance.

**Comment by fredj** [comment]
@ggetz done

**Comment by ggetz** [comment]
Awesome, thanks @fredj!

**Pull request merged**
