### PR TITLE
Nearest Sampler setting, and code clean up

### PR DESCRIPTION
**Pull request by aboutqx**
Simple code reuse.
I thought much of this is needed for Cesium.
It can also be a prepare for default parameter in function using like 
```
function drawRect(width = 100, height = 100, color = [1, 0, 0,0], params = { } ){

}
```

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @aboutqx! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/aboutqx/cesium/blob/2020-3-25/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/2020-3-25/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by aboutqx** [comment]
Also a CLA is finished, can this be accepted?

**Comment by lilleyse** [comment]
@aboutqx I don't think we'd want to take this change as-is since it changes the default filtering mode of textures from linear to nearest, which is not desired in all cases.

One alternative might be to declare a static sampler in `Sampler.js` and use that everywhere applicable.

```js
Sampler.NEAREST = Object.freeze(new Sampler({
    wrapS : TextureWrap.CLAMP_TO_EDGE,
    wrapT : TextureWrap.CLAMP_TO_EDGE,
    minificationFilter : TextureMinificationFilter.NEAREST,
    magnificationFilter : TextureMagnificationFilter.NEAREST
});
```

And use it like:

```js
globeDepth._globeColorTexture = new Texture({
    context : context,
    width : width,
    height : height,
    pixelFormat : PixelFormat.RGBA,
    pixelDatatype : pixelDatatype,
    sampler : Sampler.NEAREST
});
```

**Comment by aboutqx** [comment]
That looks better, I'll try like that. Also some `createSampler` can be optimized.

**Comment by aboutqx** [comment]
@lilleyse It's ready to be merged.

**Comment by lilleyse** [comment]
Thanks @aboutqx your changes look good. I pushed https://github.com/CesiumGS/cesium/pull/8698/commits/fdd035511ad672cae9e971f9b0ed19f256f59fb1 to add `Sampler.NEAREST` to some more areas. Once CI passes I'll merge.

**Pull request merged**
