### PR TITLE
fix: typescript issues

### PR DESCRIPTION
**Pull request by jony89**
Changes I've had to made in order to get typescript working. all changes are tested and working. I always working with the examples in sandcastle and the documentation. 

reviews, and changes requests are welcome.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jony89!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@mramato please review

**Comment by mramato** [comment]
@jony89 I appreciate the PR but we can't take any of these changes except for the `Viewer.js` constructor fix.

As I mentioned to you in my comment here, https://github.com/CesiumGS/cesium/issues/8898#issuecomment-637579223, TypeScript doesn't support getters/setters of differing types.  For example, this PR breaks the below code:

```ts
const entity = new Entity();
entity.position = new Cartesian3(1,2,3);
const currentPosition = entity.position.getValue(JulianDate.now());
```

Because TypeScript thinks that `entity.position` is a Cartesian3, but it is not.  It is a `PositionProperty`.

If there's something we're missing that would allow us to take a `Cartesian3` in position but always return a `PositionProperty`, that would be great, but I'm fairly certain this simply isn't possible to express in TypeScript.

**Comment by jony89** [comment]
@mramato Then how should one set the position property? or the material property? `PositionProperty` constructor does not support any arguments

**Comment by kring** [comment]
@jony89 if your position isn't changing with time, use `ConstantPositionProperty`

**Comment by jony89** [comment]
What if it does? what about PolygonHierarchy ? `CallbackProperty` for dynamic options, and Color values for material properties. there are many more examples. Maybe we need to rethink things here so the API will fit `typescript` 

Anyway I changed the PR and kept the viewer change only

**Comment by kring** [comment]
The documentation and type definition tell you which base type of property you need to use, e.g. `Property` or `PositionProperty`. Then you choose a _subclass_ of those based to instantiate, e.g. `ConstantProperty`, `ConstantPositionProperty`, or `SampledPositionProperty`. If you were previously just assigning a value (not a Property type), then you should always use the `Constant-` version to get equivalent behavior.

`MaterialProperty` is the only one that is a bit different. There, you choose a subclass based on the type of material (e.g. `ColorMaterialProperty`) and pass one or more instances of `Property` subclasses to its constructor.

@mramato as an aside, I wonder if we're thinking about this wrong. Users of CesiumJS are much more likely to _set_ entity properties than they are to get them. So maybe we should change the type definitions to correctly express that you're allowed to set with a simple primitive type. That means it will (incorrectly) think that that the getter might give you back a primitive type, which is not true, but in this less common and more advanced use-case, it's easy to work around that annoyance with a type assertion (cast). I'm not sure if I'm convinced on this, just throwing it out for consideration.

**Comment by courageon** [comment]
@jony89 Just came across the "position" issue in my code and Google brought me here. There is hacky work-around where you can cast the position property as an "any". It's real ugly though... I'm going to try and isolate that bit in my code in case of future changes :)

`(entity.position as any) = newCartesian3Position;`

**Pull request closed without merging**
