### PR TITLE
Migrate from Travis CI to GitHub actions

### PR DESCRIPTION
**Pull request by ggetz**
We're looking to move from Travis CI to GitHub Actions to match the rest of the Cesium organization.

While there's a lot of awesome features in GitHub Actions we can start taking advantage of to automate more of or processes, this initial PR migrates the existing Travis CI functionality. That includes:
* Linting
* Running tests
* Verifying npm packages
* Building and deploying to S3
* Running coverage and deploying results to S3
* Setting the status to include links to both of the above deployments
* A specialized deployment when pushing to the `cesium.com` branch
* Slack notifications on a failed commit on `main` or `cesium.com` branches

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/github-actions/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by mramato** [comment]
@ggetz If you search for `travis` there are still a ton of references, mostly doc but a few in .gitignore and build.js (and even a few code comments).

It's probably worth doing a pass to clean these up as well. If you think it makes sense to do them as a follow-up PR instead, that's fine too. Let me know.

**Comment by mramato** [comment]
The deployment link in the PR status 404s: http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/github-actions/

All other artifacts seem to work though.

**Comment by mramato** [comment]
That's all I have for this go around @ggetz

**Comment by ggetz** [comment]
Thanks for the review @mramato!

> The deployment link in the PR status 404s

This was due to the 30-day cleanup in s3 since we skip re-uploading existing files. We disabled this behavior for the `main` branch so that the files would be "touched" each CI run for the sake of this cleanup rule. Since it's showing up here as well, I've gone ahead and disabled it for development branches as well.

> If you search for travis there are still a ton of references, mostly doc but a few in .gitignore and build.js (and even a few code comments).

I've gone ahead and replaced these in this PR, as well as updating the contributor documentation.

**Comment by mramato** [comment]
Thanks, @ggetz I pushed one last tweak for some leftover travis references I found but will merge as soon as this goes green.

**Pull request merged**
