### PR TITLE
Fix for walls with negative heights

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes https://github.com/CesiumGS/cesium/issues/4274
Replaces https://github.com/CesiumGS/cesium/pull/9022

[sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=lVPvT9swEP1XrHxKpcpptaFtJVRDhW1ITJugG0gEoSM5gjf/iGwnECb+9zltk7hpv5BPl3fvvTvf2RVoUjF8Qk2OiMQnskDDSkF/r7AwCdLV/0JJC0yiToLRYSITudZQk6JEWmgmmGUVGgpZFiaS+FY/22z4r8kQkqMSaHV9Jo0F6QrMfPrXQbZV9bot+hVw3kp6KiGFMq6oks58w1yAti4C+Y4+aCVOMNeI5lhrqMObXkjI+090MvaB6ccBcDB5O+PDAOjj25GXEPDMRCm+IcsfrWv+ZjppPid2nuugQ259HZPbupY9GR/soVfohvH8RWkBdua3tRnWd7CoGfDjokDQzR466LIsCqUtXZ5eL39dnJ74akKo79wVfG2P2AXQGW+tc7duv1Sxyc2G5NU+l3WB7r6eCcgxCcbEuwuswWYkCSiNVrGJ1g535ypXdwvFlaZ/ijwJdvrtq26O7Q3r7aPaHsLrKJGjw2AcxMbWHOet82cmGhUpNQ9dxxZFwZ2hie7L9C9amhrTPMKGGke+NM5YRVh2tOfVkpSDMS7zUHJ+yV7ciOZx5Pg7Uq4gYzL/4fbIoW5oj9P5+RqklMaR+92vtErxe9AD5/8)

The `removeDuplicates` function in `WallGeometryLibrary` was making the incorrect assumption that the minimum height of the bottom of the wall would be `0`, and if all positions at the top of the wall were `<=0` then the height of the wall was `0` and we didn't need to render anything.  This updates the `removeDuplicates` function to check if `topHeight === bottomHeight` instead of `topHeight <= 0` to determine if the wall positions resulted in a wall with 0 height.

Also fixed the logic for computing wall normals so it works when the top of the wall was at `height === 0` by using a position that is 1m below the top wall position instead of a position with `height === 0` for the cross product computation.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/wall-height-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@lilleyse can you review, or recommend someone to review?  Thanks!

**Comment by lilleyse** [comment]
I see @YoussefV was tagged in https://github.com/CesiumGS/cesium/pull/9044.

@YoussefV are you good with reviewing this one as well afterwards?

**Comment by YoussefV** [comment]
For future people looking over this: [here is another example of a sandcastle that shows the issue (adapted from #4274)](http://localhost:8080/Apps/Sandcastle/index.html#c=3ZRRT9swEMe/yikvpFLqJIPB1oVqpSBNAmmIsfFAeHCTo7Xm2NXZSVcmvvvspGxZizQm7WmOdMrZv//dxX8pDSdoBK6Q4BgUrmCKRtQV+9LuhXlQtPlUK8uFQsqDCL7nCsAikdu5JN2IEmn0JCwIucUbTbK87pBwEOXqcfAuV93TuJYzWeMNl9I17bozVFZYgYbxsgzbDgCKVwgj2DtxNKw8vhd1J20ygg3n11Ibp9fKwM9Rppyse+Nqn92Trk5xTohm4oZah7fD9NU+Sw6PIjh4y9L0IPpV6i/XptKbTaXDu0GvVsW/iaquPqCYL6yf7TZNIkgTuOtDQm1BkLA08uE3zF0sCS57X6ilJnZy8fmMrYRdTORywcOEvR5AT6ZrK511LbsrnUzPO/RxxyTC8uUeXWHZuvIfODRsL9/HP7g09F668BKTrs5O/6VHG0cetK6udbjlj0eCKMiMXUscP3V5L6qlJgs1yZCx2GK1lG5YE8/q4itaVphW6NEs7kuzUjQgyuNnfgZQSG6MO7mvpfwkHjAPxlns+B2p1LwUav6xQZJ87bFFOr7oNhljWezS55VWaznjtFX5Bw)

**Pull request merged**
