### PR TITLE
Fix the wrong order of the boundary rectangles in TileAvailability

### PR DESCRIPTION
**Pull request by baothientran**
When rectangles are inserted into the `QuadtreeNode` in `TileAvailability`, they are ordered by level using the index returned by `binarySearch()`. However, it negates the index when it is 0, which results in the wrong order of the rectangle lists and wrongly identify a tile is not available. This is the [Sandcastle example](https://sandcastle.cesium.com/#c=bVFdS8MwFP0rlz51UNNNRIR1Q9ir4MPAF+tDmt2uwTQpN0lnFf3tpl9OdOEG7tc599yk5QStxBMSbEDjCXZopa/Z05CL80gM8c5ox6VGyqPFOtdpCjtC7hA4CFM3nLgzBKXXwkmjwRmwyElU4Coy/lgB18CJeAemBO3rAsmyXP8AziQxT6BYwEeuIRxC5ylA4QqKMPcz3DYonhiC5OdVAtcJ3Mx2m8Ddy9TV11eTL/UB30I8rVdIzanbDxrjiS2BYGch/Z6yhHhEZhtYTqpmqq/B6VXlel7JNkoKHDEJLANlTyOMtkYhU+Y4D1usoyTKrOsUbsdVAe5l3Rhy4EnFjKUO60aFN7Zp4cUrOibswNa3ZulvaHaQLcjD5sJvgVDc2lApvVJ7+Y55tM3S0P8Pqgw/SH18bJEU7/q2arV9GJOMsSwN4WWkM0YVnP4wfwM)

Below is the visual problem:

Before the fix. The tile is not really detail because it is falsely identified as unavailable and therefore, upsampled from the parent
Screenshot_20200818_013710

After the fix. It is much more detail now
Screenshot_20200818_013345

@lilleyse Can you please take a look at it? Please let me know if I should add anything

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @baothientran!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/wrong-boundary-rectangle/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
@kring can you review?

**Comment by mramato** [comment]
I'll be _that guy_ and ask if there is an easy way to add a unit test for this? Only if it doesn't require a massive amount of hoop-jumping.

**Comment by baothientran** [comment]
@mramato I think the error can be replicated with a simple unit test. I will add it right away

**Comment by baothientran** [comment]
I think this is ready for review

**Comment by lilleyse** [comment]
@baothientran can you update `CHANGES.md`?

**Comment by kring** [comment]
Thanks @baothientran, great catch!

**Pull request merged**
