### PR TITLE
Updated the `outlineWidth` documentation for various classes

### LINKED ISSUE #8577: FooGraphics documentation should explain the limitations of outlineWidth
Sandcastle example: open any basic shape (e.g. Rectangle) and try to set an outlineWidth, or search "outlineWidth" on this tracker and read any of a bunch of existing issues, starting with #40 (!)

Browser: any

Operating System: Windows only, apparently

Since the very beginning of Cesium, people have been trying to use the `outlineWidth` property on EllipseGraphics, RectangleGraphics, PolygonGraphics, etc, then coming here or to the mailing list to complain that it "doesn't work".  The reason why is explained over and over in those issues, and boils down to the ANGLE engine only supporting a width of 1, which is reflected in `scene.maximumAliasedLineWidth`.

Rather than having this conversation here every few months, please update the docs for this property in those various classes to add a note along the lines of

> NB: this property will be ignored on all major browsers on Windows platforms.  For technical details, see (link to one of these issues).

Previous issues: #40 #4223 #4352 #6667 #7022 #7265 #8485 #8523

Affected classes (tested):
* BoxGraphics
* CorridorGraphics
* CylinderGraphics
* EllipseGraphics
* EllipsoidGraphics
* PlaneGraphics
* PolygonGraphics
* PolylineVolumeGraphics
* RectangleGraphics
* WallGraphics

Of note, PolylineGraphics clearly isn't using the underlying GL engine's outline mechanism and works as expected.

### PR DESCRIPTION
**Pull request by srothst1**
Fixes #8577

Updated the `outlineWidth` member documentation for the following classes:
- `BoxGraphics`
- `CorridorGraphics`
- `CylinderGraphics`
- `EllipseGraphics`
- `EllipsoidGraphics`
- `PlaneGraphics`
- `PolygonGraphics`
- `RectangleGraphics`
- `WallGraphics`
- `PolylineVolumeGraphics`

The updated documentation clarifies how `outlineWidth` can be used. It also provides the community with technical resources that are related to `outlineWidth`.

@shehzan10 
@ebogo1

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @srothst1!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/doc-limitation-outlineWidth/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by ebogo1** [comment]
@srothst1 I might be missing some context; have we settled on a link to this Stack thread as the best solution here? I thought Omar's idea of a warning might make sense.

**Comment by srothst1** [comment]
@ebogo1 I think including more information related to `outlineWidth` in the documentation would be helpful for developers.

I would be happy to create a warning informing developers when `outlineWidth` is updated to a value that is not `1.0` on Windows. Should I move forward with this?

**Review by ebogo1 — COMMENTED** [review]
These look mostly fine to me. I don't know if we have a set format for adding notes like this in docs. Based on some documentation "notes" in `Cesium3DTileset`, maybe it'd be more consistent to write: 
```
 * Gets or sets the numeric Property specifying the width of the outline.
 * Note: This property will be ignored on all major browsers on Windows platforms. For technical details, see {@link GH_issue_url}.
```

My gut is that it's a bit much to link to a stackoverflow thread here though. @lilleyse Any thoughts?

**Comment by lilleyse** [comment]
A github link should be sufficient.

Just to add to @ebogo1's suggestion make sure to add `<p>` and `</p>` so the generated documentation has as two separate lines.

```
 * Gets or sets the numeric Property specifying the width of the outline.
 * <p>
 * Note: This property will be ignored on all major browsers on Windows platforms. For details, see (@link https://github.com/CesiumGS/cesium/issues/40}.
 * </p>
```

image

**Comment by srothst1** [comment]
@lilleyse thank you for your feedback. Just made the edits - let me know what you think!

**Comment by lilleyse** [comment]
Thanks @srothst1!

**Pull request merged**
