### PR TITLE
Use availability to determine when entity paths should be shown

### PR DESCRIPTION
**Pull request by srcejon**
As per https://community.cesium.com/t/entity-path-not-disappearing-when-entity-is-not-available/8551 and #1740, it seems entity paths are always shown even when other parts of the entity are no longer displayed due to its availability value.

This patch makes it so that the path is only displayed when the entity is available.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @srcejon! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/srcejon/cesium/blob/entity_path_use_availability/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/entity_path_use_availability/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by srcejon** [comment]
I've just signed the CLA.

**Comment by Daniel-Brosnan-Blazquez** [comment]
Dears,

We have our use cases broken since 1.90 version of Cesiumjs due to this change as we were using path availability to limit the display of segments (as the cartesian positions in the czml go beyond the stop time of the segments) and using the show parameter of path to display the segments all the time no matter where the timeline was set. So we were able to display something like this:
image

Now, since version 1.90, segments are only allowed to be shown during the availability period as shown here:
image

So, there is no possibility now to show all paths all the time.

I think that the czml options were already allowing to limit when the entity paths should be displayed through the "show" parameter of path. It does not seem to be the correct way to limit this by changing the interpretation of availability, it should be re-directed to change the "show" parameter.

Because, if this change is maintained, could you please tell us how we could obtain the same results?

Thanks in advance for any feedback.
Regards.

**Comment by srcejon** [comment]
> It does not seem to be the correct way to limit this by changing the interpretation of availability

But that is the way it seems to work for all of the other parts of an entity, 

> it should be re-directed to change the "show" parameter.

How are you setting the value of show when there's no supposedly no data available?

**Comment by Daniel-Brosnan-Blazquez** [comment]
> How are you setting the value of show when there's no supposedly no data available?

"show/interval" in this use case (showing several segments all the time) is set to cover all the period of the timeline and "availability" only covers every specific segment. So that the combination makes available a list of positions during the corresponding "availability" period but shows this list of positions during the corresponding "show/interval" period. And with this combination you can also configure the input to show the positions only during the "availability" period.

**Comment by Daniel-Brosnan-Blazquez** [comment]
So, to put it in a different perspective, now there seems to be no difference between "availability" and "show/interval".

**Comment by Daniel-Brosnan-Blazquez** [comment]
Dears,

Could you please tell if these last comments are going to be considered?

Thanks in advance for any feedback.
Regards.

**Pull request merged**
