### PR TITLE
Create Coordinates.js

### PR DESCRIPTION
**Pull request by Anigod**
Coordinates is Similar to Cartographic but in degrees ，degrees are commonly used in our company's development process，It's probably going to be a common practice。

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @Anigod! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Anigod/cesium/blob/addCoordinates/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/addCoordinates/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by Anigod** [comment]
I added tests and CLA，but api not update now，I'll write it when it's accepted

**Comment by Anigod** [comment]
use prettier

**Comment by hpinkos** [comment]
Hi @Anigod,  I'm sorry, but this isn't a change we want to take.  We use SI units (meters, seconds, radians) for all of our internal representations of measure.  We provide helper functions like `Math.toDegrees` if you need to convert radians to degrees to displaying in your UI, but aren't going to have a separate class for this as part of the API.

**Comment by Anigod** [comment]
My English is not very good, maybe the grammar is not very smooth to read, I apologize to you in advance.

Thank you for your reply. Yes, it's really UI biased.

My company and I do customized development functions based on Cesium, and we also hope to contribute to the development of Cesium. We have a lot of practical businesses and SDKs to expand. Could you please tell me how I can judge which ones can be provided for this project?

For example, mouse drawing all kinds of graphics, optimization for mouse movement triggered too frequently, coordinate pick up which integrated a variety of pick up methods, docking of geoServer, first perspective, etc.

**Comment by Anigod** [comment]
> My English is not very good, maybe the grammar is not very smooth to read, I apologize to you in advance.
> 
> Thank you for your reply. Yes, it's really UI biased.
> 
> My company and I do customized development functions based on Cesium, and we also hope to contribute to the development of Cesium. We have a lot of practical businesses and SDKs to expand. Could you please tell me how I can judge which ones can be provided for this project?
> 
> For example, mouse drawing all kinds of graphics, optimization for mouse movement triggered too frequently, coordinate pick up which integrated a variety of pick up methods, docking of geoServer, first perspective, etc.

test

**Comment by Anigod** [comment]
Excuse me, can I submit code for more business or operation like mouse drawing graphics, first person movement control, mouse picking and highlighting?

**Comment by Anigod** [comment]
Excuse me, can I submit code for more business or operation like mouse drawing graphics, first person movement control, mouse picking and highlighting?

**Pull request closed without merging**
