### PR TITLE
Fix out_FragColor handling in demodernizeShader

### LINKED ISSUE #11225: nvidia geforce gt 730   requestWebgl1:true
cesium version:103
NVIDIA GT730 graphics card
sets requestWebgl1 to true, but still reports an error 

but cesium version:101 no error;

`const viewer = new Cesium.Viewer("cesiumContainer", {
        baseLayerPicker: false, //关闭图层选择器
        //放大镜图标，查找位置工具，查找到之后会将镜头对准找到的地址，默认使用bing地图
        geocoder: false,
        //房子图标，视角返回初始位置
        homeButton: false,
        //经纬网图标，选择视角的模式，有三种：3D，2D，哥伦布视图（2.5D)
        sceneModePicker: false,
        //地图图标，图层选择器，选择要显示的地图服务和地形服务,默认会用到cesium.ion
        baseLayerPicker: false,
        //问号图标，导航帮助按钮，显示默认的地图控制帮助
        navigationHelpButton: false,
        animation: false, //动画器件，显示当前时间，允许跳转特定时间
        timeline: false, //时间轴
        //全屏图标，全屏按钮
        fullscreenButton: false,
        //虚拟现实
        vrButton: false,
        //阴影
        shadows: false,
        //点击后显示详细信息
        infoBox: false,
        //展示数据版权属性
        CreditsDisplay: false,
        //terrainExaggeration: 3.0, //地形夸大
        shouldAnimate: false,
        contextOptions:{
          requestWebgl1:true
        }
      });`

### PR DESCRIPTION
**Pull request by jjhembd**
Fixes #11225. 

`demodernizeShader.js` removes layout declarations for `out_FragColor`. However, this replacement needs to be done _before_ replacing all instances of `out_FragColor` with `gl_FragColor`.

We only have one shader with a layout declaration for `out_FragColor` (`AdjustTranslucencyFS.glsl`), which may be why we didn't notice the bug before.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jjhembd!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-translucency-webgl1/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks @jjhembd! 

Please update `CHANGES.md` with a summary of the fix.

After that, once you confirm the fix, this looks good to merge.

**Comment by jjhembd** [comment]
Here is the output of `demodernizeShader(AdjustTranslucentFS, true)` in the main branch:
```glsl
#version 100
#extension GL_EXT_draw_buffers : enable
#ifdef MRT


#else
layout (location = 0) out vec4 gl_FragColor;
#endif

uniform vec4 u_bgColor;
uniform sampler2D u_depthTexture;

varying vec2 v_textureCoordinates;

void main()
{
    if (texture2D(u_depthTexture, v_textureCoordinates).r < 1.0)
    {
#ifdef MRT
        gl_FragData[0] = u_bgColor;
        gl_FragData[1] = vec4(u_bgColor.a);
#else
        gl_FragColor = u_bgColor;
#endif
        return;
    }
    
    discard;
}
```
compared to the output from this PR:
```glsl
#version 100
#extension GL_EXT_draw_buffers : enable
#ifdef MRT


#else

#endif

uniform vec4 u_bgColor;
uniform sampler2D u_depthTexture;

varying vec2 v_textureCoordinates;

void main()
{
    if (texture2D(u_depthTexture, v_textureCoordinates).r < 1.0)
    {
#ifdef MRT
        gl_FragData[0] = u_bgColor;
        gl_FragData[1] = vec4(u_bgColor.a);
#else
        gl_FragColor = u_bgColor;
#endif
        return;
    }
    
    discard;
}
```

**Comment by jjhembd** [comment]
Hi [@1wobuzhidao](https://github.com/1wobuzhidao1), can you test this branch and see if it fixes your problem?

**Pull request merged**
