### PR TITLE
Fix SampledProperty.Prototype.Equals

### PR DESCRIPTION
**Pull request by seoular**
SampledProperty's equal function fails to check equality of all fields within a SampledProperty's data.  Say we have a new Cesium.SampledProperty(Cesium.Quaternion).  It turns out that checking equality between two sampled properties will ignore comparing most of the fields of Cesium.Quaternion (x,y,z,w fields) as the "length" variable does not represent the size of "values" and "otherValues".  Which causes Cesium to not property detect when a SampledProperty has been updated, so it wont rerender.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @seoular! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/seoular/cesium/blob/patch-1/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/patch-1/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks @seoular ! I can confirm you are now on Orbit Logic's corporate CLA.

**Comment by mramato** [comment]
Thanks @seoular.  Can you add a unit test that verifies this fix to ensure it doesn't happen again?  If you open `SampledPropertySpec.js` and look for the `equals works when samples differ` test, it should be easy to copy/paste a new version that uses Quaternion to verify that works.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @seoular! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @seoular! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @seoular! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@mramato I think this is ready now.  Can you review and merge?

**Comment by hpinkos** [comment]
@mramato bump

**Comment by mramato** [comment]
Thanks @seoular this will go out with Wednesday's release.

**Pull request merged**
