### PR TITLE
Clamp non-looped animations to start and stop times.

### LINKED ISSUE #7387: [gltf] Missing last frame during animation?
Hi folks

I recently discovered an unexpected behavior. The following lines of code don't seem to play the animation till the last frame (stop at the second-last maybe?):
```
Cesium.when(model.readyPromise).then(
    function(model) {
        model.activeAnimations.add({
            name : 'All Animations',
        });
    }
)
```
Please verify that with the following model (one cube still, the other rotates by 90 degrees). Note, that there is no gap at the beginning between the cube. Once the animation has finished in Cesium, there is a slight angle between the cubes, which indicates that there is at least one frame missing. This is not the case in BabylonJS, where the the first and last frames look correct.

The model:
[cube_rot_animOptimized_noAutoAnim2.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2649138/cube_rot_animOptimized_noAutoAnim2.zip)

Some screenshots:

first_frame_cesium
First frame Cesium

last_frame_cesium
Last frame Cesium

last_frame_babylon
Last frame Babylon

Thx a lot!

### PR DESCRIPTION
**Pull request by emackey**
Fixes #7387.

If Cesium's current time went outside of a non-looping glTF animation time interval, Cesium would not perform one final update to push the animation as far as it could go in the direction of that time.

Here's a [Sandcastle demo on master](https://sandcastle.cesium.com/#c=lVb9U+I4GP5XOt4PW24wtICssu7OIbhsHQEXWFcdZnZKG2y0TbppK8KN//u9SfoJ6t05utu8ed7vJ2/yZHMtim0ez0mAtc9aH0ckCdBF4hObDuwYoxVngRWx445h6h+aRtM4NNqH5vHc7HQNA37vPtQ+LeiTtMPCN83YrjvDDqNupOf+6lrHqGsUr/fxek1YVXZD397M3o3xdePm0bvGC9P/O+z20X8I2/GZ8whGS8C+EOl/L6hWFL1bfNbFhpNwjmm6VUm9rvRUtN38S2kJy1Ob3sNG2ZkUocvJ5OrXbD65ktgg8WMS+gTzrtY0QfRSBP1E8BrzatTXUqYvDhy57jMa24RivjioayoXjyW+26MkgBJ0tZXtR6WohPqIudjv7pUi39IlslaNJXIwFV1RMSG5TPsWQ94+Ke9mkhQQCKvSUqOhXZ4Pz8eDrvy+xb7P1tqhdoZXjGMt9rBqgLQpIUOOMQWESojQeymdYlfIVjGURymxMNXJfAu2fCP3ng9/saw8FO0PjJuiUu0ainAqLVGp0mGR+/vGmsrYcclYlSMVSv+7vdVReze4soF6zrKKqS1jwZyV0yjDFnSVUCcmjGoOx0AJ1eKE+3XNw8K9+N92obIQLokdr65x5vs1xSYFKU6ji1c2MPba9hOsZ/oGMoQrLTP0Jjx1k+OlvzfQaSw5VgT1BlRslZCCcl64c26+KedXwuoU8PqrScuCKQuMk3tCC499KC982bQlp/AA3wMzI13ANe3QbLaQ8bHd7pgndSVqt5FxZLQ+Gp1UoKolvosw5ckY2TEnz4WnObdpBOchiJC3E/WcfSXP2P3K7QCnrlWcmY+QZw7kcBHmwbA8rSjkJCAxecKRoF+qnvqUrJCJDf14paai+AGedMU/9UxQirhbXhQAAic1Ca4gTn9GtjCCzOZxuvtS24sOASndzRU4JhFWKAQnmuo5bXWJS/mYh4BsR6SSjgVGZU496GsOq85WA5n1YsdnLOxWcs8NXcIWGk/G5zn8JQtY/MjLBKrP7WLcqXUJBBPqDk6lFjMVbEUZJrbgmhzsqjGRI4bcLLQd3Jem+jnmU1kVNIoUmsjQ/iyW0AUPBfazqhZasoQK5sxCD3OMONAoiepp5NDnJIohc4ptXstdFJGhtIkiiQGByUIdMd259ifU8Wi3GnBBymSycko+tFFa/c3Z5ooRGuulvsgQXyNPtrcTvnJRQpXvrvxc6rUMUKuUbW8qyVrFbApiOGl6s5WPjkxlZzDtKBw2KwppUYFTj71ymu9FXRlHctLvzSMoNvR4L6eXVIIYHBO+hlNTOiqYc8ZLR2VNqMvWyIaexulmbgY+XtI7ee6RCMj6CDftPQyfONJsB94XkcaovxEslndsSCgVdXSSJazsIPQxSl8AUvWztjjAmwtvOXTIhFxYP7aWOSZWZNHpkdO3OtZjeHPdvzhBAPrtDh8BZLVum1+90eBxM+6b3nh4blzOpw+j4SieDO/8u77RGv201ncPHrndet7ooUcu+xfhHRgbD36A4fHDsnXmOxur8xMcOy2L3MzW5PZmvL27mW6th3A5mVvr0WDqCr3bm+9k8nBuTgbOZjywjNHg+gQdLr3oW/DrrDUb3/du+6vtw/PmZhk0e17v+8lk7XVORr+3hultRj8WB8UzWA2sgiIWo1McsYQ76pXei+AOt1z9pGkYbXiapRWdi0p104KpVu6OO56ayduoOJzew0eGAeT7VN7J2F2Vv09hs8RgOVoqt+t7fC+/IjKaZSHnXE9fBsVScTtbK4rn2uBbfSsf6bw9qB+cRvHGx1+E8C8ShAwehnAX6Qg1Ygz0gziixjJxHnGMnCgSaqeNTOXUJU8acT+/8lKGp7AdRbCzSnx5Ry0Ovpw2AF9R85kMevKEOTzCBMQzv1wqIULotAHLfa2YMX9p85LFfwA) that tries to demonstrate the problem.  The green area on the timeline shows where the animation is playing.  If you jump the time into one of the outside areas (yellow or red), the cube won't update, it will remain frozen in some in-between state.

anim-issue-v2

Here's the same [Sandcastle demo on this branch](http://cesium-dev.s3-website-us-east-1.amazonaws.com/cesium/anim-start-stop/Apps/Sandcastle/index.html#c=lVb9U+I4GP5XOt4PW24wtICssu7OIbhsHQEXWFcdZnZKG2y0TbppK8KN//u9SfoJ6t05utu8ed7vJ2/yZHMtim0ez0mAtc9aH0ckCdBF4hObDuwYoxVngRWx445h6h+aRtM4NNqH5vHc7HQNA37vPtQ+LeiTtMPCN83YrjvDDqNupOf+6lrHqGsUr/fxek1YVXZD397M3o3xdePm0bvGC9P/O+z20X8I2/GZ8whGS8C+EOl/L6hWFL1bfNbFhpNwjmm6VUm9rvRUtN38S2kJy1Ob3sNG2ZkUocvJ5OrXbD65ktgg8WMS+gTzrtY0QfRSBP1E8BrzatTXUqYvDhy57jMa24RivjioayoXjyW+26MkgBJ0tZXtR6WohPqIudjv7pUi39IlslaNJXIwFV1RMSG5TPsWQ94+Ke9mkhQQCKvSUqOhXZ4Pz8eDrvy+xb7P1tqhdoZXjGMt9rBqgLQpIUOOMQWESojQeymdYlfIVjGURymxMNXJfAu2fCP3ng9/saw8FO0PjJuiUu0ainAqLVGp0mGR+/vGmsrYcclYlSMVSv+7vdVReze4soF6zrKKqS1jwZyV0yjDFnSVUCcmjGoOx0AJ1eKE+3XNw8K9+N92obIQLokdr65x5vs1xSYFKU6ji1c2MPba9hOsZ/oGMoQrLTP0Jjx1k+OlvzfQaSw5VgT1BlRslZCCcl64c26+KedXwuoU8PqrScuCKQuMk3tCC499KC982bQlp/AA3wMzI13ANe3QbLaQ8bHd7pgndSVqt5FxZLQ+Gp1UoKolvosw5ckY2TEnz4WnObdpBOchiJC3E/WcfSXP2P3K7QCnrlWcmY+QZw7kcBHmwbA8rSjkJCAxecKRoF+qnvqUrJCJDf14paai+AGedMU/9UxQirhbXhQAAic1Ca4gTn9GtjCCzOZxuvtS24sOASndzRU4JhFWKAQnmuo5bXWJS/mYh4BsR6SSjgVGZU496GsOq85WA5n1YsdnLOxWcs8NXcIWGk/G5zn8JQtY/MjLBKrP7WLcqXUJBBPqDk6lFjMVbEUZJrbgmhzsqjGRI4bcLLQd3Jem+jnmU1kVNIoUmsjQ/iyW0AUPBfazqhZasoQK5sxCD3OMONAoiepp5NDnJIohc4ptXstdFJGhtIkiiQGByUIdMd259ifU8Wi3GnBBymSycko+tFFa/c3Z5ooRGuulvsgQXyNPtrcTvnJRQpXvrvxc6rUMUKuUbW8qyVrFbApiOGl6s5WPjkxlZzDtKBw2KwppUYFTj71ymu9FXRlHctLvzSMoNvR4L6eXVIIYHBO+hlNTOiqYc8ZLR2VNqMvWyIaexulmbgY+XtI7ee6RCMj6CDftPQyfONJsB94XkcaovxEslndsSCgVdXSSJazsIPQxSl8AUvWztjjAmwtvOXTIhFxYP7aWOSZWZNHpkdO3OtZjeHPdvzhBAPrtDh8BZLVum1+90eBxM+6b3nh4blzOpw+j4SieDO/8u77RGv201ncPHrndet7ooUcu+xfhHRgbD36A4fHDsnXmOxur8xMcOy2L3MzW5PZmvL27mW6th3A5mVvr0WDqCr3bm+9k8nBuTgbOZjywjNHg+gQdLr3oW/DrrDUb3/du+6vtw/PmZhk0e17v+8lk7XVORr+3hultRj8WB8UzWA2sgiIWo1McsYQ76pXei+AOt1z9pGkYbXiapRWdi0p104KpVu6OO56ayduoOJzew0eGAeT7VN7J2F2Vv09hs8RgOVoqt+t7fC+/IjKaZSHnXE9fBsVScTtbK4rn2uBbfSsf6bw9qB+cRvHGx1+E8C8ShAwehnAX6Qg1Ygz0gziixjJxHnGMnCgSaqeNTOXUJU8acT+/8lKGp7AdRbCzSnx5Ry0Ovpw2AF9R85kMevKEOTzCBMQzv1wqIULotAHLfa2YMX9p85LFfwA).

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/anim-start-stop/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by emackey** [comment]
I can't see what Travis is doing, but there's probably a failed test on here, I'll have to look into it.

**Comment by mramato** [comment]
> I can't see what Travis is doing

Why not?  You should be able to get the full log. Here you go either way.

```
  Scene/Model
    ✗ raises animation start, update, and stop events when removeOnStop is true
	Expected 5 to equal 4.
	<Jasmine>
	@Specs/Scene/ModelSpec.js:1776:41
	fulfilled/p<@Source/ThirdParty/when.js:194:34
	_then/<@Source/ThirdParty/when.js:295:13
	processQueue@Source/ThirdParty/when.js:645:11
	_resolve@Source/ThirdParty/when.js:331:16
	promiseResolve@Source/ThirdParty/when.js:357:11
	poller@Specs/pollToPromise.js:26:16
    ✗ Animates with an explicit stopTime
	Expected 3 to equal 2.
	<Jasmine>
	@Specs/Scene/ModelSpec.js:1846:39
	customizeJasmine/window.it/<@Specs/customizeJasmine.js:40:22
	<Jasmine>
```

**Comment by emackey** [comment]
OK, tests uncovered another edge case, where user's stop time happens before the animation's own stop time.  This is fixed now, and new tests explicitly cover the edge cases I know about.  Coverage remains at 100% for this section of code.

**Comment by emackey** [comment]
This is ready.

**Comment by mramato** [comment]
Looks simple and straightforward to me and can confirm the fix works as intended.  @lilleyse did you want to take a look at this?

**Comment by lilleyse** [comment]
Looks good to me

**Pull request merged**
