### PR TITLE
fix issues 9370

### PR DESCRIPTION
**Pull request by Anigod**
https://github.com/CesiumGS/cesium/issues/9370

It is possible to change the position during the rendering process, so that it will not crash again after processing, and it can be rendered normally

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @Anigod!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/issues-9370/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Anigod! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @Anigod! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by sanjeetsuhag** [comment]
Thanks for the PR @Anigod. Looking deeper into the issue, it seems like the root cause is not yet addressed.

Comparing the implementations for `Batch` across files like  [`StaticOutlineGeometryBatch`](https://github.com/CesiumGS/cesium/blob/main/Source/DataSources/StaticOutlineGeometryBatch.js), [`StaticGroundPolylinePerMaterialBatch`](https://github.com/CesiumGS/cesium/blob/main/Source/DataSources/StaticGroundPolylinePerMaterialBatch.js), [`StaticGeometryColorBatch`](https://github.com/CesiumGS/cesium/blob/main/Source/DataSources/StaticGeometryColorBatch.js), seems like the missing link is the following line of code:

https://github.com/CesiumGS/cesium/blob/86463647512518499d2f83b391967bd530e06cba/Source/DataSources/StaticGeometryColorBatch.js#L117

which is missing in [`StaticGroundPolylinePerMaterialBatch`](https://github.com/CesiumGS/cesium/blob/main/Source/DataSources/StaticGroundPolylinePerMaterialBatch.js) and in [``](https://github.com/CesiumGS/cesium/blob/main/Source/DataSources/StaticGroundGeometryPerMaterialBatch.js).

Adding this line seems to correct this issue.

**Comment by ggetz** [comment]
@Anigod We're trying to be more responsive to PRs and keep our PR backlog tidy. Due to inactivity, I'm going to close this PR. But please feel free to re-open when you get the chance to work on this! Thanks for your patience.

**Pull request closed without merging**
