### PR TITLE
fix vector tile byteoffset alignment to 4 bytes

### PR DESCRIPTION
**Pull request by rainliang000**
Fix byte offset alignment. 
>byteOffset += byteOffset % 4;

If the byte offset mod 4 is 1, we should add 3 to the alignment.

So i change it to
>byteOffset += (4 - (byteOffset % 4)) % 4;

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @rainliang000! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/rainliang000/cesium/blob/patch-3/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/patch-3/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by rainliang000** [comment]
add CONTRIBUTORS.md entry and Signed CLA.

**Comment by lilleyse** [comment]
@rainliang000 thanks for the fix. The old way is definitely wrong.

But there shouldn't be a need to account for padding at runtime if each section in the vctr body is properly aligned. Whitespace should be added to the end of the JSON sections so that following sections are aligned. Extra bytes should added to the end of binary sections for the same reason. The byte lengths in the header should include the padding so that you never end up with a misaligned byte offset while parsing. These are the rules for b3dm, i3dm, etc, but looks like they are not as well defined for vctr: https://github.com/CesiumGS/3d-tiles/tree/vctr/TileFormats/VectorData#implementation-notes

In any case, this is a good fix for what the code is currently doing.

**Comment by ryanliang000** [comment]
@lilleyse  Thank your for your kindly reply and tell the reasons!

**Pull request merged**
