### PR TITLE
Fixed a 32 bit vertex indices model render issue

### PR DESCRIPTION
**Pull request by renjianqiang**
There are some render error when the gltf model both contains meshes which vertices over than 65535 and another less than 65535. There is the model:[model.zip](https://github.com/CesiumGS/cesium/files/5596216/model.zip)

This model can be render correctly in `babylon.js` and `three.js`, and check valid via [glTF-Validator](http://github.khronos.org/glTF-Validator/) , so i think maybe there are some problems in ceisum.

Function `parseBufferViews()` in `Model.js` assumed all  `accessors`  for each `bufferview` should have same `componentType`, but actually this model is not.  Then function `createVertexArrays` create the wrong `rendererVertexArrays` by the wrong `indexBuffer`, and then the function `createCommand` created the wrong draw command which called by `_gl.drawElements`. At last, the render error occurred.

I try to fix this issue gracefully, but maybe there are some other more efficient methods if someone can help.
Thanks!

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @renjianqiang!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by renjianqiang** [comment]
Can anybody please help review this PR? @shunter

**Comment by mramato** [comment]
@lilleyse can you take a look at this please?

**Comment by lilleyse** [comment]
@renjianqiang thanks for the PR, however I'm not sure if this is the right fix for the problem. I'm worried about cloning the `Buffer` in this way since there might be problems if the main buffer and the cloned buffer are both destroyed.

I spent a little while thinking of other solutions but nothing seemed quick to implement. Model.js may need some major changes to how it loads index buffers and even more fundamentally I'm not sure if Buffer.js should have special handling for index buffers because it prevents indices accessors of different component types from sharing the same buffer data, a problem that vertex buffers don't have.

An approach that could work is to create a new property in `rendererResources` called `indexBuffers` that maps `bufferViewId` + `accessorId` keys to `Buffer` objects. `parseBufferViews` and `createIndexBuffer` and probably many other areas of the code would need to be updated. You're welcome to try this out but I do think it's a much bigger change.

**Comment by renjianqiang** [comment]
@lilleyse thanks for you reply. I agree with you, if we want to fix this problem from the source, we need to make some major changes to `Buffer.js` and `Model.js`. 
>  Model.js may need some major changes to how it loads index buffers and even more fundamentally I'm not sure if Buffer.js should have special handling for index buffers because it prevents indices accessors of different component types from sharing the same buffer data, a problem that vertex buffers don't have.

But i'm a little confused about this：
> I'm worried about cloning the Buffer in this way since there might be problems if the main buffer and the cloned buffer are both destroyed.

The changes i do in this PR is just shallow copy the `Buffer` object to share the same vertex buffer, and the cloned buffer will never be accessed by external.  And i also think there should be no problems even all main buffer and the cloned buffer are both destoryed, there just may be a little waste of memory.
>The WebGLRenderingContext.deleteBuffer() method of the WebGL API deletes a given WebGLBuffer. **This method has no effect if the buffer has already been deleted.**

So call the ` this._gl.deleteBuffer(this._buffer)` at `Buffer.prototype.destroy` multi times should not be problems.

Or maybe i neglect something? I am looking forward to you could point out the problem more specific.

I will consider the approach you mentioned above and try to fix it from the source next, whether or not there are problems in this PR. But i think it will be a big change which need time and test, so should we use this quick fix for a temporary emergency use if the fix has no problem?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @renjianqiang! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @renjianqiang! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @renjianqiang! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
I have a fix for this in the [`model-loading`](https://github.com/CesiumGS/cesium/tree/model-loading) refactor branch, though it's not ready for testing yet. Just to keep the PR list tidy I'm going to close this. Thanks @renjianqiang.

**Pull request closed without merging**
