### PR TITLE
optimize Primitive.prototype.getGeometryInstanceAttributes cache performance

### PR DESCRIPTION
**Pull request by verybigzhouhai**
optimize Primitive.prototype.getGeometryInstanceAttributes cache performance

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @verybigzhouhai!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/origin/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by verybigzhouhai** [comment]
https://github.com/CesiumGS/cesium/issues/11066

**Comment by ggetz** [comment]
Thanks @verybigzhouhai! 

Would you mind putting together a test case in [Sandcastle](https://sandcastle.cesium.com/) based on your notes in https://github.com/CesiumGS/cesium/issues/11066?

Also please add an item to `CHANGES.md` which summarizes your fix.

**Comment by verybigzhouhai** [comment]
@ggetz Sandcastle test has been added.
The changes.md has not been modified this month. I tried to add one. Please see if it meets the requirements

**Comment by ggetz** [comment]
Great, thanks @verybigzhouhai! I'm seeing similar timings for the initial time the attributes are set, and much faster times after.

**Pull request merged**
