### PR TITLE
Reverting Firefox OIT Fix #4815

### LINKED ISSUE #4815: Revert Firefox OIT Fix
This is a reminder to revert the changes to OIT in https://github.com/AnalyticalGraphicsInc/cesium/pull/4762 once the time is right.

OIT (in its original state before that PR) is working in Firefox nightly but still broken in Firefox 50.

### PR DESCRIPTION
**Pull request by squrki**
# Description

Reverts code change for Firefox OIT.

## Issue number and link

Issue #4815 
https://github.com/CesiumGS/cesium/issues/4815

## Testing plan

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have updated the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
@javagl Could you please review this PR?

**Review by javagl — COMMENTED** [review]
The change itself looks clean and straightforward. I think that this PR does not _completely_ revert the fix, though: There seems to be a change in https://github.com/CesiumGS/cesium/pull/5047 that addressed the same issue, in `FramebufferSpec.js`, and I _think_ that it _should_ be possble to revert that as well. 

In terms of testing ... well... it's always interesting to see a PR that links to issues where, after 1 or 2 clicks through related issues, the year "2014" appears. Verifying _the issue itself_ (as in a comparison of "before-after") is difficult in these cases, because ... I'd probably have to set up a VirtualBox with Windows XP in order to run a FireFox 50 😁 

But what I did: I checked out the state from this PR, and ran the https://sandcastle.cesium.com/index.html?src=Geometry%20and%20Appearances.html , This _does_ call `updateTextures` function that was modified here. I tried this on Chrome 129.0.6668.59 and FireFox 130.0.1 , and it worked in both cases:

Cesium OIT Fix


---

<sub>In CI, there's that green checkmark. Locally, I do have some test failures, but these seem to mainly be timeouts, and therefore seem to be unrelated to the change here)</sub>

**Comment by squrki** [comment]
@javagl I've reverted the changes to #5047 as well.

**Comment by javagl** [comment]
The current CI failure seems to only/mainly be at the linting stage. Doing an
`npm run prettier`
will probably remove some 'space' or newline somewhere, and that should fix it.

(There also is a test failure, but that seems pretty unrelated - that can be handled later if it is still there after the linting update)

@ggetz The "Review required" is new - I'm not sure whether I'm automatically expected to "Approve" this. But I'd do this as soon as CI passes (even though someone else will merge it)

**Comment by ggetz** [comment]
> The "Review required" is new - I'm not sure whether I'm automatically expected to "Approve" this. But I'd do this as soon as CI passes (even though someone else will merge it)

@javagl If you can do so, please do!

**Review by javagl — APPROVED** [review]
As mentioned in the first comment: The changes look clean. CI passes. Should go good to go.

**Comment by ggetz** [comment]
Thanks @squrki and @javagl!

**Pull request merged**
