### PR TITLE
Updates PolygonPipleine holes specs

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
Fixes https://github.com/CesiumGS/cesium/issues/10513

The triangulation is different due to internal changes in `earcut`, however, the result is still correct:

| Spec | Old | New |
| - | - | - |
| single| holes_old | holes_new |
| multiple| multiple_holes_old | multiple_holes_new |

The [Polygon Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html?src=Polygon.html&label=Geometries) examples also look correct:

image

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/polygon-pipeline-holes-specs/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
@lilleyse Just to check, do you know if there are any other implications to these triangulation changes? Or is it anything that user may have depended on such that we should mention it in `CHANGES.md`?

**Comment by lilleyse** [comment]
I don't think it matters too much if the triangulation changes as long as the overall shape is the same.

So probably not worth mentioning unless it fixes polygon bugs or improves performance. I haven't checked the `earcut` release notes.

**Comment by ggetz** [comment]
From https://github.com/mapbox/earcut#224-jul-5-2022

> Improved performance by 10–15%.

**Comment by sanjeetsuhag** [comment]
@ggetz Updated CHANGES.md

**Comment by ggetz** [comment]
Awesome, thanks @sanjeetsuhag!

**Pull request merged**
