### PR TITLE
Add background color to doc nav bar, to help with horizontal scrolling.

### LINKED ISSUE #9162: Documentation is unreadable/messy on small screen
I splitted my screen in half, one with my editor, the other with the documentation, and I encountered a problem, as you can see below, when I scrolled horizontally:

Screenshot from 2020-09-21 09-21-48

I am not sure how this can be fixed, but maybe if you set a width to `#main` using something like `calc(100% - 300px)`, you could work it out.

### PR DESCRIPTION
**Pull request by emackey**
Fixes #9162.

My local doc build is busted, so I can't test this locally except by jamming it in DevTools.

Also I set the nav bar to be a slightly darker color, to draw more attention to the main panel.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/doc-nav-bar-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by GatorScott** [comment]
Works well, but the horizontal scrollbar spans the entire window, not just the "content" side.

**Comment by emackey** [comment]
Yes, this is just a patch.  Originally these things weren't supposed to horizontally scroll at all, just word-wrap more tightly.  I'm not sure why some of them now have such wide minimum widths.

**Comment by OmarShehata** [comment]
Thanks @emackey . I think this color looks nice and it's a good quick fix since it doesn't look like a bug anymore. 

Before:

image


After:

image

The reader can scroll horizontally to see the obscured text.

**Pull request merged**
