### PR TITLE
Add warning for when clampToGround is ignored in KMLDataSource

### PR DESCRIPTION
**Pull request by OmarShehata**
This came up in https://github.com/AnalyticalGraphicsInc/cesium/issues/8404. The `clampToGround` option is ignored in KMLDataSource for lines that don't have `tesselate` to true. This isn't document and no warning is shown which makes this hard to figure out.

Here's a [localhost Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=fVVtj5s4EP4rVu5DEykFA7aBLaV36puq7l4jbXr3JR/qgLNBa3Bkm2TT0/33G3CSJdnm+AB4PM888+LxbLlG20rshEZvUSN26L0wVVt7f/Wy8auiX75XjeVVI/SrKfpn0SB4rNAaRDOttlUp9M0RWGjBrfhbaVnOncp4smj+nbxZNFvgUhtbqcYA2cFOwWuhObo5eOGZQjTCc9LpUQWg5qVKJz2qSF5v5uqzVm1T3iCrWwGkwOlYH2vZhSAaC8Q/sndPtURboQ248nYxCjy8GCHRFKqsmgcQfJ9/ep0sRu/yRZMBFIF6Y0C+tnZz4/u73c5TG9E8VMZrhPVBxQ+9cDHKO2eyD6poa6DKnWtZA7HkM27XJvP7/4O8FKbQVZ+P/OMT+C+FQWqFNp2qh/5UViC75hZe8COMEVLyTsYfUGXQco9KseKttM4eQkaArkLYQ19WaK9atONNL3E1GdgokYRqmmlneo/q1li0FIi3dq20KI/2xkojUVagPkFlpUVh5R5VDfp6d+tl/tD9Q0T3di8FqkpI1R6I1O4WWD5rIZqZkvtDfnrNbqPXPolAWCipdB6vMF7Bk/luPVDYVaVd5yTz3c/Jmv/SXNYx/i8DxpcMmX8Jyvyz1UzyQtRcPz5D+oL+sTRKtpDhj09w8kpRnhX6otRzzRuz4bo7jA9dbqBMUqJdZdfIZQ2p1vb1+VWSwZrpfPquZf7bL7Kc+afti2xrONzDZHBpKwve3qlS5GcNlPlnewPM8xHKg8wfrM6SrDQ0EkhNjl4HAbQGpThOaBTFcRpMI+bhOKUkpWFAKCPxNIxo/GwAHUEkDeMYR2kcJT0oCYIYJxGIgzC8BqIhxRSzFLPIgUKGYxZEOA7j9BqIEUpwQJMoZg4UpZQxTJMETF0DJTiMkjRmhKQORIMArGBCkiC6BuqCTkiSYojAgRISgdNRGqXkCohBEAGLSAx6DsSCENaUAPpaTCzEcUTChNFDSAzsBGnn5dWMsygKMaQ3gdocQQEN0oRhDIW7AoL4WZQQ+JIjKIa8pISG8dWQKEtZSinpAnAg4ExTDHUjDoQGR8ofnqnLth+ca+jgsxbN/MFlnHUXdf7jNBSgB81p7H34djfr1+PjpAJlAMO20/P6zyetasc4fp4pU7QYWfFkfZgTi1GPd4Pqp1L1XI0Pq5Jbfq9aDSPV42U5PgzMr8Bz2vGk4uXYUU+Pw3IymbwZTUeu7w+R/l7VG6UtarUcex50IoyPLjv+si0ehfUKYzpHDrdBF31Zbd3VfDHSYfRB85tuvq1aKe+rnwJuarh6qu0ZrPMM4v4Gc1Py7jLP1kF+64SeBwMBli9RVim55Hpg8T8) to test with. Notice the line clamps fine, but if you change the tesselate in the KML doc to `<tesselate>0</tesselate>` you'll see the line doesn't clamp and, in master, no warning or anything is shown.

We could also document or warn about the case where a line that "can be extruded" are also not clamped, so it looks like the line just can't have an altitude mode of `absolute`, `relativeToGround`, or `relativeToSeaFloor`.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/tesselate-warning/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
I'm not sure this warning makes sense.  It's working exactly as expected by the spec, isn't it? If the behavior is different than Google Earth, we should fix that, but I don't think it is in this case.

**Comment by OmarShehata** [comment]
> It's working exactly as expected by the spec, isn't it? 

I have limited experience here, but I don't think it is. All I can find [in the spec](https://developers.google.com/kml/documentation/kmlreference#elements-specific-to-linearring) is that tesselate won't work unless altitudeMode is clamp, not the other way around:

> To enable tessellation, the value for <altitudeMode> must be clampToGround or clampToSeaFloor.  

I also just tested these two KML files in Google Earth, one has tesselate on and one has it off, both are set to clamp. Both do clamp in Earth but only the tesselated one clamps in CesiumJS. So it sounds like we should be changing the behavior here? 

[two_kml_lines.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/3911497/two_kml_lines.zip)

I actually didn't realize that `clampToGround` inside the KML file meant the same thing as the `clampToGround` option you pass in to `KMLDataSource.load` (I thought the KML value just pushed all heights down instead of actually draping the geometry). Why do we have this option instead of just using the clamped value defined for each KML element?

**Comment by mramato** [comment]
> Why do we have this option instead of just using the clamped value defined for each KML element?

Because there are too many caveats for us to just always use GroundPrimitive.  Some of them are:

1. `depthTestAgainstTerrain` is required to be true for GroundPrimitive  to work properly.
2. `depthTestAgainstTerrain` is required to be false for Primitive to work properly when draped on the ellipsoid.
3. GroundPrimitive outlines don't work
4. GroundPrimitive is considerably slower than Primitive.

It used to be worse and the goal is to do what you suggest, but we have a while to go.  Some of this is captured in https://github.com/AnalyticalGraphicsInc/cesium/issues/5942 (since the real goal is terrain on by default)

**Comment by OmarShehata** [comment]
> Because there are too many caveats for us to just always use GroundPrimitive

That's fair, thanks for the explanation.

> It's working exactly as expected by the spec, isn't it? If the behavior is different than Google Earth, we should fix that, but I don't think it is in this case.

The behavior is indeed different from Google Earth here, which can be verified with the two KMLs I posted in https://github.com/AnalyticalGraphicsInc/cesium/pull/8428#issuecomment-560399926. It sounds to me like we should have CesiumJS always clamp regardless of whether tesselate is true or false, which would be a breaking change, but would match the behavior of Google Earth.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@OmarShehata what's the status of this PR?

**Comment by OmarShehata** [comment]
Thanks for the bump @hpinkos . So I took another look here, I think I see why CesiumJS does not clamp lines that have tessellate set to false. We have no way to clamp something without tesselating. 

In GE the untesselated clamped line will actually like clip through the terrain if there's not enough points originally. Furthermore, CesiumJS has no way to set a polyline's positions to be "relative to ground", so that behavior is different in GE vs CesiumJS too.

So if we just ignore the tesselate flag and clamp anyway that's technically incorrect. I think the warning here is the right behavior. 

I just pushed a fix for the lint error. Let me know what you or @mramato think of this approach.

**Comment by hpinkos** [comment]
@OmarShehata something weird happened with the commits in this branch.  Can you try resetting it or merging in master?

**Comment by OmarShehata** [comment]
@hpinkos sorry about that, not sure how that happened. Fixed now.

**Comment by hpinkos** [comment]
@mramato could you give this one a quick look?

**Comment by mramato** [comment]
While there's obviously room for improvement all around, the warning about current behavior looks fine to me.  Thanks @OmarShehata 

If you think it's worth it, please write up an issue for us to be able to match Google Earth, either exactly or in a way that makes more sense.

**Comment by OmarShehata** [comment]
It just came up on the forum again so I opened an issue to document my notes on this consider revisiting it: https://github.com/CesiumGS/cesium/issues/8760.

**Pull request merged**
