### PR TITLE
Fix tile refinement when leaf is empty

### PR DESCRIPTION
**Pull request by lilleyse**
We got a support issue about a tileset that doesn't refine property when `skipLevelOfDetail` is false, which is the default since CesiumJS 1.67. The tileset has empty leaf tiles which exposed an edge case in `executeEmptyTraversal` in `Cesium3DTilesetTraversal` in which a tile with empty leaf descendants would not refine. The fix is to refine even if the tile would refine to empty leaf tiles. Note that this only applies to leaf tiles - if there's a tile chain that consists of a content tile, an empty tile, and a content tile, it will wait for the final content tile to load before refining the top-level content tile, which is the main purpose of `executeEmptyTraversal`- to prevent holes from appearing while tiles stream in.

Technically this fix could lead to situations where the parent will refine and there will be holes wherever there's empty leaf tiles, but I think that's acceptable and in the spirit of how the tileset is constructed.

[Local sandcastle with the fix](http://localhost:8080/Apps/Sandcastle/index.html#c=bZLbjtowEEB/xcoTK1ETblmxZVEpFGQEiRYCS1BeEscUgy9ZOxdItf/eBKi0bffJmplzPPKMs0CBjJKcKPAMBMnBiGiacri55mq+ga/xSIokoIIo33j46gtfZKWXUEY0Sf4Wb0d77N6KtV++ACBV7OkPgKRYEi1ThQncK8mHusRQVGs2Hx97nTq4CgAEuOysXXki4gn4BrnMDuEUU4fO0LpATZsijcSyi0fIQqd4uxnNerCE3qLpqYRQvuNLarfWZ2dlnnfHA5u7L0177CWeu+TexTSdqdd2XJwvXl86duHR+WgW78rLnFVOccvO8HRToGMcIj4pcNWMR0fETH2NWxsTX5D1Wvw42wXu2pMqzw5R6S/cdXdRLHJn7LXtrQkt8+07U9za9lIUBvtOYG3RdPllf7CGZncSknZJZkOvGDsL36ie/v5Q98X7fcrXLUCNiSAwVpTThGZEwyCKavfpV+AdK6TkrvxY8IVRN/o6uTAyuI0VgG+Ux1Il1U5qEDYSwmMWJEQ3whSfSAKx1pVaof3GR7Uf0QzQ6PmTPwEwC7QuK/uUsRUtiG8M+o2S/09lMoio+OlkRLHgUmGH5mB+S0II+40y/NxMpGRhoP65+Tc)
[Hosted sancastle](https://sandcastle.cesium.com/#c=bZLbjtowEEB/xcoTK1ETblmxZVEpFGQEiRYCS1BeEscUgy9ZOxdItf/eBKi0bffJmplzPPKMs0CBjJKcKPAMBMnBiGiacri55mq+ga/xSIokoIIo33j46gtfZKWXUEY0Sf4Wb0d77N6KtV++ACBV7OkPgKRYEi1ThQncK8mHusRQVGs2Hx97nTq4CgAEuOysXXki4gn4BrnMDuEUU4fO0LpATZsijcSyi0fIQqd4uxnNerCE3qLpqYRQvuNLarfWZ2dlnnfHA5u7L0177CWeu+TexTSdqdd2XJwvXl86duHR+WgW78rLnFVOccvO8HRToGMcIj4pcNWMR0fETH2NWxsTX5D1Wvw42wXu2pMqzw5R6S/cdXdRLHJn7LXtrQkt8+07U9za9lIUBvtOYG3RdPllf7CGZncSknZJZkOvGDsL36ie/v5Q98X7fcrXLUCNiSAwVpTThGZEwyCKavfpV+AdK6TkrvxY8IVRN/o6uTAyuI0VgG+Ux1Il1U5qEDYSwmMWJEQ3whSfSAKx1pVaof3GR7Uf0QzQ6PmTPwEwC7QuK/uUsRUtiG8M+o2S/09lMoio+OlkRLHgUmGH5mB+S0II+40y/NxMpGRhoP65+Tc)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-empty-traversal/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Forum user confirmed this branch fixes their 3D Tileset generated by Context Capture: https://community.cesium.com/t/3dtiles-are-only-partially-displayed-with-skiplevelofdetail-disabled/10066/5?u=omar

**Comment by mramato** [comment]
@loshjawrence Can you please take a look at this?

**Comment by loshjawrence** [comment]
Looks ok, waiting for ci to pass.

**Pull request merged**
