### PR TITLE
Change "var" to "let"/"const" ES6 syntax

### PR DESCRIPTION
**Pull request by ggetz**
Part of https://github.com/CesiumGS/cesium/issues/9718

Now that IE support has been dropped, there's nothing holding us back from using ES6 features. This PR focuses on moving to `let` and `const` syntax so that it can be used across the board going forward.

The primary change here was to enable `no-var` and `prefer-const` error checking in eslint, and fixing those errors. I also updated the Coding Guide to reflect the technicality of scoping, and adding a bullet about why `const` is preferred when possible.

Note that by turning on the above two rules, I had to disable `es/no-block-scoped-variables` for `Source` and `Spec` modules as Cesium makes use of may non-function scoped variables such as scratch variables. I believe this is safe to disable as these variables are all module-scoped. I also had to bump `ecmaVersion` for `Apps` to 2015/ES6 in order to support `let`/`const` usage in Sandcastle and other demos.

For ease of review, the primary changes were made in these two commits:
* [Coding Guide updates](https://github.com/CesiumGS/cesium/commit/7711d2c50db16b2f3f87d88ff7eabe69e9b82e81)
* [eslint config changes](https://github.com/CesiumGS/cesium/commit/3de446615cc0506818646e3df3334f0fdb426c53)

And all of the corresponding fixes were made in [this commit](https://github.com/CesiumGS/cesium/commit/8143df4436b79260e9861f63c6ac134d7910a818).

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ggetz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/let-const/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
> Will there be a way to easily update open branches? I recall when Prettier was first added, there were tags before and after the change

The commits here are split up such that https://github.com/CesiumGS/cesium/pull/10026/commits/3de446615cc0506818646e3df3334f0fdb426c53 contains the configuration changes but no fixes, and https://github.com/CesiumGS/cesium/pull/10026/commits/8143df4436b79260e9861f63c6ac134d7910a818 contains all the fixes. We could tag these commits and be able to follow a similar process as https://community.cesium.com/t/cesiumjs-source-code-is-now-formatted-with-prettier/9362, substituting `npm run eslint -- --fix` for `npm run prettier`. The main difference is that we can't fully automate the fix step-- eslint is able to detect and fix most occurrences of `var`, but not all of them. So an author may need to do some manually fixes.

**Comment by mramato** [comment]
Doesn't have to be this PR, but the `disable prefer-const` in `Particle System Weather.html` is only needed there because the code itself is not well laid out and the example should be cleaned up so that it flows better. I would just write up a clean-up issue and it's probably a "good first issue" too.

**Comment by mramato** [comment]
Where we actually need it, we should use `eslint-disable-next-line prefer-const` to disable the next problematic line, rather than disabling eslint completely and needing to use `eslint-enable` on a separate line.

**Comment by mramato** [comment]
While we probably want to take a hard look at Cesium's eslint rules in our new post-IE11 world, I think that is outside the scope of this PR and those few comments are the only ones I had.

I haven't actually run this yet but will do so once `main` is merged in and then I'm happy to merge assuming no runtime problems pop up.

**Comment by ggetz** [comment]
> Where we actually need it, we should use eslint-disable-next-line prefer-const to disable the next problematic line, rather than disabling eslint completely and needing to use eslint-enable on a separate line.

I believe the only places I've used it are in Sandcastle examples. There only there for the exact reason you mention above with the code needing cleanup to have a better flow. I added them to be scoped to the entire example so they don't show up in the Sandcastle code itself. But if we're OK with that, happy to change it to what you suggest here.

**Comment by mramato** [comment]
There was a spot in `Camera.js` I noticed (just search for prefer-const), the Sandcastle can probably stay for now since we need to clean it up anyway.

**Comment by ggetz** [comment]
@mramato `main` is merged in and this is ready for another look.

**Comment by mramato** [comment]
It's the beginning of a whole new era.

**Pull request merged**
