### PR TITLE
#9952 refactor specs to not rely on Cesium Ion

### PR DESCRIPTION
**Pull request by TheMagicNacho**
This PR addresses issue https://github.com/CesiumGS/cesium/issues/9952 requesting tests on the cesium.com branch be able to run 'offline'.
I originally started working on this with pull request #https://github.com/CesiumGS/cesium/pull/10099, but was unable to complete the requested changes before the PR was closed.

I have since addressed the concerns @ggetz mentioned in the previous thread, and created a new thread and new branch.

Current issue: I can't mock the functions in Specs/Core/sampleTerrainSpec.js
If someone has access to the terrain binaries that match the requirements for the tested methods, it would be greatly appreciated.

EDIT:  Based on previously closed PRs. Had to close because Github interface wont let me adjust source and targets for PRs.
https://github.com/CesiumGS/cesium/pull/10357 
https://github.com/CesiumGS/cesium/pull/10380

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @TheMagicNacho!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/9952-offline-test/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/CesiumGS/cesium/blob/main/LICENSE.md) and that its license information is up to date with this new version.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks @TheMagicNacho. There are what looks like a few extra file changes here:

* [Source/ThirdParty/when.js](https://github.com/CesiumGS/cesium/pull/10389/files#diff-92c3761b1cbdc76bb81c66eab8db0177dce0eea58ae6ef158fdbb218b5d64b82)
* [Specs/.gitignore](https://github.com/CesiumGS/cesium/pull/10389/files#diff-760b84132065f3094b1b9acbd1995c3d536fab6102d83c0c620bc17bbb3039e2)
* [package.json](https://github.com/CesiumGS/cesium/pull/10389/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)

Are these here for a reason?

**Comment by ggetz** [comment]
Thanks @TheMagicNacho! Something is still a bit fishy with the git history here. If you look at the Files Changed, you'll see many changes that have recently gone into main in other PRs. They should not be shown in the code diff here. For instance, see CHANGES.md.

**Comment by TheMagicNacho** [comment]
@ggetz thanks for the catch. I'll try to look over it this week and figure out what's causing the issue. My assumption is that between rebasing and switching root branches, there are some artifacts created through git. I appreciate your help.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @TheMagicNacho! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @TheMagicNacho! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by ggetz** [comment]
Thanks for the interest here @TheMagicNacho. I'm going to go ahead and close this PR due to inactivity, but happy to discuss further if you want to come back to it.

**Pull request closed without merging**
