### PR TITLE
`ModelExperimental`: fix show behavior after tileset starts hidden

### PR DESCRIPTION
**Pull request by ptrgags**
If a tileset started with `show: false` (but `preloadWhenHidden: true`), and then later the tileset was toggled on, `ModelExperimental` would stay hidden. 

This was due to a line that set `model.show = tileset.show` in the constructor. Thus, the model was being hidden from the start, but nothing set it visible again when `tileset.show` was set to true.

[Sandcastle for testing](http://localhost:8080/Apps/Sandcastle/index.html#c=dVJNb9swDP0rgneoDQRyhhXFkLrBtm6HAi1aLMZ28UWR6FQYLQaS7PQD/e+l7DRot04XWXzvkY+kNbkQxWBhB16cCQc7cQ7B9p38NcbyJtPj+5xcVNaBb7KZeGycEBG858iNp8Ea8IsXofagIvwmj6aeKHkxa9xTcdq4xumxYLQIAeLbitP16Xs9gflYpSzBqTXCFRnAH3db8LYDtoILEX0Ps8TpPR6qX5D7CYF6r0G2nrqvgVNdmPx4/vnkpBjp4ZZ2C9EqDHCwtTckQ7xH+L+tVYInY5qQuGmeT/rIjz607ZzP8fyoaLJD3mmyMmhwILfs3UY7QJDKmHxfMxH3tAeirqbXQONWyhmtQkRIopoI18p/62Mkx8upabNhw6PttJm2dzpahor9kl764p65rTSy09FcNsuqUbVMtHS+2G5LPqZp5lKWEbot8iJDue71H06hQ0iOErUqX0srYwdhzdk7v4rQqEJgpO0RV/aBPS6rkvn/SJGUsW5zPYBHdZ9otx+Xl1NQSlmV/HxfGaeR/JX5GQ)

Ah I'm getting ahead of myself, I should make a unit test for `ModelExperimental3DTileContent`

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-model-experimental-show/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ptrgags** [comment]
@j9liu this is now ready for review!

**Comment by j9liu** [comment]
@ptrgags just some comments about unit tests, since the expected behavior isn't immediately obvious from a glance.

**Comment by ptrgags** [comment]
@j9liu updated!

**Review by j9liu — COMMENTED** [review]
@ptrgags looks good to me, merging now!

**Pull request merged**
