### PR TITLE
Fix crashes due to shared PolylineCollection among all CustomDataSources #7758 #9154

### PR DESCRIPTION
**Pull request by rropp5**
PolylineCollections are destroyed by the PolylineGeometryUpdater but are still available on the Scene and cause Cesium to stop rendering when they are accessed.

This commit ensures the destroyed PolylineCollections are removed from the Scene in the destroy function of PolylineGeometryUpdater so they are not evaluated in the next render cycle of the Scene.

This resolves the crashes reported under #7758 and #9154.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @rropp5! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/rropp5/cesium/blob/main/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Hi @rropp5. We'll need a signed Contributor License Agreement (CLA) to review this PR. Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) and comment back here to let us know to check this!

**Comment by rropp5** [comment]
@ggetz I just submitted. Thanks!

**Comment by rropp5** [comment]
My second commit addresses a case that I had fixed locally and neglected to push in the original commit.

**Comment by rropp5** [comment]
@ggetz Is there anything else I should do to make this PR as smooth as possible? Thanks!

**Comment by ggetz** [comment]
Apologies for the delay @rropp5! 

Please sync the latest upstream code and update `CHANGES.md` with a summary of your fix.

**Comment by rropp5** [comment]
@ggetz Apologies for the delay but I just updated the CHANGES.md. Thanks!

**Comment by ggetz** [comment]
Thank @rropp5! While I think this is a good change, I'm not sure it fixes https://github.com/CesiumGS/cesium/issues/7758 and https://github.com/CesiumGS/cesium/issues/9154. I'm able to reproduce errors in the Sandcastle examples in both of those issues.

**Comment by rropp5** [comment]
@ggetz Oh bummer, this was causing a crash in my system that looked a lot like the problems in those issues.

It resolved the crashes I was personally experiencing so i thought it covered those sandcastles as well. I don't have the best environment setup to test sandcastles but I'll have to figure that out moving forward.

**Comment by rropp5** [comment]
@ggetz I was able to find the crux of the issue this evening: each CustomDataSource was sharing a single PolylineCollection instance. This created a lot of different cases that would cause the crashes reported under #7758 and #9154.

I've updated the PolylineGeometryUpdater to uniquely identify each PolylineCollection for each CustomDataSource and this does fix #7758 and #9154 for me locally.

Additionally, after thinking about it, I decided to rollback my earlier changes locally to see if they were still necessary and it turns out they aren't. In my opinion, my most recent commit (b7928c9) is the most correct solution so I'm going to revert the earlier commits. Please take a look and let me know if you agree!

If you think there's a good reason to keep some of those changes, I'm happy to discuss. Thanks for the help.

**Comment by romejoe** [comment]
I'm not totally sure, but I think I ran into this problem last night as well, but using CZMLDataSources

**Comment by rropp5** [comment]
> I'm not totally sure, but I think I ran into this problem last night as well, but using CZMLDataSources

Given the nature of the fix, I think the problem is more specific to the PolylineGeometryUpdater and not so much the CustomDataSource. It just happens that most of the reported issues I found were linked to creating Polylines via the CustomDataSources.

**Comment by ggetz** [comment]
Thanks @rropp5! Sorry for the delay in review here. Happy to see you've identified a fix.

Would you mind updating your branch, and moving you entry in `CHANGES.md` to the February release?

**Comment by rropp5** [comment]
@ggetz done!

**Comment by ggetz** [comment]
Fantastic! Thanks for the fix @rropp5!

**Pull request merged**
