### PR TITLE
Switch to Node 12 for CI

### PR DESCRIPTION
**Pull request by mramato**
While we updated Cesium to work on 12, we never actually made CI use it. Traditionally we always use the active LTS for CI (which covers 12 until October when it becomes 14).

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @mramato!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/node-12/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
I expect some brokenness in our infrastructure, so I'll bump this when ready.

**Comment by mramato** [comment]
Okay, this is ready.  Confirmed manually that Node 10 also still works, but I expect most people are on 12 or 14 these days.

**Comment by lilleyse** [comment]
Do we still use appveyor? It's set to node 8.

https://github.com/CesiumGS/cesium/blob/master/.appveyor.yml#L7

**Comment by mramato** [comment]
We actually never re-enabled it when we switched to our own org.  It was being used to test IE11, but it was broken forever.  I'll just remove the file for now and we can always revisit in the future (maybe even via travis Windows support, since that was the main reason before)

**Pull request merged**
