### PR TITLE
Support cross-origin isolated

### PR DESCRIPTION
**Pull request by jiangheng90**
fix error when cesium run in cross-origin isolated environment
this pull request is relate to #10502. 
so when set server.cjs to cross-origin islate
```
res.header("Cross-Origin-Opener-Policy", "same-origin");
res.header("Cross-Origin-Embedder-Policy", "require-corp");
```
```BingMapsImageryProvider``` or some other request fetchJsonp will shutdown

when fix this you can use ```SharedArrayBuffer``` in you  ```globe```scope or ```DedicatedWorkerGlobalScope```

### CODE REVIEW

**Comment by ggetz** [comment]
Thanks @jiangheng90, can you please add your name to the [contributors](https://github.com/jiangheng90/cesium/blob/support-cross-origin-isolate/CONTRIBUTORS.md) file?

**Comment by jiangheng90** [comment]
> Thanks @jiangheng90, can you please add your name to the [contributors](https://github.com/jiangheng90/cesium/blob/support-cross-origin-isolate/CONTRIBUTORS.md) file?

done！

**Comment by jiangheng90** [comment]
> @jiangheng90 Can you add a bullet to `CHANGES.md` mentioning your fix?
Already done!

**Comment by jiangheng90** [comment]
> Awesome, thanks @jiangheng90! I can confirm that running Cesium in a cross-origin isolated environment was previously causing issues, and that is remedied in this PR.
> 
> One other issue that arises in this environment is that the Sandcastle favicons loaded from cesium.com are causing issues, but that's outside of the scope of this PR.
> 
> For anyone that's interested, [here's a video that explains the cross-origin isolated environment](https://www.youtube.com/watch?v=D5DLVo_TlEA) which I found helpful.

For issue in sandcastle, I have already solved by moving favorite icon in local folder. Do I need push it in this pr?
Also I make a entry in server.cjs to setup cross-origin islolated, can I add it in?

**Comment by ggetz** [comment]
Thanks @jiangheng90!

> For issue in sandcastle, I have already solved by moving favorite icon in local folder. Do I need push it in this pr?

Sure, you could do that in this PR.

> Also I make a entry in server.cjs to setup cross-origin islolated, can I add it in?

I would hold off on this for now. We probably want to update `server.js` to use https in the future, and would consider updates like this then.

**Comment by jiangheng90** [comment]
> Thanks @jiangheng90!
> 
> > For issue in sandcastle, I have already solved by moving favorite icon in local folder. Do I need push it in this pr?
> 
> Sure, you could do that in this PR.
> 
> > Also I make a entry in server.cjs to setup cross-origin islolated, can I add it in?
> 
> I would hold off on this for now. We probably want to [update `server.js` to use https](https://github.com/CesiumGS/cesium/issues/10531) in the future, and would consider updates like this then.
OK！I have remove the changes in server config

**Comment by jiangheng90** [comment]
I am not sure where the problem is， I think it maybe not caused by me

**Comment by jiangheng90** [comment]
@ggetz  I have move this to latest cesium to pass CI checks #10537

**Pull request closed without merging**
