### PR TITLE
Make fovy a read-and-write variable in PerspectiveFrustum

### PR DESCRIPTION
**Pull request by OHalford-Novetta**
To address this issue: https://community.cesium.com/t/fixed-zoom-level-for-different-screen-widths/10133/7

This change simply allows the user to directly edit the fovy for the perspective frustum. This personally has been useful in ensuring screen ratio is maintained when sharing screens across different ratios so one screen wasn't more/less "zoomed in" than another.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @OHalford-Novetta! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/OHalford-Novetta/cesium/blob/fovy/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fovy/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
@OHalford-Novetta can you share a Sandcastle showing how you use this to accomplish the consistent ratio across screens to help motivate this change?

**Comment by OHalford-Novetta** [comment]
@OmarShehata Sure thing. Can I apply branches to Sandcastle?

**Comment by OmarShehata** [comment]
@OHalford-Novetta you can run Sandcastle locally, and then share the `localhost:8080` link here, and anyone running this branch locally can open that to test it.

**Comment by OHalford-Novetta** [comment]
I'll have to come back to this later. Closing for now.

**Comment by OHalford-Novetta** [comment]
Reopening to come back to this. @OmarShehata There seems to be an issue with running Sandcastle locally. I assume I just have to `npm i; npm run start` in the cesium root directory, which worked initially, but now it refuses to connect to localhost.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OHalford-Novetta! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@OHalford-Novetta for running sandcastle locally, you also have to `npm run build`

**Comment by OHalford-Novetta** [comment]
@hpinkos It doesn't seem to work even after that. I've even removed the nodemodules directory and done a full `npm i && npm run build && npm run start` but no success.

**Comment by hpinkos** [comment]
@OHalford-Novetta what do you see when you go to `http://localhost:8080/Apps/Sandcastle/index.html`? Does it work in `master`?  It could be a problem with your branch.

**Comment by OHalford-Novetta** [comment]
I get a similar error when going to that url, both on my branch as well as on master.

**Comment by hpinkos** [comment]
@OHalford-Novetta what error do you see?

**Comment by OHalford-Novetta** [comment]
Just this from the website. This is from Chrome currently. I don't see anything in the console.
image

**Comment by hpinkos** [comment]
It looks like you didn't start the server.  Did you `npm start`?

**Comment by OHalford-Novetta** [comment]
I have 
image

**Comment by hpinkos** [comment]
Hmm, that's odd.  I'm really not quite sure why it wouldn't come up when you navigate to it.  I'm guessing you don't see anything at `http://localhost:8080` either, right?  I wonder if your computer has some sort of firewall set up

**Comment by OHalford-Novetta** [comment]
None that I know of. I did have it working before, but it seemed to be missing some of the source files. Now it's giving me nothing. I can try working on this on another network after the holidays.

**Comment by OHalford-Novetta** [comment]
@hpinkos I've done similar tests on different networks and have it still refuses to connect. It doesn't seem to be a firewall causing the issue.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OHalford-Novetta! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OHalford-Novetta! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OHalford-Novetta! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OHalford-Novetta! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OHalford-Novetta! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OHalford-Novetta! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by sanjeetsuhag** [comment]
@OHalford-Novetta I was able to run the following command to get Sandcastle working on your branch:

```bash
npm i; npm run build; npm start
```

Are you still running into the same issues?

**Comment by ggetz** [comment]
@OHalford-Novetta We're trying to be more responsive to PRs and keep our PR backlog tidy. Due to inactivity, I'm going to close this PR. But please feel free to re-open when you get the chance to work on this! Thanks for your patience!

**Pull request closed without merging**
