### PR TITLE
Fixes createFeatures not being called before getFeature in Vector3DTileContent

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
Fixes https://github.com/CesiumGS/cesium/issues/10814

In some cases, `getFeature` can be called before `update` is called, so this PR ensures that if features aren't created by the time `getFeature` is called, it should create them, similar to how it is done in `applyStyle` and `update`.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @sanjeetsuhag!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/vector-get-feature-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
@ErixenCruz Would you be able to confirm this fixes the error you saw?

**Comment by ErixenCruz** [comment]
@ggetz This fixes it thanks

**Comment by ggetz** [comment]
Thanks @sanjeetsuhag and @ErixenCruz!

**Pull request merged**
