### PR TITLE
Provide Hyperlink to Bing Maps ToU instead of Bing Maps top page

### PR DESCRIPTION
**Pull request by Lakshmi0710**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @Lakshmi0710! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/Lakshmi0710/cesium/blob/main/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks @Lakshmi0710! Can you please add an item to `CHANGES.md` that summarizes the update?

**Comment by Lakshmi0710** [comment]
@ggetz Thanks for pointing it out, I have added an item in CHANGES.md . Please check and review it.

**Comment by ggetz** [comment]
Looks good, thanks @Lakshmi0710!

**Pull request merged**
