### PR TITLE
SDF Label process tuning

### PR DESCRIPTION
**Pull request by imdaddyjnj**
I think...
"CanvasRenderingContext2D.getImageData" is too expensive.
I changed only small amount of code. It reduces 1 CanvasRenderingContext2D.getImageData call.
That's all thanks.

[ADD] measureText code tuning
Calculate leading only when more than 1 character. 
The leading calculation in measureText is extremely slow implementation(DOM create/innerHTML/append/remove/...) .
Currently measureText is called with only 1 character - for "SDF", so, precise leading is not necessary in that case.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @imdaddyjnj! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/imdaddyjnj/cesium/blob/master/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/CesiumGS/cesium/blob/master/LICENSE.md) and that its license information is up to date with this new version.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks for the PR @imdaddyjnj!  Can you fill out a CLA before we review this?  See instructions here: https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla

**Comment by imdaddyjnj** [comment]
signed CLA

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @imdaddyjnj! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @imdaddyjnj! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @imdaddyjnj! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @imdaddyjnj! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @imdaddyjnj! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Review by ebogo1 — COMMENTED** [review]
Thanks @imdaddyjnj! 

It's been a while - a few updates have happened in CesiumJS. 

1. For `bitmap-sdf`, we started using their [npm module](https://www.npmjs.com/package/bitmap-sdf) and deleted the code from our repo. Because of this, we can't accept this change into CesiumJS, but it looks like your fix might still be helpful in the [bitmap-sdf repo](https://github.com/dy/bitmap-sdf/) - keep us posted if you get a chance to open a PR there!
2. We got rid of the `measureText` file and wrote a similar function here - https://github.com/CesiumGS/cesium/blob/86ed97487ef9960fc709cc0c21eb9e91c2d687b5/Source/Core/writeTextToCanvas.js#L6 - we no longer check for text leading.

**Pull request closed without merging**
