### PR TITLE
Add early return when viewRefreshMode==onRegion

### PR DESCRIPTION
**Pull request by robert-irving-snc**
Processing a network link with onRegion refresh mode may cause Cesium to attempt numerous resource requests, instead of only the resources in the current view.

Resolves https://github.com/CesiumGS/cesium/issues/10774

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @robert-irving-snc! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/robert-irving-snc/cesium/blob/kml-viewRefresh-onRegion-fix/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/kml-viewRefresh-onRegion-fix/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Thanks for submitting your fix @robert-irving-snc!

1. There is a failing unit test for `NetworkLink with a viewRefreshMode=onRegion shows warning` that will need to be fixed before we can merged. Would you be able to take a look?
2. Please update `CHANGES.md` with a line about the change.

**Comment by robert-irving-snc** [comment]
Think I have everything passing now @ggetz please let me know if there's anything else that needs to be done to get this merged in.

Thanks!

**Comment by ggetz** [comment]
Looks good! Thanks again @robert-irving-snc!

**Pull request merged**
