### PR TITLE
Fix scaling of czm_normal

### PR DESCRIPTION
**Pull request by jjhembd**
Normals should be transformed by the inverse transpose of the model-view matrix. See [lighthouse3d.com](https://www.lighthouse3d.com/tutorials/glsl-12-tutorial/the-normal-matrix/) and Jason McKesson's [Learning Modern 3D Graphics Programming](https://paroj.github.io/gltut/Illumination/Tut09%20Normal%20Transformation.html).

The automatic uniform `czm_normal`, as computed in `UniformState`, is currently derived from the transpose of the _rotation component_ of the inverse model-view matrix. This approach is only valid when the model-view matrix has uniform scale.

I think `UniformState` was actually correct before #8182. In that PR, we renamed `Matrix4.getRotation` as`Matrix4.getMatrix3` to [better describe what it was actually doing](https://github.com/CesiumGS/cesium/issues/7398#issuecomment-445862147). But then in `UniformState`, we mistakenly [replaced `Matrix4.getRotation` with a `Matrix4.getMatrix3` _followed by_ `Matrix3.getRotation`](https://github.com/CesiumGS/cesium/pull/8182/files#diff-7c7edcf13d6add47de5007ba19ffd488b4ae5320268c6369a75aaee51045b833R1317-R1318).

This PR removes the spurious `Matrix3.getRotation` call.

One caution: ever since #8182, `czm_normal` has been unitary. This PR will leave a scale component in the matrix, so normals will need to be re-normalized after the transform.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @jjhembd!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-normal-scaling/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by jjhembd** [comment]
I pushed a similar fix for `czm_normal3D`.

I'm not sure yet what is the correct approach for `czm_inverseNormal` and `czm_inverseNormal3D`.

**Comment by lilleyse** [comment]
Excellent catch @jjhembd.

> I'm not sure yet what is the correct approach for `czm_inverseNormal` and `czm_inverseNormal3D`.

Shouldn't the `getRotation` calls be removed there too? Or is it more involved than that?

**Comment by jjhembd** [comment]
@lilleyse I think `czm_inverseNormal`, to fit the definition, should be the transpose of the model-view matrix. This would make it the true inverse of `czm_normal`, which is the transpose of the _inverse_ model-view matrix.

We were computing it as the rotation component of the inverse model-view matrix, without any transpose. This was actually valid after #8182 for model-view matrices with uniform scale, since the rotation component is orthogonal, and for orthogonal matrices the transpose and the inverse are equal.

To honor non-uniform scale throughout, I changed `czm_inverseNormal` to be the transpose of `czm_modelView`, and `czm_inverseNormal3D` to be the transpose of `czm_modelView3D`.

**Comment by lilleyse** [comment]
I ran the equations on godbolt just to confirm: https://godbolt.org/z/ar7z8dYa5. It all checks out. Thanks!

**Pull request merged**
