### PR TITLE
Added TrackingReferenceFrame.ENU

### LINKED ISSUE #12313: Tracked Entity Orientation Flip
### What happened?

We have been tracking #4647 for a few years now as we thought this was an issue related to ours and it sounded like it was resolved with #12230 last month so we thought we'd give it a try with the latest cesium `1.123` which includes it but our issue still persists.

The issue is when we track a path made by CZML the orientation seems to flip causing the screen to jitter (violently at times). Our data can get pretty noisy and I have attached a small sample of it in the sandcastle below.

Orientation at 19:30:48.576:
image

Orientation at 19:30:48.595:
image

Alternatively, is there any recommendations to how we could smooth it out so the while tracking the object the camera flip is not as violent?

### Reproduction steps

1. Load in a CZML path (preferably noisy, this occurs with the sample sandcastle CZML Path at rates > 3200x speed)
2. Track the object and preferably orientate a birds eye POV
3. Play the event and see the camera jitter and the landscape flip
...

### Sandcastle example

https://sandcastle.cesium.com/#c=rXppl6pItvZfyVWfqhfVAgEBwenqWhccEAcERURu9QdkEkUmQdR39X9/N5knTbOqT2d9uOfkcgiCvSP28Dx7h/h5dq5f/Pspffnny//+nr28/L/u5eUlCb69/P5TkPvNKczq33/65W04805hd6HvzmcvhlfvH1cuYXVO8qy7yPaYx7Cf5v7x27tUkJvVYXXx0m4eYhD6O8PCn8VK3zjmG096LMNiAbn0n69JPY7DEkfch2yQ3lQVLM9K3lb1XwQ+3XRq0jop0iSsvr2wzPfhf7++v71+MkHxvMn37a8SEOLVYfDy6XIQnv0qKerODu/afv/p1+K3z/NfAq/2fqWL3x43ehcvSb1dkib17f/CMp2WJ6OfQHWVdEZ/DMGcPL2lSRYumrp7+3QNLJunefWHsZeXKt55317+F2H8ywvzy8vrO7z865fnaf/+9C1/E9//b/KeRP1VeZsk6LaIn659zPv41L5NI4+BNPSCt3B5uP7lpa7A/O+jzMd4FZ7ztHl150PTu2xwVrrLvSp4Du6TF4ffPlYECQSe/vY6TBdZ/I+ddw4F/pfEVhbLlpmqcS7DP3213g/XMXzqdy9y1Je33Rc73kp8N9B3FG3jzOEDf4CvjdaO+MKSEHyeWigdmKxieqrE7Dg933FyvFrrA22s3HbILXbqWpbHBy+z9cweGcXowHHcZdlf8YmcDuvLer/WtNGkn/Dy+rjalpp5NFd5vM+Do732h8vlej1USRIn8mJxyPvzkT08D7R8iuToqHnTRSwstORcibzTHDzJIxK10+nKcYwmPBOM7vc2kvvybbMa6Et9K8/LtRYOw/7gSiyVD83G1IbTyViWh3Jyd/ujO72aK7Kxp4xBW2lneXyJZSXU57O+PJAt9yLPlduYbunSLFJf3vaHsq8wR2s/62vyWh4qwuE4PcG7CteCU9+15CmIVgezLZod5JFcy6qcRdTOkrV+QE1SUTaVXdof2rLXX8JCLXe7h/mxKE/vhp0XI3kUt7KyPK2IiWU9ruWBMrGRq8mzPifPB4uh3NxkOZ7D+DLR1oUsL0XQp2k3nZe1lQv3qiT1CVk1zXDhl7Ks8KedRpqViZfb0a7fZ68KGzizPZ/fj0dnejXR1pzsT0e5abOTq1pTRZfpmJAWvN1fjpbjOKYNKZzzi+osLvRcQIOU1EJFVPo2SbaNQWGfqvwhRMdixET1mJr1qbuay6KSKzVdaqkYL3MnbuIgCmdupRnmbC3ni8yzab2lxjwxhpv9cZa5KHSOWN9Pr8PJbusXThThrE1p2abZM+XwhDYilp+JyUQb3pztaKwYh7g93xlruvbvWJvs1ZmPc2lMz/wZTbcBc5sNV5sp3vTzNc8OV/4WD0/5/Q5BkSTr6Wrqr1PmIh35mpypdk5x97V8VnNKdprlzNsH29ZAq5tvbsaWzF98WTam4o6M11M5HsRqMuB9iaMpQtPrMJ6Yfdk9nla+KcvO0TzOUmt6vtPjPphlOe0r00pRVNpS1P5dVvZ3RQnuSp++xnq+7E/mVt/cK/3+aSWPx5N46t36ZpKo950cQHRd2KEc6HNl6Wme5ct806YbfnBg2wFd7PsTUZnObkrfXCo3Oba2q7GXyKMkSePDIY6d09bhNX+kKTBr0h9MEmW51I7NUl/H13VerLWRrY0jTfJjDe/Zq9oUQxEC7BZfbupl6F9TTb2tLW49mNmDxos5NV+qeXwx3bF5PeVkk08upl+ZnrFtUR5GZoliA+WEMonftot4q9yN4W4gN9ez3j9b8bnv6oebOEwq+VZd92Vrl+2g4TN2S6hr0JqreO3IfWs7DBgt3i6xshrt55uhuF1N43jcN5lhkE/09jjYj8b9yW1qlcOGmVT5kvLN7fagXffsXpv1jc0wJ9bsqojJ0BjqN3OVrOe3iXgy5ePpWoys1bCeqMwJrzTqeC7dM7NS8sORZJ6rNjflfloDAFQ3zTlmoTXAA+OoUuaepOdptpnIvmfxa0rL1+eiXO2zdLhYM9h009NgotjewlvXKM9tE/BH8sAg+zqdXtbbMB/el+zpkOnx1Z2shE2dF46lnmLHM4KiovZMsx8H6RIvUklxmPOlWFKJI8gGE7Stvt9vBld+n02V006V/a17TTl1Sm2t6dZl+LN7Zc1Wv4+r0yJ0Bzi92HZcQtlBRu542i/sabrybPWWX+zpqSzKKizj2iasM7M1qnBSXaqOrj1njUNpZuu0rO2yYE2Bne/WKCwWQjIuT2G+Y026GGOX3h7Vja/PW0YaFCM1Ptv04TLfxn00d89cfNY2Z73kXTa2nOGkGuvIuaJp1WzpJRKTOypLb4jNuz6ds+F9fVms3QMZ83h/pSZXxoqzbDoNHcIJU25vXaahVqjClrFmx6trX6uy8Jw0TarVtF6WTFRdLK8RvRAMyI4aNhNjEytXJs+cfjB2eXqhuFy2llKL8/xpcXV1w6rYKhFKT1jv8l09DESpKShhm1UYkhjPd0IUhjsuo/ZXaUaza3rDCQVtjwejWD237VGpz/P7PiZXy77u7m0wI9GO2KOB4+uyKdj7dKM6/Ha1bIIhySVbPay3xkHNVGcxP/KIU3e+d5jE2xNA9cwKC10sipW1O52m3la0BvX8Srj53ZvpbHFkT3fmyt5n2YkKdyy+RDVSvHCUn+syQY1qT87N0ivSrKmra7O3c7zx7K1tF8GZ8erMY1K2aupG8JeFmC6OjFBltZu14uBan0+o3PnueeFslbpp6hNC0WaUbfdBVpNN01KCdXF1qcmQTlvMeLCN3EF5DjZ7lvLF5W00KDaLWvDuxb0xOG4kTXbFDAXb+3VgoIFxqPfGbApqM3uxY5ggG6EQ+7xxT7RmsuJns1nhU7PivLvWnHYJl9PAsK9OOBKYyyY4iYtd26AcCXSjN7gQ88jPSMtkt1O4sfQ7Mzc0k1KWOBjSfUzZc/USVWNsmAyluKKTaTfpMMMjpwrCthZsrrwEe/HqU9IB3zJqTvH3luMOs3Bj03Od9LnbLJpZRL9kKTXiGJ3WaOlIcxXNmP0s7q8Vt11M4rWqbNqZSI0Lou2ohXGvdm7k3VDIKodpH5tLWznw0zpuHKVajfLb4mZWqzGH8WFx9HExADCImsOGkYM9PqmzluPnE34z3tuhavC4TUaxx1iqozvRkhvqd46xhOXEHXJFnc3XBFc3dqqvcqpMcGnoOdccVoJBto2bZnPWToLNMD2vri2eJWWjn/D5UtNEjBZjvuCSPqWLIwxoPmLb0Bsv2stqVFy9YrbXzovClS1tv1hMrNZcymWpePNJpFnBbbPoZ1l/7E8yLaGXeq1qaKj70z1ekGNcWk65Eicq0Z3j8Wot0tlig/f9sDjOrvPB+h6c7mU4KgqkqczNsEppvl2sjq5yNct8b7kL5FJFhk8uugnXdL+bUdeNMKtvJEzNaOKJC7OSbXcGwGmWu9we5Tl7y8fnU5DayKPv22y6cL0qSy666N/ut7oxdXy/ZDRdD8/ainenqNi6M/vGBJuFJ1Vqjs+H6zUMzlP+uh5NeXejlC1ptBJNT5xtCZfaxmETVcwpPLJVbIvKLZ8ptTmqhLa2+81mFIUXn6XYwGJjiFCK3Ualmi3P1Gh7mlZ7azfCvh1Jcc6ND6nKB5dbRbncZMWU3mXYbCzDrScnIdxB8YN3g8IrU8pzBideR0HJDAJpUy84Vjo6uxmO9KneiLHoAtcuaGOWENeLJvczIxrs6mgbyzWVmkisZ0G9GTuUKi7FfS1ejC0j6s5uI9452hInl7q2ZdvW2c3OdqN6QokGZwjCpGwyPoWLjscuds64vrbGSqaZsdYKiBWzNbvkVoa9XB2kbSUw/uJ6pSi64C7BjdH1mLUP7l3lE71djrOjEPkTjvbDgVV5QX4Vq8VwzFwlNN74wQwV/dNl6i2L2jpd6t02bQSLtBQT7Eouq8hSOkcD3DLGKMWri76+bTJP2M6sI4pud/4WpC4rRYmIOXWwyytXxMhYcCg3dhQlDMfWnjk6dAJIdBlcFo4x5QNjekPU2rLFvXMqieAgrgwWOaELw7JIKGazxquq1PfErAkrxIZoxwnLJtSJGEgzFpPljmbrTbiwuOAS6cKOjkYS7USjGvAuiaT7uRGR42diiYglXiNpOKjNIB1w28g22AvF6YcLN5bKdhzGRBr7S9pX91vDALJkD600ULYUUFyjDra7KjvE1MLKEoObSUJ0y0wiHe83gHVaSOhz04yu20t0OdiCFC0Y97DM3eiW4gW9c24pHVaycD1dENn1r3uBujnxfW6LjH251K0T+cGVu+QSMSxqSbQxyWl0wOfItphpJB6vJ+tIk6GMD3dand9nwblr9eIts19ZULOGCfRtWn8gywNMQ+kfL47Qx63h06DsusNFAb2iElyOKT1adm2jaE+Ww9E61Kthihot3azNKydlzrphTqgxd+622nm7YDadn2lbOZ7G5iHJy5G2V1bUfjo0C3MZ23KEGrw0j6qyXKfpcsxrQBXuWpmkQ9euccLUVjRe1ZUrRBmHZyITSBkQBHQnl0UYnDbRKUJAnu7RSZdVXUo2K5xcNrHLch9gL3YuZsT6+N7SNgmcsioXQmBOW6WKg41cnPs7xi5lH8nZoprbst5q5wGvzGJroRhbBbVQig/vskrJeik3vHt2t0njYLONSg3tL57epLI0Ee8zMyO5KFzWTQP46ozL1X3Me9qIsjaHTDmuxlTWVyKRFVYGOzU2C16eCGkdR9phuSGFtKZh9E5XN2FpoZM20Eece7iz0tbjVXZJT1ghiDcXM0CFkTr7eWC7xtqKr1F/w7aT2FlPCjO9RDG5n8mUVEzfy0+SOQ5rVdTVyGOH6UCx9ktnWY8C2tyzQtFMtRUXipSfKofgJh5n7I4r+eg+MU3VP+K7oO8kiJfmsEs3kcCPnfwi2ik95LfOxvcNSZYDIZCvVH6lN5Zc6fctWwu8wkRkygxuM6dZX5aqG/lFP2dth69joVVEYTNXmECeRRgJUS47xC/XeY0K1SAKmt6pYwVt9/awIgInBHuaKGGOgjCXJWtTiEIRCDFTSv5Ab6cXeUBkwg+jOJ0tlRDF1GQjR/5wJJCdISuLfi6ndKwZMp7LAj+yYzXT9waS0IarmFWosFs7nTjywVcM4rQ3c32Q5Gkr32NE0ZG5Oiv7fHJVZE+eedo9zFw1G0gs28piPBzIAzQarYp2cY8HYxdbIuWuUjVAgSA7cYKpUs6oBV4zxk6x2yk075w8bhQScVtVWQeZ31dzk58NJadWl+VUmmVBA6CuNUgxoA8SsLbdrUSzKFPRTKVtPvFv0q69H2Ojihb9A1Y5jtpjfkjHjCFXuN6XvFzEt2GsVz4SvU1re4Yls+aEVw6xpY4u+zq0eWYI98cXyxDL9OSWoyyVNgNqh4r8rBNuSEMGHxeHVKPXbHSM1luPLkKsDbnSNTbkMFqUyQ3KVK6QDYfhfVG+blf5YODLh6mFZvHMkQVtieacckkuWGoHVmyqljEmvBkQauxEYz9ft2d0nzPj+aFZG2FBXQ1kbIqsrVtGnZzTYKcUYWu2sK9dOLjV4piN/Q3mFqLcp2RumwkUvaFmgbTKNjKLB7K998l1iqxGlrbjqg/FLz/M4lGjXPmtF6tCeSE+pB9GRwW5NypkNVJ7a8/XbapRAgfkKqdJOynaK3HMy0iy1v3NXODrxNzvSjqfXyhRaUebApoUi1x2ttmkdNvK6h1qG2fNXpt1h53yam0vllPc32raP58OfM++l3ZHe72P08LwFi6i6BzWn44kfa+qw3PiZd2ZZI/55eX15e8svP3rT4eL7+/gteTtiPAhKSxyf/92jsuivzPk7wxvscw3pvv7dHz9pO/51PC/n2O/SCzhYU2ihDiWFxAjwBox5niBYXu8hCTCEiz98sIxiOcZ0uM5xIg8FsnzYekPlHCIsB9KRFACd4OYDyVY4npIRJgQVkTflSDcwyyDBVYUvlbBE/7tqPpNBd9jOFEgDC8J3GMfCKaJIkMw910DB84TWYbHgiDyX+sQJYE8dGCG6zESIrBkIn3Yioc18ywHZmG/K+FRjxckDizISl/qQAzHIvzQwZKeiHgiihJmxIcOsSd1XsHcwx8c1+2XcJzIsl8bC3E8J34oQUxPEAXQIBGC3pUgsSdyIExgBeljIywrsRxD+L+gAzPMW1i+bUToEcQyDPiEkIcOrgfCsCQwmP+uA7O9LqwQw6OvVUBQYebZVjxLJFHgGe5jG0xPkiQGTCiI79sQewLLwGpEIn6tA1z+ZCoMoYuIIHKSxD18LkB+CN0vJTwE6nd/8D0iQGixPOK/zo+P31nelKCewIuYYIF0v1y8KRGFHtdFtgTh8K6EwDywgIDxX9CBnxMdgxEkEUJGxAz72IfUEzgkYB6j9xTkBbBVl4Ec/3XscuQ5zTHPQbgQMB8Po086EJEwEVj2PT84GOJYLLEC+drnnPSc5xjBSBcrHAbRD1OhHjicg6gi76ErIEjLrvsBzV/HLo+eE52XMCS6iLEIUx+xSyCwOBGQmBUfscv0CMMRUQIffa0DPyc6L4E4IkABAmZ7OETkeqCWsJD7+F0H7oAXdwYTvnZ6B4rPiS51gYUATsgHmhAOQhVigfDkPbBE2DAWJdg4+Xojr3n+kYU83+Ek3Air5991SEIPCQAvcPVdhwB38gAmPObR12n4aqwnJVKP6fYhIPRIQ5HpIEbCEKuYeTcXWJBnEct2uMN9rYX/lOxdrCKEoUEF979rAZRhWQ6WTdB7smOpB9CLAHjEr5ME0vo51wFTO8QXAfMk6V0HEB8oRhyAGfsEWgi8BOBDvtQhfCJ1sB2kpsQA3kEP/LAWgD7hGYmRuEf8wlpYDJbi/4qOT5yOAbd5YO7XbTwSETgdEh5xAAzShw4gfgaoEElfx5bwidVf3c5gLHDcB/gSDDwFKxHBeR85AknJCjzL/xUdn1n9FccAJMAy6IFaBGBQAqABf3AfG2EB2mArX9tK/EzqfBeUkCSEwyL3lIbASQSsxX+EFZRcsFUw4NepLn7mdIHpIYBFXuCAgR46OqQFfzOcgD/SEDKJlzgIj691fOZ0ge9BNQWpDtTLP/kcyscuZbDwnOpdSQSZ9HUSip9ZnWcAxYgIFS8Ucw8lpAuELhu5hz/Ab+Af4GWI8q+VfKb1TokEXMoi4TlBoHYEiO+s/2ARYPYu1MBzX+ogn1md66IS/AlgyD8wi31lEfgPhfRDC2QNA/6AsggC8Aey/8Dm/GuhwgMk8uxDNgwCzncfP+hD6AFCEihLOPJD2Z9pHPFdcQ1bll7p9DtCAVQgCGKOwe+iITmhHQAShETEP5T9mb6hTIKsgr3wH8uGwpNAXS2JHHqAHwvFClgeuoEuO/6zaOkTaXegB8bu9ioI6GnZXfRDGoviR+UMdakE+Ail9w9l488J3GEnbASI+EM2J3ZdDZagJHjPYODbbiswyHM/NIn0maOhzmM74If+iH3EIpRIgP4SNEMIf9gEaJYFyT+wiPQhEuicEUlHKdJDJNzPvNXe/FOxBxo69wvCD0whvbLVU3piEcwMW4DG6oEzEM0ADFCbQaYIH6YAsocu4y0YfyD7M/8CAEoA49BdSSx+yIaaXOjcK3JPZoZsBVpg/8uyP9NudwuBags6Ev5B7Riaxs4mUMM9WlBoRwDiBeGttv/Psj/30JACkOjAe1LH2u+yhdfGGjII5L/30J25ofcE6V158QPZf6JZcCLkTMe0z7IBMSAkHkgFrS4EKOpqYBb9UPYf2PW1ixZZ6Acf/ZPY+QBuxWCqp3WLLDQ3XY7+2CZ/YFVotBkEucEzHyUI8IIkARYRln23N/TUUApBhAE5/tAmf+iRu/5BgPJSYHnmsW6AamiZIK/RI7yhNWdf+yq2a5t/IPozi0JGdCcVogglDPcQLUCgSp1fPszNQ8+AoPAkwg+D+w8NMe74ngC3I/YjuMXuPAIQqisw30RDo9nrzjPAEfiHjvxDIwxI9Fr6gvfFD9FiDyKtMzr5DquAMlA1QOBIHY79UPZnpuQgsDgW0Jgh4oexxV53KgGmJtz7sru+G9AV6pof4dMf214ohWEhEMSwmwcbiKTbPn6Haw46CeA+4GCISvzOwP/609OW//rH79nvmf/6GOolCduwevnnSxa2L/3wnDSnnv069vPvP/mv3/t5VntJFlbdWl7P2+qwqmDk2/sN1tv3XlTlp01epcH3gZ//9qqzewJv5t3Cykj8Y/cEaOSl5/D10nmfN2kgZ0n3uOS3l7pquvF//+1phd3jfKu8qfwQVum1XvK+6N7HlXPPC4Kfv6+mfz+lg8elXpp7wc/d07Z/e5P6/ea68mAxwTCrk/oGkj+E9cJuLAGhcVgrNy34+f2J1L/94+WnX3769Vzf0vC3d/v+T3Iq8qp+aar0516PrsNT0T12eqZ3DSioe/753Cnupv5KP9/6a5BcXpLgn//Bzi9+6p3PcCVq0nSV3MPff/rtVxrm/+nWbndJFi8uYZV6t27anv1t9jbY6/V+peHrf76zzvN051VPkt9m/H8

### Environment

Browser: Chrome Version 129.0.6668.89 (Official Build) (64-bit)
CesiumJS Version: 1.123
Operating System: Linux

### PR DESCRIPTION
**Pull request by jfayot**
# Description

Follows-up #12194 . 
Added TrackingReferenceFrame.ENU to allow tracking entities in their local East-North-Up reference frame. 

## Issue number and link

Fixes #12313 

## Testing plan

- Updated EntityViewSpec.js
- Updated Entity Tracking sandcastle
- Tested sandcastle provided in #12313 with entity's trackingReferenceFrame set to ENU.

# Author checklist

- [X] I have submitted a Contributor License Agreement
- [X] I have added my name to `CONTRIBUTORS.md`
- [X] I have updated `CHANGES.md` with a short summary of my change
- [X] I have added or updated unit tests to ensure consistent code coverage
- [X] I have updated the inline documentation, and included code examples where relevant
- [X] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
Thanks for the additional PR @jfayot! Glad to hear this is working for https://github.com/CesiumGS/cesium/issues/12313.

The code overall is looking great! Could we please note the additional fix in `CHANGES.md`? It night help give context to users with similar issues.

**Comment by jfayot** [comment]
@ggetz , I've updated the `CHANGES.md` file with the possible values that can take `Entity.trackingReferenceFrame`and a note on possible camera orientation flip when auto-detect algorithm is used.
That made me think that another tracking reference frame could be proposed: `VVLH`, which is only available through `AUTODETECT` right now.
What do you think?

**Comment by ggetz** [comment]
@jfayot That works! I think after that, all options are covered.

**Comment by jfayot** [comment]
@ggetz I realized that I got ahead of myself while proposing this `TrackingReferenceFrame.VVLH`: if `TrackingReferenceFrame.ENU` makes sense, it's because you can define ENU at any point whatever the dynamic of the entity is. However it goes differently for VVLH, this kind of reference frame cannot be defined at any condition! I guess this explains the reason for auto-detect: ENU acts as a fallback where VVLH cannot be defined.
But a pure VVLH makes no sense...

**Comment by ggetz** [comment]
Got it. The rest of the changes are all looking good. Thanks @jfayot!

**Review by ggetz — APPROVED** [review]

**Pull request merged**
