### PR TITLE
Implicit tiling bounding volumes fixes

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes a few minor issues with how bounding volumes are created in `Implicit3DTileContent` and defines a new priority order for bounding volume types.

> <ol>
> <li>Explicit min/max height
>   <ol>
>     <li>With explicit region</li>
>     <li>With implicit S2</li>
>     <li>With implicit region</li>
>   </ol>
> </li>
> <li>Explicit box</li>
> <li>Explicit region</li>
> <li>Explicit sphere</li>
> <li>Implicit S2</li>
> <li>Implicit box</li>
> <li>Implicit region</li>
> </ol>

Here "explicit" means tile metadata semantics like `TILE_BOUNDING_BOX` and "implicit" means implicitly derived from the root bounding volume. Note that "explicit S2" and "implicit sphere" are missing from the list because they don't exist as concepts. The priority order is generally based on what would create the best fit and aside from the special handling for min/max heights the priority is controlled by the order in [`Cesium3DTile.prototype.createBoundingVolume`](https://github.com/CesiumGS/cesium/blob/10112c84d7de58067b04ccb641772165af4ba81b/Source/Scene/Cesium3DTile.js#L1629-L1671).

The priority for content bounding volumes is similar:

> <ol>
> <li>Explicit min/max height
>   <ol>
>     <li>With explicit region</li>
>     <li>With tile bounding volume (S2 or region)</li>
>   </ol>
> </li>
> <li>Explicit box</li>
> <li>Explicit region</li>
> <li>Explicit sphere</li>
> <li>Tile bounding volume (when content.boundingVolume is undefined)</li>
> </ol>

Fixed a few small issues along the way:

* `CONTENT_MINIMUM_HEIGHT` and `CONTENT_MAXIMUM_HEIGHT` are no longer being ignored.
* `TILE_MINIMUM_HEIGHT` and `TILE_MAXIMUM_HEIGHT` can now apply to explicit bounding volumes
* Fixed a bug where the `combine` step was creating a bounding volume object with two different bounding volume types

I tested with [Alaska.zip](https://github.com/CesiumGS/cesium/files/7591469/Alaska.zip) which has a region as its root bounding volume and `TILE_MINIMUM_HEIGHT`, `TILE_MAXIMUM_HEIGHT`, and `TILE_BOUNDING_SPHERE` semantics. [Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bVJNc5swEP0rGk54hkgCg00cx9PUaaeHZtpJOjlxkWFjVAuJkYTTtNP/XgnR1nXDBbT7Pnaf2ILhQ4fffetB8w6kZeI9MDtoMBgk2wm4Uw2I0z66RlYPcFXJSh6ZRkcOz6BdVcIz2ga9x7EWV1E9nrfKEbkEXUUJ+lFJhPZC7WCFnpgwUMmfsz9qpgYJTiyo4vF4FVqWCzBg/3UKr/ntl9CMR/VBixWqotbafkWIUDUTrTJ2VVKaEWOZ5TW5BXOwqic3gpkDI5M4/mqUrKJppNEd925zbvnRRcKaJp6QYeTftAZ2w/6hVc9v1SAbLvePSgwdnGfl9Ox5Vlumrftich772S+yoswWixSXNM/ScpEti2Ssp2WZ0WKB50t6SemC5vlYLwqa5kWGl5kr5vl8Wcm/abbA/DDOkGI6xdhzW7euMtnfMdtiq+4dkEkTX1w65GyCaib3foeU0sAPgdSsA82wUOpwY+OwU3K60odg+9k73XuNeBokCe5JUJ55nyiJ1sa+CNj4bfzzhne90tbfYowxsdD1grmIyG6oDy7r2hhP9NA1OaWuG35EvLl+5bdDtbtm4zpPgxAP/DtU0WZNHP4/qlDjpJ+OoAV78bA23XwMRYzxmrjj60yrlNgxfab8Cw).

For this dataset make sure to also comment out these lines so that it's oriented correctly.

```js
  ModelExperimentalUtility.correctModelMatrix(
    modelMatrix,
    scene.upAxis,
    scene.forwardAxis
  );
```

# To do

* [x] Finish unit tests. See how easy it is to make samples with https://github.com/CesiumGS/3d-tiles-validator/tree/bounding-volume-semantics

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/implicit-tiling-bv-fixes/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Review by ptrgags — COMMENTED** [review]
@lilleyse so far the changes look good and existing sandcastles with implicit tiling (CDB Yemen, S2 base globe) are working fine. Though I see you still want to look into more unit tests and sample data.

**Comment by lilleyse** [comment]
@ptrgags unit tests added

**Comment by ptrgags** [comment]
@lilleyse this looks good, I just loaded the tilesets in CesiumJS to visually see that the content bounding volumes are smaller than the implicit tile bounding volumes. That all is working fine so I'm merging.

**Pull request merged**
