### PR TITLE
Fixed rendering issues related to environmentState.renderTranslucentDepthForPick.

### PR DESCRIPTION
**Pull request by ugnelis**
Solves #9824.

I have tested only cases related to transparent entities and point clouds with shading.

It is possible that this should also have to be fixed for the Cesium VR https://github.com/CesiumGS/cesium/blob/main/Source/Scene/Scene.js#L2925-L2927

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @ugnelis! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/ugnelis/cesium/blob/main/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by ugnelis** [comment]
**Update**: this fix brings other issues when `viewer.camera.switchToPerspectiveFrustum()` / `viewer.camera.switchToOrthographicFrustum()` is used. I believe the bug lays somewhere here https://github.com/CesiumGS/cesium/blob/ea7f73852361d695e007ec4e5811c43ee5db00e0/Source/Scene/Scene.js#L3391. Right now I am not able to solve this bug as I am not aware why `updateAndRenderPrimitives` is not included for `renderTranslucentDepthForPick = true` mode.

**Comment by lilleyse** [comment]
This seems like a good fix to me.

The reason why `updateAndRenderPrimitives` is not included for `renderTranslucentDepthForPick = true` is because `scene.render()` is expected to be called before `pickPosition` according to the documentation (https://cesium.com/learn/cesiumjs/ref-doc/Scene.html#pickTranslucentDepth). The idea is that the render would have already updated the primitives so we don't need to do it again, but this is a faulty assumption because primitives will push different commands depending whether it's the pick pass or render pass. I think that's why `pick` works but `render` doesn't in your workaround: https://github.com/CesiumGS/cesium/issues/9824#issuecomment-934318679.

@ugnelis can you restore your cesium fork? I was going to push to this branch but the remote is gone. My changes are here: https://github.com/CesiumGS/cesium/compare/pick-translucent-depth-fix?expand=1. 

> **Update**: this fix brings other issues when `viewer.camera.switchToPerspectiveFrustum()` / `viewer.camera.switchToOrthographicFrustum()` is used. 

I don't see this problem on my branch. Here's the sandcastle I've been using for testing: [Local sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=nVVRb+I4EP4rFrqHIHEmIQlJKa2upV1tdUitCnf3EunkJgNY69iR7VB1K/772XECCy0r7b0ksWe+mfnmGztbItGWwitIdIU4vKIZKFqX+O9mz8t6ebOeCa4J5SCz3gC9ZxwhDVKanScptrQAOemAuQSi4R8hWbF0Ll5/kPFd/zLjGXepsMqBA14z8QK4gEpvlqD0zdo4K92iTDkrwhRcnoAqmn9bSsIVq81a31m08dWyBpfBENKUgQJ9zMi9wrulM3oNi1qyfeUPgj+DErXMAa+kKG+UcXsovGAcjYI9hzY2rgTlesZEXSw2pKB8jYnWwGuiqeCHgs67wxvciRLmdL3RZn3E4YiwpCXVdAsKk6Lw2oCftDMnJUiCjdGK5/gVpq+UNzVNjppBpDZfhIeedUMoivwgiSI8jqIgisMgGrj90Sj24wBHgZ+kF0Hgx6PWEMUXcTTycZhESRpFYWi3+41RSGqU+Zj0KzTMn6jON8+CsTZ1bJKOkzBM/dgPL5I4aTP87uNRMh77SRCHaXiRpuPWMMajNDC1pEkc+b6fxl3qbsjMCGwIL9jpUC/McAJfVCSH+60p8atz8to25sRAlY3Rom0vH3hV65vckvE8sKg+urp2Z8AmKkWt4Eko2ureuBi53cZl51YdPD6Mc4f2jmL199gXVsM9Y7RSghaHACaPcWzH4t21hpsZmKCsd2sgCDqMObTO3FUx2X+1hr3rBLWREJJGLXpuanwcD1D36A86TGnOvqTkcKhmggmJb+d/3bc+u+bdKLUbnBNm+VYBnt9/Wf47mz/M/nSyLowoOVGagWW8FOs1g9taa9O4rCek3oi1JNWG5vaOau4O86q5ky7fQP4Nir6jR1foZAeh/RC4U/Rqp3QpHn+I+0XWStel55TZmaYp+Dn6CaSqILen9wS8H9afstKHi+7/kequH6XfGJy/DxfW7O2Vz61odoy2kEeeeYTeb++zx/nj867vBM96rZqf9eI0ac0LWJmfR/Er1KFglrK9E88y/pXLtUVeNtl7g960qe66o/wHLSszQ/aH4GE81FBWzMyyGr7UBqZxrpSjitB0+CN0WtAtosXVJ39KlDOilLGsasYW9Dtkvevp0Ph/gDLRlP24BcnIm3XbBNdzt4kxng7N8nOkFoK9EHkS+T8)

**Comment by ugnelis** [comment]
Hi @lilleyse, I have tried to restore my fork but I couldn't manage to do so successfully: it is missing some of my commits. Sorry about that. I suggest creating a new branch from this one where you can apply your changes

**Comment by lilleyse** [comment]
@ugnelis no problem, I opened a separate PR and included you in `CONTRIBUTORS.md`: https://github.com/CesiumGS/cesium/pull/9991

**Pull request closed without merging**
