### PR TITLE
Support for particle system scaling/sizing in world space

### PR DESCRIPTION
**Pull request by richard3d**
Allows particle system billboards to be sized in world space via `sizeInMeters` property that was added and cascaded to billboards during update/creation process.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @richard3d!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/particlesystem-worldspace-scaling/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
Thanks for the PR @richard3d!  We'll try to look at this in the next week or so

**Comment by richard3d** [comment]
Yikes! I just pushed a change to fix the merge conflict with `CONTRIBUTORS.md` can someone advise why my latest push caused AppVeyor to fail? I would really like to get this PR in :)

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
@richard3d the AppVeyor failure may have been a fluke. I would try resolving the merge conflict, merge in master and it'll re-run the CI.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@lilleyse can you review this?

**Comment by lilleyse** [comment]
@richard3d does Merijn Wijngaard also work at Prominent Edge and is he covered by your CLA? Could you add Merijn and yourself to the Corporate CLA section?

**Comment by lilleyse** [comment]
I pushed a few small tweaks in https://github.com/AnalyticalGraphicsInc/cesium/pull/7746/commits/e1907350369e6692440a8406224ae83bea0bf9af.

I'm noticing some strange behavior in one of the Sandcastle examples that uses particle bursts. `sizeInMeters` seems to be exposing some other bug where the particle bursts fill the whole screen. [Local sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=xVn/U9s6Ev9XPL0fcO6C840ESGnnWo7XcgMPjnB9P5TOjWKLRIMteSQ5Je8N//utJMuWY5OGR/LaoWBLq93VZ9faz9oLxL0Fwd8x9955FH/3TrEgWRJ80WP+XqhvTxmViFDM91pv7+gd7XQmWHpyjj2OaMQSj2bJFFQIjCPvnnEvZFQQITGVHscii6UI7miu+hLJeSCwvNFLf9UrJ7DQH7jKpyyjkfDYvccyUEySLEaSMOpJkuA7ugC/hURcgtu53n9nMUH0X0ji4J6zRF34akf6ot/tDdteH37gT2/UUqaMDpY2qkBRNMGwjUj42g6s6nfbLkSlsN+ynl+iB+yJjGMLKhEeMkhFsIoDPMp/AMPMB2HMwodAW7iFCXBFX6txCnrf1gRZWsix9DmxMOMcsN9Eo/4NoZjhEobTYiy4uLq6/t/k9ur6rdfpXDAAK98OptGKJoiQJGlMdCr1ap7PWRZHHyhJADAQkDzDbi6BqzFkmCeZG2yTBYUqKxX8zlhyy2xkFBQmAos8nS9ZhGOw8scd9eAfTogQoO9G2R57w6DbNhMzjhZELmGsW4wlBJzMkmtQTcIYX5B7taYX9O08elw/b9ZPUvUwqIludaGdOCgm9DYmIYpxRR4grg+mudkJ+T2fuKNPeu958B4owM0yGUiOwge/QMNmvGQsniIVo4iFWQJpEsywPIuxuvy4PI/8vVxEP+yrWlGaxsuPhEaEzkSpvW31lnEAdQDtNRNEh7JyvJzCLuAK0YFv/TLiV5zABaqv+E8GseMUxosVnBlBOFA4eayKm7FSe6KcfF7wwDd+32c01LZDlqSZxJflMt842Nap2rKZxbHMOM2dDxpWKel2o0Fl8akAKyES9ne5iZs6inDwihhthKzF6YeAztOVKvAZIxXnayLD+Q2LY8e8qErelv7c5OZ07j6D61ltu34BqfHiGQ/M0Y5nHGPhq2fWK3/BQmVN6QD/gipENXi0pjzthb9/UKjpBQdtF19XpwNlDUatsIYYONUuImDAcPKmGl2t4VkkwX67IU8qaZQy0Xt2sxa2/cNh0BseHh0Oet1R72B4PGp7g+Pg+PBo1B+Njga9/ujwyEYaNPY30zgaDEbHvcFx92A4NAqHg+Gwe3R8DJWzorDhQJigJI1xZE+La85SzOUyTx+7RldlLWmPfrVhJdMowVIt0F89k8B0XlD0PcFCLfPz/EMLRGI0JbEpDG6Sw7N8TgH+BYpPIbhY57T/9RkRq7A44kGbcdsdh5I61n/M4FPrW8vWC13Exp6jJuMEBvaCoAM/Zp9AQFBHi4qOceKSxA+3PAsfVu/3H5IwmMXTPccBW+3II47zmjI6yF3JxRRWv0C0x8+cM/u9bvkQ6mu7gyLW4+Iyn2HOOV/R+wUDXagWgiIZrI4WZLxDZHShw9GZja0JchFzEWKKy5DrW5uLtpgugasmiiqpySDlBB4zssjzwvHuurLABhg4zQw3xkUk7AH00ZmC3Cn2kD3AkscFmOo2uDj/9Pl2cvbh083Z2a/BdyLnH+J0juCYO2yVlKBx6W+fz2/PKkt0DBroRVGxg3K4zjdKKTtYaGumR+WChvm1xMlZWZ9ftWq5U82cnmjmWTUDVtYJXp75TfndL0lO4JKvttc8XuK+wjodTJ0JSwFh5Tm9xHByCJBV7LjQM824kGr0a/nYdjqKhQtsJr3vJI49FoZIqUVxvPTEkoaKTIccK/PI0/Q8VNkCqOD7ezi8SnUNKf5RKfb/UPwlp8w2CIp2qjuDpr7rPrXaL9DW61bVDV+pbsW7freib6D0GXXfClBjyC67fKTZdRE0VWBXkoFwMJqTFr/vPlwNxG28juUUC7M0gsCcQrCmcHzBIs2sP5mGRB1wZdXKu5RJyBHQirV8z6Farj4fKmEkC4oF2fMbBi2qHWXWW8gROHpRDJ55C8gOOGVUK48RmLQJ7hHqzTCDUxJ2E3oiRaFqZnWVqNb2NLA3BeepcwjKeIJiSP3iaG+vbNaSr/ravN1cflyq8wlxv7rQfTxtl/d3wKDJQF6sgkVeexr5jqoEpciqmrazvGRkTsWBooL/q0OuNJ0tAMEL/YYEEsqGzNeSKx1GtUYF1UbmR21KsTmI+IcwhG5a6qAiuvTCuerwhcoA3dDniW9YR6KVBY0uNPYqa1LedWKSQga55sg91B00Be6XG4MB58QVIN9yGVA5NTdU2/vHO9UFv20SSRUNXyfAgcVV559yblHvfKFLvpoKxezAW7fz3XPP871WILKpCDmZYt+oLMILj+0XFGe4sqE6uGXReKdmBf4lZkiWq0tPX+qoW6de7GiFMKl6uda7ptQ1B/S5LbjBo1FRaHzB0uXmS00d+FNWV5c+Y/VPRKKBJb02c5qI2bYTqIGivdrtBla4dbcdkrglmA273BG+23HUpcHbdrRsHl7rptOdbNtJ27u8+ky2jdFmDqqDkqVKu3pJ9jXXK/GjegGwZ7iklxdK24qDLFbvE0CicO0HZUKXz3fraapT1NreiiOTdI75bhwxqktHhmsdOWV0R3iAYuuE+/FJshugDogK/wA6h9Za5z6yx534Bnqta81svpe/TrG/K25+04k2QTSClk/GmlPemhfwl5hmfp5+bjF+035zIuQyxu/N2D9JkjIuvYzHfhB0wNE0Bs4hOtMsfMAyCIUomdvf7FcDZ5eqbZlx9YFm7PHZFPkH/bZn/3eDoyoTiBRXG3sH6aMzPGU8wnyfQzQy4U4+1QwTCvSyQkewAhnF+9BAzOgY2r8oinHd5r5kKbSEFbt2asqkVO+1+msMa56JKzu/Z1Tuf8dkNpdj2EMclYtPOhbjk4gsPBK9u3uz8g317o0XxkgImLnPYv3S7e7N+5MOyFeWwSGjnLyCjcZoqUTmvfcXZjAIgpMO3NZX5W6DuPHpRKpj8X3p/ImcsmhZGeDOnRmJ3iv+edKBi/pUdUSPmujIZYrBBa76CtglVEq4g9RV1+gRrvXLQbiDxyJVt3AJHRHanxKqfF+o43RceW8CbZwaNJ0TPI7a0F6xu+edUM+vsgTowt3wx5ZqOld2D7cKpx/hpsK5Fdz6BWqjTUBbeTW1Q9BcS1sC7RKaQkX8tpRwvQK6wSbQNb2x3CmCDQa3BSR6/JlANrzA3S2QdYNbzEjNnLd+Br4kJc2b6r8iF7WlLSbhz8TOfcv/V6TfNrGb6O+EutvYQfXdAD3nq9BOsSvtbAm5Mxr9TNyK72S7JSy5lS1hln8d2Api+30Xs/4mmOWv0HcLWW5kQ8ScW4cmw13Ooi3hvqP/Bw)

particle

**Comment by lilleyse** [comment]
> @richard3d does Merijn Wijngaard also work at Prominent Edge and is he covered by your CLA? Could you add Merijn and yourself to the Corporate CLA section?

Never mind, I think Merijn was accidentally added twice to `CONTRIBUTORS.md`. I've made the correction.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @richard3d! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
@richard3d can you address the comments from the review? https://github.com/AnalyticalGraphicsInc/cesium/pull/7746#issuecomment-532782087

**Comment by hpinkos** [comment]
@lilleyse @criyson opened the same change as this in https://github.com/CesiumGS/cesium/pull/8603.  Do you think we can get this one merged, or is the weirdness you saw when testing a showstopper?

**Comment by lilleyse** [comment]
> Do you think we can get this one merged, or is the weirdness you saw when testing a showstopper?

Whatever this was, I don't see it anymore. My theory is it was one of those bugs where hidden points/billboard would either take up the whole screen or stay in the center of the screen when hidden.

**Comment by lilleyse** [comment]
I updated `CHANGES.md` https://github.com/CesiumGS/cesium/pull/7746/commits/53400d843e6a43e488b1af7513dbf67e3678aa2e. Good to merge whenever CI passes.

**Comment by hpinkos** [comment]
Thanks @lilleyse!

And thanks @richard3d and @criyson!

**Pull request merged**
