### PR TITLE
work-around dimensionless SVG in Firefox

### LINKED ISSUE #9188: Dimensionless SVG does not render in Firefox
This issue seems specific to Firefox.  In Chromium this works fine.  My tests are on Linux but I have confirmation this issue exists on Windows and MacOS as well.

Paste this example into the Sandcastle at https://sandcastle.cesium.com/; note that the SVG referenced has no top-level `width` nor `height` attributes.
```javascript
var viewer = new Cesium.Viewer("cesiumContainer");
var collection = new Cesium.BillboardCollection();
viewer.scene.primitives.add(collection);
collection.add({
  position: Cesium.Cartesian3.fromDegrees(-75.59777, 40.03883),
  image: "https://raw.githubusercontent.com/lupomontero/psl/master/browserstack-logo.svg",
  width: 200,
  height: 200,
});
```

### PR DESCRIPTION
**Pull request by nmschulte**
Attempts to resolve #9188.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @nmschulte!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-firefox-dimensionless-svg-image/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by nmschulte** [comment]
Added unit tests.  Chromium was using a default dimension of 300x150 if there is no `viewBox`, so mirrored those defaults.  These default values affect the rasterizing/aliasing in the image, which is a potential issue with this work-around.  However, I think a blocky image is better than no image in these instances.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nmschulte! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by ggetz** [comment]
Hi @nmschulte, sorry for the delay in getting this reviewed. Was the work around in https://github.com/CesiumGS/cesium/issues/9188#issuecomment-720140897 enough for your use case? If not and you have the time to update this PR, let us know.

**Comment by nmschulte** [comment]
@ggetz I had developed a work-around for my use-case before ever distilling this information for the team and community to digest here.

There are still open questions in my response to the supposed work-around you reference; I don't think it is a general solution in line with the API CesiumJS is putting forward, no.  Combining my last remarks with my first, there is a solution to be had, the team just needs to review the situation and make a decision.  "Not a bug" would surely be a disappointing resolution in my opinion.

**Comment by ggetz** [comment]
I do see this is related to an open issue in Firefox-- https://bugzilla.mozilla.org/show_bug.cgi?id=700533-- And they seem hesitant to call this a straightforward defect, although they do admit that the behavior is different from Chrome and Edge. 

From a consistency standpoint at least, I think these changes here makes sense. If you don't mind updating your branch with the latest `main` and linking to the Firefox bug directly in your comment, then we can move forward with this. Thanks for your patience.

**Comment by ggetz** [comment]
Thanks @nmschulte !

**Pull request merged**
