### PR TITLE
add the option vertexShaderCommon to prepend the custom vertexshader …

### PR DESCRIPTION
**Pull request by mickae1**
When you want to set a custom shader, you have to include yourself all the content of the file PolylineCommon.glsl
Now with this option you can include it automatically when cesium is building the geometry.

By default the option is not activated and I've tested it with a developper tools in chrome.

It's very usefull because now I've only my code in the  custom vertex shader. 

Please review it, let me know if i've to change something.

Micka,

### CODE REVIEW

**Comment by mickae1** [comment]
> Thank you for the pull request, @mickae1! Welcome to the Cesium community!
> 
> In order for us to review your PR, please complete the following steps:
> 
> * [ ]  Send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA)
> * [ ]  Add yourself to the [contributors](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTORS.md) file
> 
> Review [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) to make sure your PR gets accepted quickly.

I've made what is needed : 

sign the CLA & edit the file CONTRIBUTORS.md

**Comment by ggetz** [comment]
Hi @mickae1, thank you for the proposal! We'll review this shortly.

**Comment by ggetz** [comment]
Thanks for the PR @mickae1! 

`PolylineCommon` is relatively small. Is there any reason not to omit the option and always prepend it?

**Comment by mickae1** [comment]
> Thanks for the PR @mickae1!
> 
> `PolylineCommon` is relatively small. Is there any reason not to omit the option and always prepend it?
@ggetz  
ok, I will do it

**Comment by mickae1** [comment]
@ggetz 

I check of what you said, PolylineCommon  is not that small, it's about 177 lines, which is tiresome to include in custom shader.

it's best for us ( in my opinion ), to see only our shader, and let cesium prepend whatever functions it need to make the shader work.

And it's what you actually do, the main function is transformed, you add other line in the shader before sending it to the opengl

**Pull request closed without merging**
