### PR TITLE
Fix for clipping and camera navigation issues below ellipsoid

### PR DESCRIPTION
**Pull request by chris-cooper**
After re-looking at https://github.com/CesiumGS/cesium/issues/9198 it seems to be related to `DepthPlane` usage in `Scene`.  It seems the `DepthPlane` is used for the following purpose:

image
https://github.com/CesiumGS/cesium/blob/master/Source/Scene/Scene.js#L3243-L3245

I tried a quick workaround to offset down by an arbitrary amount.  It seems to address the reported issue.

hack

Assuming this is a valid fix, how should it be implemented?

- Simple magic number (as shown in https://github.com/CesiumGS/cesium/commit/b96d673b8030cff6f8becc7dc6f48a15ac295568) Perhaps it should be -11000m to [cater for bathymetry](https://en.wikipedia.org/wiki/Mariana_Trench)?
- Viewer constructor options argument that is passed Viewer=>Scene=>DepthPlane
- Other

You should find the issues are improved or resolved running a local Cesium from this branch and the same sandcastle code from a local server:
[local sandcastle link](http://localhost:8080/Apps/Sandcastle/index.html#c=tVZtb9s2EP4rhLEP8uLSTtJgm+0Yc5Ki+6DMhuesKOKgpaWzRJQWBZJ2lgb+7zuJ1Gu8AN1WBJGp0z13z909pLRnihhQivFkruSeh6DIJbkGzXdbGihgBj5IJcKl9fG6o1WySvaI2nN4zJ0TeCwAf+Y2b9UJ8vtrmRgEgVp1euR5lZB2qmHb0Mud+BYEwoZkw4SG3MYSvmWGy6QyHjIulgXVASRAIyHXQENITbwEbaYRRtbGUUemObIsIOXJ1Y6LsF3EvLS7agOJUQhmMAp8mUTc7EJAzPkFffvT+dmo5YE0C4dTenHxy6AWZMu+wDznkkrNs3rI5cS1kiIcTaApC0MvbxchCdtiH1YdJItNtLYCOixX7sGaC7GWTIVD4uCEYNsijFAVSzdK4mSEVJ4rOL+hi9nHqX/l373rkbc/d6mRN8ywu4XvdXtFrD0owwMmZopHHNMXU2+Y6dVsuZzdlqAYeBSbBWxAQRJAifqtaafX/vR2/mk5+/R+Mbv7/cbCD3mYg51D0URsz3uQU2MjYC9jt5jYsjMvKYAKGXmf7bMh+eHZrg6fbTCsBjWgDaQaI5xlQ7KmEIRhaBrQwemoCIfDzZpUbQ3bs4/vfH/2gT5yE09FGjNvQC+6OWiD7c2i/YWQN6cj/B1fkvz3BLORvs3cfbZUbGZR01ZbbSeI/NFyG1mEvVpyiLxmyshIsTTmwRQF/4RB7osZFKRrPrkMbiBSANorM/faIn5jc/Zcjyst/PuQJ62QNuLD8bLmTuHZkI5VSbcs9YJs9DVCuGLJeU5nwUJcay+gdUJUODLZ2tHolgQaE/HxIMLcr2zRapNmh1a5S7N9Kp7sOVZ6VptXDxvl9SqPRx6aeEjOaiY8+kBxJoZWhuWTg1sduo3uNUqojqMXc3hVUsz8J0m1BVwKqWr9t0rq5Z74p5CvSIqZhqSOVPk9JJVd66nzHO5l0PRyM/uesqvx+J9k52h+lXK7lJ6jXzwkVXmH7GL/s79DfhK7Lmu2TQW4l/Wt1OYG8ONBQOi1vxHI/TcqpX0EdR/w/RZD4m12SZD1wbPJw3rA/HAuZFO8Ycgxx/vBg5t4XnHz9eQ5LYzcB8sq6fQ6Y22eBEyKfv7Kt6lUhuyU8CjtG8Ac2HrdX++CL2BooHXRzHG/Dh2HfE94eHnkg4sEgmmNTzY7If7gX1Ehk3Ef/V9AhURBJ9EM3+6CPWVu8enEt0ZK6biPt8eRRkqxZqoV+W8)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @chris-cooper!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/de-clip/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks for opening a PR Chris! There was some discussion here about pushing the depth plane down or other techniques that may be relevant here: https://github.com/CesiumGS/cesium/issues/7879

**Comment by chris-cooper** [comment]
Thanks @OmarShehata .  After looking at https://github.com/CesiumGS/cesium/pull/8398/files it looks like the default for `frameState.minimumTerrainHeight` could be set differently (e.g. an option argument for Scene) and then used by `DepthBuffer`.  I've tweaked this PR as an example.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by chris-cooper** [comment]
What would you like to do with this PR @OmarShehata ?

**Comment by grantis** [comment]
> What would you like to do with this PR @OmarShehata ?

Is this PR waiting on anything, this PR would possibly fix an issue we are having.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by grantis** [comment]
@OmarShehata @chris-cooper Hey folks, is this PR going to be in the next release? This appears to relate to a issue our customers face in locations such as Florida Keys. 

I've looked at the travis-ci and it looks like the tests are failing is that what is currently blocking the merge?

**Comment by dzungpng** [comment]
We are looking into this PR and other possible ways to resolve the issue. The current estimate date is the May release. @grantis

**Comment by grantis** [comment]
Hi @dzungpng , I have tested this locally on our dataset and with the latest version of `cesium` + these PR changes and it appears this change is causes further issues, I lose the model completely and it doesn't help with the clipping issue.

**Comment by slchow** [comment]
We got another bump for this issue (and request for an updated ETA) from the forum: https://community.cesium.com/t/new-cesiumjs-release/11110/15

**Comment by katSchmid** [comment]
Any news on this? Thanks

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @chris-cooper! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by ggetz** [comment]
Hi @chris-cooper and all, we just talked through this PR with @lilleyse. This is definitely a problem we've run into ourselves. While this does technically address the issue, it's a bit of a band-aid fix. We agree that `1000` seems a bit arbitrary. Can we get a real world constant, keeping in mind that some users are not using earth as their ellipsoid?
Also it may be better for this constant to live on the depth plane.

Also generally for bathymetry we disable the depth plan entirely.

**Comment by lilleyse** [comment]
> Also generally for bathymetry we disable the depth plan entirely.

Slight correction - we disable the depth plan when the camera is underground or the globe is translucent, but not necessarily for bathymetry.

**Comment by chris-cooper** [comment]
Thanks @ggetz and @lilleyse .  I've updated this PR to the latest master + tried to address your comment @ggetz .  Is this what you meant?  

[local sandcastle example](http://localhost:8080/Apps/Sandcastle/index.html#c=tVb9b+I2GP5XLLQfwkoNbQ9tA4pGP3T7gQ7E6E6nUt2Z5CWxztiRbeh6Ff/73sROCCmrdNtOVYPz+n3ej8eP7WyZJha0ZlxOtdryCDS5JNdg+GZNQw3MwgelRTR3PkGzv5ALuUXUlsNT7izhqQD8mduCRSPM36+VtAgCvWi0yMtCknqqXt3Qyp34GgTCemTFhIHcxiRfM8uVrBojSG0yFUzCrRA8NYpHk9XKgO2R026ns5C7rFxXKDUhSKCxUEugOXAOxo5iTG6s7w6byYOXPaZcXm24iOp9Tku7JyRUGIVgBqthrGTM7SYCxFx06bufLs77NQ/spHA4o93uL51KkDX7AtO8llQZnrVMLoeebYpwNIGhLIqCnFFCJFsjVYsGFos8O1sB7ZUjP7HkQiwV01GPeDghyGyMEfbN0pVWuHhC6cA3nL/Q2eTjaHw1vr9tkXc/N6lVN8yy+9k4aLaKWFvQlodMTDSPOaYvhHFgpleT+XxyV4IS4HFiZ7ACDTKEEvXboZ1ej0d300/zyaf3s8n97zcOvsvD7Nw6FCQiPe9BjayLgFwmfjB0bWdeSgAVKg4+u7ke+eHFjXafXTDsBjVgLKQGI5xni+RMEQjL0NShnbN+EQ4XNyNpv3scZx9vx+PJB/rEbTISacKCDu02c9AK6c2i/YWQ07M+/g4uSf57gtlI22VuvrhSXGZR0VZdbSeI/NHV1ncI93TFIfKaaatizdKEhyMU/DMGeSjWoCi64pPL4AZiDWCCMnOrLuJTl7PlOd5r4d+HPKmFdBEfj7c19QrPFulYl3TN0iDMlr5SEI6YvMjLmbEIxyYIabUgKnwx2diX0SwLOFiRMZ5VmPuNLbrfpNm5Vu7SbJ+KZ3fUlZ77zWt6B+219h5PPLJJj5xXTHg6guZM9JwMy5mdH+2aB+wdtLA/jl6tw5uSYvY/Saou4FJIe+q/VVKv98Q/hXxDUsweSOpIl99DUtmzmjrP4S+DQy+/Zt9TdpU6/ifZ+TK/KrWeq8CXX0ySfXu77OH+s79dfhJ7lg1bpwL8ZX2njL0B/L4QEAX1zwjy8I1KqR9BzUe83xKQwWojw4yHwCWPqgHzw7mQTXHDkGOOD51Hv+J5x4fXU+C10PcfLAvZaDUGxj4LGBZ8/srXqdKWbLQIKG1bwBxIvWkvN+EXsDQ0piBz0K5CBxHfEh5dHvkmI6FgxuDMaiPEH/wrKmQ4aKP/K6hQKGgZT/B2F+w5c0vOhmNnpJQO2vh6HGmVEkuma5H/Bg)

**Comment by ggetz** [comment]
Thanks for the update @chris-cooper! This approach looks better. Would you be able to add documentation and unit tests, and update `CHANGES.md`?

**Comment by chris-cooper** [comment]
I've added some of those things @ggetz .  For now it is just testing the option gets passed through.  I might need some help from someone with knowledge of that area of the rendering code if we want to test it more rigorously.

**Comment by ggetz** [comment]
Thanks @chris-cooper! I suppose to test this more rigorously, we could add a new test that confirms the depth plane draw command has `boundingVolume` set to the expected value. But no similar tests currently exist for `DepthPlane`. @lilleyse Any thoughts?

**Comment by lilleyse** [comment]
A test like that could be added `SceneSpec.js`

**Comment by chris-cooper** [comment]
I've tried adding a spec for that thanks @ggetz @lilleyse .

**Comment by ggetz** [comment]
Awesome! Thanks for your patience with this PR @chris-cooper !

**Comment by v8gx** [comment]
Without the logarithmic depth buffer this issue still reproduces. Here is a sandcastle where you can see the error by tilting the camera up.

https://sandcastle.cesium.com/#c=ZZJfb9MwFMW/ipWXZlLqJGvLRJtVQFuJB1gnNsFLJOTaN4mFY0e2k6mgfXdu/hTYyJPv9fndnHOTjlnSSXgCS26JhieyAyfbmn4deuGMD+XOaM+kBjuLyK9cE3w8WIute2s6KcCuLyC3wDx8M1aJx1ESXkUjIqDx1b1iGg5KycYZKY5F4cCvyTxNkiTXz1ebXOd6NEQdBw20VOYEdGAfwfn3JY50fpqNpgumHGxeQcqUzEpf1ZLve/JDWxRDxIsa9ZgcsDNxoL30EhxlQoRDxsY47BhN/mTbMevxxPSCFtbUeygtgAvnaXpD0+VqcZNEZHFN3ywX12+XJCLzVTJmr40AhXOm3bVWYjGjNH5gdaNgzzyLB42Lx1d9Zno6fccj7uA0m5ZYgSwr/wUwDmgOf819fHlB7453h4lxnClYk1XSl8/Tmqfc3jL+A8Shj3/GdcAmiILM+bOC7Ui/k3VjrEfXKkTLHtAyfmIXn1okPeXO9fOy+AJlQnZEits8ePX35AHhijmHN0Wr1IP8CXmwzWLUv8CUYULq8tiBVezcS6p0+2lsUkqzGMv/KW+MOjH7z8Tf

image

**Comment by ggetz** [comment]
Thanks for the report @v8gx. I opened https://github.com/CesiumGS/cesium/issues/10166 to track. Would you possibly be able to contribute a fix?

**Pull request merged**
