### PR TITLE
Modify error message in GlobalSurfaceTile

### PR DESCRIPTION
**Pull request by j9liu**
In response to issue [#8313](https://github.com/CesiumGS/cesium/issues/8313).

Changed the error message for failed terrain tile requests. The console now prints the error that caused the failure.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @j9liu! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/CesiumGS/cesium/blob/tile-error-message/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by shehzan10** [comment]
Congratulations on your first PR @j9liu. I've added you to the CLA list for Cesium. Can you please add an entry in https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTORS.md Under Cesium GS, Inc please?

**Comment by shehzan10** [comment]
@ebogo1 Can you please review. Also please advise on which test, if any, should be added for this change.

**Review by ebogo1 — COMMENTED** [review]
Changes look good; I confirmed that the new error was being added to the message string as expected.

Unit testing this one is a bit tricky because the `failure` function only exists inside `requestTileGeometry()`.. my first thought was to try putting a spy on `TileProviderError.handleError()` but by the time this function is called the new error argument is already part of the entire `message` string. 

~There aren't any specs testing other parts of the `failure(error)` function, but a better approach could be to expose a function like `createErrorString(x, y, level, error)` as a property of `GlobeSurfaceTile` and check that it gets called with the expected arguments. This new function would then be called by changing to `var message = createErrorString(...);`. I'm not sure it makes sense to add a function this specific to `GlobeSurfaceTile` even if it would help with testing though...~ 

edit - the first approach on spying on `TileProviderError.handleError` might be easier than I thought. Jasmine has a `toContain` function that can find substrings in a string. Something like this should work - 
```
it("Adds error message", function() {
  spyOn(TileProviderError, "handleError").and.callThrough();
    mockTerrain.requestTileGeometryWillFail(rootTile);

    return processor.process([rootTile]).then(function () {
      expect(TileProviderError.handleError.calls.count()).toBe(1);
      // Test that message argument is defined.
      expect(TileProviderError.handleError.calls.argsFor(0)[3]).toContain(<relevant error message string>);
  });
});
```

**Comment by j9liu** [comment]
Where is `TileProviderError` defined in GlobalSurfaceTileSpec.js? Or, if it is defined, how do I correctly access it?

**Comment by ebogo1** [comment]
It isn't currently defined, but you can import it with `import { TileProviderError } from "../../Source/Cesium.js";` like the other imports at the top of the file.

**Comment by j9liu** [comment]
Just added the unit test; let me know if there is anything else I need to do!

**Comment by ebogo1** [comment]
@j9liu Looks good! I pushed a small change to CHANGES.md to move the fix to the July release (and some wording changes; based on the last few released it looks like we link to pull requests rather than issues). 

I confirmed this works in Sandcastle - with bogus tile requests the ArcticDEM Sandcastle now prints:
`An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile X: 1 Y: 0 Level: 0. Error message: "Request has failed. Status Code: 404"`. 

I'll merge when my CI passes.

**Comment by ebogo1** [comment]
@j9liu Could you please close #8313 now that this is merged? Thanks!

**Comment by lilleyse** [comment]
Also @j9liu for future reference if you write "Fixes #8313" in the PR description the issue will get closed automatically when the PR is merged.

**Pull request merged**
