### PR TITLE
Moon fixed frame transformations

### PR DESCRIPTION
**Pull request by ggetz**
# Description
Adds `Transforms.computeIcrfToMoonFixedMatrix` and related functions to enable the sun position to be computed for the Moon by setting:

````js
Cesium.Transforms.computeIcrfToCentralBodyFixedMatrix = Cesium.Transforms.computeIcrfToMoonFixedMatrix;
````

## Issue number and link

N/A

## Testing plan

1. Ensure [this Sandcastle](https://ci-builds.cesium.com/cesium/moon/Apps/Sandcastle/index.html#c=pVdtcxo3EP4rGs90Ch0i7g1sXCctBuLBwWADTmKXTkfc6UCx7nSRdLYvGf/3rjDYHAdM0/gDRtK+PvusVkxitPxrUcXSCHdFjAMakpTrEZX3VKK3aHIw1zpRx9UqSdgbpcmMxTPsPyv4Ipoc/D55sVOtojNJYr00eD5CxAdRhbRAmUglYiJGRCmq1WSP8+ZCaSzuaIzevgoiCIZm5/Ppmc8G7Lx7/a1r91lXdeNhzW9169275PPH1nkDg9DX4OzOCM1v29dZf+w7NyN7fhFdZb3xldM/u9Y3UcfpZ5Z9G13VLqJh1D/rZIOzK9ZrnSe3YOxifAWG+1+m7in3s279Ezj23a45j2+y88DI3Xy+YoMvHXvQnj0O2s3Hfvu0gb+6H84/kvFYkwvlWR4Jb2+EM7waTW9mvGM1PocyOjy9u72sN7wFdgUgOpyzRAkWrOCAKhSOLgaD/hrwvoiVRpEQ8SDRALICne/ryGkqJWHxpRT3LKDyGJEHwlZ1ws//xnkZHEoRQVWapl7doLRuDiHbcY/Wd8qV9dWUKNojmXG0Km9EZlRmi82F5ZWbpspif8P4KyWWarmYVgHZjnVU3hXDUw5aIGYnVqmkSM8pGqUxYgqxeLFKpEiA6olQzECHJOVEs3tqSGvODaq/KhSyRxqgUJKIFko2BtKrUMhImZZIUk27vgzHokVjLQk/FUH23qhfEC3Z42s9d+ldgMs1hVwqz6W+Z/Rh0Z8xfVhZ+7jYK00OnruzJWIN5aRyclDJkwFjvEaVXOFSRU+leFBUDimEFNE4oMGQKsFTI3yMQsIVzalUq5pFlIOn7ackZhHZpfxClEvm3xm6FEVmVPgi2Hb2VF5rgWdEsM+Ff4cjaBuWcLaAyEW/obq1+nC8XUpqLlIeNBfhUtDTMqVbZIEAkuCQZ2NRysEaUKVZvEx1rS4tIjV8I7G7oG+bziSlaoPyVmX/etflgCMGAafRkAQsVSY/XN/ZE+UtTFI+jU22y/QWy7WsF2scKUJGJEo4NTeLVzifcTGlmMZkymmPzeaAw+wVwVwfXi77TIH/1ACTIRGi1ZB5eHiAEBiNfRowSX1tGqO63KkCkMzn8H+qqglj1ZFl2Q3bcmt23bXsmn30xz0jv7htNk+nm3kmgsVaDcJuDHchVArC+2sdqO95vDV91McwcJqJ4Fwg24YuykuYW0KnAbDewvVDz65vnot4thRwXOwdunYtJ/FU+QH33h73b1xc9zz7cLd/13NwzbHdnwigticAp45t1/XsPQHgunP0P7z30ljczUWA9sHvHmHAdl/+Tg0fuY7r/EQAzr78t5nP52/hhuPsIcDfuTaBkYBKL7Q1/bHJ3nI+4GXzwriB3qIKkyAobWS0mm/HO64lc4HANNq4lowewy+ZVLaeLoEoHFqFna3vmLxQuQDzlPLjzfqsKmT8m28FTyFMP1NA20s0ggEfIwXZFYqIkEi1mV0twcXra2Wxwu3m8MOo1xx3zoadm12Kn1ig58CBwrnSGacvFnsmjZHZwu+7vd4/zX77n8H1uNftd4qgwujngzCEZ872QeKUrAp64zjlolOfcHqatRm81OHGzKn3KZHviRyBCJElG9eoU0E2tsxHjR5W4B6rFS1q80bhKVzzfvafDG8aQDCSjPnivvFd3PWwtVXawtbm5ma0T5VNzjPDgu9bAR6xb5CGXQzB30IF0yGnGaBfcjy3Ao8IgK7RKP8Im9ZM2A0wYR8B8LZd/nFi/VCN3WWNn2EFFO39qOUeVU8HlYOTBZHfrTb/ZFEipEap5CWMq5rCqwDeS6o6TeEFB/NaqZWFk+q66knA7hEL3m55nyKfw69COAlTvqjL5ODdSRXkC6pcwDUVzwbw45STzIjN7Xe950141p5UYbldUwvBp0RuWP4X) shows moon phases over the course of about a month
2. Ensure lighting angle was not otherwise changed by default in other examples

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [x] I have added or updated unit tests to ensure consistent code coverage
- [x] I have updated the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
@jjspace Could you please review?

**Review by jjspace — COMMENTED** [review]
This looks pretty good, just some general comments. 

I don't fully understand the exact math behind this, I can confirm the sandcastles seem to work as expected on both the Moon and Earth. It's really funny/disorienting to see just how much the sun shadow wobbles around while the camera stays fixed :smile: 

With this change there's yet another "global default" we have to change to set things up to use the moon:
```js
Cesium.Ellipsoid.default = Cesium.Ellipsoid.MOON;
Cesium.Transforms.computeIcrfToCentralBodyFixedMatrix = Cesium.Transforms.computeIcrfToMoonFixedMatrix;
```
The more of these that get added the easier it'll be to miss one or not know about one you have to set. I feel like we should be able to automate this or condense things. Maybe when someone changes the default ellipsoid this changes automatically? Or maybe we have a new function to call before the viewer like `setUpForMoon` that we can add these settings to? Or maybe it could be a new option to the viewer constructor itself? My gut just says this should be easier for other devs.

**Comment by ggetz** [comment]
> The more of these that get added the easier it'll be to miss one or not know about one you have to set... My gut just says this should be easier for other devs.

Yes, I agree. I was considering whether to set it based on the default ellipsoid, but I don't want to conflate them and couple them together. I was thinking more along the lines of a helper function, like what you mention for `setUpForMoon`. Can we circle back to that after this PR?

**Comment by jjspace** [comment]
> Can we circle back to that after this PR?

That's fine, can you open an issue so we don't forget if it's worth doing?

Otherwise the code looked good and I'll trust the calculations so I'm fine to merge this.

**Pull request merged**
