### PR TITLE
Fixed flipy issue

### PR DESCRIPTION
**Pull request by ebogo1**
Fixes https://github.com/CesiumGS/cesium/issues/8852. Merge after release.

@ptrgags

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @ebogo1! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/CesiumGS/cesium/blob/fix-flipy/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-flipy/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
@ebogo1 I added you to the Cesium GS CLA

**Comment by lilleyse** [comment]
Here's a Sandcastle for testing: http://localhost:8080/Apps/Sandcastle/index.html#c=bVNha9swEP0rwp9SSOUkEChOGro0XSlsXWnaQZnHUO2LLSZLRpKdpqP/fWfJdpK22GDd0zvp7t1zzTSpOWxBk3MiYUsuwfCqoD8dNoiDxMWXSlrGJeg4OJnFMpY15m15anNMG898nAPPcovApAVqJiowCPyaTKdDMupeH/1uWSmzbFltNn0Jj1zasy9as93An7C/smAWNGfiuNibgmXwvd2606oEbXeDf7EkhDdbEYkDfOTb/iANiWUyE4An+f4pSMstB0NZmvrknhQRFxOSKKVTLvEqE3W333csutGqWEGmAczA8wk5HY9HdDTswslhcHp2tDWlI78+abGu26hfNfjbsO8kDMk6V5VICStLwLaauyWxCktPSVMOMarCISEilba5bz7TLOXY7gO82ErDsZgt6BVIcO4YR51GJgEJtEVdlSV/AfFVaaywV+Ruj9H76+Wet8JR210Jx8wOpY+365vr26vVn+XTw5XLchaL/McB3mNR+3XQRvDyKSJWV+Bi7Fgn+5GxxkjeX42powO/OTV7MTuNqfMMivJOplkwDObG7gQsupFd8KJEWUmlxYDS0EJRisYb4XOV/AVLE+O821Dn4WHqPOU14en5J/8XSQQzBnc2lRBr/gpxsJiHyP+QKhTWJ7MfNWjBdg0tHy++eZBSOg8x/DzTKiWemX538n8

**Comment by ptrgags** [comment]
I tried the sandcastle myself, I confirmed that it's a black rectangle on `master`, and a gradient on this branch.

**Comment by ptrgags** [comment]
@lilleyse let me know it's safe to merge this now. I checked it over one last time, everything looks good.

Thanks @ebogo1!

**Pull request merged**
