### PR TITLE
October 1 package updates

### PR DESCRIPTION
**Pull request by ggetz**
# Description

We can get rid of `sinon` entirely now, as [Playwright finally supports manual system time control](https://github.com/microsoft/playwright/issues/6347) :tada:

Any existing sinon functionality has been ported to use [Playwright's `Clock` API](https://playwright.dev/docs/clock).

Otherwise, these are routine package updates.

## Testing plan

1. Ensure CI passes
2. Run `test-e2e-update` locally and ensure appropriate screenshots are generated.

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] ~I have updated `CHANGES.md` with a short summary of my change~
- [ ] ~I have added or updated unit tests to ensure consistent code coverage~
- [ ] ~I have updated the inline documentation, and included code examples where relevant~
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
Could you please do a review? 

CI and running end-to-end tests locally should thoroughly cover these updates.

**Comment by lukemckinstry** [comment]
one more to check

`Apps-Sandcastle-gallery-I3S-Feature-Picking-html-renders-1-chromium-linux`
Apps-Sandcastle-gallery-I3S-Feature-Picking-html-renders-1-chromium-linux

**Comment by ggetz** [comment]
Thanks @lukemckinstry! For a bit of context, the `*-Sandcastle-*` tests simply load the initial frame of the corresponding Sandcastle.

> `loads-animated-model-1-chromium-linux`

That should be correct, we hide the background in those model tests.

> `Apps-Sandcastle-gallery-AEC-Clipping-html-renders-1-chromium-linux`

I'm not able to reproduce at all. I'm pretty sure this is unrelated to this PR, as per https://github.com/CesiumGS/cesium/issues/12227.

> `Apps-Sandcastle-gallery-ArcGIS-MapServer-html-renders-1-chromium-linux`

This is fine, see [the Sandcastle example](https://sandcastle.cesium.com/?src=ArcGIS%20MapServer.html)

> `Apps-Sandcastle-gallery-ArcGIS-Tiled-Elevation-Terrain-html-renders-1-chromium-linux`

This is fine, see [the Sandcastle example](https://sandcastle.cesium.com/?src=ArcGIS%20Tiled%20Elevation%20Terrain.html)

> `Apps-Sandcastle-gallery-Google-Earth-Enterprise-html-renders-1-chromium-linux`

Expected. This one doesn't do much without a local GEE server set up.

> `Apps-Sandcastle-gallery-I3S-3D-Object-Layer-html-renders-1-chromium-linux`

This is fine, see [the Sandcastle example](https://sandcastle.cesium.com/?src=I3S%203D%20Object%20Layer.html). The top-down view doesn't look like much.

> `Apps-Sandcastle-gallery-I3S-Feature-Picking-html-renders-1-chromium-linux`

This is fine, see [the Sandcastle example](https://sandcastle.cesium.com/?src=I3S%20Feature%20Picking.html). The top-down view doesn't look like much.

**Comment by lukemckinstry** [comment]
thanks for the responses/explanations of the screenshots @ggetz 
I think this is good to go once CI passes

**Comment by ggetz** [comment]
Thanks @lukemckinstry, this should be good to go!

**Review by lukemckinstry — APPROVED** [review]

**Pull request merged**
