### PR TITLE
Fix multiple contents race condition

### PR DESCRIPTION
**Pull request by ptrgags**
Fixes https://github.com/CesiumGS/cesium/issues/10551

In multiple contents, request throttling was creating a corner case where the contents were not yet created, but the `readyPromise` looped over an empty list of contents and resolved too soon.

The fix was to make the readyPromise return `undefined` and have `Cesium3DTile` content short-circuit the promise chain. The tile automatically re-requests the content as long as the tile is still in the `LOADING` state.

I also fixed a couple details about rendering statistics for Multiple contents/implicit tiling along the way:

* `tileset.statistics.numberOfTilesLoaded` wasn't being updated for implicit tiling like `Cesium3DTileset.loadTileset()` does
* when a request was canceled, multiple contents wasn't incrementing the number of attempted requests.

(note that for multiple contents, statistics are a bit ill-defined. if the property has "requests" in the name, it's counting the number of requests (one per inner content) but if the property has "tile" in the name, it's counting the number of tiles (1 regardless of how many inner contents there are)

@j9liu could you review when you get a chance?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-multi-content-promise/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Review by j9liu — COMMENTED** [review]
@ptrgags looks good to me, just one suggestion

**Comment by ptrgags** [comment]
@j9liu updated!

**Comment by j9liu** [comment]
@ptrgags merging now, thanks!

**Pull request merged**
