### PR TITLE
Fix export KML Sandcastle

### PR DESCRIPTION
**Pull request by OmarShehata**
Fixes https://github.com/CesiumGS/cesium/issues/8510.

I also added an `.otherwise()` because this is the second time I ran into a silent error with this Sandcastle (first time was here https://github.com/CesiumGS/cesium/issues/8432).

Tested and can confirm this works. @mramato any objections to merging now and include with release?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @OmarShehata!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/sandcastle-error/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
1. Why is the model called `Cesium Air`?
2. It doesn't appear to render properly in Google Earth: 
image

I have no problem merging for this release, but we should fix the above two problems as well.

**Comment by OmarShehata** [comment]
Good catch on the `Cesium Air`. I think it was using the airplane model before and we forgot to update the name.

I don't know why the texture isn't applied correctly. I imported the glb into Blender and exported it as COLLADA, but I still got the same result. This may have to wait until next release unless anyone has any quick fixes to try.

**Comment by lilleyse** [comment]
The glb / COLLADA load fine in other programs. Maybe it's a Google Earth bug?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @OmarShehata! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
In the spirit of https://github.com/CesiumGS/cesium/pull/8578 and keeping the sample models folder smaller, could the png be swapped with a jpg?

**Comment by OmarShehata** [comment]
Good catch @lilleyse . I've changed it to the same JPEG used by the GLB version. I've also merged in master and resolved all conflicts.

Given that the DAE itself loads correctly in other software, I think we should merge this as-is to fix this Sandcastle. If this is a dealbreaker perhaps we can consider changing to a different model for this Sandcastle.

**Comment by hpinkos** [comment]
@OmarShehata is this PR ready to go?

**Comment by OmarShehata** [comment]
@hpinkos  Yes, this fixes the original issue and I think we should get this in for the release.

**Pull request merged**
