### PR TITLE
Fix node transforms for i3dm models in ModelExperimental

### PR DESCRIPTION
**Pull request by ptrgags**
This PR addresses some [i3dm rotation issues](https://github.com/CesiumGS/cesium/issues/10255#issuecomment-1097168391) I noticed the other day. We had refactored the model matrix computation in ModelExperimental, but it looks like we missed a spot for i3dm models since the matrix order is a [bit different](https://github.com/CesiumGS/cesium/issues/10255#issuecomment-1098532598)

[Local Sandcastle for testing](http://localhost:8080/Apps/Sandcastle/index.html#c=jVZbc9o6EP4rGuY8mBkifMM2SZo5CUl6YAJpG3pL6ZwaWwQFW+ZIMinp8N/PWjJgJ+nlAdusdr+9fbt2jwiap/ji+5JwmhImw+SShDLnRGDCwmlChllMkuo5eoUkz8nRhE1YlDEh0YqSB8JBzsgD6mnED0pmTBqR+t/LwJQywieNprJst9FrHjJZ6g9uUBiBqkAyQ+ss54hmDIVCECkmrMTsZwzHZBbmiTxVyuNsQRj4nTTIejCfvo7oNR303z/2rRHtiz5714l6fa+/WH760Bt0MSj9F79egFL/cZRezoePt+nwxqLD+8X6avzWHZ4P5fXHi8frnrW4TS/vhx8/f79N369HH/v0qjdY3gLY6Pyt6KfJPIbn4fjzw2h8ag3Hp52RY+LY/5SOppf99M2Fc9ahd4NPg/f+bXAenpn+8kzcv5surH+kHJ/ni0lD1y+BFNEYKsvRjwlDSBWU55HMuJGEU5I0tRwhOacCKxEkrO5HlQMhQy4LHDjMGRQJah1XFQiLXzzeFJfipxCMursqKhBglvE0ZBHBLHswmk/Ns+UT673L39guOWUV15pUMZ3NCCdg8q8gEYAYNdCDJxE2URtZpmli82iPkiUEJ9mdUcfaed/sKSyLFgjw8mNTIfaSZykVpJB/+arks5xFsqBmYXCVhbHuUgvlfNsqbcpJGK91Y/VcqGfj218/lMEGGUrjjfbQ/KaD0raUUUnD5JfWO52EiCIOEtcxshXhYfJrjFJna7g3jjNWtK0cO6AL2GmdbUXwMhdzo9DDpWiPUXWNS1qpw31NauJtByATIutbRN+c87E+NEqGQLFVC7V9aYnT8DtN8/Qm4oSwm2UYkQvOsyJ7V+npNYVFRFTUNIUKriCVMI6NEmOfxBa02iUs54QZQNRXJ1uu1lIqJqBkX7WFtWQ3exdVN8/bWYR1sYKNe0WFhIh53fETBxXXT8pfOVHtgs2eJSvyPBw9Al8UOb4Wk1DJ8LCSaKsWwGEtklYthMNaLMrdUTl17fZugGB5J2QVFlM1abTQfte/g0hzDitjBuU/LV4F/diwAq/TNZtF2DWMO6FeVOKPIHwncBVEFUBqgDNO4zvyRzCO7T2DkUA+8afWnaZ+GW75BaUythPWLOr1AuNgkSJDj8yXcveUJFJVFl9RNkPX03sSSViWklMiDN3a5m7D1rejfs8cbY9qaJr/uNzQP9EpGfAbrZILOy2k1TY7Gk5YOaFRCAYhniXrcaZHPiZCUqY4gg5rCwImC55C5hgHttuxu56FPc92LNd1Ta+FDlzf71qWhR3PdbuO33FbyHFtuFvYt13bs7pO4DUVbzOoFXyllE52pYopJ9EvPZvYNbtWx3JNy+m6Vtc2wcsBSC23E3ie5biOb8G1o6SBZQeuXRx4rt91g2Zr6ylf/jw5E9uB6Xi27zleBwjsWdpH13QDF4Ac37ftwAtayMSObTpB13fMIHAcxy49bNQ1zvk2QxNmsXnUaDWOhVwn5GQbxt80XWZcFlvWwLgtSbpMQgikPc2jBeyqSIhtj4/bVdPjmK4QjV+98NGH1JcOnMzyJLmhjzBgJ8dt0H9mmsAcUXZ3DWxJwnWhNrdOrrQQY3zchr8vW8osS6Yhf4L8Pw)

I'm opening this PR as a draft since I'm not entirely convinced it's the correct fix. In particular, it seems like the axis correction is applied at the wrong point in the transformation chain.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-i3dm-matrices/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ptrgags** [comment]
Okay hm, compared to my initial experiment the trees now look wrong. They're right-side-up now, but the offsets are incorrect now.

image

**Comment by ptrgags** [comment]
I went back to the `1.91` tag (which was before the matrix refactor) and I can confirm that the old instancing code positioned the trees incorrectly as well:
image

I'm also noticing that even the bridge is slightly off. Compare these:

Model (Cesium 1.91)
image

ModelExperimental (Cesium 1.91)
image

**Comment by ptrgags** [comment]
Indeed, this is not quite the right approach. I'm going to be trying again a different way soon, starting with https://github.com/CesiumGS/cesium/pull/10300 and a follow-up PR soon after.

**Pull request closed without merging**
