### PR TITLE
Fix models that have mix of draco and non-draco attributes

### PR DESCRIPTION
**Pull request by lilleyse**
Before|After
--|--
broken|fixed

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @lilleyse!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-draco-mixed-attributes/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
@sanjeetsuhag Can you please review?

**Review by sanjeetsuhag — COMMENTED** [review]
The code changes look good. @lilleyse Is this a regression from the `Model.js` implementation? If so, should we call out a fix in `CHANGES.md`?

**Comment by lilleyse** [comment]
@sanjeetsuhag I'm not sure if the old Model.js had this problem, but I updated `CHANGES.md` anyways

**Comment by sanjeetsuhag** [comment]
Thanks @lilleyse!

**Pull request merged**
