### PR TITLE
Use double-ended priority queue with RequestScheduler

### PR DESCRIPTION
**Pull request by IanLilleyT**
This code was extracted from https://github.com/CesiumGS/cesium/pull/9291 to make it easier to review that PR.

This is useful for prioritizing network requests for 3D Tiles. When a new request is created, it gets added to the request queue and bumps off a request with lower priority. Previously this was implemented with `Heap` which uses a hack to get the "minimum element" in constant time: it returns the last element in its internal array, which is the last leaf tile and is not guaranteed to be the true minimum element. Finding the true minimum element in a heap takes linear time. The double-ended priority queue gets the true minimum element in constant time.

This is pretty subtle and I haven't found a real world situation where the heap removes the wrong minimum, but I'm not sure if that's because I'm looking at the wrong datasets or there's another place that sorts by priority beforehand, but it's a good change nevertheless.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @IanLilleyT!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/doubleEndedPriorityQueueRequestScheduler/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @IanLilleyT! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @IanLilleyT! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @IanLilleyT! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by lilleyse** [comment]
> This is pretty subtle and I haven't found a real world situation where the heap removes the wrong minimum, but I'm not sure if that's because I'm looking at the wrong datasets or there's another place that sorts by priority beforehand, but it's a good change nevertheless.

I looked into this as well. The only case where a new request kicks out a previous request is [here](https://github.com/CesiumGS/cesium/blob/554baa18e576fe57bc6ccc831b6a56f0d6648772/Source/Core/RequestScheduler.js#L431). This will only happen if `throttleByServer` is false. Normally when `throttleByServer` is true the request doesn't get that far - it early exits when it sees that the server is saturated. 3D Tiles and terrain set `throttleByServer` to true so it explains why we didn't see any change with this PR.

Since we don't really benefit from a double-ended priority queue after all I suggest we close this.

**Pull request closed without merging**
