### PR TITLE
Cesium 3d tile time availability

### PR DESCRIPTION
**Pull request by brianpojo56**
Added an optional availability (TimeInterval) parameter for tiles to allow for culling tiles within a tileset based on time.

I've been making animated point clouds of airborne radar by encoding time values in the batch table and reapplying styles as time changes. With large tilesets this begins to hinder performance drastically, particularly if the tileset is segmented into many children tiles. My solution was to add a time availability parameter per tile, set in tileset.json as an ISO8601 string in the form "2019-12-01T01:01:01Z/2019-12-03T01:01:01Z". An extra method call is added in the updateVisibilty method to check the tile's availability. This way a tile is only selected if the viewers time is within the availability window of said tile, and styles aren't applied to features that would otherwise be hidden.

Please see my demo here: http://brianpojo56.github.io/cesium_demo

The data being shown is:
Heymsfield, Gerald M and Lin Tian. 2017. GPM Ground Validation High Altitude Imaging Wind and Rain Airborne Profiler (HIWRAP) OLYMPEX.
Dataset available online from the NASA Global Hydrology Resource Center DAAC, Huntsville, Alabama, U.S.A.
DOI: http://dx.doi.org/10.5067/GPMGV/OLYMPEX/HIWRAP/DATA101

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @brianpojo56!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/cesium-3d-tile-time-availability/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
This demo looks very cool @brianpojo56 ! Thanks for opening this pull request.

So does each point have a time interval that styling is used to show/hide as the clock ticks, and each tile has a time interval that is assumed to be the min/max of all of its children's content? 

Are you aware of [TimeDynamicPointCloud](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/TimeDynamicPointCloud.js) ? Although that may not be ideal for this case since it gives each tile a time interval, and not each point. There's a Sandcastle example using it here: https://sandcastle.cesium.com/index.html?src=Time%20Dynamic%20Point%20Cloud.html

**Comment by brianpojo56** [comment]
Hi Omar, sorry for the long delay in a response and thank you so much for taking a look so quick. 

Yes, originally I built these animations using TimeDynamicPointCloud, but I ran into a few drawbacks with this. Often the data for a single flight from this instrument is upwards of 10 million points. Due to the close proximity of the points it is well suited for hierarchical level of detail organization by generating multiple levels of resolution, but TimeDynamicPointCloud doesn't support HLOD so we can only show a single level of detail. Each point is a sensor value for a space at a given instance of time. I've simplified it a little by removing the number of milliseconds from the original data, but this still means that we have a .pnts file for every second. For the data in the demo (about 2.5 hours) that's roughly 9000 .pnts files. This in itself isn't that terrible, however, in order to show a coherent representation we need to show a window of time (the demo shows the current time and the trailing 5 minutes of data). Since we don't have overlapping TimeIntervalCollections we need to either have multiple TimeDynamicPointClouds with slightly offset TimeIntervals, or have duplicated points across each .pnts file.

I have a time value for each point in the batch table (its stored as a float32 and is the number of seconds from a specified epoch). Each second a new style is applied to the tileset that will only show the points that are less than or equal to the current time and greater than the current time minus 5 minutes. This achieves the best results that are a balance between client performance, network traffic overhead, and file size. However, with longer flights, or when displaying multiple similar airborne instruments simultaneously, applying the new style every second starts to produce a severe performance problem. By implementing availability per tile, if the current time is outside the tile's availability the style won't be applied because it won't be selected, and drastically reduces the amount of time taken to apply a style to a high volume high density dataset.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @brianpojo56! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @brianpojo56! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @brianpojo56! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @brianpojo56! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @brianpojo56! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by brianpojo56** [comment]
This is ready again.
It's been a while since I first opened it so I merged in all of the commits since then.

**Comment by lilleyse** [comment]
@brianpojo56 I don't have many comments on the code because it looks good, but I don't know if we're ready to commit to this approach for time dynamic 3D Tiles... yet... especially as we're deciding what time-dynamic looks like for 3D Tiles Next. That said per-tile availability makes a lot of sense, we would just need to formalize it from the spec side before we could merge this PR.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @brianpojo56! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
Let's close this since there's no action we can take here until the specification is formalized, and that may ultimately change how it's implemented. Thank you very much @brianpojo56 for sharing this contribution and your demo! It was especially helpful hearing about your use case that you created this for.

**Comment by brianpojo56** [comment]
Sorry to post on a zombie PR. I pulled out the changes here and made an npm module that can be imported to extend the Cesium3DTileset class and add the functionality.
https://www.npmjs.com/package/temporal-3d-tile
Just wanted to post it here for anyone interested.

**Pull request closed without merging**
