### PR TITLE
#9952 address failing test cesium.com

### PR DESCRIPTION
**Pull request by TheMagicNacho**
This PR addresses issue https://github.com/CesiumGS/cesium/issues/9952 requesting tests on the cesium.com branch be able to run 'offline'.
I originally started working on this with pull request #https://github.com/CesiumGS/cesium/pull/10099, but was unable to complete the requested changes before the PR was closed.

I have since addressed the concerns @ggetz mentioned in the previous thread, and created a new thread and new branch.

Current issue: I can't mock the functions in Specs/Core/sampleTerrainSpec.js
If someone has access to the terrain binaries that match the requirements for the tested methods, it would be greatly appreciated.

EDIT: I closed PR #10357 because I sent the branch to cesium.com instead of main and I couldn't edit it.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @TheMagicNacho!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/9952-failing-test-cesium.com/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Changes to third party files were made.
    * Looks like a file in one of our ThirdParty folders (`ThirdParty/, Source/ThirdParty/`) has been added or modified. Please verify that it has a section in [LICENSE.md](https://github.com/CesiumGS/cesium/blob/main/LICENSE.md) and that its license information is up to date with this new version.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
Hi @TheMagicNacho, there appears to be several unrelated changes, and the commit history is showing many unrelated commits from the `cesium.com` branch. 

Your changes should be pushed a branch that is in sync with `main`, not with `cesium.com`. 

If all of your changes are in the last commit, you may be able to use the [`git reset`](https://git-scm.com/docs/git-reset) command and move your changes to a new branch, `offline-tests`.

```
git reset HEAD~
git stash
git checkout main
git checkout -b offline-tests
git stash apply
```

**Comment by TheMagicNacho** [comment]
@ggetz, your instructions make sense.
I'll open a PR from the branch based off the main branch. I just need a little time.
Thanks for your input!

**Comment by TheMagicNacho** [comment]
Closing this pull request to address rebase from cesium.com  > main.
[new PR](https://github.com/CesiumGS/cesium/pull/10389)

**Pull request closed without merging**
