### PR TITLE
Fix polyline regression with log depth

### LINKED ISSUE #8663: Polyline regression in 1.67?
Load simple.czml and zoom to GeoEye (after animating some so it's partially through the orbit)

image

In the above view, the polyline is clipped (the line moving towards the left should go all the way to the end of the screen) and there is also some weird break in the distance on the right (this should be one long continuous polyline)

Any ideas? @kring @lilleyse

### PR DESCRIPTION
**Pull request by kring**
Cesium's fancy polyline rendering sometimes needs to clip lines at the near plane. But it was still using the depth of the original vertex after clipping.

Fixes  #8663

I had hoped this would fix _all_ the log depth polyline problems, but alas no. There's still something dodgy going on with polyline depth. In any case, this was a clear bug and this fix should go into 1.68.

This PR also includes #8608 (Spector.js shader editor support) because I merged that in in order to help debug this. If anyone has a problem with that, let me know and I'll rebase this PR to remove those changes. But those changes are awesome, so please just merge them too. :)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @kring!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
@lilleyse you're probably the best person to review this, correct?  Also, SpectorJS is really useful too, so I personally don't see a reason not to include it.

**Comment by lilleyse** [comment]
Cool I'll check this out tomorrow

**Comment by lilleyse** [comment]
The change looks good. @kring do you plan on pushing any other fixes in this PR or is this ready?

**Comment by kring** [comment]
This can be merged. I hope to do a another PR today to fix the rest of the polyline/log depth issues.

**Pull request merged**
