### PR TITLE
Added CesiumDrone model, optimize GroundVehicle.

### PR DESCRIPTION
**Pull request by emackey**
Yesterday, @pjcozzi asked me if I had any other cool models to add to the collection.  I have the CesiumDrone model from a couple years ago, that might make a nice addition here.

Also, the GroundVehicle was the largest model at >7.5 MB.  I shrank the two largest images (both ORM images) to save some space.  As a result, my total contribution in this PR is a size reduction, not an increase.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @emackey!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/cesium-drone/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by pjcozzi** [comment]
Very cool, thanks @emackey! 🙏 🙏 🙏

**Comment by OmarShehata** [comment]
Thanks @emackey ! And just to confirm, we don't need to add this to the LICENSE.md file (https://github.com/CesiumGS/cesium/blob/master/LICENSE.md) because you created this model yourself right (similar to the Cesium airplane and milktruck that aren't third party models)?

**Comment by emackey** [comment]
> And just to confirm, we don't need to add this to the LICENSE.md file because you created this model yourself right?

Correct, thanks.

**Pull request merged**
