### PR TITLE
ts defintions, export Cesium as  namesapce

### PR DESCRIPTION
**Pull request by xxbld**
ts defintions 
support `new Cesium.Entity({point:...})`
and keep `cesium` module

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @xxbld! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/xxbld/cesium/blob/ts-defintions-umd/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/ts-defintions-umd/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by OmarShehata** [comment]
Thanks @xxbld ! Please submit a [contributor license agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) so we can review this PR.

**Comment by xxbld** [comment]
> Thanks @xxbld ! Please submit a [contributor license agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) so we can review this PR.

@OmarShehata  I have submitted

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @xxbld! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @xxbld! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @xxbld! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @xxbld! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @xxbld! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by hpinkos** [comment]
Thanks for the PR @xxbld!  @mramato or @kring, do you have opinions on this change?

**Comment by kring** [comment]
Hi @xxbld, thanks again for the PR and sorry it's taken so long to review it.

With your change, TypeScript always thinks there's a global `Cesium` variable. This is true when CesiumJS is included with a script tag, but it's not true when CesiumJS is imported as a CommonJS or ES6 module. As a result, this PR allows code that is missing imports to compile but then fail at runtime.

Am I understanding correctly that you're including CesiumJS via a script tag and you want correct typings for the global `Cesium` namespace that results?

If so, I think the best solution is to use a _separate_ declaration file when importing CesiumJS into global scope, rather than modifying the existing one to work in this scenario. For example, with the original CesiumJS distribution (i.e. _without_ the changes in this PR), save the following as `Cesium-global.d.ts` in the same directory as `Cesium.d.ts`:

```typescript
/// <reference path="./Cesium.d.ts" />
import * as cesium from "cesium";

declare global {
    const Cesium: typeof cesium;
}
```

And then you can use it like this:

```typescript
/// <reference path="Source/Cesium-global.d.ts" />
console.log(Cesium.Axis.X);
const v = new Cesium.Cartesian3(0.0, 1.0, 2.0);
```

This code will compile, and as long as CesiumJS is included in global scope with a `<script>` tag, it will work at runtime as well.

If that works for you, we can include `Cesium-global.d.ts` in the official CesiumJS distributions.

**Comment by xxbld** [comment]
@kring ,thanks for your answer, Your method solved my problem ! 
i will colse this pr.

**Pull request closed without merging**
