### PR TITLE
Remove unnecessary characters in sandcastle HTML

### PR DESCRIPTION
**Pull request by javagl**
This is supposed to address https://github.com/CesiumGS/cesium/issues/10917 , but I can not easily test whether this _really_ fixes it.

If somebody can 

- glance at it and say "Yep, that's it" with reasonable certainty (or ... just try it out)
- knows (or can make sure) that this change does _not_ affect anything _except_ for the deployed sandcastle

then this might be an easy fix. Otherwise, I'd leave it to others to investigate the issue further.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @javagl! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/javagl/cesium/blob/fix-sandcastle-html-characters/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-sandcastle-html-characters/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by ggetz** [comment]
I believe this is an isolated fix. Thanks @javagl! 

I think at this point, you can go ahead and add yourself to `CONTRIBUTORS.md`. 😄

**Comment by javagl** [comment]
@ggetz I (finally) updated CONTRIBUTORS.md - even though they are only small contributions for now.

Should I try to test this further in any way? If I should test it locally, I'd pragmatically set `isProduction=true` near https://github.com/CesiumGS/cesium/blob/ee8bc4b6ffed3c13e79476b7aa87f1d1f90906a7/gulpfile.js#L2060 and see whether the change here makes the expected difference, but I wonder whether the change here might have unexpected side effects that I don't have on the radar. (That `if (isProduction)` scares me... :D )

**Comment by ggetz** [comment]
Thanks @javagl!

**Comment by ggetz** [comment]
The `if (isProduction) ` path builds the version of sand castle which is deployed to the website. Since it also has the same issue, I applied the same fix. It should also apply for the standalone version, which is less obvious because the source is hidden.

**Pull request merged**
