### PR TITLE
Make sampleTerrain behaviour consistent with the rejectOnTileFail flag

### PR DESCRIPTION
**Pull request by jesseyay**
# Description

Passes through the `rejectOnTileFail` flag so it will be respected if any tile requests fail, not just if the first request fails. Note that the linked issue discusses changing the default of this flag to `true` which I tried, but it ends up failing the test [fills in what it can when given a mix of positions with and without valid tiles](https://github.com/CesiumGS/cesium/blob/11dd728dfee6c10657f8e1197776fc5a9237ef85/packages/engine/Specs/Core/sampleTerrainSpec.js#L107)

## Issue number and link

Addresses/Related to: https://github.com/CesiumGS/cesium/issues/11694

## Testing plan

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [x] I have added or updated unit tests to ensure consistent code coverage
- [x] I have update the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by chris-cooper** [comment]
@ggetz Would it be possible for you or someone on the team to have a look at this as we notice some tile errors are still slipping through unnoticed.

**Comment by ggetz** [comment]
Thanks @jesseyay! We'll review shortly with the intention of including this in the next CesiumJS release.

**Comment by chris-cooper** [comment]
> Do you or @chris-cooper have any thoughts about reversing the default of rejectOnTileFail to true given https://github.com/CesiumGS/cesium/issues/11694? That would restore behavior that broke in 1.92.

That makes sense if it was the old behaviour.  Do you want to remove the flag as part of this PR @jesseyay ?

**Comment by jesseyay** [comment]
Hey @ggetz thanks for taking a look!

I tried changing the default in this PR for `rejectOnTileFail` to `true` but there is [this test](https://github.com/CesiumGS/cesium/blame/11dd728dfee6c10657f8e1197776fc5a9237ef85/packages/engine/Specs/Core/sampleTerrainSpec.js#L107) which looks like it is 10 years old that will fail if we change it 🤔 

I did a bit of further digging and I suppose the behaviour with a 404 response depends both on the `rejectOnTileFail` flag and on the `terrainProvider` that gets passed in, so maybe the regression https://github.com/CesiumGS/cesium/issues/11694 originates in a terrain provider?

**Comment by ggetz** [comment]
Got it, thanks for looking into that @jesseyay! Sounds like we'll need to look a bit closer to find the source of the regression. No need to hold up this PR for that.

**Pull request merged**
