### PR TITLE
Prevent error when name is null or undefined (fixes #8804)

### LINKED ISSUE #8804: Entity constructor fails when passed null or undefined `name`
Sandcastle example: [here](https://sandcastle.cesium.com/#c=tVRdT8IwFP0rTV8cCXYCPhicxAhETYwmKPrSl7pdtLG7JW2HouG/2wKTr/gBiX3penfO6TlnyUbCkJGEVzDkhCC8kjZYWeTsfjqL9tLpsa3RCYlg9irHHDnOGAzQSSfBMpFl0QdH4heKHJqE0xsETquz2VBbj9PYLNXbwjj/JLDBBkbnHXgyADbar9UPquTwoPLFk+iaZK4cVqqVNguZcGIPF5d33eoCM5RvoG7lu7dxNB9POE5+db6ly9p2Lnvdzl89OjMu1X6wuyi7wAwG/utkyxdsF6ZeWeGuB/ou1NlVf7n5b5LN0023kHBCUuHSZxKBMZXymlSj1QqYn2kTcdovQ3EaOJuQQA5iuzSGhVK7l9XYrazzXrd7/S9tNX5riFZpYt1YQWuGO5X5UBtHCqMixmIH+VAJnzh+LNIXcCy1NjCTuCQlmRwRmZ1wuvZD4JSkSljr3wx8qSEKp60k9vgVmtIik/h0MwKjxDhAnmutq9mQMZbE/rjJclqrR2GWFD8B)

Browser: N/A

Operating System: N/A

---

I did a bit of digging and eventually got lost in how property-definition interacts with `Entity#merge` as called at the end of the constructor, and I can't spend any more time on it right now.  Obviously for now the fix is to not pass a null/undefined name, but shouldn't be required -- the docs say that `name` is "optional", so an options object with no `name` should be treated the same as one with `name: undefined` or `name: null`.

### PR DESCRIPTION
**Pull request by YonatanKra**
fixes #8804

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @YonatanKra! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/YonatanKra/cesium/blob/FIX-8804-entity-constructor-throws-on-null-name/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/FIX-8804-entity-constructor-throws-on-null-name/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by mramato** [comment]
Thanks for the PR @YonatanKra. I'll need to find some time to dig into this a little more to make sure the check happens in the right place.  If it happens for name, I would expect it happens for some other properties as well so there might be a more central place for the check.

**Comment by YonatanKra** [comment]
I looked at the properties involved. 
Name is the only one that's not prefilled:
https://github.com/CesiumGS/cesium/blob/c3e375d48b3385203b9148c69c86d03a42b8b0cc/Source/DataSources/Entity.js#L144

**Comment by YonatanKra** [comment]
@mramato 
I took another look at the code. 
I pushed a more robust solution.
I think the verification was all wrong in the Entity's `merge` method.
Let me know what you think.

**Comment by hpinkos** [comment]
bump @mramato

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @YonatanKra! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by mramato** [comment]
Thanks again for the PR @YonatanKra!  The issue here was a little more subtle than I thought and also affected `availability`, so I ended up pushing both a change to sync this branch up with master as well as provide a more complete fix.  I'll merge as soon as CI passes and this will go out with the release on the 1st.

**Pull request merged**
