### PR TITLE
Do not render constantly in requestRenderMode when dynamic geometries exist

### PR DESCRIPTION
**Pull request by rropp5**
# Description

Avoid requesting a new render from the Scene every time a Primitive is ready. With dynamic Primitives, they are destroyed and re-created each frame so this means they must be marked "ready" each frame. If they request a render each time they are ready, there is an infinite rendering loop that breaks requestRenderMode.

These changes simple modify the setReady() function on Primitives so it only sets the ready state and does not request a new frame.

## Issue number and link

This resolves the problems reported under #6631.

## Testing plan

I created several sandcastles on the linked issue (#6631) to address Primitives and GroundPrimitives. I have also tested to confirm non-dynamic Primitives render as expected when requestRenderMode is enabled and when it is disabled.

> [Updated original Sandcastle from #6631](https://sandcastle.cesium.com/#c=jVZtb9s2EP4rhL9UXlVZztsWxwkWOOnWIYmNOOuXeRho6WwRoUiVpJykRf77ji+SZXcZGgSmRN7rcw/vtKGKbBg8gSLnRMATmYBmdZl8dnvRu8y9TqQwlAlQ72LybSEI/ulC1jy/FKykBkZkRbmGOBxlIOBW5rgdrM2bnWQ+ub67PrhCydf+2UIsxGAwB0OWsha5JnJFZK2IZmXNqWFSEMNKWIgNRqkNVQaDDCb/qDmj4gqdJyslS/sQ2fjdw0E6PI7JAf7jMjzpW1fehqz+0wTN8zlkEmOInJ+YHJ6kcReQrXDUbyK/pY9AdK2ggZBpQg0xBZActRTkLv4EnbvzJOMye0ychwc8wFDcs90XaPfsO0FZtXKyekssq5UC8UMW3e89FWvYwjBp95Kb6XT2z/xhOjsjg8GNRLBCOiDyPUtYIcMqzhxxhmmnljZljmQhRnYr6UvcWmmkkq9Slg+ygd3m2cD7G5JGIeCEEkVFLkuSMZWhPUUqagwoQZ6YKQhW9oWJNSmArQujEe5VLTLnNJNlVRuYoB63ih+5FYkQnJhgXDEazlmt+w2rLUkqJStQ5mX3QsxpWXHIZ1Iza3kWhBzEVnMlFYmsOkO99AyX8bklkX16f06OjlsfjR/rmgq9LcQtNUVi5L3fj1hjulEwvsA/wl72v9ztGq1CQh0+oAV8ouLQ3yxYKwBtMSPvSeQBIz+RYXKMvy7mTOooZNPvO2B3JJ2MZqIr001ZwLO5dwW+q8sldp0+Kh2nKRoZ/nycdiNuauNSdhWJLCpxm0Yj/OoXBaZGmjRqePjquTXxxAjkNgzL3SLROvFNo4PQG3T6MBweJMNhenJ6aBtHkp6eHv1yNIxJmqSHDZsvM1NTzl9IpoDuePZuQhTnoZck7p2BtqlG36wNm1C4Ytuo6YYyTpeM2xe8cfZIUyQKE3hDNpQTqv3mblNNvL0d9VGXNLadfAo2JpJzcDcq+usNkajDbt+qR36Nu/vYUUZuCVXq/92Pt6n9qcH1/wBz3kKvvURbiVH72NG+rI3EYcQyj3IosFQMkQotiGo0aivcGCrlBko8D2h0hXfA+AzY9BCi6Vag7QAt9dpYgHNWacnyUffOW/azHavbmxYh3WPS/PQ7mNnxqhjl7SzFWkiV3F9fBaHX7SxtWqui2SPk1w2hsO/CClttvp0GoenuUW2nafwOGK9Yz5jJCjcdojR+o1N9OE37YShappN5IZ/ISlkWZtj1MYE4fC+QJZBF725wueiRpwIEEdIUtnfj5CxoVYHAlzZK9yGRKPhSgzb3OINA2Y8ITMmoGs725HJY1mvr+qP1rGegfFPcimNoU4HcUM6UDwCecYhhad22cwT5nuGSPuPdKX0AlvOTIkzQTwJxZa6v9OLeWJsXDhe+LL+yspJ4C2rFoyQZGMBmhaXUg2WNxcEBrbVFbDxolMY52xCWny96e99cCFXGqdZ4sqo5n7OvsOhdjAcov6PGpSvYdAOK0xcrUgwvbvxmkiTjAb5+r2Wk5EuKTkLc2xPXQCrpe8YtiLrrNaz/Ag) : Expected behavior is that the ellipse does not begin to move when play is pressed

Case 1: animation is paused, Infinity maximumRenderTimeChange

>  [Ground Primitive](https://sandcastle.cesium.com/#c=rVNNb9pAEP0rI6RKdkvWRpQLIagpyaFSo1Qk6smXjT3ANOtdd3cdoFH+e8e7ENKQSj0UyWI/3nsz+2amNNp5eCBco4Uz0LiGGTpqa/E9nCVFrwz7mdFekkZb9NLTQhc6y+AGPVj82aLr/nXFErWpsNBRT7gSNYodYh4AV3zPcbxt8TRoXGu13ZPXK9SAm0ZRST4cByZWrxRruaG6raPiLdU4W0m97HS/6AVp8tuQYRne5ry0nq8upEehzTrp0o9XS/RX8oex5xtyjFi0uvRkNCQpPBYaOL5vLW+T5EBO4SRKpvAeBqM8hXcwyMMPPsAoLDjA04sMujCk/2eY4VthqGLxomexulSKGodF7/mlh0PG7LxE7ckTOiGrKgmJUDXmr98ttaxxzGpzrAB3TE7ZtXYhS1YOoMY46l4y3vfMjBPmldRDsbCmvsClRXTJySAfirwPH3ORp4G5kxxHAwAc1vTs0fhlG86kUneyvP9mTYPWbxN27Wz6h6dJ2oeFVA6j9k5tX9h/Vdvjj9RqLoolqQ6vNMpYMb+8EGvyq3PVrGSSi1HEP3FR4oDcSF2V0nmFncO3xnBk+7n13uikMzbOTWxiNvSoL/4+RKGFOQr0+r2J81uF05gqwCeqG8P93lqVCJF5rBvF+bvsri3v0YvSuY7cQSfZS+qkogcu/tkb8w6lks7xzaJV6oZ+cfmnk4zxR1RlZEV6ef2AVsltB1sNpl/joRBikvH2baaP9rxS/g0) : Expected behavior is that the ellipse only changes size when the "Request Render" button is clicked

> [Primitive](https://sandcastle.cesium.com/#c=rVRRT9swEP4rp0qTkq04qRgvpa3GWh4mDTEVtKe8mOTa3HDszHYoHeK/72K30AGT9rBKVe3z93139/nc0mjn4Y5wgxamoHEDc3TUNeJ7iCXFoAz7udFekkZbDNLTQhc6y+AKPVj82aHrf3XFEo2psNBRT7gSNYodYhkAF3zOebzt8DRoXGq13ZM3NWrA+1ZRST6EAxOrF4qNvKema6LiNTU4r6Ve97pf9Io0+W2osAy9OS+t56OF9Ci02SR9+fFojf5C/jD27J4cI1adLj0ZDUkKD4UGzu87y9skeSancBQlU3gPo5M8hXcwysMHPsBJWHCCx4MK+jSk/2ea47fSUMXixcBida4UtQ6LwVOnz0HG7LxE7ckTOiGrKgmFUDXm77BfatngmNWWWAHumFyy6+xKlqwcQK1x1Hcy3s/MnAvmldTHYmVNs8C1RXTJ0Sg/FvkQPuYiTwNzJzmOBgDUSOvaj/sWGRhjDht68m18OJpzqdSNLG+/WdOi9duEnZzO/vA5SYewkspheqi2v+x/VdvjX6k1fFGWpHru3ChjxfJ8ITbk6zPV1jLJxUnEP/JFxUdzJXVVSucV9q5fG8OZ7efOe6OT3uz4luJgs8mvZuXvDyuMNWeBwXAwcX6rcBZLBfhETWv4DXRWJUJkHptWcf0uu+nKW/SidK4n99BJdkidVHTHAzF94z8ASiWd45NVp9QV/eKRmE0yxr+iKiMr0uvLO7RKbntYPZp9jUEhxCTj7dtMH+15ofwb) : Expected behavior is that the ellipse only changes size when the "Request Render" button is clicked

Case 2: animation is active, 2 second maximumRenderTimeChange
> [Ground Primitive](https://sandcastle.cesium.com/#c=rZNNj9MwEIb/yigSUgJdJ2XppbQVVbs3Vou6wCkXrzNtTB072E4/QPvfmTj9YrcHDkSK4o/3fWY8ngijnYeNxC1aGIPGLczQyaZi38NanEcizGdGey412jxKPuY612kK3zTUvHEIvkQQyoh1rjsUCzPmStOoYqplxT0S3tsGj+ZH9GDxZ4Ou/eqC4lemwBPBCdTIDopFENzT/plCjAet9kfztkQNuKuVFNKH5eDE4gWx4jtZNVVH/CornJVcr1ru+5CaCBVxnltPa3NKnGmzjdtDd1sr9Pf8h7HTnXSkWDZaeGk0xAn8zjVQYN9Ymsbx2ZzATYdM4C30B1kCb6CfhQfewSAMKMDzRQZtGKn/Z5jba2FkQfA8sljcKSVrh3l0Oul5kTSHIqL20kt0jBdFHBKRxZDeXjvUvMIh0RZYAB6clLJr7JILIgdRbZxsTzI8dtqMEqYR17dsaU01x5VFdPFNP7tlWQ8+ZCxLgvOAHHYFAHBYyVONhpfNO+NKPXGx/mJNjdbvY6raePJXTeOkB0uuHHbsA+14sf9KO+pf0dqOt5Kr8ymNMpYt7uZsK305VXXJ44wNOv0zXUrbYVEvGjm/VzjpKACfZFUbasXGqpix1GNVK0K79KkRa/RMONcaW+kovbSOCrmhexlf+YHpX+XO0c6yUepR/qKbmYxS0r+yKsMLqVcPG7SK71tZ2Z987hYZY6OUpted3hiqmX1B/gM) : Expected behavior is that the ellipse changes size every 2 seconds

> [Primitive](https://sandcastle.cesium.com/#c=rZNNb9swDIb/ChFggL2lsrMuFy8NViS9reiQbjv5otpMzFWWPEnOx4b+99Fy0mRtDjssgBGJet+HFCUVRjsPa8INWrgCjRuYoaO2Ft9DLMoHRZjPjPaSNNp8EH/Mda6TBL5paGTrEHyFUChTPOa6R4kwE64yrSqvNdXSI+O9bfFgvkcPFn+26Lp/XXL+2pT4THAFahR7xSIIbnn9SGHGnVa7g3lToQbcNooK8iEcnFi+INZyS3Vb98SvVOOsknrVcd+H0orQEeel9Rybc+FCm03UbbpfWqG/lT+Mvd6SY8Wy1YUnoyGK4XeugRP71vI0io7mGC56ZAxvYTROY3gDozT84B2Mw4ATPJ1U0KUh/T/TXJ5LQyXD84HF8kYpahzmg+edHoOs2TcRtSdP6IQsyygUQmXG37AballjxrQFloB7J5fsWruUBZODqDGOup1kh5s244J5JPWlWFpTz3FlEV10MUovRTqED6lI4+DcI7O+AQAV0qryWbdFFvYxhzU99y07vdAzqdSDLB6/WNOg9buIO3k1/avPUTyEpVQO41Pa4bD/lXbQv6J1r8CSVMedG2WsWNzMxYZ8da2aSkapGPf6Jz6o7tYNhoOJ8zuF054C8InqxvD1bK2KhEg81o1itEse2uIRvSic64yddJKcWiclrfmsrs48an6/0jleWbZK3dMvPq3pJGH9K6sysiS9ulujVXLXyarR9HMfFEJMEp6ed3pjuGf2BfkP) : Expected behavior is that the ellipse changes size every 2 seconds

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have update the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by ggetz** [comment]
Thanks for the suggestion @rropp5! I can confirm we have a CLA on file for you.

**Comment by ggetz** [comment]
@rropp5 I think this is a valid way to address the issue. I've tested the example from https://github.com/CesiumGS/cesium/issues/10517 where this code was originally added, and request render mode continue to function as expected.

Would you mind syncing up with `main` and updating `CHANGES.md` such that your fix is under the next release, `1.116`?

**Comment by rropp5** [comment]
@ggetz No problem! The branches should be synced now and I added 1.116 to the CHANGES.md so I believe we're good to go.

**Comment by ggetz** [comment]
Thanks @rropp5!

**Pull request merged**
