### PR TITLE
Handle geojson with null fill or stroke properties but with a non-null opacity value.

### PR DESCRIPTION
**Pull request by na9da**
Currently when loading geojson with null value for `fill` or `stroke` properties but with a valid `fill-opacity` or `stroke-opacity`, Cesium fails to load the geojson and throws a console error.

Below are sandcastle examples to reproduce the errors:
- null fill + valid fill-opacity ([link](https://sandcastle.cesium.com/#c=bVLBbtswDP0VwpdlQCrVcZomXVoMS4uhQ9ceUuzkCy3TjVZZCiQ5aTvs30c56xJ09ckk36P4+CjljcMaEL6S+7a8u4VGGwLlbERttX2AoNu1oRCfOa1t43yLUTsrSivlvQND6C20zhNg5bp4iB9CIIJVjOtwJuWDjquuEsq1ssV15Z7kAfQorEmVNjW9thBXOsAafdSqM+iBnjAhh1wgsNgSuAYI1QrIRh2fgeGBIkQHOgZo8VGDZg2g6wRoNPl+3oXR6jGJ4lJPr7QxlUNfw5b/IKzcljt8CAdEFt0/e83av7gnkYbc8EwbTVuunoOlLSwo6K4VP/rcoMxUHy92WyRfZkP4VVqAoMjSd1fT2Stl+ZoRy8XV7VVxOUy4qFsyzDyDBk2gPodW71a/T/7++Ol1nBojLl3nFfFIf3snS4Ozl/9KwrDXg9SszPa2hCh23nSBfHKepfc2WZzVKFVe1KOJmowUqhPK8+msOTktjquiOammUxxJj1t5Oj6m2VTlqp4WRVGdVpN8Vowm47w4VnlOqsjr8QzHKPm8zJFbo2LbxE+ersxKm2Ts9in2OoLAuh7s4wPQi3PtvXtTy4bZvL+liyQwfZ/5vpyP0HkzEEJG4iPCSEFWnXok1hhCIiboXB5S57Xe8Amcv2MkKIMhcKXpjFnqFyqzi7lk/H/UtGu+tbsNeYPPCbbKL252SSHEXHL4PjM6Zyr0bzr/AQ))
- null stroke + valid stroke-opacity ([link](https://sandcastle.cesium.com/#c=bVLBbtswDP0VwpdlQCrVcZomXVoMS4uhQ9ceUuzkCy3TjVZZCiQ5aTvs30c56xJ09ckk36P4+CjljcMaEL6S+7a8u4VGGwLlbERttX2AoNu1oRCfOa1t43yLUTsrSivlvQND6C20zhNg5bp4iB9CIIJVjOtwJuWDjquuEsq1ssV15Z7kAfQorEmVNjW9thBXOsAafdSqM+iBnjAhh1wgsNgSuAYI1QrIRh2fgeGBIkQHOgZo8VGDZg2g6wRoNPl+3oXR6jGJ4lJPr7QxlUNfw5b/IKzcljt8CAdEFt0/e83av7gnkYbc8EwbTVuunoOlLSwo6K4VP/rcoMxUHy92WyRfZkP4VVqAoMjSd1fT2Stl+ZoRy8XV7VVxOUy4qFsyzDyDBk2gPodW71a/T/7++Ol1nBojLl3nFfFIf3snS4Ozl/9KwrDXg9SszPa2hCh23nSBfHKepfc2WZzVKFVe1KOJmowUqhPK8+msOTktjquiOammUxxJj1t5Oj6m2VTlqp4WRVGdVpN8Vowm47w4VnlOqsjr8QzHKPm8zJFbo2LbxE+ersxKm2Ts9in2OoLAuh7s4wPQi3PtvXtTy4bZvL+liyQwfZ/5vpyP0HkzEEJG4iPCSEFWnXok1hhCIiboXB5S57Xe8Amcv2MkKIMhcKXpjFnqFyqzi7lk/H/UtGu+tbsNeYPPCbbKL252SSHEXHL4PjM6Zyr0bzr/AQ))

This PR fixes the bug so that the geojson is loaded correctly.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @na9da! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/na9da/cesium/blob/handle-geojson-null-style-with-opacity/CONTRIBUTORS.md) file!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/main/Documentation/Contributors/CLAs/README.md) for a submitted CLA.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by na9da** [comment]
This is ready for review. 

I have also signed the CLA.

**Comment by na9da** [comment]
Hi @ebogo1

I have made the recommended changes. Thank you for the review :+1:

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @na9da! 

No one has commented on this pull request in 90 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 90 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by ebogo1** [comment]
@na9da Thanks for the changes and apologies for taking a while to get this into `main`! I merged in the latest `main` after the 1.89 release and updated CHANGES.md to move the PR fix into a new 1.90 section.

**Pull request merged**
