### PR TITLE
Add `projectTo2D` option to `Cesium3DTileset`

### PR DESCRIPTION
**Pull request by j9liu**
This is a similar adjustment to #10344. Accurate 2D projection requires extra memory, and we don't want it to tax the performance of users who will only ever use 3D. Therefore, we're adding a `projectTo2D` option in `Cesium3DTileset`. Similar to `enableDebugWireframe`, only the users who need it can opt-in and use the accurate 2D projection.

[Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bVLva9swEP1XRD45kErp0jLI0rA2KSzQrqVJWwaGIUsXW5ssGemcLB373yf5R2i3frLv9N7Te3dijFzVSktlciI5ciJs7RD8gdgt+fptQe4qMMt4UFmHXE9JgVhNGdvv96fUHATN7Y55hcCkVYhMGYWKo9qBZxN5knXitOI5pEZY45HsFOzBkQtiYE8W4FVd0qeml6QD0dQLa5ArAy4djMjv1BCC4Fzo3Du7UxLctCcKBxzh2TotNy0kGY4iwQswcGslHKHrvkMXdzePt1eP6+9Pq+vn1PwZfkpNalpftCHSXNsMqIQKiw14vMyDssfuiuAdXQ0Nq82ESoMHfBuq/UyWm/YwaYLUTh8drax5AB9GLoBunS0vfYCtZPLxfHI2aWOA4ZluXOvrXxU4VYJpFhENNIjK2R8gcGM/LNtuF+hNnCoQVbMWyqVMOrtt7q6gYZLyEAZcKg8UCzDJtjYClTUkGbZb6DRfrC03Nokd0kcftdWr+F+CXtj9vUJRPHCTQ0cgZEzHo/7/ZEzPj0VvJbO1idx1VYAD6oJQ7QkjZ3TcQofxE+03UQejwczjQcO8F/qsyvhi47QTShlCWenwTjzLavEzXCC8j8QInbHX1JlUO6LkxTsvkQjNvQ8n21rrtXqBdDCfsYD/j6ptk/xuB07zQ4QVp/ObtkkpnbFQvs9Ea3XG3T/KfwE) for testing (comment / uncomment the `projectTo2D` option to see the difference)

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @j9liu!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/add-projectTo2D-to-tilesets/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by j9liu** [comment]
@ptrgags This is ready for review. Here's a [Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=jVRrT+M4FP0rVj+1UnHi2HkxHbTQApuKlB3aAoMqrdzEBdPEydoOUFb893Ee1Q6z7IovTnx9z7mvY4+Z4lUOT19KJnnOhKbZGaO6kkxBJug6Y3GRsuznc/AVaFmxLyuxEkkhlAZPnD0zaeyCPYNxy3jd2PqrXtLsx4WBcsHkqjcEf68EACphoiE/3EPmewscX14s45Pl/M/r6PRmJd4GTTDLagNB9qKZSPsdrDW2GzxZ8IypSKiSJbqQMX/hokZbVpsq35/U+TWlmbQ72uRDioa/8eySAOeSCt0lPZ0DmhigAroAu6KSgBcCUKWYVivRZRgVAqZsQ6tMHzfOi2LLhAm86rHd9GF9nvBLPo2WrxGa8ciEvnKTceRF2/L2ejwNoXH6Kz3fGqfodZafPcSvd3k8Rzx+3O4uFt9IPIn15c3p6+UYbe/ys8f45vvLXb7czW4ifjGelneGbDb5pqI8e0jNf7z4/jxbHKN4cezOsA1T/zafrc+i/I9TfOLy++ntdOnfBRN6YvvliXq8Wm/R71ovJtV21Wu6sBKbSiS6rjUraNrP6JplQ1DJbNBOt+22rjvJ9HtlvJsU0/3GH9TYw3oZtttSFo+m/4vCmRyCDc0Uq+2NEgCwrI4Z5vSF51U+TyRjYl7ShJ1KWdRaJI1nN9pGbLA0EuaaPxlt0zTtdxw15Vs72qYWM5SMPdG6uFqs/8zwiikz4ITBjSzy43rEUdpHgeeG9qDVWIe/V41e1KfgPg7IL3Ddwk8kT+/Zp0iw47UkHYU27VCfRbqD9n7trwHNmaRwk+0WRTuclCnNRdMRcPhulFRq80cF7h84xHVCD0HPczAihNjeEBwQ3w8RQhB7hITYd8kQYOKYL4K+QxwPhTjwBs3IC8nr56UL0onCxOaSJf8b2YbEDpGLiI1wSFDo2CbKgbEi4gaehzDBPjKr21gD5ATEqQ884ockGAz3karyv4uzoRPY2HN8D3uuGZmH2hihTQJiiLDvO07gBUNgQ+zYOAh9bAcBxtjpIrw1a1rJfYV28671hr2R0ruMHe3T+I3nZSF1fRX6EFqa5WVGTSLWukq2RvGJUu0lAGBk/QwdpfwJ8PTrB08uSDLzJJmTTZVlc/5qRHU0soz/v6C1fri4v3xiMqO72u0BHV20RgjhyDLbj5G6KLI1lb8w/wA) with the instanced trees.

Unfortunately, the old 2D projection method for `ModelInstanceCollection` doesn't translate well to `ModelExperimental`, and without `projectTo2D` the projection for `i3dm` models is a lot more inaccurate. However, I'm not sure if it's worth trying to fix this problem -- if users need correct projection then they can enable the `projectTo2D` flag.

**Review by ptrgags — COMMENTED** [review]
@j9liu the code looks good, just noticed one thing that we could add to the documentation for the parameter.

**Comment by j9liu** [comment]
@ptrgags updated!

**Comment by ptrgags** [comment]
Looks good, thanks @j9liu!

**Pull request merged**
