### PR TITLE
Add HeightReference.CLIP_TO_GROUND 

### PR DESCRIPTION
**Pull request by srcejon**
For #10029, add HeightReference.CLIP_TO_GROUND to support absolute positions that are clipped so they do not go underground.

Tested with entity models, labels, billboards, points and boxes from CZML.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @srcejon!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by sanjeetsuhag** [comment]
Thank you for your contribution @srcejon! Ideally, any additions to `HeightReference` in CesiumJS would also make it into the [CZML spec](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/HeightReferenceValue). I'm not sure if `CLIP_TO_GROUND` is the best name for this kind of behavior, but I understand what this feature is trying to accomplish.

After testing this feature in Sandcastle, it seems like a few things might need fixing:

#### Moving Entity

| [`CLAMP_TO_GROUND`](http://localhost:8080/Apps/Sandcastle/index.html#c=zVh5b9s2FP8qRP6SV1W2c61xkmKek6UZnNiI3RbDXBS0RNtEKFIgqThp4e++x0NX4iAphmE1AokS38H3e6dyhyW6o2RNJDpFnKzRgCiap9En+y6Y7cT2eSC4xpQTOdsJ0fcZR4jyhfhd3PfQAjNFQtRun1GF54ygS7eD1jRZEm1oFWEk1lTwS57QGGsht7CVRCDaU1nelchZ0uc0xZr0kJa55ULn3HJhuwFcyhBrIiUccyzFHU0IaPHWxJIA92chWTJ1JEErnPFN63jGZ7zd9sIYXa405Us0x4okCI6iV3CwnKNMKGq0zLgDK1Ix4SRaMjEnEbHcw4L51B6yKTkhmV7B8ZSlUAIEw0KhOYF7YtX4s6ME8MgygmW0VZmVNAVB/SVQK+3taWqdEG1lSswTkSKep3NwsCJg1EJIFANcVGnCNZJE5Uwr0OWhusJ6FSmibyzrteWcAGOw16oJn4ucJwqJBRI5CKZpzqwXkKYpgXNDVCmNpYZjebl/5oxifgZuiBZSpGYRmHizi91O9yBEu/AHt+5hy6hyMkS2VQROkgkBMxIV2CAxukKz2jvs2HstlCu2oDXjhRVX+Na4VpIi/KlC2KGWAJ8EqIwtlRNiJuLbyGqawgYcy67New6Sj58QiqykE9lzZHEuJfjhNRLtFdyyJBUkg/JdNByNxl8n09H4GNJjKAA4bw7hySNJ4C1NM0Zt0nc79aCBczDIc6RF3avO3aWUgir6JkQ6FYGD39pZwHsBESsBcoSLIIypjEGeRBnWEOsc6gOkBHj5waTEipj0MXG4yLkrA7FIs1yTAfAxw/iHTc8AwAkRnCsEwQnNVcvVIxMumRQZkfqhWcomOM0YScY+hceeyAKMbD4EhpkCV+cYbienJorM6s0p2j/w8p0GoxJzVTnAposWN+59QJ1QR6ydU1+MXvOrItj8aLl6No7NZl1ZUaFqsQESYYX5nss4spSEVBoBR/TGY4h+Qd3oAK7WnFiowBvaKg8CiNfJXZmAOvqEsA4MJ/eNQhK0gPWg0wFJ7zqdphGF8yw61mWBATAsLXOhZUjb7T6DGuqqOkRYJiiUMuNJguMVUpYbrQla+iiMPE4ufCHfQCBRRlPwvTh3oaZXrsJqC+T3UEkKb+g9YRP6DTrSu7B6HQsmqq4zME/R9KZ/PRn3b86vpzVKkWuTQYMtDH+dD4ejz09pP9NEr3por9zZ+NXGQbgxF0l0DrlVgAkbG5eQA5dNviIAAA9VyJTQu6pbC6VncvBtt7sbdbudw6O9EJIl6hwd7b/b74aoE3XKPtGPdY4Zeyj8VGl2avwpTp93S9XIPC2+w5ThOWXmQQvXnjFkGfiHyDvMEFbuZbMjWf/XmXv1xDLF99ILABf4MST426H7DGEVODZ1e48y2NTCnr2WTrKLL+bmbPuoiO2eHuOkxN2OMlvD0TH2cy3M0BM7dL1jhaSAkq/XxfxSujIVdySFfYtEjbQBxCcC7QHQGVX7ZbUss7A8xlBgN7k4bpQxDI0jFQlhxjeSZDBcmBmj7njkCMpkyiXtodlOFLXhz6U9VDjctlSqfSFN5/kEU1LMSPMJ5qE5TKNOTEphDszTcZWWh/t+y3WWG7Ig0GhjUibbh+b7aDDsX42/TkdfL25GH6/PbEaVtk5WYm3tgOa1MkEGRYfyW2R7pas3CQQh6sKQZQo7rCHqDeDKIm7YSpsBFsFyh363MAAyRFLMGv4YC/ZgNFwwsb7yBKVDyviDuXA9Fmsz7naibhmB8UulZVPU7LUrLF03OW3qg3E/SdA819rkkbCJWqFgmoqbXGHWSMQaGCZQ62OsNLM97owsMEwaUyHYHMvfrRj4ojCfFmgKPGeGB74nyo4fFL3cjxkSx7ckOS/qBPieLACO5LhG5EeQrQU+fJLBHwi0K74cUx2v7NgUdMJnWvnbo07L9lmDxY8BouDj4zEYW1GYGML/G4FtjbsJQ/gCSfegIvn1oGzsL4BnjWtUd4WotpVKvQq9PnQliRf6RxB0qh4fCpsqOhcw597bMcJ/i8JcagcK210y4RuKKU3RMwe8Ijy3gPrmUSaphknIFLrLuqgeGoIzoRX2M2jB9/5LtixqUKi5O0nvqX3u58yJiuJsPtwaGkaZbShBjQU1zXFjYVWItpD02RI6hl6lZTVxx26cusa+KUa62ogSvhIPvJT2C8eUPi5SKHg/AzgHrwGnTlKmSmFQZc9/gNoHIlOqfzbQdn8korwJ/wKmL/Y622koMvk423Ff/TvhzonSD4y8LwT8RtNMSA1DCAtg/NAE+ji0WdWe51A04ENcqULbSbvOepLQO0ST0y3/HkMxw0rBziJndhSZ7bw/aQP9E1YmbCUe3RHJ8IMhW3XfD93LKIpO2vC4nVO7YgMshSXV3hbzm1Jq638A) | [`CLIP_TO_GROUND`](http://localhost:8080/Apps/Sandcastle/index.html#c=zVh5b9s2FP8qRP6SV1W2c61xkmKek6UZnNiI3RbDXBS0RNtEKFIgqThp4e++x0NX4iAphmE1AokS38H3e6dyhyW6o2RNJDpFnKzRgCiap9En+y6Y7cT2eSC4xpQTOdsJ0fcZR4jyhfhd3PfQAjNFQtRun1GF54ygS7eD1jRZEm1oFWEk1lTwS57QGGsht7CVRCDaU1nelchZ0uc0xZr0kJa55ULn3HJhuwFcyhBrIiUccyzFHU0IaPHWxJIA92chWTJ1JEErnPFN63jGZ7zd9sIYXa405Us0x4okCI6iV3CwnKNMKGq0zLgDK1Ix4SRaMjEnEbHcw4L51B6yKTkhmV7B8ZSlUAIEw0KhOYF7YtX4s6ME8MgygmW0VZmVNAVB/SVQK+3taWqdEG1lSswTkSKep3NwsCJg1EJIFANcVGnCNZJE5Uwr0OWhusJ6FSmibyzrteWcAGOw16oJn4ucJwqJBRI5CKZpzqwXkKYpgXNDVCmNpYZjebl/5oxifgZuiBZSpGYRmHizi91O9yBEu/AHt+5hy6hyMkS2VQROkgkBMxIV2CAxukKz2jvs2HstlCu2oDXjhRVX+Na4VpIi/KlC2KGWAJ8EqIwtlRNiJuLbyGqawgYcy67New6Sj58QiqykE9lzZHEuJfjhNRLtFdyyJBUkg/JdNByNxl8n09H4GNJjKAA4bw7hySNJ4C1NM0Zt0nc79aCBczDIc6RF3avO3aWUgir6JkQ6FYGD39pZwHsBESsBcoSLIIypjEGeRBnWEOsc6gOkBHj5waTEipj0MXG4yLkrA7FIs1yTAfAxw/iHTc8AwAkRnCsEwQnNVcvVIxMumRQZkfqhWcomOM0YScY+hceeyAKMbD4EhpkCV+cYbienJorM6s0p2j/w8p0GoxJzVTnAposWN+59QJ1QR6ydU1+MXvOrItj8aLl6No7NZl1ZUaFqsQESYYX5nss4spSEVBoBR/TGY4h+Qd3oAK7WnFiowBvaKg8CiNfJXZmAOvqEsA4MJ/eNQhK0gPWg0wFJ7zqdphGF8yw61mWBATAsLXOhZUjb7T6DGuqqOkRYJiiUMuNJguMVUpYbrQla+iiMPE4ufCHfQCBRRlPwvTh3oaZXrsJqC+T3UEkKb+g9YRP6DTrSu7B6HQsmqq4zME/R9KZ/PRn3b86vpzVKkWuTQYMtDH+dD4ejz09pP9NEr3por9zZ+NXGQbgxF0l0DrlVgAkbG5eQA5dNviIAAA9VyJTQu6pbC6VncvBtt7sbdbudw6O9EJIl6hwd7b/b74aoE3XKPtGPdY4Zeyj8VGl2avwpTp93S9XIPC2+w5ThOWXmQQvXnjFkGfiHyDvMEFbuZbMjWf/XmXv1xDLF99ILABf4MST426H7DGEVODZ1e48y2NTCnr2WTrKLL+bmbPuoiO2eHuOkxN2OMlvD0TH2cy3M0BM7dL1jhaSAkq/XxfxSujIVdySFfYtEjbQBxCcC7QHQGVX7ZbUss7A8xlBgN7k4bpQxDI0jFQlhxjeSZDBcmBmj7njkCMpkyiXtodlOFLXhz6U9VDjctlSqfSFN5/kEU1LMSPMJ5qE5TKNOTEphDszTcZWWh/t+y3WWG7Ig0GhjUibbh+b7aDC8HH+djr5e3Iw+Xp/ZhCpNnazE2poBvWtlYgxqDuW3yLZKV24SiEHUhRnL1HVYQ9AbvJUF3LCVJgMqguUO/G5xfkgQSTFruGMs2IPRcMHE+soTlP4oww/GwvVYrM2024m6ZQDGL1WWTVGy166udN3gtKnPxf0kQfNca5NGwuZphYLpKW5whVEjEWtgmECpj7HSzLa4M7LAMGhMhWBzLH+3YuCDwnxZoCnwnBke+JwoG35QtHI/ZUgc35LkvCgT4HqyADiS4xqRn0C21vfwSQJ/INCt+HJMdbyyU1PQCZ/p5G+POi3bZg0WPwaIgm+Px2BsRWFiCP9vBLb17SYM4Qsk3YOK5NeDsq+/AJ41rlHcFaLaFir1KvT60JQkXugfQdCpenwobIroXMCYe2+nCP8pCmOpnSdsc8mE7yemMkXPHPCK8NwC6ntHmaQaBiFT5y7ronpoCM6ETtjPoAPf+w/ZsqZBnebuJL2n9rmfMycqarP5bmtoGGW2nwQ1FtQ0x02FVSHaQtJnS2gYepWW1cQdu3HqGvummOhqE0r4SjzwUtoPHFP6uEih4P0M4By8Bpw6SZkqhUGVPf8Bah+ITKn+2UDb/ZGI8ib8C5i+2Otsp6HI5ONsx33074Q7J0o/MPK+EPAbTTMhNcwgLIDpQxPo49BmVXueQ9GA73ClCm0n7TrrSULvEE1Ot/x3DMUMKwU7i5zZSWS28/6kDfRPWJmwlXh0RyTDD4Zs1X0/dC+jKDppw+N2Tu2KDbAUllR7W8xvSqmt/wE) |
| - | - |
| clamp_to_ground_live | clip_to_ground_live2 |

 #### Terrain Exaggeration
 
| [`CLAMP_TO_GROUND`](http://localhost:8080/Apps/Sandcastle/index.html#c=xRdZjxo3+K9Y9CHQgncOhgFCVu1uoqZSko02Rx9KFXlmvGCtsUceDyyt+O/97DmY4Uhp1KoPaOzP332zJgqtGd1QhV4gQTfolmYsX+HPFtadd2J7v5VCEyaomnf66M+5QEhTpQDyXsk1S6iaVoSxokTTX6XiyccCpdvrz8Wu93wu5mIN4rKYCgrSCrHYXp8XTwsuI/NkYdje4MV+cSnw1RNZLKgimkkBmB52voZxTzl81/Q1ZYulNvhDx7Ekc1EIickKcHFGtTG5a21LaKaZsAymTafcEqXhRITfNWgI+f4oGIXY8YNhOHFCx+8X8GA0Go7GY+wMw5HjDSfjEu5NPN9zhtgHhMnId33PwHv2VSpGwclHQl9TkjCxeM90vLyXnJeiXex5oe+NXX/sjfyJNwpKGQMH+57nT0au54cO/AJ3WD6B5Y4Xeg7QTRx3PHId3x9XGlQRKqICqjDNaIZJkhROSWXGLvCIOwyCEAz03RCOYVB7JJiEno/D0B2PPbfW1ngk8Mc4GLqh7zuTcLz3COWcpZlkybRIOYQUuIKdU8BGto+an14pZQUpqRjhdZbeSi4Vvn/1skRY2vy4pw9UURHT6d75LTi+ffPT2/dfPt59+fn+7tO7gnrXTu81y3LC2R/0KPe0yqlFe8hFbPM3TxPQ7G2pXbdX2MkeUPcMl17lCSNpWTG+MP2f70lpu4rOMmiQEJ4uCeCCtku8grJ2jZtbjL6HDPOCXoOIk63tLKXWENMnTUXyKd0QlWRT65J+++2l3IiTr0JDhQD0twqC9mz3MZxWbvkBuTYTmiixCXs7fwykazPG2mNPhamlNQ0Gu/6looNLJbu1ZLct+VsEf7PEbzFy8D8ZCYIvD+w+phcG9vfytCuTuDGJcNVFIJ9bw+4Vp2tbADdEJHUx1yZYFtPiU8uxhWGS2R5qqUXt7KD1ZbRywhkVcpHQBxjJSUECPWguDvtJoynRzVuZUF7VYrNup+fr3+qlWl1kemm7MW3xVLtrUlQt72sj/l2+imAVqU3ATd0Lh10+/0tmZYeqWbZNtCPIMj7h0J0xqYz/o5Dxo8w11orEj3sVe+U+o6XkETENMJFxvoIWhhdUQ76Y4832lwQWrBJn3jFEh3xJmvLtDRNmA8j2/PsVZ0PzIBXMC5AiYJVBTOzNas2TytQlye42Zm9LqdLbriHq1WPlQH6VrUbruyijak0iTpt6WPIaLcujLFYsot3jUPcaeToXH6BUYpJpTs2G8VEuFpze5FpDShi0eedzNQBRFUNUBqdjk/LMgLRvdcJ14yWNH2myH5tnh3OJWZb9ibhb3YuKOlTehqLSvnNPVxK0bdputua9UqU2pxMaVHHtgno+PQGl2GFtu+j0O7NMbzm9rsLwI1ulUmmUK97F+ErTVQrkNLuKcjBR4zjLqhmN0HdVjjZabgTJvFASOswUqUVEukMPFqry5+DxnhrWQvAAJOcUDdOnBjiSCv4VDMzClmftx92RaCbSXDcVWENqspjwAcRqAf1pxZKE02OpAy3TKfJakqunSEI8Vu3XY9F4Ces1bVn/AP91Bpuy10WSJ4fks6umv2cJWyOWvDjxVwnFnGQZvDzknH+ArJt3rmdXgH9EyqVd8u/AcBgIBm3pXr8pgBjj2RVcT1PW7aMO/0ybIr3eGzTTkUy21815OdOqdTeQ5LqZsrMrAByjtCEAK2KntykFZRQRCzAS4iXg5pgTeYKTa46ZpqmBYseFG9QXGUTQ2QC0JjyHCdksgz6ywE+2DqfomRXzrGHlaQU07JBGFPgabsHfyznieGQ3ANQFvjvoUv+C+waw5uxdOCkupRPPeLDdJ/5LHx4MzH/qRbi2chLujaRtZvpf) | [`CLIP_TO_GROUND`](http://localhost:8080/Apps/Sandcastle/index.html#c=xRdZjxo3+K9Y9CHQgncOYICQVbWbqImUZKPN0YdSRZ4ZL1hr7JHHA0sr/ns/e26OlEat+oDG/vzdNxui0IbRLVXoBRJ0i25pyrI1/mJh3UUnsvdbKTRhgqpFp4/+XAiENFUKIB+U3LCYqllJGClKNP1VKh5/ylG6vf5C7HvPF2IhNiAujaigIC0Xi+31ef605DI0TxaG7Q1e7BcXAl89keWSKqKZFIDpYedbGPeUw3dDX1O2XGmDP3QcS7IQuZCIrAEXp1Qbk7vWtpimmgnLYNZ0yi1RGk5E+F2DhpDvj0fjADv+aBhMncDx+zl8NB4Px5MJdobB2PGG00kB96ae7zlD7APCdOy7vmfgPfsqFaPg5COhrymJmVh+YDpa3UvOC9Eu9rzA9yauP/HG/tQbjwoZAwf7nudPx67nBw78Ru6weALLHS/wHKCbOu5k7Dq+Pyk1KCOURwVUYZrRFJM4zp2SyJRd4BF3OBoFYKDvBnAMRpVHRtPA83EQuJOJ51baGo+M/AkeDd3A951pMKk9QjlnSSpZPMtTDiEFrmDnFLCR7aPmp1dIWUNKKkZ4laW3kkuF71+9LBBWNj/u6QNVVER0Vju/Bce3b998+Prp7usv93ef3+fE+3Z2b1iaEc7+oEepp1VGLdpDJiKbvlkSg2LvCuW6vdxM9oC6Z7j0SkcYSauS8YXZ/7wmpe0iOsugQUJ4siKAC9qu8Bqq2jVebjH6ERLMG/UaRJzsbGMptIaQPmkq4s/Jlqg4nVmX9NtvL+VWnHwVGgoEoL+VEFSzrUM4K93yE3JtIjRRIhP1dvoYSNcmjLXHnnJTC2saDPb9S0WPLpXsVpLdtuTvEfzdEr/HyMH/ZCQIvjywdUwvDOzvxWlfJHFjEOGyiUA+t2bdK043tgBuiIirYq5MsCxm+aeSYwvDJLM9VFLz2tlD50tp6YQzKmQipg8wkeOcBHrQQhz2k0ZTott3Mqa8rMVm3c7O17/VS7W6yOzSdmPa4ql216QoW963Jvz7bB3CJlKZgJu65w67fPwXzIoOVbFsm2gnkGV8wqF7Y1IR/0cho0eZaawViR5rFXvFOqOl5CExDTCWUbaGFoaXVEO+mOPN7k0M+1WBs+gYokO+JEn47oYJswCkNf9+ydnQPEgF8wKkCNhkEBO1Wa15Upq6Iund1qxtCVV61zVEvWqsHMgvs9VofRemVG1IyGlTD0teoaVZmEaKhbR7HOpeI08X4iOUSkRSzalZMD7J5ZLTm0xrSAmDtuh8KQcgKmOIiuB0bFKeGZD2rUq4brSi0SON67F5djgXmEXZn4i71T2vqEPlbShK7Tv3dC1B26btZmmulSq0OZ3QoIpr99Pz6Qko+Qpr20Wn35mnesfpdRmGn9k6kUqjTPEuxlearhMgp+lVmIGJGkdpWs5ohH4oc7TRckNI5qWS0GFmSC1D0h16sE8VPwdPamrYCsEDkJwzNEyeGuBQKvhTMDD7Wpa2H/dHoplIMt1UYAOpySLCBxCrJfSnNYtjTo+lDrRMZshrSS6fQgnxWLdfj0XjFWzXtGX9A/zVGWyLXhdKHh+Sz6+a/p7HbINY/OLEPyUUcZKm8PKQcf4Rsm7RuZ5fAf4RKZd2x78Dw2EgGLSVe/02B2KM51dwPU1ZtY8q/HNtivS6NmiuQxnvrpvzcq5V624g8XUzZedXADhGaUMAlsdO7xIKyigilmAkxEvAzTEn8gQn1xxTTRMDxY4LN6gvMgihswFoQ3gGE7JZBn1kgZ9tHc7QMyvmWcPK0wpo2CGNKPA13EZ/L+eI45HdAFAX+O6gS/0L7hvAmlO7cJpfCiee8WC7T/yXPjwYmP/Ui3Bt5STcG0nbzPS/AA) |
| - | - |
| clamp_to_ground_ | clip_to_ground_ |

**Comment by srcejon** [comment]
Thanks for reviewing this. 

Can you clarify the first problem? Are you say the vehicle goes under the terrain? I do not see that with your test case:

clip_to_ground

I'm not familiar with the exaggeration feature - I'll take a look.

**Comment by sanjeetsuhag** [comment]
@srcejon Apologies for the confusion, I tested against you `main` branch, not the PR branch. Seems like the moving entity case is working well but the terrain exaggeration is still broken. I've updated my comment above with the GIFs from the correct branch.

**Comment by srcejon** [comment]
Hopefully this is the required behaviour, but please review the code:

clip_to_ground_eggs

**Comment by sanjeetsuhag** [comment]
The latest changes look great in Sandcastle, @srcejon. I think the functionality is in place, but this feature needs to be unit tested. Additionally, I still think we need to revisit the naming here; I am not sure if `CLIP` is the right term here, necessarily. Some options could be `CLAMP_UNDER_GROUND`/`CLAMP_WHEN_UNDERGROUND` ?

Additionally, it would be useful to bring this change into the [CZML spec](https://github.com/AnalyticalGraphicsInc/czml-writer).

@lilleyse Do you have any better suggestions for the name here?

**Comment by lilleyse** [comment]
Just throwing an idea out there - instead of adding a new HeightReference could each entity have a minimum and maximum height property?

**Comment by sanjeetsuhag** [comment]
@srcejon In the interest of keeping the list of pull requests tidy, I'm going to close this PR. Feel free to re-open with any new updates.

**Pull request closed without merging**
