### PR TITLE
Fixed image splitting in VR mode

### PR DESCRIPTION
**Pull request by SorryNotSorryBasileus**
Fixed image splitting in VR #8137  according to [http://paulbourke.net/stereographics/stereorender/](http://paulbourke.net/stereographics/stereorender/). Tested in HTC Vive.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @SorryNotSorryBasileus! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/SorryNotSorryBasileus/cesium/blob/master/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by hpinkos** [comment]
@lilleyse or @tfili can you review this?

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
I can confirm @SorryNotSorryBasileus has a signed CLA so this is good to start reviewing.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by Lastkraftwagen** [comment]
Who should be noted here to merge this fix? very useful changes for working with vr. Please, somebody with write access, megre this request.

**Comment by mramato** [comment]
@Lastkraftwagen I apologize for the slow response here.  @lilleyse are you the best person to review this, or can you suggest someone else?

**Comment by Lastkraftwagen** [comment]
@lilleyse, I've asked @SorryNotSorryBasileus for permissions and resolved merge conflicts with CONTRIBUTORS.md. Can you merge this pull request, please?

**Comment by SorryNotSorryBasileus** [comment]
Couple of before-after screenshots.
before
after

**Comment by Lastkraftwagen** [comment]
I've tested the code, written by @SorryNotSorryBasileus , on Oculus CV1. Everything works correctly.

**Comment by lilleyse** [comment]
@SorryNotSorryBasileus @Lastkraftwagen thanks for the PR and screenshots. I have a Google Cardboard I'm going to try out.

My only code suggestion (right now) is to not allocate two `PerspectiveOffCenterFrustum` every frame. Is it possible to reuse a scratch `PerspectiveOffCenterFrustum`?

**Comment by lilleyse** [comment]
@SorryNotSorryBasileus I pushed some cleanup related changes in https://github.com/CesiumGS/cesium/pull/8138/commits/bec06174e2847cb65c2f258c5f7eca924b8b38bf. I confirmed that after my changes it looks exactly the same as your changes. I still need to do a final test with the Cardboard but I expect to merge this tonight or tomorrow.

**Comment by lilleyse** [comment]
Something buggy is happening when `scene.logarithmicDepthBuffer` is false. I noticed it on my phone which doesn't support `gl_FragDepth` and falls back to multifrustum. I think it's only working for the closest frustum.

vr-multifrustum

**Comment by emackey** [comment]
Off-topic, but someday it would be nice to deprecate this whole fake VR implementation and replace it with proper WebXR integration.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by midnight-dev** [comment]
> Something buggy is happening when `scene.logarithmicDepthBuffer` is false. I noticed it on my phone which doesn't support `gl_FragDepth` and falls back to multifrustum. I think it's only working for the closest frustum.

@lilleyse I'm not viewing it with a headset, just using an eye trick. I don't see anything horribly wrong with the screenshot, but the basket seems a little off. Was this what caught your attention, or is the distance to the background off? I only notice an issue with the basket using just my eyes. 

Also, does this multifrustum issue occur in the current pseudo VR code? If so, that problem may be outside the scope of this PR, which attempts to fix the projection angles for less eye strain.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @SorryNotSorryBasileus! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by emackey** [comment]
@cesium-concierge stop

**Comment by ggetz** [comment]
@SorryNotSorryBasileus thanks for your work here, but we're going to opt to close this out. We feel our current implementation is really a stop gap solution for VR and would rather proper XR support. If you have any interest in the implantation or have further thoughts, please let us know here: https://github.com/CesiumGS/cesium/issues/3422.

**Pull request closed without merging**
