### PR TITLE
Re-add trailing spaces to make prettier merge cleaner

### PR DESCRIPTION
**Pull request by jjspace**
# Description

In #12206 it seems some extra changes bled in to remove trailing spaces and a few extra newlines in a couple sandcastles. These apparently are not formatted automatically with `prettier` itself so I think they came from my review process in VSCode stripping the trailing spaces when I save the files. 

The [merge process](https://github.com/CesiumGS/cesium/pull/12206#issuecomment-2377930855) for those prettier changes says to use `strategy=ours` when merging the prettier changes. This means every PR this is merged into will likely show these set of files as changes when compared to `main`. This PR is just to "revert" that to make other PR reviews easier. (first noticed in https://github.com/CesiumGS/cesium/pull/12212/commits/b73f87e2c93ffd7c510a3c973c52b4d237f4d03f)

## Issue number and link

Related to #12172

## Testing plan

- create a test branch off of another PR
- do the `prettier` merge process but swap out this branch instead of `origin/main`
- confirm the final diff doesn't show these changes

# Author checklist

- [ ] I have submitted a Contributor License Agreement
- [ ] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [ ] I have added or updated unit tests to ensure consistent code coverage
- [ ] I have updated the inline documentation, and included code examples where relevant
- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by jjspace** [comment]
@ggetz we're potentially getting into some weird `git` territory here. Should this PR contain the commit to revert these changes? If that got merged to main would that prevent them from polluting other PRs? or just create more conflicts?

**Comment by ggetz** [comment]
@jjspace Given https://github.com/CesiumGS/cesium/pull/12206#issuecomment-2379955367, does it make sense to close this?

**Comment by jjhembd** [comment]
@jjspace thanks for tracking down what the difference was... I saw too many changes when I followed the original merge process, but didn't take the time to understand why.
Whatever your VSCode did, I think it was good? So I would vote for not adding those extra spaces back in.

**Comment by jjspace** [comment]
> Given https://github.com/CesiumGS/cesium/pull/12206#issuecomment-2379955367, does it make sense to close this?

Yes, I tried again with @jjhembd's change in that branch and it worked much smoother. I'm closing this in favor of keeping the changes even if they were in addition to base `prettier`.

> thanks for tracking down what the difference was... I saw too many changes when I followed the original merge process, but didn't take the time to understand why.

After looking closer I did notice that the merge of `post-prettier-v3` in my first attempt of https://github.com/CesiumGS/cesium/pull/12212 was actually completely empty given the strategy. 

> Whatever your VSCode did, I think it was good? So I would vote for not adding those extra spaces back in.

I agree, I think it's best to not have trailing spaces anywhere but apparently that's not enforced with prettier inside template strings.

**Pull request closed without merging**
